/* This file was generated by the Hex-Rays decompiler version 9.1.0.250226.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>

#include <stdarg.h>


//-------------------------------------------------------------------------
// Function declarations

int init_proc();
void sub_8DFC();
// int __fastcall shm_abc02GetImportState(_DWORD); weak
// void abort(void);
// int *_errno_location(void);
// int __fastcall _deregister_frame_info(_DWORD); weak
// int sprintf(char *s, const char *format, ...);
// int open(const char *file, int oflag, ...);
// int pthread_join(pthread_t th, void **thread_return);
// char *strerror(int errnum);
// int _xstat(int ver, const char *filename, struct stat *stat_buf);
// int _gmon_start__(void); weak
// int pthread_attr_setschedpolicy(pthread_attr_t *attr, int policy);
// int system(const char *command);
// ssize_t write(int fd, const void *buf, size_t n);
// int __fastcall _register_frame_info(_DWORD, _DWORD); weak
// void *memset(void *s, int c, size_t n);
// int _libc_start_main(int (*main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// uint16_t htons(uint16_t hostshort);
// int pthread_attr_setstacksize(pthread_attr_t *attr, size_t stacksize);
// int __fastcall Ssc_clearMasterLed(_DWORD); weak
// ssize_t read(int fd, void *buf, size_t nbytes);
// void perror(const char *s);
// int __fastcall shm_rdndntGetAll(_DWORD); weak
// int usleep(__useconds_t useconds);
// int __fastcall Ssc_setMasterLed(_DWORD); weak
// int ioctl(int fd, unsigned int request, ...);
// int pthread_mutex_unlock(pthread_mutex_t *mutex);
// int pthread_attr_init(pthread_attr_t *attr);
// void bcopy(const void *src, void *dest, size_t n);
// int nanosleep(const struct timespec *requested_time, struct timespec *remaining);
// void *memcpy(void *dest, const void *src, size_t n);
// int pthread_attr_setinheritsched(pthread_attr_t *attr, int inherit);
// int __fastcall shm_ledGetAllLedBits(_DWORD, _DWORD, _DWORD); weak
// int pthread_attr_setschedparam(pthread_attr_t *attr, const struct sched_param *param);
// int printf(const char *format, ...);
// int raise(int sig);
// int clock_gettime(clockid_t clock_id, struct timespec *tp);
// int close(int fd);
// int fprintf(FILE *stream, const char *format, ...);
// int pthread_mutex_lock(pthread_mutex_t *mutex);
// int pthread_create(pthread_t *newthread, const pthread_attr_t *attr, void *(*start_routine)(void *), void *arg);
// unsigned int sleep(unsigned int seconds);
// int __fastcall Ssc_clearCouplingLed(_DWORD); weak
// int __fastcall shm_abc02GetOp(_DWORD); weak
// int __fastcall shm_abc02GetMode(_DWORD); weak
// int puts(const char *s);
// int __fastcall WriteToGpio_STATUS_LED(_DWORD); weak
// int vfprintf(FILE *s, const char *format, __gnuc_va_list arg);
// int __fastcall Ssc_setCouplingLed(_DWORD); weak
void __noreturn start(void (*a1)(void), int a2, int a3, int a4, ...);
int sub_908C();
int sub_90B0();
void sub_9138();
int *sub_9140();
void sub_9194();
int __fastcall sub_919C(int a1);
int __fastcall sub_9214(int a1);
int __fastcall sub_928C(int a1);
int sub_9304();
int sub_9354();
int sub_93A4();
int sub_93E8();
int sub_9458();
int sub_94C4();
int sub_94D8();
int sub_94EC();
int sub_9710();
void __fastcall __noreturn start_routine(void *a1);
void __fastcall __noreturn sub_98A8(void *a1);
void sub_9AB0();
int __fastcall main(int a1, char **a2, char **a3); // idb
int sub_9C08();
int sub_9C9C();
int __fastcall sub_9CD0(int a1, int a2, _DWORD *a3);
int __fastcall sub_9DE0(int a1, int a2, int a3);
int __fastcall sub_9EE4(int a1, int a2, _DWORD *a3);
int __fastcall sub_9FE8(int a1, int a2, int a3);
int __fastcall sub_A0E0(int a1);
int __fastcall sub_A170(int a1);
int __fastcall sub_A23C(int a1, _DWORD *a2);
int __fastcall sub_A32C(int a1, int a2);
int __fastcall sub_A43C(int a1);
int __fastcall sub_A510(int a1);
int sub_A5D0();
int sub_A66C();
int __fastcall sub_A708(int a1, int a2);
int __fastcall sub_A7F4(int a1, int a2);
int __fastcall sub_A8E0(int a1, int a2);
int __fastcall sub_A9CC(int a1, int a2);
int __fastcall sub_AAB8(int a1, int a2);
int __fastcall sub_AB9C(int a1, const char *a2);
int __fastcall sub_ACA8(int a1, int a2);
int __fastcall sub_AD94(int a1, const char *a2);
int __fastcall sub_AEA4(int a1, int a2);
int __fastcall sub_AF90(int a1, const char *a2);
int __fastcall sub_B0A0(int a1);
int __fastcall sub_B19C(int a1, int a2, int a3);
int __fastcall sub_B330(int a1, int a2);
int __fastcall Ssc_getPortLinkState(_DWORD *a1);
int __fastcall sub_B5C0(int a1);
void *__fastcall Ssc_getPortStatsCounter(void *a1, int a2);
int __fastcall sub_B7AC(_DWORD *a1);
int __fastcall sub_B7F8(int a1);
int __fastcall sub_B840(int a1);
int __fastcall sub_B940(int a1);
int sub_BA04();
int __fastcall sub_BAD4(const void *a1, _DWORD *a2);
int __fastcall sub_BC00(const void *a1, void *a2);
int __fastcall sub_BDF8(const void *a1, void *a2);
int __fastcall sub_BFF0(_DWORD *a1);
int __fastcall sub_C0D8(char *a1, size_t a2, int a3);
int __fastcall sub_C88C(const void *a1, char a2, int a3);
int __fastcall sub_C9BC(const void *a1, int a2, int a3);
int sub_CB14();
int sub_CB6C();
int sub_CBC4();
int __fastcall sub_CBE8(int a1, const void *a2, int a3);
int __fastcall sub_CC40(int a1, const void *a2, int a3);
int __fastcall sub_CCAC(int a1, const void *a2);
int __fastcall sub_CD04(int a1);
int __fastcall sub_CDE8(int a1, int a2);
int __fastcall sub_CEF8(_DWORD *a1, int a2);
int __fastcall sub_D038(_DWORD *a1, unsigned __int8 a2, int a3, int a4);
int __fastcall sub_D1B8(_DWORD *a1, int a2, int a3);
int __fastcall sub_D304(_DWORD *a1, int a2, int a3);
void sub_D460();
int __fastcall sub_D474(int a1);
int __fastcall sub_D540(int result);
int __fastcall sub_D5BC(int result);
int __fastcall sub_D638(int a1, int a2);
int __fastcall sub_D718(int a1, int a2);
int __fastcall sub_D7F8(int a1, int a2);
int __fastcall sub_D904(int a1);
int __fastcall sub_DA0C(int a1, int a2, const void *a3);
void sub_DB24();
int __fastcall sub_DB40(int a1, _DWORD *a2, _DWORD *a3);
int __fastcall sub_DC8C(int a1, int a2);
int sub_DE58();
int sub_DF50();
int sub_E07C();
void sub_E1B0();
int __fastcall sub_E1C4(const void *a1, int a2, int a3);
int __fastcall sub_E2F4(const void *a1, __int16 a2);
int __fastcall sub_E434(int a1);
int sub_E500();
int __fastcall sub_E5BC(int a1, int a2);
int __fastcall sub_E6C4(int a1, int a2);
int __fastcall sub_E7CC(int a1, int a2);
int __fastcall sub_E8AC(int a1, int a2);
int __fastcall sub_E98C(int a1, int a2);
int __fastcall sub_EA6C(int a1);
int __fastcall sub_EB40(int a1);
int __fastcall sub_EC0C(int a1);
int __fastcall sub_ECE0(int a1);
int __fastcall sub_EDAC(int a1);
int __fastcall sub_EE80(unsigned __int8 *a1, int *a2, _DWORD *a3);
_BYTE *__fastcall sub_EF70(_BYTE *result, char a2, __int16 a3);
ssize_t __fastcall sub_F044(int a1, int a2, int a3, int a4, int a5, __int16 a6);
ssize_t __fastcall sub_F224(int a1, int a2, int a3, int a4, int a5, int a6, __int16 a7);
int __fastcall sub_F384(int a1, int a2, int a3, const void *a4, size_t n, int a6);
int __fastcall sub_F520(int a1, int a2, int a3, int a4, void *src, size_t n, int a7); // idb
char *__fastcall sub_F77C(const char *a1);
int __fastcall sub_F7C0(int a1, int a2, int a3);
int __fastcall sub_F858(int a1);
int __fastcall sub_F898(int a1);
__time_t Ssys_current_secs();
int Ssys_current_msecs();
int __fastcall sub_FA14(_DWORD *a1);
int __fastcall sub_FA8C(_DWORD *a1, _DWORD *a2);
char *sub_FB08();
int __fastcall sub_FB3C(unsigned __int8 *a1, int a2);
int __fastcall Ssys_UI_port2MdlPort(int a1, _DWORD *a2, int *a3);
int sub_FC54(int result, const char *a2, ...);
int __fastcall sub_FCC4(int a1);
void sub_FD08();
int __fastcall sub_FD40(int a1);
int __fastcall sub_FE0C(int a1);
int __fastcall sub_FEFC(int a1, _DWORD *a2);
int __fastcall sub_FFE4(int a1, _DWORD *a2);
unsigned int __fastcall sub_100CC(unsigned int result, unsigned int a2);
unsigned int __fastcall sub_101C4(unsigned int a1, unsigned int a2);
int __fastcall sub_101DC(int result, unsigned int a2);
int __fastcall sub_10304(int a1, unsigned int a2);
int sub_1031C();
int nullsub_1(); // weak
void init(void); // idb
int __fastcall sub_10398(char *filename, struct stat *stat_buf); // idb
int sub_103A8();
void sub_103DC();
int term_proc();

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN unk_111D4; // weak
_UNKNOWN *off_1A000 = (_UNKNOWN *)0xFFFFFFFF; // weak
int dword_1A008[] = { -1 }; // weak
int dword_1A00C = 0; // weak
int dword_1A010 = 0; // weak
_UNKNOWN *off_1A1F8 = &unk_1A1F0; // weak
char byte_1A1FC = '\0'; // weak
char byte_1A1FD = '\x90'; // weak
char byte_1A1FE = '\xE8'; // weak
char byte_1A1FF = '\x05'; // weak
char byte_1A200 = '\0'; // weak
char byte_1A201 = '\b'; // weak
_UNKNOWN unk_1A204; // weak
_UNKNOWN unk_1A20C; // weak
int dword_1A264 = 11; // weak
int stderr; // weak
char byte_1A274; // weak
int dword_1A278; // weak
_UNKNOWN unk_1A27C; // weak
char byte_1A294; // weak
int dword_1A298; // weak
int dword_1A29C; // weak
int dword_1A2A4; // weak
pthread_mutex_t mutex; // idb
_UNKNOWN unk_1A2C0; // weak
_UNKNOWN unk_1A2C4; // weak
int dword_1A2C8; // weak
_BYTE byte_1A2D0[12]; // weak
__int16 word_1A2DC; // weak
char byte_1A2DE; // weak
char byte_1A2DF; // weak
char byte_1A2E0; // weak
_UNKNOWN unk_1A2E1; // weak
char byte_1A8AC; // weak
char byte_1A8AD; // weak
char byte_1A8AE; // weak
char byte_1A8AF; // weak
char byte_1A8B0; // weak
char byte_1A8B1; // weak
char byte_1A8B2; // weak
char byte_1A8B3; // weak
char byte_1A8B4; // weak
char byte_1A8B5; // weak
char byte_1A8B6; // weak
char byte_1A8B7; // weak
_UNKNOWN unk_1A8B8; // weak
_UNKNOWN unk_1A8BC; // weak
char byte_1AE98[128]; // idb
int dword_1AF18; // weak
int dword_1AF1C; // weak
_UNKNOWN unk_1AF20; // weak
int dword_1AF24; // weak
int dword_1AF2C; // weak
int dword_1AF34; // weak
int dword_1AF3C; // weak
int dword_1AF44; // weak
int dword_1AF60; // weak
int dword_1AF64; // weak
int dword_1AF68; // weak
// extern _UNKNOWN __gmon_start__; weak


//----- (00008DE8) --------------------------------------------------------
int init_proc()
{
  sub_908C();
  sub_9140();
  return sub_103A8();
}

//----- (00008DFC) --------------------------------------------------------
void sub_8DFC()
{
  JUMPOUT(0);
}
// 8E08: control flows out of bounds to 0

//----- (00009050) --------------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __noreturn start(void (*a1)(void), int a2, int a3, int a4, ...)
{
  int v4; // [sp-4h] [bp-4h]
  va_list va; // [sp+0h] [bp+0h] BYREF

  va_start(va, a4);
  _libc_start_main(main, v4, (char **)va, init, (void (*)(void))nullsub_1, a1, va);
  abort();
}
// 905C: positive sp value 4 has been found
// 9078: variable 'v4' is possibly undefined
// 1032C: using guessed type int nullsub_1();

//----- (0000908C) --------------------------------------------------------
int sub_908C()
{
  int result; // r0

  if ( &__gmon_start__ )
    return _gmon_start__();
  return result;
}
// 8E7C: using guessed type int _gmon_start__(void);

//----- (000090B0) --------------------------------------------------------
int sub_90B0()
{
  int v0; // r3
  unsigned int i; // r6
  int result; // r0

  if ( !byte_1A274 )
  {
    v0 = dword_1A278;
    for ( i = &dword_1A00C - dword_1A008 - 1; dword_1A278 < i; v0 = dword_1A278 )
    {
      dword_1A278 = v0 + 1;
      result = ((int (*)(void))dword_1A008[v0 + 1])();
    }
    if ( _deregister_frame_info )
      result = _deregister_frame_info(&unk_111D4);
    byte_1A274 = 1;
  }
  return result;
}
// 8E34: using guessed type int __fastcall _deregister_frame_info(_DWORD);
// 1A008: using guessed type int dword_1A008[];
// 1A00C: using guessed type int dword_1A00C;
// 1A274: using guessed type char byte_1A274;
// 1A278: using guessed type int dword_1A278;

//----- (00009138) --------------------------------------------------------
void sub_9138()
{
  ;
}

//----- (00009140) --------------------------------------------------------
int *sub_9140()
{
  if ( _register_frame_info )
    _register_frame_info(&unk_111D4, &unk_1A27C);
  return &dword_1A010;
}
// 8EAC: using guessed type int __fastcall _register_frame_info(_DWORD, _DWORD);
// 1A010: using guessed type int dword_1A010;

//----- (00009194) --------------------------------------------------------
void sub_9194()
{
  ;
}

//----- (0000919C) --------------------------------------------------------
int __fastcall sub_919C(int a1)
{
  char s[260]; // [sp+8h] [bp-104h] BYREF

  if ( a1 )
    sprintf(s, "echo %d > %s", 512, "/proc/moxa/gpio_clr");
  else
    sprintf(s, "echo %d > %s", 512, "/proc/moxa/gpio_set");
  return system(s);
}

//----- (00009214) --------------------------------------------------------
int __fastcall sub_9214(int a1)
{
  char s[260]; // [sp+8h] [bp-104h] BYREF

  if ( a1 )
    sprintf(s, "echo %d > %s", 2048, "/proc/moxa/gpio_clr");
  else
    sprintf(s, "echo %d > %s", 2048, "/proc/moxa/gpio_set");
  return system(s);
}

//----- (0000928C) --------------------------------------------------------
int __fastcall sub_928C(int a1)
{
  char s[260]; // [sp+8h] [bp-104h] BYREF

  if ( a1 )
    sprintf(s, "echo %d > %s", 256, "/proc/moxa/gpio_clr");
  else
    sprintf(s, "echo %d > %s", 256, "/proc/moxa/gpio_set");
  return system(s);
}

//----- (00009304) --------------------------------------------------------
int sub_9304()
{
  _BYTE v1[40]; // [sp+4h] [bp-30h] BYREF
  int v2; // [sp+2Ch] [bp-8h]

  v2 = 0;
  shm_rdndntGetAll(v1);
  if ( v1[32] || v1[33] )
    return 1;
  return v2;
}
// 8F0C: using guessed type int __fastcall shm_rdndntGetAll(_DWORD);

//----- (00009354) --------------------------------------------------------
int sub_9354()
{
  _BYTE v1[40]; // [sp+4h] [bp-30h] BYREF
  int v2; // [sp+2Ch] [bp-8h]

  v2 = 0;
  shm_rdndntGetAll(v1);
  if ( v1[34] || v1[35] )
    return 1;
  return v2;
}
// 8F0C: using guessed type int __fastcall shm_rdndntGetAll(_DWORD);

//----- (000093A4) --------------------------------------------------------
int sub_93A4()
{
  _BYTE v1[40]; // [sp+4h] [bp-30h] BYREF
  int v2; // [sp+2Ch] [bp-8h]

  v2 = 0;
  shm_rdndntGetAll(v1);
  if ( v1[36] )
    return 1;
  return v2;
}
// 8F0C: using guessed type int __fastcall shm_rdndntGetAll(_DWORD);

//----- (000093E8) --------------------------------------------------------
int sub_93E8()
{
  char s[260]; // [sp+0h] [bp-104h] BYREF

  sprintf(s, "echo %d > %s", 64, "/proc/moxa/gpio_set");
  system(s);
  sprintf(s, "echo %d > %s", 128, "/proc/moxa/gpio_clr");
  return system(s);
}

//----- (00009458) --------------------------------------------------------
int sub_9458()
{
  char s[260]; // [sp+0h] [bp-104h] BYREF

  sprintf(s, "echo %d > %s", 64, "/proc/moxa/gpio_set");
  system(s);
  sprintf(s, "echo %d > %s", 128, "/proc/moxa/gpio_set");
  return system(s);
}

//----- (000094C4) --------------------------------------------------------
int sub_94C4()
{
  return sub_928C(1);
}

//----- (000094D8) --------------------------------------------------------
int sub_94D8()
{
  return sub_928C(0);
}

//----- (000094EC) --------------------------------------------------------
int sub_94EC()
{
  char s[260]; // [sp+0h] [bp-104h] BYREF

  sprintf(s, "echo %d > %s", 256, "/proc/moxa/gpio_clr");
  system(s);
  sprintf(s, "echo %d > %s", 512, "/proc/moxa/gpio_set");
  system(s);
  sprintf(s, "echo %d > %s", 2048, "/proc/moxa/gpio_set");
  system(s);
  usleep(0x186A0u);
  sprintf(s, "echo %d > %s", 256, "/proc/moxa/gpio_set");
  system(s);
  sprintf(s, "echo %d > %s", 512, "/proc/moxa/gpio_clr");
  system(s);
  sprintf(s, "echo %d > %s", 2048, "/proc/moxa/gpio_set");
  system(s);
  usleep(0x186A0u);
  sprintf(s, "echo %d > %s", 256, "/proc/moxa/gpio_set");
  system(s);
  sprintf(s, "echo %d > %s", 512, "/proc/moxa/gpio_set");
  system(s);
  sprintf(s, "echo %d > %s", 2048, "/proc/moxa/gpio_clr");
  system(s);
  usleep(0x186A0u);
  sprintf(s, "echo %d > %s", 256, "/proc/moxa/gpio_set");
  system(s);
  sprintf(s, "echo %d > %s", 512, "/proc/moxa/gpio_set");
  system(s);
  sprintf(s, "echo %d > %s", 2048, "/proc/moxa/gpio_set");
  return system(s);
}

//----- (00009710) --------------------------------------------------------
int sub_9710()
{
  return WriteToGpio_STATUS_LED(64);
}
// 902C: using guessed type int __fastcall WriteToGpio_STATUS_LED(_DWORD);

//----- (0000972C) --------------------------------------------------------
void __fastcall __noreturn start_routine(void *a1)
{
  int ImportState; // r0
  char v2; // [sp+5h] [bp-6Fh] BYREF
  char v3; // [sp+6h] [bp-6Eh] BYREF
  char v4; // [sp+7h] [bp-6Dh] BYREF
  stat stat_buf; // [sp+8h] [bp-6Ch] BYREF
  int v6; // [sp+64h] [bp-10h]
  int v7; // [sp+68h] [bp-Ch]
  char v8; // [sp+6Fh] [bp-5h]

  v6 = 0;
  v7 = 0;
  v8 = 0;
  while ( 1 )
  {
    while ( 1 )
    {
      while ( sub_10398("/mnt/ramdisk/cfgready", &stat_buf) < 0 )
        sleep(1u);
      usleep(0x30D40u);
      shm_abc02GetMode(&v4);
      shm_abc02GetOp(&v3);
      ImportState = shm_abc02GetImportState(&v2);
      if ( v4 != 1 )
        break;
      v8 = 0;
      if ( v3 == 2 )
      {
        byte_1A294 = 1;
        v6 = 2;
        v7 = 0;
      }
      else
      {
        ImportState = sub_101DC(v7, 5u);
        v6 = (ImportState & 1) != 0;
        ++v7;
        if ( v2 == 1 )
          v6 = 3;
        byte_1A294 = 0;
      }
      (*((void (__fastcall **)(int))&unk_1AF20 + 2 * v6 + 1))(ImportState);
    }
    if ( !v8 )
    {
      byte_1A294 = 0;
      sub_9710();
      v7 = 0;
      v8 = 1;
    }
  }
}
// 8E10: using guessed type int __fastcall shm_abc02GetImportState(_DWORD);
// 9008: using guessed type int __fastcall shm_abc02GetOp(_DWORD);
// 9014: using guessed type int __fastcall shm_abc02GetMode(_DWORD);
// 1A294: using guessed type char byte_1A294;

//----- (000098A8) --------------------------------------------------------
void __fastcall __noreturn sub_98A8(void *a1)
{
  char v1; // [sp+9h] [bp-23h] BYREF
  char v2; // [sp+Ah] [bp-22h] BYREF
  char v3; // [sp+Bh] [bp-21h] BYREF
  int v4; // [sp+Ch] [bp-20h]
  char v5; // [sp+11h] [bp-1Bh]
  char v6; // [sp+12h] [bp-1Ah]
  char v7; // [sp+13h] [bp-19h]
  int v8; // [sp+14h] [bp-18h]
  int v9; // [sp+18h] [bp-14h]
  int v10; // [sp+1Ch] [bp-10h]
  int v11; // [sp+20h] [bp-Ch]

  v4 = 0;
  v5 = 0;
  v6 = 0;
  v7 = 0;
  v3 = 0;
  v2 = 0;
  v1 = 0;
  v8 = 0;
  v9 = 0;
  v10 = 0;
  v11 = 0;
  while ( 1 )
  {
    while ( byte_1A294 )
    {
      sleep(1u);
      v5 = 0;
      v6 = 0;
      v7 = 0;
      v8 = 0;
      v9 = 0;
      v10 = 0;
      v11 = 0;
    }
    shm_ledGetAllLedBits(&v3, &v2, &v1);
    v11 = sub_9304();
    v9 = sub_9354();
    if ( v9 )
    {
      if ( v11 )
      {
        if ( v8 )
        {
          Ssc_clearMasterLed(1);
          v8 = 0;
        }
        else
        {
          Ssc_setMasterLed(1);
          v8 = 1;
        }
      }
      else
      {
        Ssc_setMasterLed(1);
      }
    }
    else
    {
      Ssc_clearMasterLed(1);
    }
    if ( sub_93A4() )
      Ssc_setCouplingLed(1);
    else
      Ssc_clearCouplingLed(1);
    if ( v6 != v2 )
    {
      if ( v2 )
        sub_919C(1);
      else
        sub_919C(0);
      v6 = v2;
    }
    if ( v7 != v1 )
    {
      if ( v1 )
        sub_9214(1);
      else
        sub_9214(0);
      v7 = v1;
    }
    usleep(0x30D40u);
  }
}
// 8EE8: using guessed type int __fastcall Ssc_clearMasterLed(_DWORD);
// 8F24: using guessed type int __fastcall Ssc_setMasterLed(_DWORD);
// 8F84: using guessed type int __fastcall shm_ledGetAllLedBits(_DWORD, _DWORD, _DWORD);
// 8FFC: using guessed type int __fastcall Ssc_clearCouplingLed(_DWORD);
// 9044: using guessed type int __fastcall Ssc_setCouplingLed(_DWORD);
// 1A294: using guessed type char byte_1A294;

//----- (00009AB0) --------------------------------------------------------
void sub_9AB0()
{
  dword_1AF24 = (int)sub_93E8;
  dword_1AF2C = (int)sub_9458;
  dword_1AF34 = (int)sub_94EC;
  dword_1AF3C = (int)sub_94C4;
  dword_1AF44 = (int)sub_94D8;
}
// 1AF24: using guessed type int dword_1AF24;
// 1AF2C: using guessed type int dword_1AF2C;
// 1AF34: using guessed type int dword_1AF34;
// 1AF3C: using guessed type int dword_1AF3C;
// 1AF44: using guessed type int dword_1AF44;

//----- (00009B18) --------------------------------------------------------
int __fastcall main(int a1, char **a2, char **a3)
{
  pthread_attr_t attr; // [sp+Ch] [bp-58h] BYREF
  pthread_t newthread; // [sp+30h] [bp-34h] BYREF
  pthread_attr_t v6; // [sp+34h] [bp-30h] BYREF
  sched_param param; // [sp+58h] [bp-Ch] BYREF
  pthread_t th[2]; // [sp+5Ch] [bp-8h] BYREF

  sub_9AB0();
  pthread_attr_init(&attr);
  pthread_create(&newthread, 0, (void *(*)(void *))start_routine, 0);
  pthread_attr_init(&v6);
  pthread_attr_setinheritsched(&v6, 1);
  pthread_attr_setschedpolicy(&v6, 2);
  param.__sched_priority = 20;
  pthread_attr_setschedparam(&v6, &param);
  pthread_attr_setstacksize(&attr, 0x8000u);
  pthread_create(th, &attr, (void *(*)(void *))sub_98A8, 0);
  pthread_join(th[0], 0);
  pthread_join(newthread, 0);
  return 0;
}

//----- (00009C08) --------------------------------------------------------
int sub_9C08()
{
  dword_1A298 = 0;
  if ( dword_1A29C )
    return dword_1A29C;
  dword_1A29C = open("/dev/eth_switch", 2);
  if ( dword_1A29C >= 0 )
    return dword_1A29C;
  perror("open");
  dword_1A29C = 0;
  return -1;
}
// 1A298: using guessed type int dword_1A298;
// 1A29C: using guessed type int dword_1A29C;

//----- (00009C9C) --------------------------------------------------------
int sub_9C9C()
{
  close(dword_1A29C);
  dword_1A29C = 0;
  return 0;
}
// 1A29C: using guessed type int dword_1A29C;

//----- (00009CD0) --------------------------------------------------------
int __fastcall sub_9CD0(int a1, int a2, _DWORD *a3)
{
  int v4; // r0
  _BYTE v9[4]; // [sp+18h] [bp-214h] BYREF
  int v10; // [sp+1Ch] [bp-210h] BYREF
  int fd; // [sp+21Ch] [bp-10h]
  int v12; // [sp+220h] [bp-Ch]
  int *v13; // [sp+224h] [bp-8h]

  v12 = 1;
  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  v9[0] = 1;
  v9[2] = 12;
  v9[3] = 0;
  v13 = &v10;
  v4 = sub_FD40(a1);
  *v13 = v4;
  v13[1] = a2;
  if ( ioctl(fd, 0x82044700, v9) < 0 )
    sub_FC54(3, "ioctl READ_REG_IOCTL error\n");
  sub_FC54(6, "port %d, REG 0x%x => 0x%x\n", a1, a2, v13[2]);
  *a3 = v13[2];
  return v12;
}

//----- (00009DE0) --------------------------------------------------------
int __fastcall sub_9DE0(int a1, int a2, int a3)
{
  int v4; // r0
  _BYTE v9[4]; // [sp+18h] [bp-214h] BYREF
  int v10; // [sp+1Ch] [bp-210h] BYREF
  int fd; // [sp+21Ch] [bp-10h]
  int v12; // [sp+220h] [bp-Ch]
  int *v13; // [sp+224h] [bp-8h]

  v12 = 1;
  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  v9[0] = 1;
  v9[2] = 12;
  v9[3] = 0;
  v13 = &v10;
  v4 = sub_FD40(a1);
  *v13 = v4;
  v13[1] = a2;
  v13[2] = a3;
  if ( ioctl(fd, 0x42044701u, v9) < 0 )
    sub_FC54(3, "ioctl WRITE_REG_IOCTL error\n");
  sub_FC54(6, "port %d, REG 0x%x , VAL = 0x%x\n", a1, a2, a3);
  return v12;
}

//----- (00009EE4) --------------------------------------------------------
int __fastcall sub_9EE4(int a1, int a2, _DWORD *a3)
{
  _BYTE v8[4]; // [sp+18h] [bp-214h] BYREF
  _DWORD v9[128]; // [sp+1Ch] [bp-210h] BYREF
  int fd; // [sp+21Ch] [bp-10h]
  int v11; // [sp+220h] [bp-Ch]
  _DWORD *v12; // [sp+224h] [bp-8h]

  v11 = 1;
  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  v8[0] = 0;
  v8[2] = 12;
  v8[3] = 0;
  v12 = v9;
  v9[0] = a1;
  v9[1] = a2;
  if ( ioctl(fd, 0x82044700, v8) < 0 )
    sub_FC54(3, "ioctl READ_REG_IOCTL error\n");
  sub_FC54(6, "PHY 0x%x, REG 0x%x => 0x%x\n", a1, a2, v12[2]);
  *a3 = v12[2];
  return v11;
}

//----- (00009FE8) --------------------------------------------------------
int __fastcall sub_9FE8(int a1, int a2, int a3)
{
  _BYTE v8[4]; // [sp+18h] [bp-214h] BYREF
  _DWORD v9[128]; // [sp+1Ch] [bp-210h] BYREF
  int fd; // [sp+21Ch] [bp-10h]
  int v11; // [sp+220h] [bp-Ch]
  _DWORD *v12; // [sp+224h] [bp-8h]

  v11 = 1;
  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  v8[0] = 0;
  v8[2] = 12;
  v8[3] = 0;
  v12 = v9;
  v9[0] = a1;
  v9[1] = a2;
  v9[2] = a3;
  if ( ioctl(fd, 0x42044701u, v8) < 0 )
    sub_FC54(3, "ioctl WRITE_REG_IOCTL error\n");
  sub_FC54(6, "PHY 0x%x, REG 0x%x , VAL = 0x%x\n", a1, a2, a3);
  return v11;
}

//----- (0000A0E0) --------------------------------------------------------
int __fastcall sub_A0E0(int a1)
{
  if ( ((1 << a1) & dword_1A298) != 0 )
  {
    sub_FC54(7, "%s() %d vport = %d isGiga\n", "Ssc_isGigaCopperLink", 184, a1);
    return 1;
  }
  else
  {
    sub_FC54(7, "%s() %d vport = %d notGiga\n", "Ssc_isGigaCopperLink", 188, a1);
    return 0;
  }
}
// 1A298: using guessed type int dword_1A298;

//----- (0000A170) --------------------------------------------------------
int __fastcall sub_A170(int a1)
{
  char v2; // r0
  int v5; // [sp+Ch] [bp-10h] BYREF
  int fd; // [sp+10h] [bp-Ch]
  int v7; // [sp+14h] [bp-8h]

  v7 = 1;
  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  if ( ioctl(fd, 0x8004470A, &v5) < 0 )
    sub_FC54(3, "ioctl ETHSW_LINK_STATUS_GET error\n");
  v2 = sub_FD40(a1);
  if ( ((1 << v2) & v5) != 0 )
    v7 = 0;
  sub_FC54(7, "port %d isDown = %d\n", a1, v7);
  return v7;
}

//----- (0000A23C) --------------------------------------------------------
int __fastcall sub_A23C(int a1, _DWORD *a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 1;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_FD40(a1);
  *v8 = v3;
  if ( ioctl(fd, 0x82044702, s) >= 0 )
  {
    *a2 = v8[1];
    return 0;
  }
  else
  {
    sub_FC54(3, "%s() ioctl error\n", "Ssc_port_speed_get");
    return -1;
  }
}

//----- (0000A32C) --------------------------------------------------------
int __fastcall sub_A32C(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+14h] [bp-210h] BYREF
  int *v8; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  sub_FC54(7, "%s() %d >>>>>>> port %d %d\n", "Ssc_port_speed_set", 266, a1, a2);
  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 1;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_FD40(a1);
  *v8 = v3;
  v8[1] = a2;
  if ( ioctl(fd, 0x42044703u, s) < 0 )
    sub_FC54(3, "%s() ioctl error\n", "Ssc_port_speed_set");
  return 0;
}

//----- (0000A43C) --------------------------------------------------------
int __fastcall sub_A43C(int a1)
{
  int v2; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v6; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 7;
  s[2] = 8;
  s[3] = 0;
  v6 = (int *)&s[4];
  v2 = sub_FD40(a1);
  *v6 = v2;
  if ( ioctl(fd, 0x42044703u, s) < 0 )
    sub_FC54(3, "%s() ioctl error\n", "Ssc_port_learing_disable");
  return 0;
}

//----- (0000A510) --------------------------------------------------------
int __fastcall sub_A510(int a1)
{
  int v2; // r0
  _BYTE v5[4]; // [sp+Ch] [bp-210h] BYREF
  int v6; // [sp+10h] [bp-20Ch] BYREF
  int *v7; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  v5[0] = 8;
  v5[2] = 8;
  v5[3] = 0;
  v7 = &v6;
  v2 = sub_FD40(a1);
  *v7 = v2;
  if ( ioctl(fd, 0x42044703u, v5) < 0 )
    sub_FC54(3, "%s() ioctl error\n", "Ssc_port_learing_enable");
  return 0;
}

//----- (0000A5D0) --------------------------------------------------------
int sub_A5D0()
{
  _BYTE v2[516]; // [sp+4h] [bp-210h] BYREF
  int fd; // [sp+208h] [bp-Ch]

  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  v2[0] = 9;
  v2[2] = 8;
  v2[3] = 0;
  if ( ioctl(fd, 0x42044703u, v2) < 0 )
    sub_FC54(3, "%s() ioctl error\n", "Ssc_cpuport_learing_disable");
  return 0;
}

//----- (0000A66C) --------------------------------------------------------
int sub_A66C()
{
  _BYTE v2[520]; // [sp+4h] [bp-210h] BYREF
  int fd; // [sp+20Ch] [bp-8h]

  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  v2[0] = 10;
  v2[2] = 8;
  v2[3] = 0;
  if ( ioctl(fd, 0x42044703u, v2) < 0 )
    sub_FC54(3, "%s() ioctl error\n", "Ssc_cpuport_learing_enable");
  return 0;
}

//----- (0000A708) --------------------------------------------------------
int __fastcall sub_A708(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 2;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_FD40(a1);
  *v8 = v3;
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_FC54(3, "%s() ioctl error\n", "Ssc_port_duplex_get");
  *(_DWORD *)a2 = v8[1];
  return *(_DWORD *)a2;
}

//----- (0000A7F4) --------------------------------------------------------
int __fastcall sub_A7F4(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 11;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_FD40(a1);
  *v8 = v3;
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_FC54(3, "%s() ioctl error\n", "Ssc_port_qinq_get");
  *(_DWORD *)a2 = v8[1];
  return *(_DWORD *)a2;
}

//----- (0000A8E0) --------------------------------------------------------
int __fastcall sub_A8E0(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 12;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_FD40(a1);
  *v8 = v3;
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_FC54(3, "%s() ioctl error\n", "Ssc_port_egress_get");
  *(_DWORD *)a2 = v8[1];
  return *(_DWORD *)a2;
}

//----- (0000A9CC) --------------------------------------------------------
int __fastcall sub_A9CC(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 13;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_FD40(a1);
  *v8 = v3;
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_FC54(3, "%s() ioctl error\n", "Ssc_port_802dot1q_mode_get");
  *(_DWORD *)a2 = v8[1];
  return *(_DWORD *)a2;
}

//----- (0000AAB8) --------------------------------------------------------
int __fastcall sub_AAB8(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+8h] [bp-214h] BYREF
  int v8; // [sp+20Ch] [bp-10h]
  int *v9; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 13;
  s[2] = 8;
  s[3] = 0;
  v9 = (int *)&s[4];
  v3 = sub_FD40(a1);
  *v9 = v3;
  v9[1] = a2;
  if ( ioctl(fd, 0x42044703u, s) < 0 )
    sub_FC54(3, "%s() ioctl error\n", "Ssc_port_802dot1q_mode_set");
  return v8;
}

//----- (0000AB9C) --------------------------------------------------------
int __fastcall sub_AB9C(int a1, const char *a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+14h] [bp-210h] BYREF
  int *v8; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  sub_FC54(7, "%s() %d >>>>>>> port %d %s\n", "Ssc_port_duplex_set", 548, a1, a2);
  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 2;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_FD40(a1);
  *v8 = v3;
  v8[1] = (int)a2;
  if ( ioctl(fd, 0x42044703u, s) < 0 )
    sub_FC54(3, "%s() ioctl error\n", "Ssc_port_duplex_set");
  return 0;
}

//----- (0000ACA8) --------------------------------------------------------
int __fastcall sub_ACA8(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 4;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_FD40(a1);
  *v8 = v3;
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_FC54(3, "%s() ioctl error\n", "Ssc_port_pause_get");
  *(_DWORD *)a2 = v8[1];
  return *(_DWORD *)a2;
}

//----- (0000AD94) --------------------------------------------------------
int __fastcall sub_AD94(int a1, const char *a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+14h] [bp-210h] BYREF
  int *v8; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  sub_FC54(7, "%s() %d >>>>>>> port %d %s\n", "Ssc_port_pause_set", 619, a1, a2);
  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 4;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_FD40(a1);
  *v8 = v3;
  v8[1] = (int)a2;
  if ( ioctl(fd, 0x42044703u, s) < 0 )
    sub_FC54(3, "%s() ioctl error\n", "Ssc_port_pause_set");
  return 0;
}

//----- (0000AEA4) --------------------------------------------------------
int __fastcall sub_AEA4(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 3;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_FD40(a1);
  *v8 = v3;
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_FC54(3, "%s() ioctl error\n", "Ssc_port_mdi_get");
  *(_DWORD *)a2 = v8[1];
  return *(_DWORD *)a2;
}

//----- (0000AF90) --------------------------------------------------------
int __fastcall sub_AF90(int a1, const char *a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+14h] [bp-210h] BYREF
  int *v8; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  sub_FC54(7, "%s() %d >>>>>>> port %d %s\n", "Ssc_port_mdi_set", 689, a1, a2);
  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 3;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_FD40(a1);
  *v8 = v3;
  v8[1] = (int)a2;
  if ( ioctl(fd, 0x42044703u, s) < 0 )
    sub_FC54(3, "%s() ioctl SET_PORT_STATE error\n", "Ssc_port_mdi_set");
  return 0;
}

//----- (0000B0A0) --------------------------------------------------------
int __fastcall sub_B0A0(int a1)
{
  int v2; // r0
  _BYTE s[516]; // [sp+14h] [bp-210h] BYREF
  int *v6; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 1;
  s[2] = 8;
  s[3] = 0;
  v6 = (int *)&s[4];
  v2 = sub_FD40(a1);
  *v6 = v2;
  if ( ioctl(fd, 0x82044708, s) < 0 )
    sub_FC54(3, "ioctl GET_PORT_STATE error\n");
  sub_FC54(5, "%s() Port %d state = %d\n", "Ssc_getPortState", *v6, v6[1]);
  return v6[1];
}

//----- (0000B19C) --------------------------------------------------------
int __fastcall sub_B19C(int a1, int a2, int a3)
{
  int result; // r0
  int v4; // r0
  char v5; // [sp+14h] [bp-220h]
  int v6; // [sp+18h] [bp-21Ch]
  _BYTE s[516]; // [sp+24h] [bp-210h] BYREF
  int *v9; // [sp+228h] [bp-Ch]
  int fd; // [sp+22Ch] [bp-8h]

  v6 = a2;
  v5 = a3;
  sub_FC54(5, "%s() %d >>>>>> port %d state %d, flags = 0x%02x\n", "Ssc_setPortState", 772, a1, a2, a3);
  result = sub_9C08();
  fd = result;
  if ( result >= 0 )
  {
    if ( (unsigned int)(v6 - 2) > 3 )
    {
      if ( (v5 & 1) != 0 )
      {
        v6 = 2;
      }
      else if ( (v5 & 4) != 0 )
      {
        v6 = 1;
      }
      else
      {
        v6 = 5;
      }
    }
    memset(s, 0, sizeof(s));
    s[0] = 1;
    s[2] = 8;
    s[3] = 0;
    v9 = (int *)&s[4];
    v4 = sub_FD40(a1);
    *v9 = v4;
    v9[1] = v6;
    if ( ioctl(fd, 0x42044709u, s) < 0 )
      sub_FC54(3, "ioctl SET_PORT_STATE error\n");
    return sub_FC54(5, "%s() Port %d state = %d\n", "Ssc_setPortState", *v9, v9[1]);
  }
  return result;
}

//----- (0000B330) --------------------------------------------------------
int __fastcall sub_B330(int a1, int a2)
{
  const char *v2; // r3
  char *v3; // r0
  int v5; // r0
  char s[128]; // [sp+14h] [bp-298h] BYREF
  _BYTE v10[516]; // [sp+94h] [bp-218h] BYREF
  int *v11; // [sp+298h] [bp-14h]
  int fd; // [sp+29Ch] [bp-10h]

  fd = 0;
  if ( a2 )
    v2 = "Enable";
  else
    v2 = "Disable";
  sub_FC54(7, "%s() %d >>>>>>> port %d %s\n", "Ssc_port_enable_set", 834, a1, v2);
  if ( a1 <= 7 )
  {
    fd = sub_9C08();
    if ( fd >= 0 )
    {
      memset(v10, 0, sizeof(v10));
      v10[0] = 0;
      v10[2] = 8;
      v10[3] = 0;
      v11 = (int *)&v10[4];
      v5 = sub_FD40(a1);
      *v11 = v5;
      v11[1] = a2;
      if ( ioctl(fd, 0x42044703u, v10) < 0 )
        sub_FC54(3, "%s() ioctl SET_PORT_STATE error\n", "Ssc_port_enable_set");
      return 0;
    }
    else
    {
      return -1;
    }
  }
  else
  {
    v3 = sub_F77C("port_enable");
    sprintf(s, " echo %x,%d > %s", a1, a2, v3);
    system(s);
    printf("msg = %s\n", s);
    return 0;
  }
}

//----- (0000B4C8) --------------------------------------------------------
int __fastcall Ssc_getPortLinkState(_DWORD *a1)
{
  char v2; // r0
  int v5; // [sp+8h] [bp-14h] BYREF
  int v6; // [sp+Ch] [bp-10h]
  int i; // [sp+10h] [bp-Ch]
  int fd; // [sp+14h] [bp-8h]

  v6 = 1;
  i = 0;
  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  if ( ioctl(fd, 0x8004470A, &v5) < 0 )
    sub_FC54(3, "ioctl ETHSW_LINK_STATUS_GET error\n");
  for ( i = 0; i <= 9; ++i )
  {
    v2 = sub_FD40(i);
    if ( ((1 << v2) & v5) != 0 )
      *a1 |= 1 << i;
  }
  return v6;
}

//----- (0000B5C0) --------------------------------------------------------
int __fastcall sub_B5C0(int a1)
{
  int v2; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v6; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 0;
  s[2] = 8;
  s[3] = 0;
  v6 = (int *)&s[4];
  v2 = sub_FD40(a1);
  *v6 = v2;
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_FC54(3, "%s() ioctl SET_PORT_STATE error\n", "Ssc_port_enable_get");
  return v6[1];
}

//----- (0000B698) --------------------------------------------------------
void *__fastcall Ssc_getPortStatsCounter(void *a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-218h] BYREF
  int *v7; // [sp+210h] [bp-14h]
  int fd; // [sp+214h] [bp-10h]

  fd = sub_9C08();
  if ( fd < 0 )
    fprintf((FILE *)stderr, "%s() device open failed\n", "Ssc_getPortStatsCounter");
  memset(s, 0, sizeof(s));
  s[0] = 0;
  strcpy(&s[2], "d");
  v7 = (int *)&s[4];
  v3 = sub_FD40(a2);
  *v7 = v3;
  if ( ioctl(fd, 0x80044714, s) < 0 )
    sub_FC54(3, "%s() ioctl GET_PORT_STATSCOUNTER error\n", "Ssc_getPortStatsCounter");
  memcpy(a1, v7 + 1, 0x60u);
  return a1;
}
// 1A270: using guessed type int stderr;

//----- (0000B7AC) --------------------------------------------------------
int __fastcall sub_B7AC(_DWORD *a1)
{
  pthread_mutex_lock(&mutex);
  *a1 = dword_1A2A4;
  dword_1A2A4 = 0;
  return pthread_mutex_unlock(&mutex);
}
// 1A2A4: using guessed type int dword_1A2A4;

//----- (0000B7F8) --------------------------------------------------------
int __fastcall sub_B7F8(int a1)
{
  pthread_mutex_lock(&mutex);
  dword_1A2A4 |= a1;
  return pthread_mutex_unlock(&mutex);
}
// 1A2A4: using guessed type int dword_1A2A4;

//----- (0000B840) --------------------------------------------------------
int __fastcall sub_B840(int a1)
{
  int result; // r0
  int v3; // [sp+10h] [bp-214h] BYREF
  _BYTE s[516]; // [sp+14h] [bp-210h] BYREF
  _BYTE *v5; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  sub_FC54(5, "%s() %d pbmp = %lx\n", "Ssc_flushMacAddr", 979, a1);
  result = sub_9C08();
  fd = result;
  if ( result >= 0 )
  {
    memset(s, 0, sizeof(s));
    s[0] = 1;
    s[2] = 12;
    s[3] = 0;
    v5 = &s[4];
    sub_FEFC(a1, &v3);
    *((_DWORD *)v5 + 2) = v3;
    if ( ioctl(fd, 0x42044705u, s) < 0 )
      sub_FC54(3, "ioctl ETHSW_FDB_FLUSH error\n");
    return sub_B7F8(a1);
  }
  return result;
}

//----- (0000B940) --------------------------------------------------------
int __fastcall sub_B940(int a1)
{
  _DWORD s[130]; // [sp+Ch] [bp-210h] BYREF
  int fd; // [sp+214h] [bp-8h]

  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, 0x204u);
  LOBYTE(s[0]) = 8;
  HIWORD(s[0]) = 4;
  s[129] = &s[1];
  s[1] = a1;
  if ( ioctl(fd, 0x42044705u, s) < 0 )
    sub_FC54(3, "ioctl ETHSW_TYPE_FDB_AGE_TIME error\n");
  return 0;
}

//----- (0000BA04) --------------------------------------------------------
int sub_BA04()
{
  _DWORD s[129]; // [sp+0h] [bp-214h] BYREF
  int v3; // [sp+204h] [bp-10h]
  _DWORD *v4; // [sp+208h] [bp-Ch]
  int fd; // [sp+20Ch] [bp-8h]

  v3 = 0;
  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  LOBYTE(s[0]) = 0;
  HIWORD(s[0]) = 4;
  v4 = &s[1];
  s[1] = 1;
  if ( ioctl(fd, 0x82044704, s, s) < 0 )
    sub_FC54(3, "%s() ioctl ETHSW_FDB_GET error\n", "Ssc_fdbGetEntry");
  return v3;
}

//----- (0000BAD4) --------------------------------------------------------
int __fastcall sub_BAD4(const void *a1, _DWORD *a2)
{
  int v6; // [sp+8h] [bp-21Ch] BYREF
  _BYTE s[516]; // [sp+Ch] [bp-218h] BYREF
  int v8; // [sp+210h] [bp-14h]
  int fd; // [sp+214h] [bp-10h]
  void *dest; // [sp+218h] [bp-Ch]
  int v11; // [sp+21Ch] [bp-8h]

  v8 = 0;
  v11 = 0;
  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  v6 = 0;
  memset(s, 0, sizeof(s));
  s[0] = 7;
  s[2] = 28;
  s[3] = 0;
  dest = &s[4];
  memcpy(&s[4], a1, 6u);
  if ( ioctl(fd, 0x82044704, s) < 0 )
    sub_FC54(3, "%s() ioctl ETHSW_FDB_GET error\n", "Ssc_fdbGetMacPbmp");
  v8 = *((unsigned __int8 *)dest + 25);
  if ( v8 )
    sub_FFE4(*((_DWORD *)dest + 3), &v6);
  *a2 = v6;
  return v8;
}

//----- (0000BC00) --------------------------------------------------------
int __fastcall sub_BC00(const void *a1, void *a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+2Ch] [bp-228h] BYREF
  int v8; // [sp+230h] [bp-24h]
  int fd; // [sp+234h] [bp-20h]
  void *dest; // [sp+238h] [bp-1Ch]
  int i; // [sp+23Ch] [bp-18h]

  v8 = 0;
  i = 0;
  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 7;
  s[2] = 28;
  s[3] = 0;
  dest = &s[4];
  memcpy(&s[4], a1, 6u);
  if ( ioctl(fd, 0x82044704, s) < 0 )
    sub_FC54(3, "%s() ioctl ETHSW_FDB_GET error\n", "Ssc_fdbFindMacEntry");
  v8 = *((unsigned __int8 *)dest + 25);
  if ( v8 )
  {
    for ( i = 0; i <= 9; ++i )
    {
      if ( (*((_DWORD *)dest + 3) & (1 << i)) != 0 )
      {
        v3 = sub_FE0C(i);
        *((_DWORD *)dest + 2) = v3;
        break;
      }
    }
    memcpy(a2, dest, 0x1Cu);
  }
  printf(
    "%s() addr = %02x:%02x:%02x:%02x:%02x:%02x, port = %02x (%d), inused = %d\n",
    "Ssc_fdbFindMacEntry",
    *(unsigned __int8 *)dest,
    *((unsigned __int8 *)dest + 1),
    *((unsigned __int8 *)dest + 2),
    *((unsigned __int8 *)dest + 3),
    *((unsigned __int8 *)dest + 4),
    *((unsigned __int8 *)dest + 5),
    *((_DWORD *)dest + 3),
    *((_DWORD *)dest + 2),
    *((unsigned __int8 *)dest + 25));
  return v8;
}

//----- (0000BDF8) --------------------------------------------------------
int __fastcall sub_BDF8(const void *a1, void *a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+2Ch] [bp-228h] BYREF
  int v8; // [sp+230h] [bp-24h]
  int fd; // [sp+234h] [bp-20h]
  void *dest; // [sp+238h] [bp-1Ch]
  int i; // [sp+23Ch] [bp-18h]

  v8 = 0;
  i = 0;
  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 7;
  s[2] = 28;
  s[3] = 0;
  dest = &s[4];
  memcpy(&s[4], a1, 6u);
  if ( ioctl(fd, 0x82044704, s) < 0 )
    sub_FC54(3, "%s() ioctl ETHSW_FDB_GET error\n", "Ssc_fdbFindAllMacEntry");
  v8 = *((unsigned __int8 *)dest + 25);
  if ( v8 )
  {
    for ( i = 0; i <= 13; ++i )
    {
      if ( (*((_DWORD *)dest + 3) & (1 << i)) != 0 )
      {
        v3 = sub_FE0C(i);
        *((_DWORD *)dest + 2) = v3;
        break;
      }
    }
    memcpy(a2, dest, 0x1Cu);
  }
  printf(
    "%s() addr = %02x:%02x:%02x:%02x:%02x:%02x, port = %02x (%d), inused = %d\n",
    "Ssc_fdbFindAllMacEntry",
    *(unsigned __int8 *)dest,
    *((unsigned __int8 *)dest + 1),
    *((unsigned __int8 *)dest + 2),
    *((unsigned __int8 *)dest + 3),
    *((unsigned __int8 *)dest + 4),
    *((unsigned __int8 *)dest + 5),
    *((_DWORD *)dest + 3),
    *((_DWORD *)dest + 2),
    *((unsigned __int8 *)dest + 25));
  return v8;
}

//----- (0000BFF0) --------------------------------------------------------
int __fastcall sub_BFF0(_DWORD *a1)
{
  int v2; // r4
  _BYTE s[516]; // [sp+8h] [bp-21Ch] BYREF
  int v6; // [sp+20Ch] [bp-18h]
  int *v7; // [sp+210h] [bp-14h]
  int fd; // [sp+214h] [bp-10h]

  v6 = 0;
  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 6;
  s[2] = 16;
  s[3] = 0;
  v7 = (int *)&s[4];
  if ( ioctl(fd, 0x82044704, s) < 0 )
    sub_FC54(3, "%s() ioctl ETHSW_FDB_GET error\n", "Ssc_fdbGetAddrTableSize");
  v6 = *v7;
  v2 = v7[3];
  *a1 = v7[2];
  a1[1] = v2;
  return v6;
}

//----- (0000C0D8) --------------------------------------------------------
int __fastcall sub_C0D8(char *a1, size_t a2, int a3)
{
  unsigned int v4; // r0
  int v5; // r4
  _BYTE v10[14336]; // [sp+10h] [bp-3834h] BYREF
  int v11; // [sp+3810h] [bp-34h] BYREF
  int v12; // [sp+3814h] [bp-30h]
  int fd; // [sp+3818h] [bp-2Ch]
  ssize_t v14; // [sp+381Ch] [bp-28h]
  int v15; // [sp+3820h] [bp-24h]
  int i; // [sp+3824h] [bp-20h]
  int v17; // [sp+3828h] [bp-1Ch]
  int v18; // [sp+382Ch] [bp-18h]
  int v19; // [sp+3830h] [bp-14h]
  int v20; // [sp+3834h] [bp-10h]

  fd = 0;
  v14 = 0;
  v15 = 0;
  i = 0;
  v17 = 0;
  v18 = 0;
  v19 = 0;
  v20 = 0;
  v11 = 0;
  v12 = 0;
  if ( a1 )
  {
    fd = sub_9C08();
    if ( fd >= 0 )
    {
      memset(v10, 0, sizeof(v10));
      v17 = sub_BFF0(&v11);
      if ( v17 > 511 )
        v18 = 512;
      else
        v18 = v17;
      if ( v11 == unk_1A2C0 && v12 == unk_1A2C4 )
      {
LABEL_10:
        sub_9C9C();
        return dword_1A2C8;
      }
      else
      {
        memset(a1, 0, a2);
        dword_1A2C8 = 0;
        unk_1A2C0 = v11;
        unk_1A2C4 = v12;
        while ( 1 )
        {
          v14 = read(fd, v10, 28 * v18);
          if ( v14 == -1 )
            break;
          v4 = sub_100CC(v14, 0x1Cu);
          v15 += v4;
          for ( i = 0; i < v18; ++i )
          {
            if ( a3 )
            {
              if ( v10[28 * i] == 1
                && (unsigned __int8)v10[28 * i + 1] == 128
                && (unsigned __int8)v10[28 * i + 2] == 194 )
              {
                continue;
              }
              v5 = *(_DWORD *)&v10[28 * i + 12];
              if ( (v5 & (1 << sub_FD40(14))) != 0 )
                continue;
            }
            memcpy(&a1[92 * dword_1A2C8], &v10[28 * i], 6u);
            if ( a1[92 * dword_1A2C8] == 1 )
            {
              strcpy(&a1[92 * dword_1A2C8 + 6], "mcast");
              strcpy(&a1[92 * dword_1A2C8 + 14], "static");
            }
            else
            {
              strcpy(&a1[92 * dword_1A2C8 + 6], "ucast");
              if ( *(_DWORD *)&v10[28 * i + 16] == 1 )
                strcpy(&a1[92 * dword_1A2C8 + 14], "learn");
              else
                strcpy(&a1[92 * dword_1A2C8 + 14], "static");
            }
            a1[92 * dword_1A2C8 + 32] = v10[28 * i + 26];
            sub_FFE4(*(_DWORD *)&v10[28 * i + 12], &a1[92 * dword_1A2C8 + 28]);
            ++dword_1A2C8;
          }
          if ( v15 >= v17 )
            goto LABEL_10;
          v19 = v17 - v15;
          if ( v17 - v15 <= 512 )
            v18 = v19;
          else
            v18 = 512;
        }
        fprintf((FILE *)stderr, "%s() %d read error\n", "Ssc_fdbGetAddrTable", 1260);
        return -1;
      }
    }
    else
    {
      return -1;
    }
  }
  else
  {
    fprintf((FILE *)stderr, "%s() %d Invalid argument\n", "Ssc_fdbGetAddrTable", 1228);
    return -1;
  }
}
// 1A270: using guessed type int stderr;
// 1A2C8: using guessed type int dword_1A2C8;

//----- (0000C88C) --------------------------------------------------------
int __fastcall sub_C88C(const void *a1, char a2, int a3)
{
  int result; // r0
  int v7; // [sp+18h] [bp-214h] BYREF
  _BYTE s[516]; // [sp+1Ch] [bp-210h] BYREF
  void *dest; // [sp+220h] [bp-Ch]
  int fd; // [sp+224h] [bp-8h]

  sub_FC54(5, "%s() %d lpbmp = %lx\n", "Ssc_fdbAddUcastEntry", 1338, a3);
  result = sub_9C08();
  fd = result;
  if ( result >= 0 )
  {
    memset(s, 0, sizeof(s));
    v7 = 0;
    s[0] = 3;
    s[2] = 16;
    s[3] = 0;
    dest = &s[4];
    memcpy(&s[4], a1, 6u);
    sub_FEFC(a3, &v7);
    *((_DWORD *)dest + 2) = v7;
    *((_BYTE *)dest + 13) = a2;
    result = ioctl(fd, 0x42044705u, s);
    if ( result < 0 )
      return sub_FC54(3, "ioctl ETHSW_FDB_SET error\n");
  }
  return result;
}

//----- (0000C9BC) --------------------------------------------------------
int __fastcall sub_C9BC(const void *a1, int a2, int a3)
{
  int result; // r0
  int v7; // [sp+18h] [bp-214h] BYREF
  _BYTE s[516]; // [sp+1Ch] [bp-210h] BYREF
  _BYTE *v9; // [sp+220h] [bp-Ch]
  int fd; // [sp+224h] [bp-8h]

  sub_FC54(5, "%s() %d lpbmp = %lx\n", "Ssc_setMgmtFrame", 1386, a3);
  result = sub_9C08();
  fd = result;
  if ( result >= 0 )
  {
    memset(s, 0, sizeof(s));
    v7 = 0;
    s[0] = 2;
    s[2] = 20;
    s[3] = 0;
    v9 = &s[4];
    memcpy(&s[8], a1, 6u);
    sub_FEFC(a3, &v7);
    *((_DWORD *)v9 + 3) = v7;
    *(_DWORD *)v9 = a2;
    if ( a2 )
    {
      v9[16] = a2;
      v9[17] = 7;
    }
    result = ioctl(fd, 0x42044705u, s);
    if ( result < 0 )
      return sub_FC54(3, "ioctl ETHSW_FDB_SET error\n");
  }
  return result;
}

//----- (0000CB14) --------------------------------------------------------
int sub_CB14()
{
  sub_FC54(7, "%s() %d\n", "Ssc_enable_manage_port", 1429);
  return sub_C9BC(off_1A1F8, 1, 0x4000);
}
// 1A1F8: using guessed type _UNKNOWN *off_1A1F8;

//----- (0000CB6C) --------------------------------------------------------
int sub_CB6C()
{
  sub_FC54(7, "%s() %d\n", "Ssc_disable_manage_port", 1447);
  return sub_C9BC(off_1A1F8, 0, 0);
}
// 1A1F8: using guessed type _UNKNOWN *off_1A1F8;

//----- (0000CBC4) --------------------------------------------------------
int sub_CBC4()
{
  return sub_E2F4(off_1A1F8, 0);
}
// 1A1F8: using guessed type _UNKNOWN *off_1A1F8;

//----- (0000CBE8) --------------------------------------------------------
int __fastcall sub_CBE8(int a1, const void *a2, int a3)
{
  sub_FC54(5, "%s() %d lpbmp = 0x%lx\n", "Ssc_enable_manage_multiport", 1464, a3);
  return sub_C9BC(a2, 1, a3);
}

//----- (0000CC40) --------------------------------------------------------
int __fastcall sub_CC40(int a1, const void *a2, int a3)
{
  sub_FC54(5, "%s() %d lpbmp = 0x%lx\n", "Ssc_disable_manage_multiport", 1473, a3);
  return sub_C9BC(a2, 1, 0x4000);
}

//----- (0000CCAC) --------------------------------------------------------
int __fastcall sub_CCAC(int a1, const void *a2)
{
  sub_FC54(7, "%s() %d\n", "Ssc_delete_manage_multiport", 1484);
  return sub_C9BC(a2, 0, 0);
}

//----- (0000CD04) --------------------------------------------------------
int __fastcall sub_CD04(int a1)
{
  _BYTE s[516]; // [sp+14h] [bp-210h] BYREF
  _BYTE *v4; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  sub_FC54(7, "%s() %d >>>>>>> port %d\n", "Ssc_cpuGetRate", 1500, a1);
  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 6;
  s[2] = 8;
  s[3] = 0;
  v4 = &s[4];
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_FC54(3, "%s() ioctl error\n", "Ssc_cpuGetRate");
  return 0;
}

//----- (0000CDE8) --------------------------------------------------------
int __fastcall sub_CDE8(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+14h] [bp-210h] BYREF
  int *v8; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  sub_FC54(7, "%s() %d >>>>>>> port %d %d\n", "Ssc_cpuSetRate", 1526, a1, a2);
  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 6;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_FD40(a1);
  *v8 = v3;
  v8[1] = a2;
  if ( ioctl(fd, 0x42044703u, s) < 0 )
    sub_FC54(3, "%s() ioctl error\n", "Ssc_cpuSetRate");
  return 0;
}

//----- (0000CEF8) --------------------------------------------------------
int __fastcall sub_CEF8(_DWORD *a1, int a2)
{
  int v3; // r0
  _DWORD s[129]; // [sp+8h] [bp-214h] BYREF
  int i; // [sp+20Ch] [bp-10h]
  _DWORD *v9; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  LOBYTE(s[0]) = 0;
  HIWORD(s[0]) = 16;
  v9 = &s[1];
  s[3] = a2;
  s[1] = -1;
  s[4] = 0;
  for ( i = 0; i <= 13; ++i )
  {
    if ( (*a1 & (1 << i)) != 0 )
    {
      v3 = sub_FD40(i);
      v9[1] = v3;
      if ( ioctl(fd, 0x4204470Du, s) < 0 )
        sub_FC54(3, "%s() ioctl error\n", "Ssc_mirrorport_reset");
    }
  }
  return 0;
}

//----- (0000D038) --------------------------------------------------------
int __fastcall sub_D038(_DWORD *a1, unsigned __int8 a2, int a3, int a4)
{
  int v5; // r0
  _DWORD s[129]; // [sp+10h] [bp-214h] BYREF
  int i; // [sp+214h] [bp-10h]
  int *v13; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  i = 0;
  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  LOBYTE(s[0]) = 0;
  HIWORD(s[0]) = 16;
  v13 = &s[1];
  s[3] = a3;
  if ( a4 )
    *v13 = sub_FD40(a2 - 1);
  else
    *v13 = -1;
  v13[3] = a4;
  for ( i = 0; i <= 13; ++i )
  {
    if ( (*a1 & (1 << i)) != 0 )
    {
      v5 = sub_FD40(i);
      v13[1] = v5;
      if ( ioctl(fd, 0x4204470Du, s) < 0 )
        sub_FC54(3, "%s() ioctl error\n", "Ssc_mirrorport_enable_set");
    }
  }
  return 0;
}

//----- (0000D1B8) --------------------------------------------------------
int __fastcall sub_D1B8(_DWORD *a1, int a2, int a3)
{
  int v4; // r0
  _DWORD s[129]; // [sp+14h] [bp-218h] BYREF
  int i; // [sp+218h] [bp-14h]
  int v11; // [sp+21Ch] [bp-10h]
  _DWORD *v12; // [sp+220h] [bp-Ch]
  int fd; // [sp+224h] [bp-8h]

  v11 = 0;
  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  LOBYTE(s[0]) = 1;
  HIWORD(s[0]) = 16;
  v12 = &s[1];
  s[3] = a2;
  s[1] = -1;
  s[4] = a3;
  for ( i = 0; i <= 13; ++i )
  {
    if ( (*a1 & (1 << i)) != 0 )
    {
      v4 = sub_FD40(i);
      v12[1] = v4;
      if ( ioctl(fd, 0x4204470Du, s) < 0 )
        sub_FC54(3, "%s() ioctl error\n", "Ssc_targetport_reset");
    }
  }
  return 0;
}

//----- (0000D304) --------------------------------------------------------
int __fastcall sub_D304(_DWORD *a1, int a2, int a3)
{
  int v4; // r0
  _DWORD s[134]; // [sp+10h] [bp-22Ch] BYREF
  int i; // [sp+228h] [bp-14h]
  _DWORD *v11; // [sp+230h] [bp-Ch]
  int fd; // [sp+234h] [bp-8h]

  s[129] = 0;
  s[130] = 0;
  s[132] = 0;
  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, 0x204u);
  LOBYTE(s[0]) = 1;
  HIWORD(s[0]) = 16;
  v11 = &s[1];
  s[3] = a2;
  s[1] = -1;
  s[4] = a3;
  for ( i = 0; i <= 13; ++i )
  {
    if ( (*a1 & (1 << i)) != 0 )
    {
      v4 = sub_FD40(i);
      v11[1] = v4;
      if ( ioctl(fd, 0x4204470Du, s) < 0 )
        sub_FC54(3, "%s() ioctl error\n", "Ssc_targetport_enable_set");
    }
  }
  return 0;
}

//----- (0000D460) --------------------------------------------------------
void sub_D460()
{
  ;
}

//----- (0000D474) --------------------------------------------------------
int __fastcall sub_D474(int a1)
{
  _DWORD s[130]; // [sp+Ch] [bp-210h] BYREF
  int fd; // [sp+214h] [bp-8h]

  puts("Ssc_setQosSchedulingMode");
  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, 0x204u);
  LOBYTE(s[0]) = 0;
  HIWORD(s[0]) = 4;
  s[129] = &s[1];
  s[1] = a1;
  if ( ioctl(fd, 0x42044711u, s) < 0 )
    sub_FC54(3, "ioctl ETHSW_TYPE_QOS_SCHEDULING_MODE error\n");
  return 0;
}

//----- (0000D540) --------------------------------------------------------
int __fastcall sub_D540(int result)
{
  int v1; // [sp+4h] [bp-10h]
  int i; // [sp+Ch] [bp-8h]

  v1 = result;
  for ( i = 0; i <= 9; ++i )
  {
    if ( ((1 << i) & v1) != 0 )
      result = sub_D638(i, 1);
    else
      result = sub_D638(i, 0);
  }
  return result;
}

//----- (0000D5BC) --------------------------------------------------------
int __fastcall sub_D5BC(int result)
{
  int v1; // [sp+4h] [bp-10h]
  int i; // [sp+Ch] [bp-8h]

  v1 = result;
  for ( i = 0; i <= 9; ++i )
  {
    if ( ((1 << i) & v1) != 0 )
      result = sub_D718(i, 1);
    else
      result = sub_D718(i, 0);
  }
  return result;
}

//----- (0000D638) --------------------------------------------------------
int __fastcall sub_D638(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 1;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_FD40(a1);
  *v8 = v3;
  v8[1] = a2;
  if ( ioctl(fd, 0x42044711u, s) < 0 )
    sub_FC54(3, "%s() ioctl error\n", "Ssc_port_tos_set");
  return 0;
}

//----- (0000D718) --------------------------------------------------------
int __fastcall sub_D718(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 2;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_FD40(a1);
  *v8 = v3;
  v8[1] = a2;
  if ( ioctl(fd, 0x42044711u, s) < 0 )
    sub_FC54(3, "%s() ioctl error\n", "Ssc_port_cos_set");
  return 0;
}

//----- (0000D7F8) --------------------------------------------------------
int __fastcall sub_D7F8(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+14h] [bp-210h] BYREF
  int *v8; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  sub_FC54(7, "%s() %d >>>>>>> port %d %d\n", "Ssc_port_priority_set", 1861, a1, a2);
  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 3;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_FD40(a1);
  *v8 = v3;
  v8[1] = a2;
  if ( ioctl(fd, 0x42044711u, s) < 0 )
    sub_FC54(3, "%s() ioctl error\n", "Ssc_port_priority_set");
  return 0;
}

//----- (0000D904) --------------------------------------------------------
int __fastcall sub_D904(int a1)
{
  _BYTE s[516]; // [sp+8h] [bp-214h] BYREF
  int *v5; // [sp+20Ch] [bp-10h]
  int fd; // [sp+210h] [bp-Ch]
  int i; // [sp+214h] [bp-8h]

  i = 0;
  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 4;
  s[2] = 8;
  s[3] = 0;
  v5 = (int *)&s[4];
  for ( i = 0; i <= 7; ++i )
  {
    *v5 = i;
    v5[1] = *(_DWORD *)(a1 + 4 * i);
    if ( ioctl(fd, 0x42044711u, s) < 0 )
      sub_FC54(3, "ioctl ETHSW_TYPE_QOS_SCHEDULING_MODE error\n");
  }
  return 0;
}

//----- (0000DA0C) --------------------------------------------------------
int __fastcall sub_DA0C(int a1, int a2, const void *a3)
{
  _DWORD s[130]; // [sp+10h] [bp-21Ch] BYREF
  int fd; // [sp+218h] [bp-14h]
  int v10; // [sp+21Ch] [bp-10h]

  v10 = 0;
  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, 0x204u);
  LOBYTE(s[0]) = 5;
  HIWORD(s[0]) = 264;
  s[129] = &s[1];
  s[1] = a1;
  s[2] = a2;
  memcpy(&s[3], a3, 0x100u);
  if ( ioctl(fd, 0x42044711u, s) < 0 )
    sub_FC54(3, "ioctl ETHSW_TYPE_QOS_SCHEDULING_MODE error\n");
  return 0;
}

//----- (0000DB24) --------------------------------------------------------
void sub_DB24()
{
  ;
}

//----- (0000DB40) --------------------------------------------------------
int __fastcall sub_DB40(int a1, _DWORD *a2, _DWORD *a3)
{
  _DWORD s[129]; // [sp+1Ch] [bp-210h] BYREF
  _DWORD *v9; // [sp+220h] [bp-Ch]
  int fd; // [sp+224h] [bp-8h]

  sub_FC54(7, "%s() %d >>>>>>> vid %d\n", "Ssc_getVlanPortmap", 2011, a1);
  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  LOBYTE(s[0]) = 0;
  HIWORD(s[0]) = 12;
  v9 = &s[1];
  s[1] = a1;
  if ( ioctl(fd, 0x82044706, s) >= 0 )
  {
    sub_FFE4(v9[1], a2);
    sub_FFE4(v9[2], a3);
    printf("vid=%d, tagged=%x, untagged=%x\r\n", a1, *a2, *a3);
    return 0;
  }
  else
  {
    sub_FC54(3, "%s() ioctl error\n", "Ssc_getVlanPortmap");
    return -1;
  }
}

//----- (0000DC8C) --------------------------------------------------------
int __fastcall sub_DC8C(int a1, int a2)
{
  int v6; // [sp+14h] [bp-218h] BYREF
  int v7; // [sp+18h] [bp-214h] BYREF
  _DWORD s[129]; // [sp+1Ch] [bp-210h] BYREF
  _DWORD *v9; // [sp+220h] [bp-Ch]
  int fd; // [sp+224h] [bp-8h]

  fd = 0;
  sub_FC54(7, "%s() %d >>>>>>> vid %d enable = %d\n", "Ssc_vlanEnableCpuPort", 2043, a1, a2);
  if ( a1 > 0 && a1 <= 4094 )
  {
    fd = sub_9C08();
    if ( fd >= 0 )
    {
      v7 = 0;
      v6 = 0;
      memset(s, 0, sizeof(s));
      sub_DB40(a1, &v7, &v6);
      LOBYTE(s[0]) = 1;
      HIWORD(s[0]) = 12;
      v9 = &s[1];
      s[1] = a1;
      if ( a2 )
        v7 |= 0x4000u;
      else
        v7 &= ~0x4000u;
      sub_FEFC(v7, v9 + 1);
      sub_FEFC(v6, v9 + 2);
      if ( ioctl(fd, 0x82044707, s) >= 0 )
      {
        return 0;
      }
      else
      {
        sub_FC54(3, "%s() ioctl error\n", "Ssc_vlanEnableCpuPort");
        return -1;
      }
    }
    else
    {
      return -1;
    }
  }
  else
  {
    printf("%s() %d Invalid vid = %d\n", "Ssc_vlanEnableCpuPort", 2046, a1);
    return -1;
  }
}

//----- (0000DE58) --------------------------------------------------------
int sub_DE58()
{
  _BYTE s[516]; // [sp+4h] [bp-210h] BYREF
  _BYTE *v3; // [sp+208h] [bp-Ch]
  int fd; // [sp+20Ch] [bp-8h]

  sub_FC54(7, "%s() %d \n", "Ssc_vlanGetTable", 2089);
  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 2;
  s[2] = 12;
  s[3] = 0;
  v3 = &s[4];
  if ( ioctl(fd, 0x82044706, s) >= 0 )
  {
    printf("%s() %d \n", "Ssc_vlanGetTable", 2106);
    return 0;
  }
  else
  {
    sub_FC54(3, "%s() ioctl error\n", "Ssc_vlanGetTable");
    return -1;
  }
}

//----- (0000DF50) --------------------------------------------------------
int sub_DF50()
{
  int v1; // r0
  _BYTE s[516]; // [sp+8h] [bp-214h] BYREF
  int i; // [sp+20Ch] [bp-10h]
  int *v5; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  for ( i = 0; i <= 9; ++i )
  {
    sub_FC54(7, "%s() %d >>>>>>> port %d\n", "Ssc_initIgmpsnooping", 2133, i);
    memset(s, 0, sizeof(s));
    s[0] = 5;
    s[2] = 8;
    s[3] = 0;
    v5 = (int *)&s[4];
    v1 = sub_FD40(i);
    *v5 = v1;
    v5[1] = 1;
    if ( ioctl(fd, 0x42044703u, s) < 0 )
    {
      sub_FC54(3, "%s() ioctl error\n", "Ssc_initIgmpsnooping");
      return -1;
    }
  }
  return 0;
}

//----- (0000E07C) --------------------------------------------------------
int sub_E07C()
{
  int v1; // r0
  _BYTE s[516]; // [sp+8h] [bp-214h] BYREF
  int i; // [sp+20Ch] [bp-10h]
  int *v5; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  for ( i = 0; i <= 9; ++i )
  {
    sub_FC54(7, "%s() %d >>>>>>> port %d %d\n", "Ssc_destroyIgmpsnooping", 2169, i, 0);
    memset(s, 0, sizeof(s));
    s[0] = 5;
    s[2] = 8;
    s[3] = 0;
    v5 = (int *)&s[4];
    v1 = sub_FD40(i);
    *v5 = v1;
    v5[1] = 0;
    if ( ioctl(fd, 0x42044703u, s) < 0 )
    {
      sub_FC54(3, "%s() ioctl error\n", "Ssc_destroyIgmpsnooping");
      return -1;
    }
  }
  return 0;
}

//----- (0000E1B0) --------------------------------------------------------
void sub_E1B0()
{
  ;
}

//----- (0000E1C4) --------------------------------------------------------
int __fastcall sub_E1C4(const void *a1, int a2, int a3)
{
  _DWORD s[129]; // [sp+10h] [bp-214h] BYREF
  int v8; // [sp+214h] [bp-10h]
  _DWORD *v9; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  v8 = 0;
  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  LOBYTE(s[0]) = 2;
  HIWORD(s[0]) = 20;
  v9 = &s[1];
  memcpy(&s[2], a1, 6u);
  sub_FEFC(a3, &s[4]);
  if ( ioctl(fd, 0x42044705u, s) >= 0 )
  {
    if ( v8 )
      sub_FC54(3, "%s: bcm_mcast_addr_add fail err=%d\n", "Ssc_mcastAddrAdd", v8);
    return v8;
  }
  else
  {
    sub_FC54(3, "ioctl ETHSW_FDB_SET error\n");
    return -1;
  }
}

//----- (0000E2F4) --------------------------------------------------------
int __fastcall sub_E2F4(const void *a1, __int16 a2)
{
  _BYTE s[520]; // [sp+8h] [bp-214h] BYREF
  int fd; // [sp+210h] [bp-Ch]
  _BYTE *v8; // [sp+214h] [bp-8h]

  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, 0x204u);
  if ( (unsigned __int8)a2 | (__int16)(HIBYTE(a2) << 8) )
    s[0] = 2;
  else
    s[0] = 5;
  s[2] = 20;
  s[3] = 0;
  v8 = &s[4];
  memcpy(&s[8], a1, 6u);
  if ( ioctl(fd, 0x42044705u, s) >= 0 )
    return 0;
  sub_FC54(3, "ioctl ETHSW_FDB_SET error\n");
  return -1;
}

//----- (0000E434) --------------------------------------------------------
int __fastcall sub_E434(int a1)
{
  _DWORD s[129]; // [sp+Ch] [bp-210h] BYREF
  int fd; // [sp+210h] [bp-Ch]
  _DWORD *v6; // [sp+214h] [bp-8h]

  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  LOBYTE(s[0]) = 1;
  HIWORD(s[0]) = 4;
  v6 = &s[1];
  s[1] = a1;
  if ( ioctl(fd, 0x4204470Fu, s) < 0 )
    sub_FC54(3, "%s() ioctl ETHSW_PORT_TRUNK_SET error\n", "Ssc_trunkSetHashMode");
  return 0;
}

//----- (0000E500) --------------------------------------------------------
int sub_E500()
{
  _BYTE s[516]; // [sp+4h] [bp-210h] BYREF
  int fd; // [sp+208h] [bp-Ch]
  _BYTE *v4; // [sp+20Ch] [bp-8h]

  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 0;
  s[2] = 8;
  s[3] = 0;
  v4 = &s[4];
  if ( ioctl(fd, 0x8204470E, s) < 0 )
    sub_FC54(3, "%s() ioctl ETHSW_PORT_TRUNK_GET error\n", "Ssc_trunkGetInfo");
  return 0;
}

//----- (0000E5BC) --------------------------------------------------------
int __fastcall sub_E5BC(int a1, int a2)
{
  int v6; // [sp+8h] [bp-214h] BYREF
  _DWORD s[129]; // [sp+Ch] [bp-210h] BYREF
  int fd; // [sp+210h] [bp-Ch]
  _DWORD *v9; // [sp+214h] [bp-8h]

  printf("%s() %d %x\n", "Ssc_trunkSetMember", a1, a2);
  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  LOBYTE(s[0]) = 2;
  HIWORD(s[0]) = 8;
  v9 = &s[1];
  s[1] = a1;
  sub_FEFC(a2, &v6);
  v9[1] = v6;
  if ( ioctl(fd, 0x4204470Fu, s) < 0 )
    sub_FC54(3, "%s() ioctl ETHSW_PORT_TRUNK_SET error\n", "Ssc_trunkSetMember");
  return 0;
}

//----- (0000E6C4) --------------------------------------------------------
int __fastcall sub_E6C4(int a1, int a2)
{
  int v6; // [sp+8h] [bp-214h] BYREF
  _DWORD s[129]; // [sp+Ch] [bp-210h] BYREF
  int fd; // [sp+210h] [bp-Ch]
  _DWORD *v9; // [sp+214h] [bp-8h]

  printf("%s() %d %x\n", "Ssc_trunkClearMember", a1, a2);
  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  LOBYTE(s[0]) = 3;
  HIWORD(s[0]) = 8;
  v9 = &s[1];
  s[1] = a1;
  sub_FEFC(a2, &v6);
  v9[1] = v6;
  if ( ioctl(fd, 0x4204470Fu, s) < 0 )
    sub_FC54(3, "%s() ioctl ETHSW_PORT_TRUNK_SET error\n", "Ssc_trunkClearMember");
  return 0;
}

//----- (0000E7CC) --------------------------------------------------------
int __fastcall sub_E7CC(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 0;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_FD40(a1);
  *v8 = v3;
  v8[1] = a2;
  if ( ioctl(fd, 0x42044713u, s) < 0 )
    sub_FC54(3, "%s() ioctl error\n", "Ssc_setIngressRateLimitMode");
  return 0;
}

//----- (0000E8AC) --------------------------------------------------------
int __fastcall sub_E8AC(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 1;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_FD40(a1);
  *v8 = v3;
  v8[1] = a2;
  if ( ioctl(fd, 0x42044713u, s) < 0 )
    sub_FC54(3, "%s() ioctl error\n", "Ssc_setIngressRateLimit");
  return 0;
}

//----- (0000E98C) --------------------------------------------------------
int __fastcall sub_E98C(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 2;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_FD40(a1);
  *v8 = v3;
  v8[1] = a2;
  if ( ioctl(fd, 0x42044713u, s) < 0 )
    sub_FC54(3, "%s() ioctl error\n", "Ssc_setEgressRateLimit");
  return 0;
}

//----- (0000EA6C) --------------------------------------------------------
int __fastcall sub_EA6C(int a1)
{
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  _BYTE *v5; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 14;
  s[2] = 8;
  s[3] = 0;
  v5 = &s[4];
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_FC54(3, "%s() ioctl error\n", "Ssc_cpu_qinq_get");
  *(_DWORD *)a1 = *((_DWORD *)v5 + 1);
  return *(_DWORD *)a1;
}

//----- (0000EB40) --------------------------------------------------------
int __fastcall sub_EB40(int a1)
{
  _DWORD s[131]; // [sp+8h] [bp-214h] BYREF
  int fd; // [sp+214h] [bp-8h]

  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, 0x204u);
  LOBYTE(s[0]) = 14;
  HIWORD(s[0]) = 8;
  s[130] = &s[1];
  s[2] = a1;
  if ( ioctl(fd, 0x42044703u, s) < 0 )
    sub_FC54(3, "%s() ioctl error\n", "Ssc_cpu_qinq_set");
  return 0;
}

//----- (0000EC0C) --------------------------------------------------------
int __fastcall sub_EC0C(int a1)
{
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  _BYTE *v5; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 15;
  s[2] = 8;
  s[3] = 0;
  v5 = &s[4];
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_FC54(3, "%s() ioctl error\n", "Ssc_cpu_egress_get");
  *(_DWORD *)a1 = *((_DWORD *)v5 + 1);
  return *(_DWORD *)a1;
}

//----- (0000ECE0) --------------------------------------------------------
int __fastcall sub_ECE0(int a1)
{
  _DWORD s[131]; // [sp+8h] [bp-214h] BYREF
  int fd; // [sp+214h] [bp-8h]

  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, 0x204u);
  LOBYTE(s[0]) = 15;
  HIWORD(s[0]) = 8;
  s[130] = &s[1];
  s[2] = a1;
  if ( ioctl(fd, 0x42044703u, s) < 0 )
    sub_FC54(3, "%s() ioctl error\n", "Ssc_cpu_egress_set");
  return 0;
}

//----- (0000EDAC) --------------------------------------------------------
int __fastcall sub_EDAC(int a1)
{
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  _BYTE *v5; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_9C08();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 16;
  s[2] = 8;
  s[3] = 0;
  v5 = &s[4];
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_FC54(3, "%s() ioctl error\n", "Ssc_cpu_802dot1q_mode_get");
  *(_DWORD *)a1 = *((_DWORD *)v5 + 1);
  return *(_DWORD *)a1;
}

//----- (0000EE80) --------------------------------------------------------
int __fastcall sub_EE80(unsigned __int8 *a1, int *a2, _DWORD *a3)
{
  sub_FC54(7, "dsa[0-3]=0x%x 0x%x 0x%x 0x%x\n", *a1, a1[1], a1[2], a1[3]);
  *a2 = a1[1] >> 3;
  *a3 = ((a1[2] & 0xF) << 8) + a1[3];
  sub_FC54(7, "Packet from port %d, vid %d\n", *a2, *a3);
  return 0;
}

//----- (0000EF70) --------------------------------------------------------
_BYTE *__fastcall sub_EF70(_BYTE *result, char a2, __int16 a3)
{
  *result = 64;
  if ( a3 )
    *result |= 0x20u;
  result[1] = 8 * a2;
  result[2] = ~((unsigned int)~((unsigned __int16)(((unsigned __int8)a3 | (HIBYTE(a3) << 8)) & 0xF00) >> 8 << 27) >> 27);
  result[3] = a3;
  return result;
}

//----- (0000F044) --------------------------------------------------------
ssize_t __fastcall sub_F044(int a1, int a2, int a3, int a4, int a5, __int16 a6)
{
  _BYTE v10[4]; // [sp+48h] [bp-2Ch] BYREF
  int v11; // [sp+4Ch] [bp-28h]
  size_t n; // [sp+50h] [bp-24h]
  int v13; // [sp+54h] [bp-20h]

  v11 = 0;
  memset(&byte_1A8AC, 0, 0x5EAu);
  v13 = sub_FD40(a3);
  sub_EF70(v10, v13, (unsigned __int8)a6 | (HIBYTE(a6) << 8));
  memcpy(&byte_1A8AC, (const void *)a4, 0xCu);
  memcpy(&unk_1A8B8, v10, 4u);
  memcpy(&unk_1A8BC, (const void *)(a4 + 12), a5 - 12);
  n = a5 + 4;
  sub_FC54(
    7,
    "%s() %d DA=%x:%x:%x:%x:%x:%x SA=%x:%x:%x:%x:%x:%x frame_len = %d\n",
    "frame_send",
    98,
    (unsigned __int8)byte_1A8AC,
    (unsigned __int8)byte_1A8AD,
    (unsigned __int8)byte_1A8AE,
    (unsigned __int8)byte_1A8AF,
    (unsigned __int8)byte_1A8B0,
    (unsigned __int8)byte_1A8B1,
    (unsigned __int8)byte_1A8B2,
    (unsigned __int8)byte_1A8B3,
    (unsigned __int8)byte_1A8B4,
    (unsigned __int8)byte_1A8B5,
    (unsigned __int8)byte_1A8B6,
    (unsigned __int8)byte_1A8B7,
    a5 + 4);
  return write(a1, &byte_1A8AC, n);
}
// 1A8AC: using guessed type char byte_1A8AC;
// 1A8AD: using guessed type char byte_1A8AD;
// 1A8AE: using guessed type char byte_1A8AE;
// 1A8AF: using guessed type char byte_1A8AF;
// 1A8B0: using guessed type char byte_1A8B0;
// 1A8B1: using guessed type char byte_1A8B1;
// 1A8B2: using guessed type char byte_1A8B2;
// 1A8B3: using guessed type char byte_1A8B3;
// 1A8B4: using guessed type char byte_1A8B4;
// 1A8B5: using guessed type char byte_1A8B5;
// 1A8B6: using guessed type char byte_1A8B6;
// 1A8B7: using guessed type char byte_1A8B7;

//----- (0000F224) --------------------------------------------------------
ssize_t __fastcall sub_F224(int a1, int a2, int a3, int a4, int a5, int a6, __int16 a7)
{
  int v12; // [sp+18h] [bp-14h] BYREF
  int v13; // [sp+1Ch] [bp-10h] BYREF
  ssize_t v14; // [sp+20h] [bp-Ch]
  int i; // [sp+24h] [bp-8h]

  v14 = 0;
  sub_FC54(7, "%s() %d\n", "Ssc_sendPacket", 158);
  v13 = 0;
  v12 = 0;
  sub_FEFC(a5, &v13);
  sub_FEFC(a6, &v12);
  for ( i = 0; i <= 9; ++i )
  {
    if ( ((1 << i) & a6) != 0 )
      v14 = sub_F044(a1, a2, i, a3, a4, 0);
    if ( ((1 << i) & a5) != 0 )
      v14 = sub_F044(a1, a2, i, a3, a4, (unsigned __int8)a7 | (HIBYTE(a7) << 8));
  }
  sub_FC54(6, "%s() len = %d, ret = %d\n", "Ssc_sendPacket", a4, v14);
  return v14;
}

//----- (0000F384) --------------------------------------------------------
int __fastcall sub_F384(int a1, int a2, int a3, const void *a4, size_t n, int a6)
{
  ssize_t v11; // [sp+24h] [bp-10h]
  signed int na; // [sp+38h] [bp+4h]

  sub_FC54(7, "%s() sendBPDU to port %d\n", "Ssc_sendBpduPacket", a3);
  memcpy(byte_1A2D0, off_1A1F8, 6u);
  if ( a6 )
    bcopy(&unk_1A204, &byte_1A2D0[6], 6u);
  else
    bcopy(&byte_1A1FC, &byte_1A2D0[6], 6u);
  word_1A2DC = htons(n + 3);
  byte_1A2DE = 66;
  byte_1A2DF = 66;
  byte_1A2E0 = 3;
  bcopy(a4, &unk_1A2E1, n);
  for ( na = n + 17; na <= 59; ++na )
    byte_1A2D0[na] = 0;
  v11 = sub_F044(a1, a2, a3, (int)byte_1A2D0, na, 0);
  return sub_FC54(6, "%s() len = %d, ret = %d\n", "Ssc_sendBpduPacket", na, v11);
}
// 1A1F8: using guessed type _UNKNOWN *off_1A1F8;
// 1A1FC: using guessed type char byte_1A1FC;
// 1A2D0: using guessed type _BYTE byte_1A2D0[12];
// 1A2DC: using guessed type __int16 word_1A2DC;
// 1A2DE: using guessed type char byte_1A2DE;
// 1A2DF: using guessed type char byte_1A2DF;
// 1A2E0: using guessed type char byte_1A2E0;

//----- (0000F520) --------------------------------------------------------
int __fastcall sub_F520(int a1, int a2, int a3, int a4, void *src, size_t n, int a7)
{
  int result; // r0
  _BYTE dest[6]; // [sp+34h] [bp-68h] BYREF
  _WORD v13[4]; // [sp+3Ah] [bp-62h] BYREF
  char v14; // [sp+42h] [bp-5Ah]
  char v15; // [sp+43h] [bp-59h]
  char v16; // [sp+44h] [bp-58h]
  _BYTE v17[3]; // [sp+45h] [bp-57h] BYREF
  ssize_t v18; // [sp+8Ch] [bp-10h]
  signed int na; // [sp+A4h] [bp+8h]

  v18 = 0;
  sub_FC54(
    7,
    "%s() sendBPDU to port %d for ring %d, SA = %x:%x:%x:%x:%x:%x\n",
    "Ssc_sendTR2Packet",
    a4,
    a3,
    (unsigned __int8)byte_1A1FC,
    (unsigned __int8)byte_1A1FD,
    (unsigned __int8)byte_1A1FE,
    (unsigned __int8)byte_1A1FF,
    (unsigned __int8)byte_1A200,
    (unsigned __int8)byte_1A201);
  result = sub_A170(a4);
  if ( !result )
  {
    if ( a3 )
      memcpy(dest, (const void *)dword_1AF64, sizeof(dest));
    else
      memcpy(dest, (const void *)dword_1AF60, sizeof(dest));
    if ( a7 )
      bcopy(&unk_1A204, v13, 6u);
    else
      bcopy(&byte_1A1FC, v13, 6u);
    v13[3] = htons(n + 3);
    v14 = 66;
    v15 = 66;
    v16 = 3;
    bcopy(src, v17, n);
    for ( na = n + 17; na <= 59; ++na )
      dest[na] = 0;
    v18 = sub_F044(a1, a2, a4, (int)dest, na, 0);
    return sub_FC54(6, "%s() len = %d, ret = %d\n", "Ssc_sendTR2Packet", na, v18);
  }
  return result;
}
// 1A1FC: using guessed type char byte_1A1FC;
// 1A1FD: using guessed type char byte_1A1FD;
// 1A1FE: using guessed type char byte_1A1FE;
// 1A1FF: using guessed type char byte_1A1FF;
// 1A200: using guessed type char byte_1A200;
// 1A201: using guessed type char byte_1A201;
// 1AF60: using guessed type int dword_1AF60;
// 1AF64: using guessed type int dword_1AF64;

//----- (0000F77C) --------------------------------------------------------
char *__fastcall sub_F77C(const char *a1)
{
  sprintf(byte_1AE98, "%s/%s", "/proc/moxa", a1);
  return byte_1AE98;
}

//----- (0000F7C0) --------------------------------------------------------
int __fastcall sub_F7C0(int a1, int a2, int a3)
{
  char *v3; // r0
  char s[128]; // [sp+1Ch] [bp-90h] BYREF
  int v8; // [sp+9Ch] [bp-10h]

  v8 = sub_FD40(a1);
  v3 = sub_F77C("port_speed_set");
  sprintf(s, " echo %x,%x,%x > %s", v8, a2, a3, v3);
  printf("msg = %s\n", s);
  system(s);
  return 0;
}

//----- (0000F858) --------------------------------------------------------
int __fastcall sub_F858(int a1)
{
  printf("%s() %d >>>>>> %d ms\n", "Ssys_ms2ticks", 28, a1);
  return a1;
}

//----- (0000F898) --------------------------------------------------------
int __fastcall sub_F898(int a1)
{
  struct timespec remaining; // [sp+10h] [bp-14h] BYREF
  struct timespec requested_time; // [sp+18h] [bp-Ch] BYREF

  requested_time.tv_sec = 0;
  requested_time.tv_nsec = 1000000 * a1;
  return nanosleep(&requested_time, &remaining);
}

//----- (0000F8F4) --------------------------------------------------------
__time_t Ssys_current_secs()
{
  int *v0; // r0
  char *v1; // r0
  timespec tp; // [sp+0h] [bp-Ch] BYREF

  if ( clock_gettime(1, &tp) != -1 )
    return tp.tv_sec;
  v0 = _errno_location();
  v1 = strerror(*v0);
  sub_FC54(3, "%s() error = %s\n", "Ssys_current_secs", v1);
  return -1;
}

//----- (0000F964) --------------------------------------------------------
int Ssys_current_msecs()
{
  int *v0; // r0
  char *v1; // r0
  int v3; // r4
  struct timespec tp; // [sp+0h] [bp-14h] BYREF

  if ( clock_gettime(1, &tp) == -1 )
  {
    v0 = _errno_location();
    v1 = strerror(*v0);
    sub_FC54(3, "%s() error = %s\n", "Ssys_current_msecs", v1);
    return -1;
  }
  else
  {
    v3 = 1000 * tp.tv_sec;
    return v3 + sub_101DC(tp.tv_nsec, 0xF4240u);
  }
}

//----- (0000FA14) --------------------------------------------------------
int __fastcall sub_FA14(_DWORD *a1)
{
  int v1; // r4
  int result; // r0
  struct timespec tp; // [sp+8h] [bp-14h] BYREF

  clock_gettime(1, &tp);
  v1 = (1000 * tp.tv_sec) >> 31;
  *a1 = 1000 * tp.tv_sec;
  a1[1] = v1;
  result = sub_101DC(tp.tv_nsec, 0x3E8u);
  a1[2] = result;
  return result;
}

//----- (0000FA8C) --------------------------------------------------------
int __fastcall sub_FA8C(_DWORD *a1, _DWORD *a2)
{
  return 1000 * (*a2 - *a1) + a2[2] - a1[2];
}

//----- (0000FB08) --------------------------------------------------------
char *sub_FB08()
{
  return &byte_1A1FC;
}
// 1A1FC: using guessed type char byte_1A1FC;

//----- (0000FB3C) --------------------------------------------------------
int __fastcall sub_FB3C(unsigned __int8 *a1, int a2)
{
  unsigned int v4; // r4

  v4 = 0;
  while ( a2 > 1 )
  {
    v4 += *a1 | (a1[1] << 8);
    a1 += 2;
    a2 -= 2;
  }
  if ( a2 == 1 )
    v4 += *a1;
  return (unsigned __int16)~(HIWORD(v4) + v4 + ((unsigned int)(HIWORD(v4) + (unsigned __int16)v4) >> 16));
}

//----- (0000FBFC) --------------------------------------------------------
int __fastcall Ssys_UI_port2MdlPort(int a1, _DWORD *a2, int *a3)
{
  if ( a1 > 9 )
    return 0;
  *a2 = 0;
  *a3 = a1;
  return 1;
}

//----- (0000FC54) --------------------------------------------------------
int sub_FC54(int result, const char *a2, ...)
{
  va_list varg_r2; // [sp+20h] [bp+8h] BYREF

  va_start(varg_r2, a2);
  if ( result <= dword_1AF68 )
    return vfprintf((FILE *)stderr, a2, varg_r2);
  return result;
}
// 1A270: using guessed type int stderr;
// 1AF68: using guessed type int dword_1AF68;

//----- (0000FCC4) --------------------------------------------------------
int __fastcall sub_FCC4(int a1)
{
  dword_1AF68 = a1;
  return printf("Debug message level set to %d\n", a1);
}
// 1AF68: using guessed type int dword_1AF68;

//----- (0000FD08) --------------------------------------------------------
void sub_FD08()
{
  dword_1AF1C = (int)&unk_1A20C;
  dword_1AF18 = 1;
}
// 1AF18: using guessed type int dword_1AF18;
// 1AF1C: using guessed type int dword_1AF1C;

//----- (0000FD40) --------------------------------------------------------
int __fastcall sub_FD40(int a1)
{
  int i; // [sp+Ch] [bp-10h]
  int v5; // [sp+10h] [bp-Ch]

  v5 = -1;
  if ( !dword_1AF18 )
    sub_FD08();
  for ( i = 0; i < dword_1A264; ++i )
  {
    if ( *(_DWORD *)(dword_1AF1C + 8 * i) == a1 )
    {
      v5 = *(_DWORD *)(dword_1AF1C + 8 * i + 4);
      break;
    }
  }
  if ( i == dword_1A264 )
    return -1;
  else
    return v5;
}
// 1A264: using guessed type int dword_1A264;
// 1AF18: using guessed type int dword_1AF18;
// 1AF1C: using guessed type int dword_1AF1C;

//----- (0000FE0C) --------------------------------------------------------
int __fastcall sub_FE0C(int a1)
{
  int i; // [sp+14h] [bp-10h]
  int v5; // [sp+18h] [bp-Ch]

  v5 = -1;
  if ( !dword_1AF18 )
    sub_FD08();
  for ( i = 0; i < dword_1A264; ++i )
  {
    if ( *(_DWORD *)(dword_1AF1C + 8 * i + 4) == a1 )
    {
      v5 = *(_DWORD *)(dword_1AF1C + 8 * i);
      break;
    }
  }
  if ( i == dword_1A264 )
    return -1;
  sub_FC54(7, "%s(): port %d from port %d\n", "spm_getLogicalPortId", v5, a1);
  return v5;
}
// 1A264: using guessed type int dword_1A264;
// 1AF18: using guessed type int dword_1AF18;
// 1AF1C: using guessed type int dword_1AF1C;

//----- (0000FEFC) --------------------------------------------------------
int __fastcall sub_FEFC(int a1, _DWORD *a2)
{
  int i; // [sp+8h] [bp-14h]
  int v6; // [sp+10h] [bp-Ch]

  if ( !dword_1AF18 )
    sub_FD08();
  v6 = 0;
  for ( i = 0; i < dword_1A264; ++i )
  {
    if ( ((1 << *(_DWORD *)(dword_1AF1C + 8 * i)) & a1) != 0 )
      v6 |= 1 << *(_DWORD *)(dword_1AF1C + 8 * i + 4);
  }
  *a2 = v6;
  return 0;
}
// 1A264: using guessed type int dword_1A264;
// 1AF18: using guessed type int dword_1AF18;
// 1AF1C: using guessed type int dword_1AF1C;

//----- (0000FFE4) --------------------------------------------------------
int __fastcall sub_FFE4(int a1, _DWORD *a2)
{
  int i; // [sp+8h] [bp-14h]
  int v6; // [sp+10h] [bp-Ch]

  if ( !dword_1AF18 )
    sub_FD08();
  v6 = 0;
  for ( i = 0; i < dword_1A264; ++i )
  {
    if ( ((1 << *(_DWORD *)(dword_1AF1C + 8 * i + 4)) & a1) != 0 )
      v6 |= 1 << *(_DWORD *)(dword_1AF1C + 8 * i);
  }
  *a2 = v6;
  return 0;
}
// 1A264: using guessed type int dword_1A264;
// 1AF18: using guessed type int dword_1AF18;
// 1AF1C: using guessed type int dword_1AF1C;

//----- (000100CC) --------------------------------------------------------
unsigned int __fastcall sub_100CC(unsigned int result, unsigned int a2)
{
  unsigned int v2; // r3
  bool v3; // cf
  bool v4; // cf
  int v5; // r2
  bool v6; // zf
  int v7; // r2

  if ( a2 != 1 )
  {
    if ( a2 )
    {
      if ( result <= a2 )
      {
        return result == a2;
      }
      else if ( (a2 & (a2 - 1)) != 0 )
      {
        if ( (a2 & 0xE0000000) != 0 )
        {
          v2 = 1;
        }
        else
        {
          a2 *= 8;
          v2 = 8;
        }
        while ( 1 )
        {
          v3 = a2 >= 0x10000000;
          if ( a2 < 0x10000000 )
            v3 = a2 >= result;
          if ( v3 )
            break;
          a2 *= 16;
          v2 *= 16;
        }
        while ( 1 )
        {
          v4 = a2 >= 0x80000000;
          if ( a2 < 0x80000000 )
            v4 = a2 >= result;
          if ( v4 )
            break;
          a2 *= 2;
          v2 *= 2;
        }
        v5 = 0;
        while ( 1 )
        {
          if ( result >= a2 )
          {
            result -= a2;
            v5 |= v2;
          }
          if ( result >= a2 >> 1 )
          {
            result -= a2 >> 1;
            v5 |= v2 >> 1;
          }
          if ( result >= a2 >> 2 )
          {
            result -= a2 >> 2;
            v5 |= v2 >> 2;
          }
          if ( result >= a2 >> 3 )
          {
            result -= a2 >> 3;
            v5 |= v2 >> 3;
          }
          v6 = result == 0;
          if ( result )
          {
            v2 >>= 4;
            v6 = v2 == 0;
          }
          if ( v6 )
            break;
          a2 >>= 4;
        }
        return v5;
      }
      else
      {
        if ( a2 < 0x10000 )
        {
          v7 = 0;
        }
        else
        {
          a2 >>= 16;
          v7 = 16;
        }
        if ( a2 >= 0x100 )
        {
          a2 >>= 8;
          v7 += 8;
        }
        if ( a2 >= 0x10 )
        {
          a2 >>= 4;
          v7 += 4;
        }
        if ( a2 <= 4 )
          v7 += a2 >> 1;
        else
          LOBYTE(v7) = v7 + 3;
        result >>= v7;
      }
    }
    else
    {
      sub_1031C();
      return 0;
    }
  }
  return result;
}

//----- (000101C4) --------------------------------------------------------
unsigned int __fastcall sub_101C4(unsigned int a1, unsigned int a2)
{
  return sub_100CC(a1, a2);
}

//----- (000101DC) --------------------------------------------------------
int __fastcall sub_101DC(int result, unsigned int a2)
{
  int v2; // r12
  unsigned int v3; // r3
  unsigned int v4; // r2
  bool v5; // cf
  bool v6; // cf
  bool v7; // zf
  int v8; // r2

  v2 = result ^ a2;
  if ( a2 )
  {
    if ( (a2 & 0x80000000) != 0 )
      a2 = -a2;
    if ( a2 == 1 )
    {
      if ( (v2 ^ result) < 0 )
        return -result;
    }
    else
    {
      v3 = result;
      if ( result < 0 )
        v3 = -result;
      if ( v3 <= a2 )
      {
        if ( v3 < a2 )
          result = 0;
        if ( v3 == a2 )
          return (v2 >> 31) | 1;
      }
      else if ( (a2 & (a2 - 1)) != 0 )
      {
        if ( (a2 & 0xE0000000) != 0 )
        {
          v4 = 1;
        }
        else
        {
          a2 *= 8;
          v4 = 8;
        }
        while ( 1 )
        {
          v5 = a2 >= 0x10000000;
          if ( a2 < 0x10000000 )
            v5 = a2 >= v3;
          if ( v5 )
            break;
          a2 *= 16;
          v4 *= 16;
        }
        while ( 1 )
        {
          v6 = a2 >= 0x80000000;
          if ( a2 < 0x80000000 )
            v6 = a2 >= v3;
          if ( v6 )
            break;
          a2 *= 2;
          v4 *= 2;
        }
        result = 0;
        while ( 1 )
        {
          if ( v3 >= a2 )
          {
            v3 -= a2;
            result |= v4;
          }
          if ( v3 >= a2 >> 1 )
          {
            v3 -= a2 >> 1;
            result |= v4 >> 1;
          }
          if ( v3 >= a2 >> 2 )
          {
            v3 -= a2 >> 2;
            result |= v4 >> 2;
          }
          if ( v3 >= a2 >> 3 )
          {
            v3 -= a2 >> 3;
            result |= v4 >> 3;
          }
          v7 = v3 == 0;
          if ( v3 )
          {
            v4 >>= 4;
            v7 = v4 == 0;
          }
          if ( v7 )
            break;
          a2 >>= 4;
        }
        if ( v2 < 0 )
          return -result;
      }
      else
      {
        if ( a2 < 0x10000 )
        {
          v8 = 0;
        }
        else
        {
          a2 >>= 16;
          v8 = 16;
        }
        if ( a2 >= 0x100 )
        {
          a2 >>= 8;
          v8 += 8;
        }
        if ( a2 >= 0x10 )
        {
          a2 >>= 4;
          v8 += 4;
        }
        if ( a2 <= 4 )
          v8 += a2 >> 1;
        else
          LOBYTE(v8) = v8 + 3;
        result = v3 >> v8;
        if ( v2 < 0 )
          return -result;
      }
    }
  }
  else
  {
    sub_1031C();
    return 0;
  }
  return result;
}

//----- (00010304) --------------------------------------------------------
int __fastcall sub_10304(int a1, unsigned int a2)
{
  return sub_101DC(a1, a2);
}

//----- (0001031C) --------------------------------------------------------
int sub_1031C()
{
  return raise(8);
}

//----- (00010330) --------------------------------------------------------
void init(void)
{
  init_proc();
}

//----- (00010398) --------------------------------------------------------
int __fastcall sub_10398(char *filename, struct stat *stat_buf)
{
  return _xstat(3, filename, stat_buf);
}

//----- (000103A8) --------------------------------------------------------
int sub_103A8()
{
  int (*v0)(void); // r3
  _UNKNOWN **v1; // r4
  int result; // r0
  int (*v3)(void); // t1

  v0 = (int (*)(void))off_1A000;
  if ( off_1A000 != (_UNKNOWN *)-1 )
  {
    v1 = &off_1A000;
    do
    {
      result = v0();
      v3 = (int (*)(void))*--v1;
      v0 = v3;
    }
    while ( v3 != (int (*)(void))-1 );
  }
  return result;
}
// 1A000: using guessed type _UNKNOWN *off_1A000;

//----- (000103DC) --------------------------------------------------------
void sub_103DC()
{
  ;
}

//----- (000103E4) --------------------------------------------------------
int term_proc()
{
  return sub_90B0();
}

// nfuncs=239 queued=142 decompiled=142 lumina nreq=0 worse=0 better=0
// ALL OK, 142 function(s) have been successfully decompiled
