/* This file was generated by the Hex-Rays decompiler version 9.1.0.250226.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int init_proc();
void sub_728();
// int __fastcall _deregister_frame_info(_DWORD); weak
// int sprintf(char *s, const char *format, ...);
// FILE *popen(const char *command, const char *modes);
// int _gmon_start__(void); weak
// int __fastcall Ssys_CheckString(_DWORD); weak
// char *fgets(char *s, int n, FILE *stream);
// int __fastcall _register_frame_info(_DWORD, _DWORD); weak
// void *memset(void *s, int c, size_t n);
int __fastcall j_shm_sysGetRadiusInfo(void *a1);
// void *memcpy(void *dest, const void *src, size_t n);
// size_t strlen(const char *s);
// int __fastcall shm_enterCS(_DWORD, _DWORD, _DWORD, _DWORD); weak
// char *strstr(const char *haystack, const char *needle);
// int __fastcall shm_leaveCS(_DWORD, _DWORD, _DWORD); weak
int __fastcall j_shm_sysGetAccounts(void *a1);
// int strncmp(const char *s1, const char *s2, size_t n);
// int _cxa_finalize(void *);
// int pclose(FILE *stream);
int call_gmon_start();
int _do_global_dtors_aux();
void call___do_global_dtors_aux();
int *frame_dummy();
void call_frame_dummy();
int __fastcall shm_sysSetRadiusInfo(const void *a1);
int __fastcall shm_sysGetRadiusInfo(void *a1);
int __fastcall nameStrTranslate(int a1, int a2, void *a3, size_t a4);
int __fastcall passwdStrTranslate(int a1, int a2, void *a3, size_t a4);
int __fastcall RadiusAuth(const char *a1, const char *a2);
int get_raudius_enable();
int __fastcall shm_sysGetAccounts(void *a1);
int __fastcall radius_isLocalAccountExist(const char *a1);
int _do_global_ctors_aux();
void call___do_global_ctors_aux();
int term_proc();
// int __cxa_finalize(void *);
// int __fastcall Jv_RegisterClasses(_DWORD); weak

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN _FRAME_END__; // weak
_UNKNOWN *_CTOR_LIST__ = (_UNKNOWN *)0xFFFFFFFF; // weak
int _JCR_LIST__ = 0; // weak
_UNKNOWN *_dso_handle = &_dso_handle; // weak
char completed_2899; // weak
_UNKNOWN object_2931; // weak
// extern _UNKNOWN __deregister_frame_info; weak
// extern _UNKNOWN __register_frame_info; weak
// extern _UNKNOWN __gmon_start__; weak


//----- (00000714) --------------------------------------------------------
int init_proc()
{
  call_gmon_start();
  frame_dummy();
  return _do_global_ctors_aux();
}

//----- (00000728) --------------------------------------------------------
void sub_728()
{
  JUMPOUT(0);
}
// 734: control flows out of bounds to 0

//----- (0000079C) --------------------------------------------------------
// attributes: thunk
int __fastcall j_shm_sysGetRadiusInfo(void *a1)
{
  return shm_sysGetRadiusInfo(a1);
}

//----- (000007E4) --------------------------------------------------------
// attributes: thunk
int __fastcall j_shm_sysGetAccounts(void *a1)
{
  return shm_sysGetAccounts(a1);
}

//----- (00000814) --------------------------------------------------------
int call_gmon_start()
{
  int result; // r0

  if ( &__gmon_start__ )
    return _gmon_start__();
  return result;
}
// 760: using guessed type int _gmon_start__(void);

//----- (00000838) --------------------------------------------------------
int _do_global_dtors_aux()
{
  int result; // r0

  if ( !completed_2899 )
  {
    if ( &__cxa_finalize )
      result = _cxa_finalize(_dso_handle);
    if ( &__deregister_frame_info )
      result = _deregister_frame_info(&_FRAME_END__);
    completed_2899 = 1;
  }
  return result;
}
// 73C: using guessed type int __fastcall _deregister_frame_info(_DWORD);
// 9748: using guessed type _UNKNOWN *_dso_handle;
// 9750: using guessed type char completed_2899;

//----- (000008FC) --------------------------------------------------------
void call___do_global_dtors_aux()
{
  ;
}

//----- (00000904) --------------------------------------------------------
int *frame_dummy()
{
  int *result; // r0

  if ( &__register_frame_info )
    _register_frame_info(&_FRAME_END__, &object_2931);
  result = &_JCR_LIST__;
  if ( _JCR_LIST__ )
  {
    if ( &Jv_RegisterClasses )
      return (int *)Jv_RegisterClasses(&_JCR_LIST__);
  }
  return result;
}
// 784: using guessed type int __fastcall _register_frame_info(_DWORD, _DWORD);
// 9608: using guessed type int _JCR_LIST__;
// 97FC: using guessed type int __fastcall Jv_RegisterClasses(_DWORD);

//----- (0000097C) --------------------------------------------------------
void call_frame_dummy()
{
  ;
}

//----- (00000984) --------------------------------------------------------
int __fastcall shm_sysSetRadiusInfo(const void *a1)
{
  _DWORD v3[2]; // [sp+Ch] [bp-8h] BYREF

  shm_enterCS(1507, 7894, v3, 1112);
  memcpy((void *)(v3[0] + 720), a1, 0x188u);
  shm_leaveCS(1507, 7894, v3);
  return 0;
}
// 7C0: using guessed type int __fastcall shm_enterCS(_DWORD, _DWORD, _DWORD, _DWORD);
// 7D8: using guessed type int __fastcall shm_leaveCS(_DWORD, _DWORD, _DWORD);

//----- (000009FC) --------------------------------------------------------
int __fastcall shm_sysGetRadiusInfo(void *a1)
{
  _DWORD v3[2]; // [sp+Ch] [bp-8h] BYREF

  shm_enterCS(1507, 7894, v3, 1112);
  memcpy(a1, (const void *)(v3[0] + 720), 0x188u);
  shm_leaveCS(1507, 7894, v3);
  return 0;
}
// 7C0: using guessed type int __fastcall shm_enterCS(_DWORD, _DWORD, _DWORD, _DWORD);
// 7D8: using guessed type int __fastcall shm_leaveCS(_DWORD, _DWORD, _DWORD);

//----- (00000A74) --------------------------------------------------------
int __fastcall nameStrTranslate(int a1, int a2, void *a3, size_t a4)
{
  int i; // [sp+10h] [bp-Ch]
  int v9; // [sp+14h] [bp-8h]
  int v10; // [sp+14h] [bp-8h]
  int v11; // [sp+14h] [bp-8h]
  int v12; // [sp+14h] [bp-8h]

  v9 = 0;
  memset(a3, 0, a4);
  for ( i = 0; i < a2; ++i )
  {
    if ( *(_BYTE *)(a1 + i) == 92 )
    {
      *((_BYTE *)a3 + v9) = 92;
      v10 = v9 + 1;
      *((_BYTE *)a3 + v10++) = 92;
      *((_BYTE *)a3 + v10) = 92;
      v9 = v10 + 1;
    }
    else if ( *(_BYTE *)(a1 + i) == 36 )
    {
      *((_BYTE *)a3 + v9) = 92;
      v11 = v9 + 1;
      *((_BYTE *)a3 + v11) = 36;
      v9 = v11 + 1;
    }
    else
    {
      if ( *(_BYTE *)(a1 + i) == 34 )
      {
        *((_BYTE *)a3 + v9) = 37;
        v12 = v9 + 1;
        *((_BYTE *)a3 + v12) = 50;
        v9 = v12 + 1;
        *((_BYTE *)a3 + v9) = 50;
      }
      else
      {
        *((_BYTE *)a3 + v9) = *(_BYTE *)(a1 + i);
      }
      ++v9;
    }
  }
  return 0;
}

//----- (00000C6C) --------------------------------------------------------
int __fastcall passwdStrTranslate(int a1, int a2, void *a3, size_t a4)
{
  int i; // [sp+10h] [bp-Ch]
  int v9; // [sp+14h] [bp-8h]
  int v10; // [sp+14h] [bp-8h]
  int v11; // [sp+14h] [bp-8h]
  int v12; // [sp+14h] [bp-8h]

  v9 = 0;
  memset(a3, 0, a4);
  for ( i = 0; i < a2; ++i )
  {
    if ( *(_BYTE *)(a1 + i) == 92 )
    {
      *((_BYTE *)a3 + v9) = 92;
      v10 = v9 + 1;
      *((_BYTE *)a3 + v10++) = 92;
      *((_BYTE *)a3 + v10) = 92;
      v9 = v10 + 1;
    }
    else if ( *(_BYTE *)(a1 + i) == 36 )
    {
      *((_BYTE *)a3 + v9) = 92;
      v11 = v9 + 1;
      *((_BYTE *)a3 + v11) = 36;
      v9 = v11 + 1;
    }
    else
    {
      if ( *(_BYTE *)(a1 + i) == 34 )
      {
        *((_BYTE *)a3 + v9) = 37;
        v12 = v9 + 1;
        *((_BYTE *)a3 + v12) = 50;
        v9 = v12 + 1;
        *((_BYTE *)a3 + v9) = 50;
      }
      else
      {
        *((_BYTE *)a3 + v9) = *(_BYTE *)(a1 + i);
      }
      ++v9;
    }
  }
  return 0;
}

//----- (00000E64) --------------------------------------------------------
int __fastcall RadiusAuth(const char *a1, const char *a2)
{
  size_t v2; // r0
  size_t v3; // r0
  char v8[12]; // [sp+18h] [bp-4ACh] BYREF
  char v9[12]; // [sp+98h] [bp-42Ch] BYREF
  char haystack[256]; // [sp+118h] [bp-3ACh] BYREF
  char command[256]; // [sp+218h] [bp-2ACh] BYREF
  _BYTE v12[4]; // [sp+318h] [bp-1ACh] BYREF
  int v13; // [sp+31Ch] [bp-1A8h]
  _BYTE v14[384]; // [sp+320h] [bp-1A4h] BYREF
  FILE *stream; // [sp+4A0h] [bp-24h]
  int i; // [sp+4A4h] [bp-20h]
  int v17; // [sp+4B0h] [bp-14h]
  int v18; // [sp+4B4h] [bp-10h]

  v17 = 0;
  v18 = 0;
  v2 = strlen(a1);
  nameStrTranslate((int)a1, v2, v9, 0x80u);
  v3 = strlen(a2);
  passwdStrTranslate((int)a2, v3, v8, 0x80u);
  j_shm_sysGetRadiusInfo(v12);
  if ( Ssys_CheckString(a1) < 0 || Ssys_CheckString(a2) < 0 )
    return -1;
  for ( i = 0; i <= 1; ++i )
  {
    memset(command, 0, sizeof(command));
    if ( v13 )
      sprintf(
        command,
        "(echo \"User-Name=\\\"%s\\\",CHAP-Password=\\\"%s\\\"\" | /usr/local/bin/radclient %s:%s -t 3 -r 1 -x auth \"%s\" 2>&1)",
        v9,
        v8,
        &v14[64 * i],
        &v14[64 * i + 256],
        &v14[64 * i + 128]);
    else
      sprintf(
        command,
        "(echo \"User-Name=\\\"%s\\\",User-Password=\\\"%s\\\"\" | /usr/local/bin/radclient %s:%s -t 3 -r 1 -x auth \"%s\" 2>&1)",
        v9,
        v8,
        &v14[64 * i],
        &v14[64 * i + 256],
        &v14[64 * i + 128]);
    stream = popen(command, "r");
    if ( !stream )
      return -1;
    while ( 1 )
    {
      memset(haystack, 0, sizeof(haystack));
      if ( !fgets(haystack, 256, stream) )
        break;
      if ( strstr(haystack, "Access-Reject") )
        goto LABEL_23;
      if ( strstr(haystack, "Access-Accept") )
      {
        while ( 1 )
        {
          memset(haystack, 0, sizeof(haystack));
          if ( !fgets(haystack, 256, stream) )
            break;
          if ( strstr(haystack, "Service-Type") )
          {
            if ( strstr(haystack, "Administrative-User") )
            {
              pclose(stream);
              return 6;
            }
            if ( !strstr(haystack, "Callback-Login-User") && strstr(haystack, "Login-User") )
            {
              pclose(stream);
              return 1;
            }
            break;
          }
        }
LABEL_23:
        pclose(stream);
        return -1;
      }
    }
  }
  return 0;
}
// 76C: using guessed type int __fastcall Ssys_CheckString(_DWORD);

//----- (00001284) --------------------------------------------------------
int get_raudius_enable()
{
  _DWORD v1[99]; // [sp+0h] [bp-18Ch] BYREF

  j_shm_sysGetRadiusInfo(v1);
  return v1[0];
}

//----- (000012AC) --------------------------------------------------------
int __fastcall shm_sysGetAccounts(void *a1)
{
  void *src[2]; // [sp+Ch] [bp-8h] BYREF

  shm_enterCS(1507, 7894, src, 1112);
  memcpy(a1, src[0], 0x2D0u);
  shm_leaveCS(1507, 7894, src);
  return 0;
}
// 7C0: using guessed type int __fastcall shm_enterCS(_DWORD, _DWORD, _DWORD, _DWORD);
// 7D8: using guessed type int __fastcall shm_leaveCS(_DWORD, _DWORD, _DWORD);

//----- (00001320) --------------------------------------------------------
int __fastcall radius_isLocalAccountExist(const char *a1)
{
  char s[720]; // [sp+Ch] [bp-2E8h] BYREF
  int i; // [sp+2DCh] [bp-18h]
  int v5; // [sp+2E0h] [bp-14h]
  size_t n; // [sp+2E4h] [bp-10h]

  i = 0;
  v5 = 0;
  n = 0;
  memset(s, 0, sizeof(s));
  j_shm_sysGetAccounts(s);
  n = strlen(a1);
  for ( i = 0; i <= 9; ++i )
  {
    if ( s[72 * i] && n == strlen(&s[72 * i]) && !strncmp(a1, &s[72 * i], n) )
      return 1;
  }
  return v5;
}

//----- (0000145C) --------------------------------------------------------
int _do_global_ctors_aux()
{
  int (*v0)(void); // r3
  _UNKNOWN **v1; // r4
  int result; // r0
  int (*v3)(void); // t1

  v0 = (int (*)(void))_CTOR_LIST__;
  if ( _CTOR_LIST__ != (_UNKNOWN *)-1 )
  {
    v1 = &_CTOR_LIST__;
    do
    {
      result = v0();
      v3 = (int (*)(void))*--v1;
      v0 = v3;
    }
    while ( v3 != (int (*)(void))-1 );
  }
  return result;
}
// 95F8: using guessed type _UNKNOWN *_CTOR_LIST__;

//----- (000014A0) --------------------------------------------------------
void call___do_global_ctors_aux()
{
  ;
}

//----- (000014A8) --------------------------------------------------------
int term_proc()
{
  return _do_global_dtors_aux();
}

// nfuncs=53 queued=20 decompiled=20 lumina nreq=0 worse=0 better=0
// ALL OK, 20 function(s) have been successfully decompiled
