/* This file was generated by the Hex-Rays decompiler version 9.1.0.250226.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>

#include <stdarg.h>


//-------------------------------------------------------------------------
// Function declarations

int init_proc();
void sub_8E24();
// int fputs(const char *s, FILE *stream);
// void abort(void);
// int *_errno_location(void);
// int __fastcall _deregister_frame_info(_DWORD); weak
// int sprintf(char *s, const char *format, ...);
// int open(const char *file, int oflag, ...);
// char *strerror(int errnum);
// int __fastcall get_shm_interface_name_by_vid(_DWORD, _DWORD); weak
// int memcmp(const void *s1, const void *s2, size_t n);
// char *inet_ntoa(struct in_addr in);
// int __fastcall Semaphore_V(_DWORD); weak
// int _gmon_start__(void); weak
// int system(const char *command);
// ssize_t write(int fd, const void *buf, size_t n);
// int __fastcall _register_frame_info(_DWORD, _DWORD); weak
// void *memset(void *s, int c, size_t n);
// int _libc_start_main(int (*main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// uint16_t htons(uint16_t hostshort);
// int __fastcall net_OpenSocketToInterface_Recv(_DWORD, _DWORD); weak
// ssize_t read(int fd, void *buf, size_t nbytes);
// void perror(const char *s);
// int ioctl(int fd, unsigned int request, ...);
// int pthread_mutex_unlock(pthread_mutex_t *mutex);
// int fclose(FILE *stream);
// void bcopy(const void *src, void *dest, size_t n);
// int __fastcall CS_End(_DWORD, _DWORD, _DWORD); weak
// int nanosleep(const struct timespec *requested_time, struct timespec *remaining);
// void *memcpy(void *dest, const void *src, size_t n);
// size_t strlen(const char *s);
// FILE *fopen(const char *filename, const char *modes);
// int printf(const char *format, ...);
// int raise(int sig);
// int atoi(const char *nptr);
// int clock_gettime(clockid_t clock_id, struct timespec *tp);
// int __fastcall Semaphore_P(_DWORD); weak
// int select(int nfds, fd_set *readfds, fd_set *writefds, fd_set *exceptfds, struct timeval *timeout);
// int __fastcall sock_path(_DWORD); weak
// int close(int fd);
// size_t fwrite(const void *ptr, size_t size, size_t n, FILE *s);
// int __fastcall get_slave_interface_in_bridge(_DWORD, _DWORD); weak
// int fprintf(FILE *stream, const char *format, ...);
// int pthread_mutex_lock(pthread_mutex_t *mutex);
// int fputc(int c, FILE *stream);
// int __fastcall CS_Start(int a1, int a2, int a3);
// int puts(const char *s);
// int vfprintf(FILE *s, const char *format, __gnuc_va_list arg);
// int snprintf(char *s, size_t maxlen, const char *format, ...);
// int __fastcall Semaphore_init(_DWORD); weak
// int strcmp(const char *s1, const char *s2);
// int __fastcall net_RecvFromInterface1(_DWORD, _DWORD); weak
void __noreturn start(void (*a1)(void), int a2, int a3, int a4, ...);
int sub_90CC();
int sub_90F0();
void sub_9178();
int *sub_9180();
void sub_91D4();
bool sub_91DC();
int sub_924C();
int __fastcall sub_92D8(char *a1, size_t a2);
int sub_9858();
void __fastcall __noreturn main(int a1, char **a2, char **a3);
int sub_B298();
int sub_B32C();
int __fastcall sub_B360(int a1, int a2, _DWORD *a3);
int __fastcall sub_B470(int a1, int a2, int a3);
int __fastcall sub_B574(int a1, int a2, _DWORD *a3);
int __fastcall sub_B678(int a1, int a2, int a3);
int __fastcall sub_B770(int a1);
int __fastcall sub_B800(int a1);
int __fastcall sub_B8CC(int a1, _DWORD *a2);
int __fastcall sub_B9BC(int a1, int a2);
int __fastcall sub_BACC(int a1);
int __fastcall sub_BBA0(int a1);
int sub_BC60();
int sub_BCFC();
int __fastcall sub_BD98(int a1, int a2);
int __fastcall sub_BE84(int a1, int a2);
int __fastcall sub_BF70(int a1, int a2);
int __fastcall sub_C05C(int a1, int a2);
int __fastcall sub_C148(int a1, int a2);
int __fastcall sub_C22C(int a1, const char *a2);
int __fastcall sub_C338(int a1, int a2);
int __fastcall sub_C424(int a1, const char *a2);
int __fastcall sub_C534(int a1, int a2);
int __fastcall sub_C620(int a1, const char *a2);
int __fastcall sub_C730(int a1);
int __fastcall sub_C82C(int a1, int a2, int a3);
int __fastcall sub_C9C0(int a1, int a2);
int __fastcall Ssc_getPortLinkState(_DWORD *a1);
int __fastcall sub_CC50(int a1);
void *__fastcall Ssc_getPortStatsCounter(void *a1, int a2);
int __fastcall sub_CE3C(_DWORD *a1);
int __fastcall sub_CE88(int a1);
int __fastcall sub_CED0(int a1);
int __fastcall sub_CFD0(int a1);
int sub_D094();
int __fastcall sub_D164(const void *a1, _DWORD *a2);
int __fastcall sub_D290(const void *a1, void *a2);
int __fastcall sub_D488(const void *a1, void *a2);
int __fastcall sub_D680(_DWORD *a1);
int __fastcall sub_D768(char *a1, size_t a2, int a3);
int __fastcall sub_DF1C(const void *a1, char a2, int a3);
int __fastcall sub_E04C(const void *a1, int a2, int a3);
int sub_E1A4();
int sub_E1FC();
int sub_E254();
int __fastcall sub_E278(int a1, const void *a2, int a3);
int __fastcall sub_E2D0(int a1, const void *a2, int a3);
int __fastcall sub_E33C(int a1, const void *a2);
int __fastcall sub_E394(int a1);
int __fastcall sub_E478(int a1, int a2);
int __fastcall sub_E588(_DWORD *a1, int a2);
int __fastcall sub_E6C8(_DWORD *a1, unsigned __int8 a2, int a3, int a4);
int __fastcall sub_E848(_DWORD *a1, int a2, int a3);
int __fastcall sub_E994(_DWORD *a1, int a2, int a3);
void sub_EAF0();
int __fastcall sub_EB04(int a1);
int __fastcall sub_EBD0(int result);
int __fastcall sub_EC4C(int result);
int __fastcall sub_ECC8(int a1, int a2);
int __fastcall sub_EDA8(int a1, int a2);
int __fastcall sub_EE88(int a1, int a2);
int __fastcall sub_EF94(int a1);
int __fastcall sub_F09C(int a1, int a2, const void *a3);
void sub_F1B4();
int __fastcall sub_F1D0(int a1, _DWORD *a2, _DWORD *a3);
int __fastcall sub_F31C(int a1, int a2);
int sub_F4E8();
int sub_F5E0();
int sub_F70C();
void sub_F840();
int __fastcall sub_F854(const void *a1, int a2, int a3);
int __fastcall sub_F984(const void *a1, __int16 a2);
int __fastcall sub_FAC4(int a1);
int sub_FB90();
int __fastcall sub_FC4C(int a1, int a2);
int __fastcall sub_FD54(int a1, int a2);
int __fastcall sub_FE5C(int a1, int a2);
int __fastcall sub_FF3C(int a1, int a2);
int __fastcall sub_1001C(int a1, int a2);
int __fastcall sub_100FC(int a1);
int __fastcall sub_101D0(int a1);
int __fastcall sub_1029C(int a1);
int __fastcall sub_10370(int a1);
int __fastcall sub_1043C(int a1);
int __fastcall sub_10510(unsigned __int8 *a1, int *a2, _DWORD *a3);
_BYTE *__fastcall sub_10600(_BYTE *result, char a2, __int16 a3);
ssize_t __fastcall sub_106D4(int a1, int a2, int a3, int a4, int a5, __int16 a6);
ssize_t __fastcall sub_108B4(int a1, int a2, int a3, int a4, int a5, int a6, __int16 a7);
int __fastcall sub_10A14(int a1, int a2, int a3, const void *a4, size_t n, int a6);
int __fastcall sub_10BB0(int a1, int a2, int a3, int a4, void *src, size_t n, int a7); // idb
char *__fastcall sub_10E0C(const char *a1);
int __fastcall sub_10E50(int a1, int a2, int a3);
int __fastcall sub_10EE8(int a1);
int __fastcall sub_10F28(int a1);
__time_t Ssys_current_secs();
int Ssys_current_msecs();
int __fastcall sub_110A4(_DWORD *a1);
int __fastcall sub_1111C(_DWORD *a1, _DWORD *a2);
char *sub_11198();
int __fastcall sub_111CC(unsigned __int8 *a1, int a2);
int __fastcall Ssys_UI_port2MdlPort(int a1, _DWORD *a2, int *a3);
int sub_112E4(int result, const char *a2, ...);
int __fastcall sub_11354(int a1);
void sub_11398();
int __fastcall sub_113D0(int a1);
int __fastcall sub_1149C(int a1);
int __fastcall sub_1158C(int a1, _DWORD *a2);
int __fastcall sub_11674(int a1, _DWORD *a2);
unsigned int __fastcall sub_1175C(unsigned int result, unsigned int a2);
unsigned int __fastcall sub_11854(unsigned int a1, unsigned int a2);
int __fastcall sub_1186C(int result, unsigned int a2);
int __fastcall sub_11994(int a1, unsigned int a2);
int sub_119AC();
int nullsub_1(); // weak
void init(void); // idb
int sub_11A28();
void sub_11A5C();
int term_proc();
// int __fastcall CS_Start(_DWORD, _DWORD, _DWORD); weak

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN unk_13000; // weak
_UNKNOWN *off_1B050 = (_UNKNOWN *)0xFFFFFFFF; // weak
int dword_1B058[] = { -1 }; // weak
int dword_1B05C = 0; // weak
int dword_1B060 = 0; // weak
_UNKNOWN *off_1B250 = &unk_1B248; // weak
char byte_1B254 = '\0'; // weak
char byte_1B255 = '\x90'; // weak
char byte_1B256 = '\xE8'; // weak
char byte_1B257 = '\x05'; // weak
char byte_1B258 = '\0'; // weak
char byte_1B259 = '\b'; // weak
_UNKNOWN unk_1B25C; // weak
_UNKNOWN unk_1B264; // weak
int dword_1B2BC = 11; // weak
int stderr; // weak
char byte_1B2CC; // weak
int dword_1B2D0; // weak
_UNKNOWN unk_1B2D4; // weak
char byte_1B2EC; // weak
_DWORD dword_1B2F0[2176]; // weak
int dword_1D4F0; // weak
int dword_1D4F4; // weak
int dword_1D4F8; // weak
_UNKNOWN unk_1D4FC; // weak
_UNKNOWN unk_1D504; // weak
int dword_1D574; // weak
_UNKNOWN unk_1D594; // weak
int dword_1D604; // weak
int dword_1D628; // weak
int dword_1D62C; // weak
int dword_1D634; // weak
pthread_mutex_t mutex; // idb
_UNKNOWN unk_1D650; // weak
_UNKNOWN unk_1D654; // weak
int dword_1D658; // weak
_BYTE byte_1D660[12]; // weak
__int16 word_1D66C; // weak
char byte_1D66E; // weak
char byte_1D66F; // weak
char byte_1D670; // weak
_UNKNOWN unk_1D671; // weak
char byte_1DC3C; // weak
char byte_1DC3D; // weak
char byte_1DC3E; // weak
char byte_1DC3F; // weak
char byte_1DC40; // weak
char byte_1DC41; // weak
char byte_1DC42; // weak
char byte_1DC43; // weak
char byte_1DC44; // weak
char byte_1DC45; // weak
char byte_1DC46; // weak
char byte_1DC47; // weak
_UNKNOWN unk_1DC48; // weak
_UNKNOWN unk_1DC4C; // weak
char byte_1E228[128]; // idb
int dword_1E2A8; // weak
int dword_1E2AC; // weak
int dword_1E308; // weak
int dword_1E30C; // weak
int dword_1E310; // weak
// extern _UNKNOWN __gmon_start__; weak


//----- (00008E10) --------------------------------------------------------
int init_proc()
{
  sub_90CC();
  sub_9180();
  return sub_11A28();
}

//----- (00008E24) --------------------------------------------------------
void sub_8E24()
{
  JUMPOUT(0);
}
// 8E30: control flows out of bounds to 0

//----- (00009090) --------------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __noreturn start(void (*a1)(void), int a2, int a3, int a4, ...)
{
  int v4; // [sp-4h] [bp-4h]
  va_list va; // [sp+0h] [bp+0h] BYREF

  va_start(va, a4);
  _libc_start_main((int (*)(int, char **, char **))main, v4, (char **)va, init, (void (*)(void))nullsub_1, a1, va);
  abort();
}
// 909C: positive sp value 4 has been found
// 90B8: variable 'v4' is possibly undefined
// 119BC: using guessed type int nullsub_1();

//----- (000090CC) --------------------------------------------------------
int sub_90CC()
{
  int result; // r0

  if ( &__gmon_start__ )
    return _gmon_start__();
  return result;
}
// 8EBC: using guessed type int _gmon_start__(void);

//----- (000090F0) --------------------------------------------------------
int sub_90F0()
{
  int v0; // r3
  unsigned int i; // r6
  int result; // r0

  if ( !byte_1B2CC )
  {
    v0 = dword_1B2D0;
    for ( i = &dword_1B05C - dword_1B058 - 1; dword_1B2D0 < i; v0 = dword_1B2D0 )
    {
      dword_1B2D0 = v0 + 1;
      result = ((int (*)(void))dword_1B058[v0 + 1])();
    }
    if ( _deregister_frame_info )
      result = _deregister_frame_info(&unk_13000);
    byte_1B2CC = 1;
  }
  return result;
}
// 8E5C: using guessed type int __fastcall _deregister_frame_info(_DWORD);
// 1B058: using guessed type int dword_1B058[];
// 1B05C: using guessed type int dword_1B05C;
// 1B2CC: using guessed type char byte_1B2CC;
// 1B2D0: using guessed type int dword_1B2D0;

//----- (00009178) --------------------------------------------------------
void sub_9178()
{
  ;
}

//----- (00009180) --------------------------------------------------------
int *sub_9180()
{
  if ( _register_frame_info )
    _register_frame_info(&unk_13000, &unk_1B2D4);
  return &dword_1B060;
}
// 8EE0: using guessed type int __fastcall _register_frame_info(_DWORD, _DWORD);
// 1B060: using guessed type int dword_1B060;

//----- (000091D4) --------------------------------------------------------
void sub_91D4()
{
  ;
}

//----- (000091DC) --------------------------------------------------------
bool sub_91DC()
{
  _BYTE v1[8]; // [sp+4h] [bp-10h] BYREF
  int v2; // [sp+Ch] [bp-8h]

  v2 = 0;
  CS_Start(1492, 7890, v1);
  CS_End(1492, 7890, v1);
  return v2 == 1;
}
// 8F64: using guessed type int __fastcall CS_End(_DWORD, _DWORD, _DWORD);
// 903C: using guessed type int __fastcall CS_Start(_DWORD, _DWORD, _DWORD);

//----- (0000924C) --------------------------------------------------------
int sub_924C()
{
  int result; // r0
  _BYTE s1[12]; // [sp+0h] [bp-14h] BYREF
  int v2; // [sp+Ch] [bp-8h]

  v2 = 0;
  do
    v2 = net_RecvFromInterface1(&unk_1D594, s1);
  while ( v2 < 0 );
  result = memcmp(s1, &dword_1D4F0, 0xCu);
  if ( result )
  {
    Semaphore_P(1504);
    memcpy(&dword_1D4F0, s1, 0xCu);
    return Semaphore_V(1504);
  }
  return result;
}
// 8EB0: using guessed type int __fastcall Semaphore_V(_DWORD);
// 8FD0: using guessed type int __fastcall Semaphore_P(_DWORD);
// 9084: using guessed type int __fastcall net_RecvFromInterface1(_DWORD, _DWORD);
// 1D4F0: using guessed type int dword_1D4F0;

//----- (000092D8) --------------------------------------------------------
int __fastcall sub_92D8(char *a1, size_t a2)
{
  char *s; // [sp+4h] [bp-10h]
  int i; // [sp+8h] [bp-Ch]
  int v6; // [sp+Ch] [bp-8h]

  s = a1;
  v6 = 0;
  *a1 = 0;
  for ( i = 0; i <= 127; ++i )
  {
    if ( dword_1B2F0[17 * i] == 1
      && dword_1B2F0[17 * i + 13] == 1
      && dword_1B2F0[17 * i + 5] != 1
      && dword_1B2F0[17 * i + 5] != 2
      && dword_1B2F0[17 * i + 5] != 3
      && dword_1B2F0[17 * i + 5] != 4
      && dword_1B2F0[17 * i + 5] != 5
      && dword_1B2F0[17 * i + 5] != 6
      && dword_1B2F0[17 * i + 5] != 7
      && dword_1B2F0[17 * i + 5] != 8
      && dword_1B2F0[17 * i + 5] != 11
      && dword_1B2F0[17 * i + 5] != 12
      && dword_1B2F0[17 * i + 5] != 15
      && dword_1B2F0[17 * i + 5] != 16
      && dword_1B2F0[17 * i + 5] != 17
      && dword_1B2F0[17 * i + 5] != 20
      && dword_1B2F0[17 * i + 5] != 21
      && dword_1B2F0[17 * i + 5] != 22
      && dword_1B2F0[17 * i + 5] != 23
      && dword_1B2F0[17 * i + 5] != 24
      && dword_1B2F0[17 * i + 5] != 43
      && dword_1B2F0[17 * i + 5] != 13
      && dword_1B2F0[17 * i + 5] != 14 )
    {
      if ( v6 <= 0 )
      {
        *s = 0;
      }
      else
      {
        s += strlen(s);
        snprintf(s, a2, ",", dword_1B2F0[17 * i + 5]);
      }
      s += strlen(s);
      snprintf(s, a2, "%d", dword_1B2F0[17 * i + 5]);
      ++v6;
    }
  }
  return v6;
}
// 1B2F0: using guessed type _DWORD dword_1B2F0[2176];

//----- (00009858) --------------------------------------------------------
int sub_9858()
{
  char *v0; // r0
  char *v1; // r0
  char *v2; // r0
  char *v3; // r0
  char *v4; // r0
  char *v5; // r0
  char v7[32]; // [sp+ACh] [bp-278h] BYREF
  char command[512]; // [sp+CCh] [bp-258h] BYREF
  in_addr in; // [sp+2CCh] [bp-58h]
  int i; // [sp+2D8h] [bp-4Ch]
  int j; // [sp+2DCh] [bp-48h]
  int k; // [sp+2E0h] [bp-44h]
  int v13; // [sp+2E4h] [bp-40h]
  int v14; // [sp+2E8h] [bp-3Ch]
  FILE *s; // [sp+2F8h] [bp-2Ch]
  int v16; // [sp+2FCh] [bp-28h]
  int v17; // [sp+300h] [bp-24h]
  int v18; // [sp+304h] [bp-20h]
  int v19; // [sp+308h] [bp-1Ch]
  int v20; // [sp+30Ch] [bp-18h]
  int v21; // [sp+310h] [bp-14h]
  int v22; // [sp+314h] [bp-10h]

  v16 = 0;
  v22 = 0;
  byte_1B2EC = 0;
  do
    v16 = net_RecvFromInterface1(&unk_1D504, &dword_1B2F0);
  while ( v16 < 0 );
  if ( v16 <= 127 )
    memset((char *)&dword_1B2F0 + 68 * v16, 0, 68 * (128 - v16));
  system("killall ScriptModbus");
  s = fopen("/mnt/ramdisk/script/ScriptModbus", "w+");
  fwrite("iptables -t filter -F modbus_forward\n", 1u, 0x25u, s);
  fwrite("iptables -t filter -Z modbus_forward\n", 1u, 0x25u, s);
  fwrite("ebtables -F OUTPUT\n", 1u, 0x13u, s);
  fwrite("ebtables -Z OUTPUT\n", 1u, 0x13u, s);
  if ( dword_1D4F0 == 1 )
  {
    fprintf(
      s,
      "iptables -t filter -A modbus_forward -p tcp --dport %d -m state --state ESTABLISHED -m modbus --multicommand 1 -j DROP\n",
      dword_1D4F4);
    fprintf(
      s,
      "iptables -t filter -A modbus_forward -p tcp --sport %d -m state --state ESTABLISHED -m modbus --multicommand 1 -j DROP\n",
      dword_1D4F4);
    fprintf(
      s,
      "iptables -t filter -A modbus_forward -p udp --dport %d -m state --state ESTABLISHED -m modbus --multicommand 1 -j DROP\n",
      dword_1D4F4);
    fprintf(
      s,
      "iptables -t filter -A modbus_forward -p udp --sport %d -m state --state ESTABLISHED -m modbus --multicommand 1 -j DROP\n",
      dword_1D4F4);
  }
  if ( dword_1D4F8 == 1 )
  {
    v22 = sub_92D8(command, 512);
    if ( v22 <= 0 )
    {
      fprintf(
        s,
        "iptables -t filter -A modbus_forward -p tcp --dport %d -m modbus --malformed 1 -j DROP\n",
        dword_1D4F4);
      fprintf(
        s,
        "iptables -t filter -A modbus_forward -p tcp --sport %d -m modbus --malformed 1 -j DROP\n",
        dword_1D4F4);
      fprintf(
        s,
        "iptables -t filter -A modbus_forward -p udp --dport %d -m modbus --malformed 1 -j DROP\n",
        dword_1D4F4);
      fprintf(
        s,
        "iptables -t filter -A modbus_forward -p udp --sport %d -m modbus --malformed 1 -j DROP\n",
        dword_1D4F4);
    }
    else
    {
      fprintf(
        s,
        "iptables -t filter -A modbus_forward -p tcp --dport %d -m modbus --malexcludedfc %s --malformed 1 -j DROP\n",
        dword_1D4F4,
        command);
      fprintf(
        s,
        "iptables -t filter -A modbus_forward -p tcp --sport %d -m modbus --malexcludedfc %s --malformed 1 -j DROP\n",
        dword_1D4F4,
        command);
      fprintf(
        s,
        "iptables -t filter -A modbus_forward -p udp --dport %d -m modbus --malexcludedfc %s --malformed 1 -j DROP\n",
        dword_1D4F4,
        command);
      fprintf(
        s,
        "iptables -t filter -A modbus_forward -p udp --sport %d -m modbus --malexcludedfc %s --malformed 1 -j DROP\n",
        dword_1D4F4,
        command);
    }
  }
  for ( i = 0; i <= 127; ++i )
  {
    v20 = 0;
    v21 = 1;
    if ( *((_DWORD *)&dword_1B2F0 + 17 * i + 3) )
      v13 = 1;
    else
      v13 = 2;
    if ( *((_DWORD *)&dword_1B2F0 + 17 * i + 15) == 1 || *((_DWORD *)&dword_1B2F0 + 17 * i + 15) == 2 )
      v14 = 1;
    else
      v14 = 2;
    for ( j = 0; j < v13; ++j )
    {
      if ( *((_DWORD *)&dword_1B2F0 + 17 * i) == 1 )
      {
        for ( k = 0; k < v14; ++k )
        {
          fwrite("iptables -t filter -A modbus_forward ", 1u, 0x25u, s);
          memset(v7, 0, sizeof(v7));
          if ( *((_DWORD *)&dword_1B2F0 + 17 * i + 1) && *((_DWORD *)&dword_1B2F0 + 17 * i + 1) != 0x7FFFFFFF )
          {
            if ( get_slave_interface_in_bridge(*((_DWORD *)&dword_1B2F0 + 17 * i + 1), v7) == 1 )
            {
              fprintf(s, "-m physdev --physdev-in %s ", v7);
              byte_1B2EC = 0;
            }
            else
            {
              get_shm_interface_name_by_vid(*((_DWORD *)&dword_1B2F0 + 17 * i + 1), v7);
              fprintf(s, "-i %s ", v7);
              byte_1B2EC = *((_DWORD *)&dword_1B2F0 + 17 * i + 1) <= 0xFFFu;
            }
          }
          memset(v7, 0, sizeof(v7));
          if ( *((_DWORD *)&dword_1B2F0 + 17 * i + 2) && *((_DWORD *)&dword_1B2F0 + 17 * i + 2) != 0x7FFFFFFF )
          {
            if ( get_slave_interface_in_bridge(*((_DWORD *)&dword_1B2F0 + 17 * i + 2), v7) == 1 )
            {
              if ( byte_1B2EC == 1
                || !*((_DWORD *)&dword_1B2F0 + 17 * i + 1)
                || *((_DWORD *)&dword_1B2F0 + 17 * i + 1) == 0x7FFFFFFF )
              {
                fprintf(s, "-o br8001 -j MARK --set-mark %d ", *((_DWORD *)&dword_1B2F0 + 17 * i + 1));
              }
              else
              {
                fprintf(s, "-m physdev --physdev-out %s ", v7);
              }
            }
            else
            {
              get_shm_interface_name_by_vid(*((_DWORD *)&dword_1B2F0 + 17 * i + 2), v7);
              fprintf(s, "-o %s ", v7);
            }
          }
          if ( *((_DWORD *)&dword_1B2F0 + 17 * i + 3) )
          {
            if ( *((_DWORD *)&dword_1B2F0 + 17 * i + 3) != 1 )
            {
LABEL_41:
              fwrite("-p udp ", 1u, 7u, s);
              goto LABEL_42;
            }
          }
          else if ( j )
          {
            goto LABEL_41;
          }
          fwrite("-p tcp ", 1u, 7u, s);
LABEL_42:
          if ( *((_DWORD *)&dword_1B2F0 + 17 * i + 15) == 1 || *((_DWORD *)&dword_1B2F0 + 17 * i + 15) != 2 && k )
            fprintf(s, "--dport %d ", dword_1D4F4);
          else
            fprintf(s, "--sport %d ", dword_1D4F4);
          if ( *((_DWORD *)&dword_1B2F0 + 17 * i + 9) )
          {
            if ( *((_DWORD *)&dword_1B2F0 + 17 * i + 10) )
            {
              fwrite("-m iprange --src-range ", 1u, 0x17u, s);
              in.s_addr = *((_DWORD *)&dword_1B2F0 + 17 * i + 9);
              v1 = inet_ntoa(in);
              fputs(v1, s);
              in.s_addr = *((_DWORD *)&dword_1B2F0 + 17 * i + 10);
              v2 = inet_ntoa(in);
              fprintf(s, "-%s ", v2);
            }
            else
            {
              in.s_addr = *((_DWORD *)&dword_1B2F0 + 17 * i + 9);
              v0 = inet_ntoa(in);
              fprintf(s, "-s %s ", v0);
            }
          }
          if ( *((_DWORD *)&dword_1B2F0 + 17 * i + 11) )
          {
            if ( *((_DWORD *)&dword_1B2F0 + 17 * i + 12) )
            {
              fwrite("-m iprange --dst-range ", 1u, 0x17u, s);
              in.s_addr = *((_DWORD *)&dword_1B2F0 + 17 * i + 11);
              v4 = inet_ntoa(in);
              fputs(v4, s);
              in.s_addr = *((_DWORD *)&dword_1B2F0 + 17 * i + 12);
              v5 = inet_ntoa(in);
              fprintf(s, "-%s ", v5);
            }
            else
            {
              in.s_addr = *((_DWORD *)&dword_1B2F0 + 17 * i + 11);
              v3 = inet_ntoa(in);
              fprintf(s, "-d %s ", v3);
            }
          }
          fwrite("-m state --state ESTABLISHED -m modbus ", 1u, 0x27u, s);
          if ( *((_DWORD *)&dword_1B2F0 + 17 * i + 4) )
            fprintf(s, "--unitid %d ", *((_DWORD *)&dword_1B2F0 + 17 * i + 4));
          if ( *((_DWORD *)&dword_1B2F0 + 17 * i + 5) )
            fprintf(s, "--funccode %d ", *((_DWORD *)&dword_1B2F0 + 17 * i + 5));
          if ( *((_DWORD *)&dword_1B2F0 + 17 * i + 5) != 5 && *((_DWORD *)&dword_1B2F0 + 17 * i + 5) != 6 )
          {
            if ( *((_DWORD *)&dword_1B2F0 + 17 * i + 15) == 1 )
            {
              fprintf(s, "--commandtype %d ", 1);
            }
            else if ( *((_DWORD *)&dword_1B2F0 + 17 * i + 15) == 2 )
            {
              fprintf(s, "--commandtype %d ", 2);
            }
          }
          switch ( *((_DWORD *)&dword_1B2F0 + 17 * i + 5) )
          {
            case 2:
              v19 = 0;
              break;
            case 4:
              v19 = 0;
              break;
            case 3:
            case 6:
            case 0x10:
            case 0x16:
            case 0x17:
              v19 = 0;
              break;
            default:
              v19 = 0;
              break;
          }
          if ( !*((_BYTE *)&dword_1B2F0 + 68 * i + 24) || !strcmp((const char *)&dword_1B2F0 + 68 * i + 24, " ") )
          {
            if ( *((_BYTE *)&dword_1B2F0 + 68 * i + 30) && strcmp((const char *)&dword_1B2F0 + 68 * i + 30, " ") )
              fprintf(s, "! --refnumrange :%s ", (const char *)&dword_1B2F0 + 68 * i + 30);
          }
          else if ( *((_BYTE *)&dword_1B2F0 + 68 * i + 30) && strcmp((const char *)&dword_1B2F0 + 68 * i + 30, " ") )
          {
            v17 = atoi((const char *)&dword_1B2F0 + 68 * i + 24);
            v18 = atoi((const char *)&dword_1B2F0 + 68 * i + 30);
            if ( *((_DWORD *)&dword_1B2F0 + 17 * i + 16) == 1 )
              fprintf(s, "--refnumrange %d:%d ", v17 - v19 - 1, v18 - v19 - 1);
            else
              fprintf(s, "--refnumrange %d:%d ", v17 - v19, v18 - v19);
          }
          else
          {
            v17 = atoi((const char *)&dword_1B2F0 + 68 * i + 24);
            if ( *((_DWORD *)&dword_1B2F0 + 17 * i + 16) == 1 )
              fprintf(s, "--refnum %d ", v17 - v19 - 1);
            else
              fprintf(s, "--refnum %d ", v17 - v19);
          }
          if ( *((_DWORD *)&dword_1B2F0 + 17 * i + 2)
            && get_slave_interface_in_bridge(*((_DWORD *)&dword_1B2F0 + 17 * i + 2), v7) == 1
            && (byte_1B2EC == 1
             || !*((_DWORD *)&dword_1B2F0 + 17 * i + 1)
             || *((_DWORD *)&dword_1B2F0 + 17 * i + 1) == 0x7FFFFFFF) )
          {
            fputc(10, s);
            fprintf(s, "ebtables -A OUTPUT -o %s --mark %d ", v7, *((_DWORD *)&dword_1B2F0 + 17 * i + 1));
          }
          if ( *((_DWORD *)&dword_1B2F0 + 17 * i + 13) == 2 )
            fwrite("-j DROP\n", 1u, 8u, s);
          else
            fwrite("-j ACCEPT\n", 1u, 0xAu, s);
        }
      }
    }
  }
  fwrite("conntrack -F\n", 1u, 0xDu, s);
  fclose(s);
  Semaphore_P(1504);
  sprintf(command, "sh %s", "/mnt/ramdisk/script/ScriptModbus");
  system(command);
  return Semaphore_V(1504);
}
// 8E8C: using guessed type int __fastcall get_shm_interface_name_by_vid(_DWORD, _DWORD);
// 8EB0: using guessed type int __fastcall Semaphore_V(_DWORD);
// 8FD0: using guessed type int __fastcall Semaphore_P(_DWORD);
// 900C: using guessed type int __fastcall get_slave_interface_in_bridge(_DWORD, _DWORD);
// 9084: using guessed type int __fastcall net_RecvFromInterface1(_DWORD, _DWORD);
// 92D8: using guessed type int __fastcall sub_92D8(_DWORD, _DWORD);
// 1B2EC: using guessed type char byte_1B2EC;
// 1D4F0: using guessed type int dword_1D4F0;
// 1D4F4: using guessed type int dword_1D4F4;
// 1D4F8: using guessed type int dword_1D4F8;

//----- (0000AD7C) --------------------------------------------------------
void __fastcall __noreturn main(int a1, char **a2, char **a3)
{
  int v3; // r0
  int v4; // r0
  timeval timeout; // [sp+60h] [bp-ACh] BYREF
  fd_set readfds; // [sp+68h] [bp-A4h] BYREF
  int v7; // [sp+E8h] [bp-24h]
  int v8; // [sp+ECh] [bp-20h]
  unsigned int i; // [sp+F0h] [bp-1Ch]
  fd_set *p_readfds; // [sp+F4h] [bp-18h]
  unsigned int j; // [sp+F8h] [bp-14h]
  fd_set *v12; // [sp+FCh] [bp-10h]
  unsigned int k; // [sp+100h] [bp-Ch]
  fd_set *v14; // [sp+104h] [bp-8h]

  memset(&dword_1B2F0, 0, 0x2200u);
  memset(&dword_1D4F0, 0, 0xCu);
  memset(&unk_1D4FC, 0, 8u);
  Semaphore_init(1504);
  v3 = sock_path("NET_SCRIPT_MODBUS.SOCKET");
  net_OpenSocketToInterface_Recv(&unk_1D504, v3);
  v4 = sock_path("NET_SCRIPT_MODBUS_GLOBAL.SOCKET");
  net_OpenSocketToInterface_Recv(&unk_1D594, v4);
  if ( dword_1D574 > v7 )
    v7 = dword_1D574;
  if ( dword_1D604 > v7 )
    v7 = dword_1D604;
  timeout.tv_sec = 3;
  timeout.tv_usec = 0;
  p_readfds = &readfds;
  for ( i = 0; i <= 0x1F; ++i )
    p_readfds->__fds_bits[i] = 0;
  readfds.__fds_bits[(unsigned int)dword_1D574 >> 5] |= 1 << (dword_1D574 & 0x1F);
  readfds.__fds_bits[(unsigned int)dword_1D604 >> 5] |= 1 << (dword_1D604 & 0x1F);
  printf("%s, %d\n", "main", 697);
  while ( 1 )
  {
    while ( 1 )
    {
      while ( 1 )
      {
        timeout.tv_sec = 3;
        timeout.tv_usec = 0;
        v8 = select(v7 + 1, &readfds, 0, 0, &timeout);
        if ( v8 != -1 )
          break;
        perror("select()");
      }
      if ( v8 )
        break;
      v12 = &readfds;
      for ( j = 0; j <= 0x1F; ++j )
        v12->__fds_bits[j] = 0;
      readfds.__fds_bits[(unsigned int)dword_1D604 >> 5] |= 1 << (dword_1D604 & 0x1F);
      readfds.__fds_bits[(unsigned int)dword_1D574 >> 5] |= 1 << (dword_1D574 & 0x1F);
      sub_91DC();
    }
    if ( (((unsigned int)readfds.__fds_bits[(unsigned int)dword_1D604 >> 5] >> (dword_1D604 & 0x1F)) & 1) != 0 )
      sub_924C();
    if ( (((unsigned int)readfds.__fds_bits[(unsigned int)dword_1D574 >> 5] >> (dword_1D574 & 0x1F)) & 1) != 0 )
      sub_9858();
    v14 = &readfds;
    for ( k = 0; k <= 0x1F; ++k )
      v14->__fds_bits[k] = 0;
    readfds.__fds_bits[(unsigned int)dword_1D604 >> 5] |= 1 << (dword_1D604 & 0x1F);
    readfds.__fds_bits[(unsigned int)dword_1D574 >> 5] |= 1 << (dword_1D574 & 0x1F);
  }
}
// 8F10: using guessed type int __fastcall net_OpenSocketToInterface_Recv(_DWORD, _DWORD);
// 8FE8: using guessed type int __fastcall sock_path(_DWORD);
// 906C: using guessed type int __fastcall Semaphore_init(_DWORD);
// 91DC: using guessed type int sub_91DC(void);
// 924C: using guessed type int sub_924C(void);
// 9858: using guessed type int sub_9858(void);
// 1D4F0: using guessed type int dword_1D4F0;
// 1D574: using guessed type int dword_1D574;
// 1D604: using guessed type int dword_1D604;

//----- (0000B298) --------------------------------------------------------
int sub_B298()
{
  dword_1D628 = 0;
  if ( dword_1D62C )
    return dword_1D62C;
  dword_1D62C = open("/dev/eth_switch", 2);
  if ( dword_1D62C >= 0 )
    return dword_1D62C;
  perror("open");
  dword_1D62C = 0;
  return -1;
}
// 1D628: using guessed type int dword_1D628;
// 1D62C: using guessed type int dword_1D62C;

//----- (0000B32C) --------------------------------------------------------
int sub_B32C()
{
  close(dword_1D62C);
  dword_1D62C = 0;
  return 0;
}
// 1D62C: using guessed type int dword_1D62C;

//----- (0000B360) --------------------------------------------------------
int __fastcall sub_B360(int a1, int a2, _DWORD *a3)
{
  int v4; // r0
  _BYTE v9[4]; // [sp+18h] [bp-214h] BYREF
  int v10; // [sp+1Ch] [bp-210h] BYREF
  int fd; // [sp+21Ch] [bp-10h]
  int v12; // [sp+220h] [bp-Ch]
  int *v13; // [sp+224h] [bp-8h]

  v12 = 1;
  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  v9[0] = 1;
  v9[2] = 12;
  v9[3] = 0;
  v13 = &v10;
  v4 = sub_113D0(a1);
  *v13 = v4;
  v13[1] = a2;
  if ( ioctl(fd, 0x82044700, v9) < 0 )
    sub_112E4(3, "ioctl READ_REG_IOCTL error\n");
  sub_112E4(6, "port %d, REG 0x%x => 0x%x\n", a1, a2, v13[2]);
  *a3 = v13[2];
  return v12;
}

//----- (0000B470) --------------------------------------------------------
int __fastcall sub_B470(int a1, int a2, int a3)
{
  int v4; // r0
  _BYTE v9[4]; // [sp+18h] [bp-214h] BYREF
  int v10; // [sp+1Ch] [bp-210h] BYREF
  int fd; // [sp+21Ch] [bp-10h]
  int v12; // [sp+220h] [bp-Ch]
  int *v13; // [sp+224h] [bp-8h]

  v12 = 1;
  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  v9[0] = 1;
  v9[2] = 12;
  v9[3] = 0;
  v13 = &v10;
  v4 = sub_113D0(a1);
  *v13 = v4;
  v13[1] = a2;
  v13[2] = a3;
  if ( ioctl(fd, 0x42044701u, v9) < 0 )
    sub_112E4(3, "ioctl WRITE_REG_IOCTL error\n");
  sub_112E4(6, "port %d, REG 0x%x , VAL = 0x%x\n", a1, a2, a3);
  return v12;
}

//----- (0000B574) --------------------------------------------------------
int __fastcall sub_B574(int a1, int a2, _DWORD *a3)
{
  _BYTE v8[4]; // [sp+18h] [bp-214h] BYREF
  _DWORD v9[128]; // [sp+1Ch] [bp-210h] BYREF
  int fd; // [sp+21Ch] [bp-10h]
  int v11; // [sp+220h] [bp-Ch]
  _DWORD *v12; // [sp+224h] [bp-8h]

  v11 = 1;
  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  v8[0] = 0;
  v8[2] = 12;
  v8[3] = 0;
  v12 = v9;
  v9[0] = a1;
  v9[1] = a2;
  if ( ioctl(fd, 0x82044700, v8) < 0 )
    sub_112E4(3, "ioctl READ_REG_IOCTL error\n");
  sub_112E4(6, "PHY 0x%x, REG 0x%x => 0x%x\n", a1, a2, v12[2]);
  *a3 = v12[2];
  return v11;
}

//----- (0000B678) --------------------------------------------------------
int __fastcall sub_B678(int a1, int a2, int a3)
{
  _BYTE v8[4]; // [sp+18h] [bp-214h] BYREF
  _DWORD v9[128]; // [sp+1Ch] [bp-210h] BYREF
  int fd; // [sp+21Ch] [bp-10h]
  int v11; // [sp+220h] [bp-Ch]
  _DWORD *v12; // [sp+224h] [bp-8h]

  v11 = 1;
  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  v8[0] = 0;
  v8[2] = 12;
  v8[3] = 0;
  v12 = v9;
  v9[0] = a1;
  v9[1] = a2;
  v9[2] = a3;
  if ( ioctl(fd, 0x42044701u, v8) < 0 )
    sub_112E4(3, "ioctl WRITE_REG_IOCTL error\n");
  sub_112E4(6, "PHY 0x%x, REG 0x%x , VAL = 0x%x\n", a1, a2, a3);
  return v11;
}

//----- (0000B770) --------------------------------------------------------
int __fastcall sub_B770(int a1)
{
  if ( ((1 << a1) & dword_1D628) != 0 )
  {
    sub_112E4(7, "%s() %d vport = %d isGiga\n", "Ssc_isGigaCopperLink", 184, a1);
    return 1;
  }
  else
  {
    sub_112E4(7, "%s() %d vport = %d notGiga\n", "Ssc_isGigaCopperLink", 188, a1);
    return 0;
  }
}
// 1D628: using guessed type int dword_1D628;

//----- (0000B800) --------------------------------------------------------
int __fastcall sub_B800(int a1)
{
  char v2; // r0
  int v5; // [sp+Ch] [bp-10h] BYREF
  int fd; // [sp+10h] [bp-Ch]
  int v7; // [sp+14h] [bp-8h]

  v7 = 1;
  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  if ( ioctl(fd, 0x8004470A, &v5) < 0 )
    sub_112E4(3, "ioctl ETHSW_LINK_STATUS_GET error\n");
  v2 = sub_113D0(a1);
  if ( ((1 << v2) & v5) != 0 )
    v7 = 0;
  sub_112E4(7, "port %d isDown = %d\n", a1, v7);
  return v7;
}

//----- (0000B8CC) --------------------------------------------------------
int __fastcall sub_B8CC(int a1, _DWORD *a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 1;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_113D0(a1);
  *v8 = v3;
  if ( ioctl(fd, 0x82044702, s) >= 0 )
  {
    *a2 = v8[1];
    return 0;
  }
  else
  {
    sub_112E4(3, "%s() ioctl error\n", "Ssc_port_speed_get");
    return -1;
  }
}

//----- (0000B9BC) --------------------------------------------------------
int __fastcall sub_B9BC(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+14h] [bp-210h] BYREF
  int *v8; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  sub_112E4(7, "%s() %d >>>>>>> port %d %d\n", "Ssc_port_speed_set", 266, a1, a2);
  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 1;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_113D0(a1);
  *v8 = v3;
  v8[1] = a2;
  if ( ioctl(fd, 0x42044703u, s) < 0 )
    sub_112E4(3, "%s() ioctl error\n", "Ssc_port_speed_set");
  return 0;
}

//----- (0000BACC) --------------------------------------------------------
int __fastcall sub_BACC(int a1)
{
  int v2; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v6; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 7;
  s[2] = 8;
  s[3] = 0;
  v6 = (int *)&s[4];
  v2 = sub_113D0(a1);
  *v6 = v2;
  if ( ioctl(fd, 0x42044703u, s) < 0 )
    sub_112E4(3, "%s() ioctl error\n", "Ssc_port_learing_disable");
  return 0;
}

//----- (0000BBA0) --------------------------------------------------------
int __fastcall sub_BBA0(int a1)
{
  int v2; // r0
  _BYTE v5[4]; // [sp+Ch] [bp-210h] BYREF
  int v6; // [sp+10h] [bp-20Ch] BYREF
  int *v7; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  v5[0] = 8;
  v5[2] = 8;
  v5[3] = 0;
  v7 = &v6;
  v2 = sub_113D0(a1);
  *v7 = v2;
  if ( ioctl(fd, 0x42044703u, v5) < 0 )
    sub_112E4(3, "%s() ioctl error\n", "Ssc_port_learing_enable");
  return 0;
}

//----- (0000BC60) --------------------------------------------------------
int sub_BC60()
{
  _BYTE v2[516]; // [sp+4h] [bp-210h] BYREF
  int fd; // [sp+208h] [bp-Ch]

  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  v2[0] = 9;
  v2[2] = 8;
  v2[3] = 0;
  if ( ioctl(fd, 0x42044703u, v2) < 0 )
    sub_112E4(3, "%s() ioctl error\n", "Ssc_cpuport_learing_disable");
  return 0;
}

//----- (0000BCFC) --------------------------------------------------------
int sub_BCFC()
{
  _BYTE v2[520]; // [sp+4h] [bp-210h] BYREF
  int fd; // [sp+20Ch] [bp-8h]

  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  v2[0] = 10;
  v2[2] = 8;
  v2[3] = 0;
  if ( ioctl(fd, 0x42044703u, v2) < 0 )
    sub_112E4(3, "%s() ioctl error\n", "Ssc_cpuport_learing_enable");
  return 0;
}

//----- (0000BD98) --------------------------------------------------------
int __fastcall sub_BD98(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 2;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_113D0(a1);
  *v8 = v3;
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_112E4(3, "%s() ioctl error\n", "Ssc_port_duplex_get");
  *(_DWORD *)a2 = v8[1];
  return *(_DWORD *)a2;
}

//----- (0000BE84) --------------------------------------------------------
int __fastcall sub_BE84(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 11;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_113D0(a1);
  *v8 = v3;
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_112E4(3, "%s() ioctl error\n", "Ssc_port_qinq_get");
  *(_DWORD *)a2 = v8[1];
  return *(_DWORD *)a2;
}

//----- (0000BF70) --------------------------------------------------------
int __fastcall sub_BF70(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 12;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_113D0(a1);
  *v8 = v3;
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_112E4(3, "%s() ioctl error\n", "Ssc_port_egress_get");
  *(_DWORD *)a2 = v8[1];
  return *(_DWORD *)a2;
}

//----- (0000C05C) --------------------------------------------------------
int __fastcall sub_C05C(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 13;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_113D0(a1);
  *v8 = v3;
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_112E4(3, "%s() ioctl error\n", "Ssc_port_802dot1q_mode_get");
  *(_DWORD *)a2 = v8[1];
  return *(_DWORD *)a2;
}

//----- (0000C148) --------------------------------------------------------
int __fastcall sub_C148(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+8h] [bp-214h] BYREF
  int v8; // [sp+20Ch] [bp-10h]
  int *v9; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 13;
  s[2] = 8;
  s[3] = 0;
  v9 = (int *)&s[4];
  v3 = sub_113D0(a1);
  *v9 = v3;
  v9[1] = a2;
  if ( ioctl(fd, 0x42044703u, s) < 0 )
    sub_112E4(3, "%s() ioctl error\n", "Ssc_port_802dot1q_mode_set");
  return v8;
}

//----- (0000C22C) --------------------------------------------------------
int __fastcall sub_C22C(int a1, const char *a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+14h] [bp-210h] BYREF
  int *v8; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  sub_112E4(7, "%s() %d >>>>>>> port %d %s\n", "Ssc_port_duplex_set", 548, a1, a2);
  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 2;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_113D0(a1);
  *v8 = v3;
  v8[1] = (int)a2;
  if ( ioctl(fd, 0x42044703u, s) < 0 )
    sub_112E4(3, "%s() ioctl error\n", "Ssc_port_duplex_set");
  return 0;
}

//----- (0000C338) --------------------------------------------------------
int __fastcall sub_C338(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 4;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_113D0(a1);
  *v8 = v3;
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_112E4(3, "%s() ioctl error\n", "Ssc_port_pause_get");
  *(_DWORD *)a2 = v8[1];
  return *(_DWORD *)a2;
}

//----- (0000C424) --------------------------------------------------------
int __fastcall sub_C424(int a1, const char *a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+14h] [bp-210h] BYREF
  int *v8; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  sub_112E4(7, "%s() %d >>>>>>> port %d %s\n", "Ssc_port_pause_set", 619, a1, a2);
  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 4;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_113D0(a1);
  *v8 = v3;
  v8[1] = (int)a2;
  if ( ioctl(fd, 0x42044703u, s) < 0 )
    sub_112E4(3, "%s() ioctl error\n", "Ssc_port_pause_set");
  return 0;
}

//----- (0000C534) --------------------------------------------------------
int __fastcall sub_C534(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 3;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_113D0(a1);
  *v8 = v3;
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_112E4(3, "%s() ioctl error\n", "Ssc_port_mdi_get");
  *(_DWORD *)a2 = v8[1];
  return *(_DWORD *)a2;
}

//----- (0000C620) --------------------------------------------------------
int __fastcall sub_C620(int a1, const char *a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+14h] [bp-210h] BYREF
  int *v8; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  sub_112E4(7, "%s() %d >>>>>>> port %d %s\n", "Ssc_port_mdi_set", 689, a1, a2);
  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 3;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_113D0(a1);
  *v8 = v3;
  v8[1] = (int)a2;
  if ( ioctl(fd, 0x42044703u, s) < 0 )
    sub_112E4(3, "%s() ioctl SET_PORT_STATE error\n", "Ssc_port_mdi_set");
  return 0;
}

//----- (0000C730) --------------------------------------------------------
int __fastcall sub_C730(int a1)
{
  int v2; // r0
  _BYTE s[516]; // [sp+14h] [bp-210h] BYREF
  int *v6; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 1;
  s[2] = 8;
  s[3] = 0;
  v6 = (int *)&s[4];
  v2 = sub_113D0(a1);
  *v6 = v2;
  if ( ioctl(fd, 0x82044708, s) < 0 )
    sub_112E4(3, "ioctl GET_PORT_STATE error\n");
  sub_112E4(5, "%s() Port %d state = %d\n", "Ssc_getPortState", *v6, v6[1]);
  return v6[1];
}

//----- (0000C82C) --------------------------------------------------------
int __fastcall sub_C82C(int a1, int a2, int a3)
{
  int result; // r0
  int v4; // r0
  char v5; // [sp+14h] [bp-220h]
  int v6; // [sp+18h] [bp-21Ch]
  _BYTE s[516]; // [sp+24h] [bp-210h] BYREF
  int *v9; // [sp+228h] [bp-Ch]
  int fd; // [sp+22Ch] [bp-8h]

  v6 = a2;
  v5 = a3;
  sub_112E4(5, "%s() %d >>>>>> port %d state %d, flags = 0x%02x\n", "Ssc_setPortState", 772, a1, a2, a3);
  result = sub_B298();
  fd = result;
  if ( result >= 0 )
  {
    if ( (unsigned int)(v6 - 2) > 3 )
    {
      if ( (v5 & 1) != 0 )
      {
        v6 = 2;
      }
      else if ( (v5 & 4) != 0 )
      {
        v6 = 1;
      }
      else
      {
        v6 = 5;
      }
    }
    memset(s, 0, sizeof(s));
    s[0] = 1;
    s[2] = 8;
    s[3] = 0;
    v9 = (int *)&s[4];
    v4 = sub_113D0(a1);
    *v9 = v4;
    v9[1] = v6;
    if ( ioctl(fd, 0x42044709u, s) < 0 )
      sub_112E4(3, "ioctl SET_PORT_STATE error\n");
    return sub_112E4(5, "%s() Port %d state = %d\n", "Ssc_setPortState", *v9, v9[1]);
  }
  return result;
}

//----- (0000C9C0) --------------------------------------------------------
int __fastcall sub_C9C0(int a1, int a2)
{
  const char *v2; // r3
  char *v3; // r0
  int v5; // r0
  char s[128]; // [sp+14h] [bp-298h] BYREF
  _BYTE v10[516]; // [sp+94h] [bp-218h] BYREF
  int *v11; // [sp+298h] [bp-14h]
  int fd; // [sp+29Ch] [bp-10h]

  fd = 0;
  if ( a2 )
    v2 = "Enable";
  else
    v2 = "Disable";
  sub_112E4(7, "%s() %d >>>>>>> port %d %s\n", "Ssc_port_enable_set", 834, a1, v2);
  if ( a1 <= 7 )
  {
    fd = sub_B298();
    if ( fd >= 0 )
    {
      memset(v10, 0, sizeof(v10));
      v10[0] = 0;
      v10[2] = 8;
      v10[3] = 0;
      v11 = (int *)&v10[4];
      v5 = sub_113D0(a1);
      *v11 = v5;
      v11[1] = a2;
      if ( ioctl(fd, 0x42044703u, v10) < 0 )
        sub_112E4(3, "%s() ioctl SET_PORT_STATE error\n", "Ssc_port_enable_set");
      return 0;
    }
    else
    {
      return -1;
    }
  }
  else
  {
    v3 = sub_10E0C("port_enable");
    sprintf(s, " echo %x,%d > %s", a1, a2, v3);
    system(s);
    printf("msg = %s\n", s);
    return 0;
  }
}

//----- (0000CB58) --------------------------------------------------------
int __fastcall Ssc_getPortLinkState(_DWORD *a1)
{
  char v2; // r0
  int v5; // [sp+8h] [bp-14h] BYREF
  int v6; // [sp+Ch] [bp-10h]
  int i; // [sp+10h] [bp-Ch]
  int fd; // [sp+14h] [bp-8h]

  v6 = 1;
  i = 0;
  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  if ( ioctl(fd, 0x8004470A, &v5) < 0 )
    sub_112E4(3, "ioctl ETHSW_LINK_STATUS_GET error\n");
  for ( i = 0; i <= 9; ++i )
  {
    v2 = sub_113D0(i);
    if ( ((1 << v2) & v5) != 0 )
      *a1 |= 1 << i;
  }
  return v6;
}

//----- (0000CC50) --------------------------------------------------------
int __fastcall sub_CC50(int a1)
{
  int v2; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v6; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 0;
  s[2] = 8;
  s[3] = 0;
  v6 = (int *)&s[4];
  v2 = sub_113D0(a1);
  *v6 = v2;
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_112E4(3, "%s() ioctl SET_PORT_STATE error\n", "Ssc_port_enable_get");
  return v6[1];
}

//----- (0000CD28) --------------------------------------------------------
void *__fastcall Ssc_getPortStatsCounter(void *a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-218h] BYREF
  int *v7; // [sp+210h] [bp-14h]
  int fd; // [sp+214h] [bp-10h]

  fd = sub_B298();
  if ( fd < 0 )
    fprintf((FILE *)stderr, "%s() device open failed\n", "Ssc_getPortStatsCounter");
  memset(s, 0, sizeof(s));
  s[0] = 0;
  strcpy(&s[2], "d");
  v7 = (int *)&s[4];
  v3 = sub_113D0(a2);
  *v7 = v3;
  if ( ioctl(fd, 0x80044714, s) < 0 )
    sub_112E4(3, "%s() ioctl GET_PORT_STATSCOUNTER error\n", "Ssc_getPortStatsCounter");
  memcpy(a1, v7 + 1, 0x60u);
  return a1;
}
// 1B2C8: using guessed type int stderr;

//----- (0000CE3C) --------------------------------------------------------
int __fastcall sub_CE3C(_DWORD *a1)
{
  pthread_mutex_lock(&mutex);
  *a1 = dword_1D634;
  dword_1D634 = 0;
  return pthread_mutex_unlock(&mutex);
}
// 1D634: using guessed type int dword_1D634;

//----- (0000CE88) --------------------------------------------------------
int __fastcall sub_CE88(int a1)
{
  pthread_mutex_lock(&mutex);
  dword_1D634 |= a1;
  return pthread_mutex_unlock(&mutex);
}
// 1D634: using guessed type int dword_1D634;

//----- (0000CED0) --------------------------------------------------------
int __fastcall sub_CED0(int a1)
{
  int result; // r0
  int v3; // [sp+10h] [bp-214h] BYREF
  _BYTE s[516]; // [sp+14h] [bp-210h] BYREF
  _BYTE *v5; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  sub_112E4(5, "%s() %d pbmp = %lx\n", "Ssc_flushMacAddr", 979, a1);
  result = sub_B298();
  fd = result;
  if ( result >= 0 )
  {
    memset(s, 0, sizeof(s));
    s[0] = 1;
    s[2] = 12;
    s[3] = 0;
    v5 = &s[4];
    sub_1158C(a1, &v3);
    *((_DWORD *)v5 + 2) = v3;
    if ( ioctl(fd, 0x42044705u, s) < 0 )
      sub_112E4(3, "ioctl ETHSW_FDB_FLUSH error\n");
    return sub_CE88(a1);
  }
  return result;
}

//----- (0000CFD0) --------------------------------------------------------
int __fastcall sub_CFD0(int a1)
{
  _DWORD s[130]; // [sp+Ch] [bp-210h] BYREF
  int fd; // [sp+214h] [bp-8h]

  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, 0x204u);
  LOBYTE(s[0]) = 8;
  HIWORD(s[0]) = 4;
  s[129] = &s[1];
  s[1] = a1;
  if ( ioctl(fd, 0x42044705u, s) < 0 )
    sub_112E4(3, "ioctl ETHSW_TYPE_FDB_AGE_TIME error\n");
  return 0;
}

//----- (0000D094) --------------------------------------------------------
int sub_D094()
{
  _DWORD s[129]; // [sp+0h] [bp-214h] BYREF
  int v3; // [sp+204h] [bp-10h]
  _DWORD *v4; // [sp+208h] [bp-Ch]
  int fd; // [sp+20Ch] [bp-8h]

  v3 = 0;
  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  LOBYTE(s[0]) = 0;
  HIWORD(s[0]) = 4;
  v4 = &s[1];
  s[1] = 1;
  if ( ioctl(fd, 0x82044704, s, s) < 0 )
    sub_112E4(3, "%s() ioctl ETHSW_FDB_GET error\n", "Ssc_fdbGetEntry");
  return v3;
}

//----- (0000D164) --------------------------------------------------------
int __fastcall sub_D164(const void *a1, _DWORD *a2)
{
  int v6; // [sp+8h] [bp-21Ch] BYREF
  _BYTE s[516]; // [sp+Ch] [bp-218h] BYREF
  int v8; // [sp+210h] [bp-14h]
  int fd; // [sp+214h] [bp-10h]
  void *dest; // [sp+218h] [bp-Ch]
  int v11; // [sp+21Ch] [bp-8h]

  v8 = 0;
  v11 = 0;
  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  v6 = 0;
  memset(s, 0, sizeof(s));
  s[0] = 7;
  s[2] = 28;
  s[3] = 0;
  dest = &s[4];
  memcpy(&s[4], a1, 6u);
  if ( ioctl(fd, 0x82044704, s) < 0 )
    sub_112E4(3, "%s() ioctl ETHSW_FDB_GET error\n", "Ssc_fdbGetMacPbmp");
  v8 = *((unsigned __int8 *)dest + 25);
  if ( v8 )
    sub_11674(*((_DWORD *)dest + 3), &v6);
  *a2 = v6;
  return v8;
}

//----- (0000D290) --------------------------------------------------------
int __fastcall sub_D290(const void *a1, void *a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+2Ch] [bp-228h] BYREF
  int v8; // [sp+230h] [bp-24h]
  int fd; // [sp+234h] [bp-20h]
  void *dest; // [sp+238h] [bp-1Ch]
  int i; // [sp+23Ch] [bp-18h]

  v8 = 0;
  i = 0;
  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 7;
  s[2] = 28;
  s[3] = 0;
  dest = &s[4];
  memcpy(&s[4], a1, 6u);
  if ( ioctl(fd, 0x82044704, s) < 0 )
    sub_112E4(3, "%s() ioctl ETHSW_FDB_GET error\n", "Ssc_fdbFindMacEntry");
  v8 = *((unsigned __int8 *)dest + 25);
  if ( v8 )
  {
    for ( i = 0; i <= 9; ++i )
    {
      if ( (*((_DWORD *)dest + 3) & (1 << i)) != 0 )
      {
        v3 = sub_1149C(i);
        *((_DWORD *)dest + 2) = v3;
        break;
      }
    }
    memcpy(a2, dest, 0x1Cu);
  }
  printf(
    "%s() addr = %02x:%02x:%02x:%02x:%02x:%02x, port = %02x (%d), inused = %d\n",
    "Ssc_fdbFindMacEntry",
    *(unsigned __int8 *)dest,
    *((unsigned __int8 *)dest + 1),
    *((unsigned __int8 *)dest + 2),
    *((unsigned __int8 *)dest + 3),
    *((unsigned __int8 *)dest + 4),
    *((unsigned __int8 *)dest + 5),
    *((_DWORD *)dest + 3),
    *((_DWORD *)dest + 2),
    *((unsigned __int8 *)dest + 25));
  return v8;
}

//----- (0000D488) --------------------------------------------------------
int __fastcall sub_D488(const void *a1, void *a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+2Ch] [bp-228h] BYREF
  int v8; // [sp+230h] [bp-24h]
  int fd; // [sp+234h] [bp-20h]
  void *dest; // [sp+238h] [bp-1Ch]
  int i; // [sp+23Ch] [bp-18h]

  v8 = 0;
  i = 0;
  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 7;
  s[2] = 28;
  s[3] = 0;
  dest = &s[4];
  memcpy(&s[4], a1, 6u);
  if ( ioctl(fd, 0x82044704, s) < 0 )
    sub_112E4(3, "%s() ioctl ETHSW_FDB_GET error\n", "Ssc_fdbFindAllMacEntry");
  v8 = *((unsigned __int8 *)dest + 25);
  if ( v8 )
  {
    for ( i = 0; i <= 13; ++i )
    {
      if ( (*((_DWORD *)dest + 3) & (1 << i)) != 0 )
      {
        v3 = sub_1149C(i);
        *((_DWORD *)dest + 2) = v3;
        break;
      }
    }
    memcpy(a2, dest, 0x1Cu);
  }
  printf(
    "%s() addr = %02x:%02x:%02x:%02x:%02x:%02x, port = %02x (%d), inused = %d\n",
    "Ssc_fdbFindAllMacEntry",
    *(unsigned __int8 *)dest,
    *((unsigned __int8 *)dest + 1),
    *((unsigned __int8 *)dest + 2),
    *((unsigned __int8 *)dest + 3),
    *((unsigned __int8 *)dest + 4),
    *((unsigned __int8 *)dest + 5),
    *((_DWORD *)dest + 3),
    *((_DWORD *)dest + 2),
    *((unsigned __int8 *)dest + 25));
  return v8;
}

//----- (0000D680) --------------------------------------------------------
int __fastcall sub_D680(_DWORD *a1)
{
  int v2; // r4
  _BYTE s[516]; // [sp+8h] [bp-21Ch] BYREF
  int v6; // [sp+20Ch] [bp-18h]
  int *v7; // [sp+210h] [bp-14h]
  int fd; // [sp+214h] [bp-10h]

  v6 = 0;
  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 6;
  s[2] = 16;
  s[3] = 0;
  v7 = (int *)&s[4];
  if ( ioctl(fd, 0x82044704, s) < 0 )
    sub_112E4(3, "%s() ioctl ETHSW_FDB_GET error\n", "Ssc_fdbGetAddrTableSize");
  v6 = *v7;
  v2 = v7[3];
  *a1 = v7[2];
  a1[1] = v2;
  return v6;
}

//----- (0000D768) --------------------------------------------------------
int __fastcall sub_D768(char *a1, size_t a2, int a3)
{
  unsigned int v4; // r0
  int v5; // r4
  _BYTE v10[14336]; // [sp+10h] [bp-3834h] BYREF
  int v11; // [sp+3810h] [bp-34h] BYREF
  int v12; // [sp+3814h] [bp-30h]
  int fd; // [sp+3818h] [bp-2Ch]
  ssize_t v14; // [sp+381Ch] [bp-28h]
  int v15; // [sp+3820h] [bp-24h]
  int i; // [sp+3824h] [bp-20h]
  int v17; // [sp+3828h] [bp-1Ch]
  int v18; // [sp+382Ch] [bp-18h]
  int v19; // [sp+3830h] [bp-14h]
  int v20; // [sp+3834h] [bp-10h]

  fd = 0;
  v14 = 0;
  v15 = 0;
  i = 0;
  v17 = 0;
  v18 = 0;
  v19 = 0;
  v20 = 0;
  v11 = 0;
  v12 = 0;
  if ( a1 )
  {
    fd = sub_B298();
    if ( fd >= 0 )
    {
      memset(v10, 0, sizeof(v10));
      v17 = sub_D680(&v11);
      if ( v17 > 511 )
        v18 = 512;
      else
        v18 = v17;
      if ( v11 == unk_1D650 && v12 == unk_1D654 )
      {
LABEL_10:
        sub_B32C();
        return dword_1D658;
      }
      else
      {
        memset(a1, 0, a2);
        dword_1D658 = 0;
        unk_1D650 = v11;
        unk_1D654 = v12;
        while ( 1 )
        {
          v14 = read(fd, v10, 28 * v18);
          if ( v14 == -1 )
            break;
          v4 = sub_1175C(v14, 0x1Cu);
          v15 += v4;
          for ( i = 0; i < v18; ++i )
          {
            if ( a3 )
            {
              if ( v10[28 * i] == 1
                && (unsigned __int8)v10[28 * i + 1] == 128
                && (unsigned __int8)v10[28 * i + 2] == 194 )
              {
                continue;
              }
              v5 = *(_DWORD *)&v10[28 * i + 12];
              if ( (v5 & (1 << sub_113D0(14))) != 0 )
                continue;
            }
            memcpy(&a1[92 * dword_1D658], &v10[28 * i], 6u);
            if ( a1[92 * dword_1D658] == 1 )
            {
              strcpy(&a1[92 * dword_1D658 + 6], "mcast");
              strcpy(&a1[92 * dword_1D658 + 14], "static");
            }
            else
            {
              strcpy(&a1[92 * dword_1D658 + 6], "ucast");
              if ( *(_DWORD *)&v10[28 * i + 16] == 1 )
                strcpy(&a1[92 * dword_1D658 + 14], "learn");
              else
                strcpy(&a1[92 * dword_1D658 + 14], "static");
            }
            a1[92 * dword_1D658 + 32] = v10[28 * i + 26];
            sub_11674(*(_DWORD *)&v10[28 * i + 12], &a1[92 * dword_1D658 + 28]);
            ++dword_1D658;
          }
          if ( v15 >= v17 )
            goto LABEL_10;
          v19 = v17 - v15;
          if ( v17 - v15 <= 512 )
            v18 = v19;
          else
            v18 = 512;
        }
        fprintf((FILE *)stderr, "%s() %d read error\n", "Ssc_fdbGetAddrTable", 1260);
        return -1;
      }
    }
    else
    {
      return -1;
    }
  }
  else
  {
    fprintf((FILE *)stderr, "%s() %d Invalid argument\n", "Ssc_fdbGetAddrTable", 1228);
    return -1;
  }
}
// 1B2C8: using guessed type int stderr;
// 1D658: using guessed type int dword_1D658;

//----- (0000DF1C) --------------------------------------------------------
int __fastcall sub_DF1C(const void *a1, char a2, int a3)
{
  int result; // r0
  int v7; // [sp+18h] [bp-214h] BYREF
  _BYTE s[516]; // [sp+1Ch] [bp-210h] BYREF
  void *dest; // [sp+220h] [bp-Ch]
  int fd; // [sp+224h] [bp-8h]

  sub_112E4(5, "%s() %d lpbmp = %lx\n", "Ssc_fdbAddUcastEntry", 1338, a3);
  result = sub_B298();
  fd = result;
  if ( result >= 0 )
  {
    memset(s, 0, sizeof(s));
    v7 = 0;
    s[0] = 3;
    s[2] = 16;
    s[3] = 0;
    dest = &s[4];
    memcpy(&s[4], a1, 6u);
    sub_1158C(a3, &v7);
    *((_DWORD *)dest + 2) = v7;
    *((_BYTE *)dest + 13) = a2;
    result = ioctl(fd, 0x42044705u, s);
    if ( result < 0 )
      return sub_112E4(3, "ioctl ETHSW_FDB_SET error\n");
  }
  return result;
}

//----- (0000E04C) --------------------------------------------------------
int __fastcall sub_E04C(const void *a1, int a2, int a3)
{
  int result; // r0
  int v7; // [sp+18h] [bp-214h] BYREF
  _BYTE s[516]; // [sp+1Ch] [bp-210h] BYREF
  _BYTE *v9; // [sp+220h] [bp-Ch]
  int fd; // [sp+224h] [bp-8h]

  sub_112E4(5, "%s() %d lpbmp = %lx\n", "Ssc_setMgmtFrame", 1386, a3);
  result = sub_B298();
  fd = result;
  if ( result >= 0 )
  {
    memset(s, 0, sizeof(s));
    v7 = 0;
    s[0] = 2;
    s[2] = 20;
    s[3] = 0;
    v9 = &s[4];
    memcpy(&s[8], a1, 6u);
    sub_1158C(a3, &v7);
    *((_DWORD *)v9 + 3) = v7;
    *(_DWORD *)v9 = a2;
    if ( a2 )
    {
      v9[16] = a2;
      v9[17] = 7;
    }
    result = ioctl(fd, 0x42044705u, s);
    if ( result < 0 )
      return sub_112E4(3, "ioctl ETHSW_FDB_SET error\n");
  }
  return result;
}

//----- (0000E1A4) --------------------------------------------------------
int sub_E1A4()
{
  sub_112E4(7, "%s() %d\n", "Ssc_enable_manage_port", 1429);
  return sub_E04C(off_1B250, 1, 0x4000);
}
// 1B250: using guessed type _UNKNOWN *off_1B250;

//----- (0000E1FC) --------------------------------------------------------
int sub_E1FC()
{
  sub_112E4(7, "%s() %d\n", "Ssc_disable_manage_port", 1447);
  return sub_E04C(off_1B250, 0, 0);
}
// 1B250: using guessed type _UNKNOWN *off_1B250;

//----- (0000E254) --------------------------------------------------------
int sub_E254()
{
  return sub_F984(off_1B250, 0);
}
// 1B250: using guessed type _UNKNOWN *off_1B250;

//----- (0000E278) --------------------------------------------------------
int __fastcall sub_E278(int a1, const void *a2, int a3)
{
  sub_112E4(5, "%s() %d lpbmp = 0x%lx\n", "Ssc_enable_manage_multiport", 1464, a3);
  return sub_E04C(a2, 1, a3);
}

//----- (0000E2D0) --------------------------------------------------------
int __fastcall sub_E2D0(int a1, const void *a2, int a3)
{
  sub_112E4(5, "%s() %d lpbmp = 0x%lx\n", "Ssc_disable_manage_multiport", 1473, a3);
  return sub_E04C(a2, 1, 0x4000);
}

//----- (0000E33C) --------------------------------------------------------
int __fastcall sub_E33C(int a1, const void *a2)
{
  sub_112E4(7, "%s() %d\n", "Ssc_delete_manage_multiport", 1484);
  return sub_E04C(a2, 0, 0);
}

//----- (0000E394) --------------------------------------------------------
int __fastcall sub_E394(int a1)
{
  _BYTE s[516]; // [sp+14h] [bp-210h] BYREF
  _BYTE *v4; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  sub_112E4(7, "%s() %d >>>>>>> port %d\n", "Ssc_cpuGetRate", 1500, a1);
  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 6;
  s[2] = 8;
  s[3] = 0;
  v4 = &s[4];
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_112E4(3, "%s() ioctl error\n", "Ssc_cpuGetRate");
  return 0;
}

//----- (0000E478) --------------------------------------------------------
int __fastcall sub_E478(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+14h] [bp-210h] BYREF
  int *v8; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  sub_112E4(7, "%s() %d >>>>>>> port %d %d\n", "Ssc_cpuSetRate", 1526, a1, a2);
  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 6;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_113D0(a1);
  *v8 = v3;
  v8[1] = a2;
  if ( ioctl(fd, 0x42044703u, s) < 0 )
    sub_112E4(3, "%s() ioctl error\n", "Ssc_cpuSetRate");
  return 0;
}

//----- (0000E588) --------------------------------------------------------
int __fastcall sub_E588(_DWORD *a1, int a2)
{
  int v3; // r0
  _DWORD s[129]; // [sp+8h] [bp-214h] BYREF
  int i; // [sp+20Ch] [bp-10h]
  _DWORD *v9; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  LOBYTE(s[0]) = 0;
  HIWORD(s[0]) = 16;
  v9 = &s[1];
  s[3] = a2;
  s[1] = -1;
  s[4] = 0;
  for ( i = 0; i <= 13; ++i )
  {
    if ( (*a1 & (1 << i)) != 0 )
    {
      v3 = sub_113D0(i);
      v9[1] = v3;
      if ( ioctl(fd, 0x4204470Du, s) < 0 )
        sub_112E4(3, "%s() ioctl error\n", "Ssc_mirrorport_reset");
    }
  }
  return 0;
}

//----- (0000E6C8) --------------------------------------------------------
int __fastcall sub_E6C8(_DWORD *a1, unsigned __int8 a2, int a3, int a4)
{
  int v5; // r0
  _DWORD s[129]; // [sp+10h] [bp-214h] BYREF
  int i; // [sp+214h] [bp-10h]
  int *v13; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  i = 0;
  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  LOBYTE(s[0]) = 0;
  HIWORD(s[0]) = 16;
  v13 = &s[1];
  s[3] = a3;
  if ( a4 )
    *v13 = sub_113D0(a2 - 1);
  else
    *v13 = -1;
  v13[3] = a4;
  for ( i = 0; i <= 13; ++i )
  {
    if ( (*a1 & (1 << i)) != 0 )
    {
      v5 = sub_113D0(i);
      v13[1] = v5;
      if ( ioctl(fd, 0x4204470Du, s) < 0 )
        sub_112E4(3, "%s() ioctl error\n", "Ssc_mirrorport_enable_set");
    }
  }
  return 0;
}

//----- (0000E848) --------------------------------------------------------
int __fastcall sub_E848(_DWORD *a1, int a2, int a3)
{
  int v4; // r0
  _DWORD s[129]; // [sp+14h] [bp-218h] BYREF
  int i; // [sp+218h] [bp-14h]
  int v11; // [sp+21Ch] [bp-10h]
  _DWORD *v12; // [sp+220h] [bp-Ch]
  int fd; // [sp+224h] [bp-8h]

  v11 = 0;
  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  LOBYTE(s[0]) = 1;
  HIWORD(s[0]) = 16;
  v12 = &s[1];
  s[3] = a2;
  s[1] = -1;
  s[4] = a3;
  for ( i = 0; i <= 13; ++i )
  {
    if ( (*a1 & (1 << i)) != 0 )
    {
      v4 = sub_113D0(i);
      v12[1] = v4;
      if ( ioctl(fd, 0x4204470Du, s) < 0 )
        sub_112E4(3, "%s() ioctl error\n", "Ssc_targetport_reset");
    }
  }
  return 0;
}

//----- (0000E994) --------------------------------------------------------
int __fastcall sub_E994(_DWORD *a1, int a2, int a3)
{
  int v4; // r0
  _DWORD s[134]; // [sp+10h] [bp-22Ch] BYREF
  int i; // [sp+228h] [bp-14h]
  _DWORD *v11; // [sp+230h] [bp-Ch]
  int fd; // [sp+234h] [bp-8h]

  s[129] = 0;
  s[130] = 0;
  s[132] = 0;
  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, 0x204u);
  LOBYTE(s[0]) = 1;
  HIWORD(s[0]) = 16;
  v11 = &s[1];
  s[3] = a2;
  s[1] = -1;
  s[4] = a3;
  for ( i = 0; i <= 13; ++i )
  {
    if ( (*a1 & (1 << i)) != 0 )
    {
      v4 = sub_113D0(i);
      v11[1] = v4;
      if ( ioctl(fd, 0x4204470Du, s) < 0 )
        sub_112E4(3, "%s() ioctl error\n", "Ssc_targetport_enable_set");
    }
  }
  return 0;
}

//----- (0000EAF0) --------------------------------------------------------
void sub_EAF0()
{
  ;
}

//----- (0000EB04) --------------------------------------------------------
int __fastcall sub_EB04(int a1)
{
  _DWORD s[130]; // [sp+Ch] [bp-210h] BYREF
  int fd; // [sp+214h] [bp-8h]

  puts("Ssc_setQosSchedulingMode");
  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, 0x204u);
  LOBYTE(s[0]) = 0;
  HIWORD(s[0]) = 4;
  s[129] = &s[1];
  s[1] = a1;
  if ( ioctl(fd, 0x42044711u, s) < 0 )
    sub_112E4(3, "ioctl ETHSW_TYPE_QOS_SCHEDULING_MODE error\n");
  return 0;
}

//----- (0000EBD0) --------------------------------------------------------
int __fastcall sub_EBD0(int result)
{
  int v1; // [sp+4h] [bp-10h]
  int i; // [sp+Ch] [bp-8h]

  v1 = result;
  for ( i = 0; i <= 9; ++i )
  {
    if ( ((1 << i) & v1) != 0 )
      result = sub_ECC8(i, 1);
    else
      result = sub_ECC8(i, 0);
  }
  return result;
}

//----- (0000EC4C) --------------------------------------------------------
int __fastcall sub_EC4C(int result)
{
  int v1; // [sp+4h] [bp-10h]
  int i; // [sp+Ch] [bp-8h]

  v1 = result;
  for ( i = 0; i <= 9; ++i )
  {
    if ( ((1 << i) & v1) != 0 )
      result = sub_EDA8(i, 1);
    else
      result = sub_EDA8(i, 0);
  }
  return result;
}

//----- (0000ECC8) --------------------------------------------------------
int __fastcall sub_ECC8(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 1;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_113D0(a1);
  *v8 = v3;
  v8[1] = a2;
  if ( ioctl(fd, 0x42044711u, s) < 0 )
    sub_112E4(3, "%s() ioctl error\n", "Ssc_port_tos_set");
  return 0;
}

//----- (0000EDA8) --------------------------------------------------------
int __fastcall sub_EDA8(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 2;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_113D0(a1);
  *v8 = v3;
  v8[1] = a2;
  if ( ioctl(fd, 0x42044711u, s) < 0 )
    sub_112E4(3, "%s() ioctl error\n", "Ssc_port_cos_set");
  return 0;
}

//----- (0000EE88) --------------------------------------------------------
int __fastcall sub_EE88(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+14h] [bp-210h] BYREF
  int *v8; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  sub_112E4(7, "%s() %d >>>>>>> port %d %d\n", "Ssc_port_priority_set", 1861, a1, a2);
  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 3;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_113D0(a1);
  *v8 = v3;
  v8[1] = a2;
  if ( ioctl(fd, 0x42044711u, s) < 0 )
    sub_112E4(3, "%s() ioctl error\n", "Ssc_port_priority_set");
  return 0;
}

//----- (0000EF94) --------------------------------------------------------
int __fastcall sub_EF94(int a1)
{
  _BYTE s[516]; // [sp+8h] [bp-214h] BYREF
  int *v5; // [sp+20Ch] [bp-10h]
  int fd; // [sp+210h] [bp-Ch]
  int i; // [sp+214h] [bp-8h]

  i = 0;
  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 4;
  s[2] = 8;
  s[3] = 0;
  v5 = (int *)&s[4];
  for ( i = 0; i <= 7; ++i )
  {
    *v5 = i;
    v5[1] = *(_DWORD *)(a1 + 4 * i);
    if ( ioctl(fd, 0x42044711u, s) < 0 )
      sub_112E4(3, "ioctl ETHSW_TYPE_QOS_SCHEDULING_MODE error\n");
  }
  return 0;
}

//----- (0000F09C) --------------------------------------------------------
int __fastcall sub_F09C(int a1, int a2, const void *a3)
{
  _DWORD s[130]; // [sp+10h] [bp-21Ch] BYREF
  int fd; // [sp+218h] [bp-14h]
  int v10; // [sp+21Ch] [bp-10h]

  v10 = 0;
  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, 0x204u);
  LOBYTE(s[0]) = 5;
  HIWORD(s[0]) = 264;
  s[129] = &s[1];
  s[1] = a1;
  s[2] = a2;
  memcpy(&s[3], a3, 0x100u);
  if ( ioctl(fd, 0x42044711u, s) < 0 )
    sub_112E4(3, "ioctl ETHSW_TYPE_QOS_SCHEDULING_MODE error\n");
  return 0;
}

//----- (0000F1B4) --------------------------------------------------------
void sub_F1B4()
{
  ;
}

//----- (0000F1D0) --------------------------------------------------------
int __fastcall sub_F1D0(int a1, _DWORD *a2, _DWORD *a3)
{
  _DWORD s[129]; // [sp+1Ch] [bp-210h] BYREF
  _DWORD *v9; // [sp+220h] [bp-Ch]
  int fd; // [sp+224h] [bp-8h]

  sub_112E4(7, "%s() %d >>>>>>> vid %d\n", "Ssc_getVlanPortmap", 2011, a1);
  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  LOBYTE(s[0]) = 0;
  HIWORD(s[0]) = 12;
  v9 = &s[1];
  s[1] = a1;
  if ( ioctl(fd, 0x82044706, s) >= 0 )
  {
    sub_11674(v9[1], a2);
    sub_11674(v9[2], a3);
    printf("vid=%d, tagged=%x, untagged=%x\r\n", a1, *a2, *a3);
    return 0;
  }
  else
  {
    sub_112E4(3, "%s() ioctl error\n", "Ssc_getVlanPortmap");
    return -1;
  }
}

//----- (0000F31C) --------------------------------------------------------
int __fastcall sub_F31C(int a1, int a2)
{
  int v6; // [sp+14h] [bp-218h] BYREF
  int v7; // [sp+18h] [bp-214h] BYREF
  _DWORD s[129]; // [sp+1Ch] [bp-210h] BYREF
  _DWORD *v9; // [sp+220h] [bp-Ch]
  int fd; // [sp+224h] [bp-8h]

  fd = 0;
  sub_112E4(7, "%s() %d >>>>>>> vid %d enable = %d\n", "Ssc_vlanEnableCpuPort", 2043, a1, a2);
  if ( a1 > 0 && a1 <= 4094 )
  {
    fd = sub_B298();
    if ( fd >= 0 )
    {
      v7 = 0;
      v6 = 0;
      memset(s, 0, sizeof(s));
      sub_F1D0(a1, &v7, &v6);
      LOBYTE(s[0]) = 1;
      HIWORD(s[0]) = 12;
      v9 = &s[1];
      s[1] = a1;
      if ( a2 )
        v7 |= 0x4000u;
      else
        v7 &= ~0x4000u;
      sub_1158C(v7, v9 + 1);
      sub_1158C(v6, v9 + 2);
      if ( ioctl(fd, 0x82044707, s) >= 0 )
      {
        return 0;
      }
      else
      {
        sub_112E4(3, "%s() ioctl error\n", "Ssc_vlanEnableCpuPort");
        return -1;
      }
    }
    else
    {
      return -1;
    }
  }
  else
  {
    printf("%s() %d Invalid vid = %d\n", "Ssc_vlanEnableCpuPort", 2046, a1);
    return -1;
  }
}

//----- (0000F4E8) --------------------------------------------------------
int sub_F4E8()
{
  _BYTE s[516]; // [sp+4h] [bp-210h] BYREF
  _BYTE *v3; // [sp+208h] [bp-Ch]
  int fd; // [sp+20Ch] [bp-8h]

  sub_112E4(7, "%s() %d \n", "Ssc_vlanGetTable", 2089);
  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 2;
  s[2] = 12;
  s[3] = 0;
  v3 = &s[4];
  if ( ioctl(fd, 0x82044706, s) >= 0 )
  {
    printf("%s() %d \n", "Ssc_vlanGetTable", 2106);
    return 0;
  }
  else
  {
    sub_112E4(3, "%s() ioctl error\n", "Ssc_vlanGetTable");
    return -1;
  }
}

//----- (0000F5E0) --------------------------------------------------------
int sub_F5E0()
{
  int v1; // r0
  _BYTE s[516]; // [sp+8h] [bp-214h] BYREF
  int i; // [sp+20Ch] [bp-10h]
  int *v5; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  for ( i = 0; i <= 9; ++i )
  {
    sub_112E4(7, "%s() %d >>>>>>> port %d\n", "Ssc_initIgmpsnooping", 2133, i);
    memset(s, 0, sizeof(s));
    s[0] = 5;
    s[2] = 8;
    s[3] = 0;
    v5 = (int *)&s[4];
    v1 = sub_113D0(i);
    *v5 = v1;
    v5[1] = 1;
    if ( ioctl(fd, 0x42044703u, s) < 0 )
    {
      sub_112E4(3, "%s() ioctl error\n", "Ssc_initIgmpsnooping");
      return -1;
    }
  }
  return 0;
}

//----- (0000F70C) --------------------------------------------------------
int sub_F70C()
{
  int v1; // r0
  _BYTE s[516]; // [sp+8h] [bp-214h] BYREF
  int i; // [sp+20Ch] [bp-10h]
  int *v5; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  for ( i = 0; i <= 9; ++i )
  {
    sub_112E4(7, "%s() %d >>>>>>> port %d %d\n", "Ssc_destroyIgmpsnooping", 2169, i, 0);
    memset(s, 0, sizeof(s));
    s[0] = 5;
    s[2] = 8;
    s[3] = 0;
    v5 = (int *)&s[4];
    v1 = sub_113D0(i);
    *v5 = v1;
    v5[1] = 0;
    if ( ioctl(fd, 0x42044703u, s) < 0 )
    {
      sub_112E4(3, "%s() ioctl error\n", "Ssc_destroyIgmpsnooping");
      return -1;
    }
  }
  return 0;
}

//----- (0000F840) --------------------------------------------------------
void sub_F840()
{
  ;
}

//----- (0000F854) --------------------------------------------------------
int __fastcall sub_F854(const void *a1, int a2, int a3)
{
  _DWORD s[129]; // [sp+10h] [bp-214h] BYREF
  int v8; // [sp+214h] [bp-10h]
  _DWORD *v9; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  v8 = 0;
  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  LOBYTE(s[0]) = 2;
  HIWORD(s[0]) = 20;
  v9 = &s[1];
  memcpy(&s[2], a1, 6u);
  sub_1158C(a3, &s[4]);
  if ( ioctl(fd, 0x42044705u, s) >= 0 )
  {
    if ( v8 )
      sub_112E4(3, "%s: bcm_mcast_addr_add fail err=%d\n", "Ssc_mcastAddrAdd", v8);
    return v8;
  }
  else
  {
    sub_112E4(3, "ioctl ETHSW_FDB_SET error\n");
    return -1;
  }
}

//----- (0000F984) --------------------------------------------------------
int __fastcall sub_F984(const void *a1, __int16 a2)
{
  _BYTE s[520]; // [sp+8h] [bp-214h] BYREF
  int fd; // [sp+210h] [bp-Ch]
  _BYTE *v8; // [sp+214h] [bp-8h]

  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, 0x204u);
  if ( (unsigned __int8)a2 | (__int16)(HIBYTE(a2) << 8) )
    s[0] = 2;
  else
    s[0] = 5;
  s[2] = 20;
  s[3] = 0;
  v8 = &s[4];
  memcpy(&s[8], a1, 6u);
  if ( ioctl(fd, 0x42044705u, s) >= 0 )
    return 0;
  sub_112E4(3, "ioctl ETHSW_FDB_SET error\n");
  return -1;
}

//----- (0000FAC4) --------------------------------------------------------
int __fastcall sub_FAC4(int a1)
{
  _DWORD s[129]; // [sp+Ch] [bp-210h] BYREF
  int fd; // [sp+210h] [bp-Ch]
  _DWORD *v6; // [sp+214h] [bp-8h]

  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  LOBYTE(s[0]) = 1;
  HIWORD(s[0]) = 4;
  v6 = &s[1];
  s[1] = a1;
  if ( ioctl(fd, 0x4204470Fu, s) < 0 )
    sub_112E4(3, "%s() ioctl ETHSW_PORT_TRUNK_SET error\n", "Ssc_trunkSetHashMode");
  return 0;
}

//----- (0000FB90) --------------------------------------------------------
int sub_FB90()
{
  _BYTE s[516]; // [sp+4h] [bp-210h] BYREF
  int fd; // [sp+208h] [bp-Ch]
  _BYTE *v4; // [sp+20Ch] [bp-8h]

  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 0;
  s[2] = 8;
  s[3] = 0;
  v4 = &s[4];
  if ( ioctl(fd, 0x8204470E, s) < 0 )
    sub_112E4(3, "%s() ioctl ETHSW_PORT_TRUNK_GET error\n", "Ssc_trunkGetInfo");
  return 0;
}

//----- (0000FC4C) --------------------------------------------------------
int __fastcall sub_FC4C(int a1, int a2)
{
  int v6; // [sp+8h] [bp-214h] BYREF
  _DWORD s[129]; // [sp+Ch] [bp-210h] BYREF
  int fd; // [sp+210h] [bp-Ch]
  _DWORD *v9; // [sp+214h] [bp-8h]

  printf("%s() %d %x\n", "Ssc_trunkSetMember", a1, a2);
  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  LOBYTE(s[0]) = 2;
  HIWORD(s[0]) = 8;
  v9 = &s[1];
  s[1] = a1;
  sub_1158C(a2, &v6);
  v9[1] = v6;
  if ( ioctl(fd, 0x4204470Fu, s) < 0 )
    sub_112E4(3, "%s() ioctl ETHSW_PORT_TRUNK_SET error\n", "Ssc_trunkSetMember");
  return 0;
}

//----- (0000FD54) --------------------------------------------------------
int __fastcall sub_FD54(int a1, int a2)
{
  int v6; // [sp+8h] [bp-214h] BYREF
  _DWORD s[129]; // [sp+Ch] [bp-210h] BYREF
  int fd; // [sp+210h] [bp-Ch]
  _DWORD *v9; // [sp+214h] [bp-8h]

  printf("%s() %d %x\n", "Ssc_trunkClearMember", a1, a2);
  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  LOBYTE(s[0]) = 3;
  HIWORD(s[0]) = 8;
  v9 = &s[1];
  s[1] = a1;
  sub_1158C(a2, &v6);
  v9[1] = v6;
  if ( ioctl(fd, 0x4204470Fu, s) < 0 )
    sub_112E4(3, "%s() ioctl ETHSW_PORT_TRUNK_SET error\n", "Ssc_trunkClearMember");
  return 0;
}

//----- (0000FE5C) --------------------------------------------------------
int __fastcall sub_FE5C(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 0;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_113D0(a1);
  *v8 = v3;
  v8[1] = a2;
  if ( ioctl(fd, 0x42044713u, s) < 0 )
    sub_112E4(3, "%s() ioctl error\n", "Ssc_setIngressRateLimitMode");
  return 0;
}

//----- (0000FF3C) --------------------------------------------------------
int __fastcall sub_FF3C(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 1;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_113D0(a1);
  *v8 = v3;
  v8[1] = a2;
  if ( ioctl(fd, 0x42044713u, s) < 0 )
    sub_112E4(3, "%s() ioctl error\n", "Ssc_setIngressRateLimit");
  return 0;
}

//----- (0001001C) --------------------------------------------------------
int __fastcall sub_1001C(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 2;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_113D0(a1);
  *v8 = v3;
  v8[1] = a2;
  if ( ioctl(fd, 0x42044713u, s) < 0 )
    sub_112E4(3, "%s() ioctl error\n", "Ssc_setEgressRateLimit");
  return 0;
}

//----- (000100FC) --------------------------------------------------------
int __fastcall sub_100FC(int a1)
{
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  _BYTE *v5; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 14;
  s[2] = 8;
  s[3] = 0;
  v5 = &s[4];
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_112E4(3, "%s() ioctl error\n", "Ssc_cpu_qinq_get");
  *(_DWORD *)a1 = *((_DWORD *)v5 + 1);
  return *(_DWORD *)a1;
}

//----- (000101D0) --------------------------------------------------------
int __fastcall sub_101D0(int a1)
{
  _DWORD s[131]; // [sp+8h] [bp-214h] BYREF
  int fd; // [sp+214h] [bp-8h]

  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, 0x204u);
  LOBYTE(s[0]) = 14;
  HIWORD(s[0]) = 8;
  s[130] = &s[1];
  s[2] = a1;
  if ( ioctl(fd, 0x42044703u, s) < 0 )
    sub_112E4(3, "%s() ioctl error\n", "Ssc_cpu_qinq_set");
  return 0;
}

//----- (0001029C) --------------------------------------------------------
int __fastcall sub_1029C(int a1)
{
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  _BYTE *v5; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 15;
  s[2] = 8;
  s[3] = 0;
  v5 = &s[4];
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_112E4(3, "%s() ioctl error\n", "Ssc_cpu_egress_get");
  *(_DWORD *)a1 = *((_DWORD *)v5 + 1);
  return *(_DWORD *)a1;
}

//----- (00010370) --------------------------------------------------------
int __fastcall sub_10370(int a1)
{
  _DWORD s[131]; // [sp+8h] [bp-214h] BYREF
  int fd; // [sp+214h] [bp-8h]

  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, 0x204u);
  LOBYTE(s[0]) = 15;
  HIWORD(s[0]) = 8;
  s[130] = &s[1];
  s[2] = a1;
  if ( ioctl(fd, 0x42044703u, s) < 0 )
    sub_112E4(3, "%s() ioctl error\n", "Ssc_cpu_egress_set");
  return 0;
}

//----- (0001043C) --------------------------------------------------------
int __fastcall sub_1043C(int a1)
{
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  _BYTE *v5; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_B298();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 16;
  s[2] = 8;
  s[3] = 0;
  v5 = &s[4];
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_112E4(3, "%s() ioctl error\n", "Ssc_cpu_802dot1q_mode_get");
  *(_DWORD *)a1 = *((_DWORD *)v5 + 1);
  return *(_DWORD *)a1;
}

//----- (00010510) --------------------------------------------------------
int __fastcall sub_10510(unsigned __int8 *a1, int *a2, _DWORD *a3)
{
  sub_112E4(7, "dsa[0-3]=0x%x 0x%x 0x%x 0x%x\n", *a1, a1[1], a1[2], a1[3]);
  *a2 = a1[1] >> 3;
  *a3 = ((a1[2] & 0xF) << 8) + a1[3];
  sub_112E4(7, "Packet from port %d, vid %d\n", *a2, *a3);
  return 0;
}

//----- (00010600) --------------------------------------------------------
_BYTE *__fastcall sub_10600(_BYTE *result, char a2, __int16 a3)
{
  *result = 64;
  if ( a3 )
    *result |= 0x20u;
  result[1] = 8 * a2;
  result[2] = ~((unsigned int)~((unsigned __int16)(((unsigned __int8)a3 | (HIBYTE(a3) << 8)) & 0xF00) >> 8 << 27) >> 27);
  result[3] = a3;
  return result;
}

//----- (000106D4) --------------------------------------------------------
ssize_t __fastcall sub_106D4(int a1, int a2, int a3, int a4, int a5, __int16 a6)
{
  _BYTE v10[4]; // [sp+48h] [bp-2Ch] BYREF
  int v11; // [sp+4Ch] [bp-28h]
  size_t n; // [sp+50h] [bp-24h]
  int v13; // [sp+54h] [bp-20h]

  v11 = 0;
  memset(&byte_1DC3C, 0, 0x5EAu);
  v13 = sub_113D0(a3);
  sub_10600(v10, v13, (unsigned __int8)a6 | (HIBYTE(a6) << 8));
  memcpy(&byte_1DC3C, (const void *)a4, 0xCu);
  memcpy(&unk_1DC48, v10, 4u);
  memcpy(&unk_1DC4C, (const void *)(a4 + 12), a5 - 12);
  n = a5 + 4;
  sub_112E4(
    7,
    "%s() %d DA=%x:%x:%x:%x:%x:%x SA=%x:%x:%x:%x:%x:%x frame_len = %d\n",
    "frame_send",
    98,
    (unsigned __int8)byte_1DC3C,
    (unsigned __int8)byte_1DC3D,
    (unsigned __int8)byte_1DC3E,
    (unsigned __int8)byte_1DC3F,
    (unsigned __int8)byte_1DC40,
    (unsigned __int8)byte_1DC41,
    (unsigned __int8)byte_1DC42,
    (unsigned __int8)byte_1DC43,
    (unsigned __int8)byte_1DC44,
    (unsigned __int8)byte_1DC45,
    (unsigned __int8)byte_1DC46,
    (unsigned __int8)byte_1DC47,
    a5 + 4);
  return write(a1, &byte_1DC3C, n);
}
// 1DC3C: using guessed type char byte_1DC3C;
// 1DC3D: using guessed type char byte_1DC3D;
// 1DC3E: using guessed type char byte_1DC3E;
// 1DC3F: using guessed type char byte_1DC3F;
// 1DC40: using guessed type char byte_1DC40;
// 1DC41: using guessed type char byte_1DC41;
// 1DC42: using guessed type char byte_1DC42;
// 1DC43: using guessed type char byte_1DC43;
// 1DC44: using guessed type char byte_1DC44;
// 1DC45: using guessed type char byte_1DC45;
// 1DC46: using guessed type char byte_1DC46;
// 1DC47: using guessed type char byte_1DC47;

//----- (000108B4) --------------------------------------------------------
ssize_t __fastcall sub_108B4(int a1, int a2, int a3, int a4, int a5, int a6, __int16 a7)
{
  int v12; // [sp+18h] [bp-14h] BYREF
  int v13; // [sp+1Ch] [bp-10h] BYREF
  ssize_t v14; // [sp+20h] [bp-Ch]
  int i; // [sp+24h] [bp-8h]

  v14 = 0;
  sub_112E4(7, "%s() %d\n", "Ssc_sendPacket", 158);
  v13 = 0;
  v12 = 0;
  sub_1158C(a5, &v13);
  sub_1158C(a6, &v12);
  for ( i = 0; i <= 9; ++i )
  {
    if ( ((1 << i) & a6) != 0 )
      v14 = sub_106D4(a1, a2, i, a3, a4, 0);
    if ( ((1 << i) & a5) != 0 )
      v14 = sub_106D4(a1, a2, i, a3, a4, (unsigned __int8)a7 | (HIBYTE(a7) << 8));
  }
  sub_112E4(6, "%s() len = %d, ret = %d\n", "Ssc_sendPacket", a4, v14);
  return v14;
}

//----- (00010A14) --------------------------------------------------------
int __fastcall sub_10A14(int a1, int a2, int a3, const void *a4, size_t n, int a6)
{
  ssize_t v11; // [sp+24h] [bp-10h]
  signed int na; // [sp+38h] [bp+4h]

  sub_112E4(7, "%s() sendBPDU to port %d\n", "Ssc_sendBpduPacket", a3);
  memcpy(byte_1D660, off_1B250, 6u);
  if ( a6 )
    bcopy(&unk_1B25C, &byte_1D660[6], 6u);
  else
    bcopy(&byte_1B254, &byte_1D660[6], 6u);
  word_1D66C = htons(n + 3);
  byte_1D66E = 66;
  byte_1D66F = 66;
  byte_1D670 = 3;
  bcopy(a4, &unk_1D671, n);
  for ( na = n + 17; na <= 59; ++na )
    byte_1D660[na] = 0;
  v11 = sub_106D4(a1, a2, a3, (int)byte_1D660, na, 0);
  return sub_112E4(6, "%s() len = %d, ret = %d\n", "Ssc_sendBpduPacket", na, v11);
}
// 1B250: using guessed type _UNKNOWN *off_1B250;
// 1B254: using guessed type char byte_1B254;
// 1D660: using guessed type _BYTE byte_1D660[12];
// 1D66C: using guessed type __int16 word_1D66C;
// 1D66E: using guessed type char byte_1D66E;
// 1D66F: using guessed type char byte_1D66F;
// 1D670: using guessed type char byte_1D670;

//----- (00010BB0) --------------------------------------------------------
int __fastcall sub_10BB0(int a1, int a2, int a3, int a4, void *src, size_t n, int a7)
{
  int result; // r0
  _BYTE dest[6]; // [sp+34h] [bp-68h] BYREF
  _WORD v13[4]; // [sp+3Ah] [bp-62h] BYREF
  char v14; // [sp+42h] [bp-5Ah]
  char v15; // [sp+43h] [bp-59h]
  char v16; // [sp+44h] [bp-58h]
  _BYTE v17[3]; // [sp+45h] [bp-57h] BYREF
  ssize_t v18; // [sp+8Ch] [bp-10h]
  signed int na; // [sp+A4h] [bp+8h]

  v18 = 0;
  sub_112E4(
    7,
    "%s() sendBPDU to port %d for ring %d, SA = %x:%x:%x:%x:%x:%x\n",
    "Ssc_sendTR2Packet",
    a4,
    a3,
    (unsigned __int8)byte_1B254,
    (unsigned __int8)byte_1B255,
    (unsigned __int8)byte_1B256,
    (unsigned __int8)byte_1B257,
    (unsigned __int8)byte_1B258,
    (unsigned __int8)byte_1B259);
  result = sub_B800(a4);
  if ( !result )
  {
    if ( a3 )
      memcpy(dest, (const void *)dword_1E30C, sizeof(dest));
    else
      memcpy(dest, (const void *)dword_1E308, sizeof(dest));
    if ( a7 )
      bcopy(&unk_1B25C, v13, 6u);
    else
      bcopy(&byte_1B254, v13, 6u);
    v13[3] = htons(n + 3);
    v14 = 66;
    v15 = 66;
    v16 = 3;
    bcopy(src, v17, n);
    for ( na = n + 17; na <= 59; ++na )
      dest[na] = 0;
    v18 = sub_106D4(a1, a2, a4, (int)dest, na, 0);
    return sub_112E4(6, "%s() len = %d, ret = %d\n", "Ssc_sendTR2Packet", na, v18);
  }
  return result;
}
// 1B254: using guessed type char byte_1B254;
// 1B255: using guessed type char byte_1B255;
// 1B256: using guessed type char byte_1B256;
// 1B257: using guessed type char byte_1B257;
// 1B258: using guessed type char byte_1B258;
// 1B259: using guessed type char byte_1B259;
// 1E308: using guessed type int dword_1E308;
// 1E30C: using guessed type int dword_1E30C;

//----- (00010E0C) --------------------------------------------------------
char *__fastcall sub_10E0C(const char *a1)
{
  sprintf(byte_1E228, "%s/%s", "/proc/moxa", a1);
  return byte_1E228;
}

//----- (00010E50) --------------------------------------------------------
int __fastcall sub_10E50(int a1, int a2, int a3)
{
  char *v3; // r0
  char s[128]; // [sp+1Ch] [bp-90h] BYREF
  int v8; // [sp+9Ch] [bp-10h]

  v8 = sub_113D0(a1);
  v3 = sub_10E0C("port_speed_set");
  sprintf(s, " echo %x,%x,%x > %s", v8, a2, a3, v3);
  printf("msg = %s\n", s);
  system(s);
  return 0;
}

//----- (00010EE8) --------------------------------------------------------
int __fastcall sub_10EE8(int a1)
{
  printf("%s() %d >>>>>> %d ms\n", "Ssys_ms2ticks", 28, a1);
  return a1;
}

//----- (00010F28) --------------------------------------------------------
int __fastcall sub_10F28(int a1)
{
  struct timespec remaining; // [sp+10h] [bp-14h] BYREF
  struct timespec requested_time; // [sp+18h] [bp-Ch] BYREF

  requested_time.tv_sec = 0;
  requested_time.tv_nsec = 1000000 * a1;
  return nanosleep(&requested_time, &remaining);
}

//----- (00010F84) --------------------------------------------------------
__time_t Ssys_current_secs()
{
  int *v0; // r0
  char *v1; // r0
  timespec tp; // [sp+0h] [bp-Ch] BYREF

  if ( clock_gettime(1, &tp) != -1 )
    return tp.tv_sec;
  v0 = _errno_location();
  v1 = strerror(*v0);
  sub_112E4(3, "%s() error = %s\n", "Ssys_current_secs", v1);
  return -1;
}

//----- (00010FF4) --------------------------------------------------------
int Ssys_current_msecs()
{
  int *v0; // r0
  char *v1; // r0
  int v3; // r4
  struct timespec tp; // [sp+0h] [bp-14h] BYREF

  if ( clock_gettime(1, &tp) == -1 )
  {
    v0 = _errno_location();
    v1 = strerror(*v0);
    sub_112E4(3, "%s() error = %s\n", "Ssys_current_msecs", v1);
    return -1;
  }
  else
  {
    v3 = 1000 * tp.tv_sec;
    return v3 + sub_1186C(tp.tv_nsec, 0xF4240u);
  }
}

//----- (000110A4) --------------------------------------------------------
int __fastcall sub_110A4(_DWORD *a1)
{
  int v1; // r4
  int result; // r0
  struct timespec tp; // [sp+8h] [bp-14h] BYREF

  clock_gettime(1, &tp);
  v1 = (1000 * tp.tv_sec) >> 31;
  *a1 = 1000 * tp.tv_sec;
  a1[1] = v1;
  result = sub_1186C(tp.tv_nsec, 0x3E8u);
  a1[2] = result;
  return result;
}

//----- (0001111C) --------------------------------------------------------
int __fastcall sub_1111C(_DWORD *a1, _DWORD *a2)
{
  return 1000 * (*a2 - *a1) + a2[2] - a1[2];
}

//----- (00011198) --------------------------------------------------------
char *sub_11198()
{
  return &byte_1B254;
}
// 1B254: using guessed type char byte_1B254;

//----- (000111CC) --------------------------------------------------------
int __fastcall sub_111CC(unsigned __int8 *a1, int a2)
{
  unsigned int v4; // r4

  v4 = 0;
  while ( a2 > 1 )
  {
    v4 += *a1 | (a1[1] << 8);
    a1 += 2;
    a2 -= 2;
  }
  if ( a2 == 1 )
    v4 += *a1;
  return (unsigned __int16)~(HIWORD(v4) + v4 + ((unsigned int)(HIWORD(v4) + (unsigned __int16)v4) >> 16));
}

//----- (0001128C) --------------------------------------------------------
int __fastcall Ssys_UI_port2MdlPort(int a1, _DWORD *a2, int *a3)
{
  if ( a1 > 9 )
    return 0;
  *a2 = 0;
  *a3 = a1;
  return 1;
}

//----- (000112E4) --------------------------------------------------------
int sub_112E4(int result, const char *a2, ...)
{
  va_list varg_r2; // [sp+20h] [bp+8h] BYREF

  va_start(varg_r2, a2);
  if ( result <= dword_1E310 )
    return vfprintf((FILE *)stderr, a2, varg_r2);
  return result;
}
// 1B2C8: using guessed type int stderr;
// 1E310: using guessed type int dword_1E310;

//----- (00011354) --------------------------------------------------------
int __fastcall sub_11354(int a1)
{
  dword_1E310 = a1;
  return printf("Debug message level set to %d\n", a1);
}
// 1E310: using guessed type int dword_1E310;

//----- (00011398) --------------------------------------------------------
void sub_11398()
{
  dword_1E2AC = (int)&unk_1B264;
  dword_1E2A8 = 1;
}
// 1E2A8: using guessed type int dword_1E2A8;
// 1E2AC: using guessed type int dword_1E2AC;

//----- (000113D0) --------------------------------------------------------
int __fastcall sub_113D0(int a1)
{
  int i; // [sp+Ch] [bp-10h]
  int v5; // [sp+10h] [bp-Ch]

  v5 = -1;
  if ( !dword_1E2A8 )
    sub_11398();
  for ( i = 0; i < dword_1B2BC; ++i )
  {
    if ( *(_DWORD *)(dword_1E2AC + 8 * i) == a1 )
    {
      v5 = *(_DWORD *)(dword_1E2AC + 8 * i + 4);
      break;
    }
  }
  if ( i == dword_1B2BC )
    return -1;
  else
    return v5;
}
// 1B2BC: using guessed type int dword_1B2BC;
// 1E2A8: using guessed type int dword_1E2A8;
// 1E2AC: using guessed type int dword_1E2AC;

//----- (0001149C) --------------------------------------------------------
int __fastcall sub_1149C(int a1)
{
  int i; // [sp+14h] [bp-10h]
  int v5; // [sp+18h] [bp-Ch]

  v5 = -1;
  if ( !dword_1E2A8 )
    sub_11398();
  for ( i = 0; i < dword_1B2BC; ++i )
  {
    if ( *(_DWORD *)(dword_1E2AC + 8 * i + 4) == a1 )
    {
      v5 = *(_DWORD *)(dword_1E2AC + 8 * i);
      break;
    }
  }
  if ( i == dword_1B2BC )
    return -1;
  sub_112E4(7, "%s(): port %d from port %d\n", "spm_getLogicalPortId", v5, a1);
  return v5;
}
// 1B2BC: using guessed type int dword_1B2BC;
// 1E2A8: using guessed type int dword_1E2A8;
// 1E2AC: using guessed type int dword_1E2AC;

//----- (0001158C) --------------------------------------------------------
int __fastcall sub_1158C(int a1, _DWORD *a2)
{
  int i; // [sp+8h] [bp-14h]
  int v6; // [sp+10h] [bp-Ch]

  if ( !dword_1E2A8 )
    sub_11398();
  v6 = 0;
  for ( i = 0; i < dword_1B2BC; ++i )
  {
    if ( ((1 << *(_DWORD *)(dword_1E2AC + 8 * i)) & a1) != 0 )
      v6 |= 1 << *(_DWORD *)(dword_1E2AC + 8 * i + 4);
  }
  *a2 = v6;
  return 0;
}
// 1B2BC: using guessed type int dword_1B2BC;
// 1E2A8: using guessed type int dword_1E2A8;
// 1E2AC: using guessed type int dword_1E2AC;

//----- (00011674) --------------------------------------------------------
int __fastcall sub_11674(int a1, _DWORD *a2)
{
  int i; // [sp+8h] [bp-14h]
  int v6; // [sp+10h] [bp-Ch]

  if ( !dword_1E2A8 )
    sub_11398();
  v6 = 0;
  for ( i = 0; i < dword_1B2BC; ++i )
  {
    if ( ((1 << *(_DWORD *)(dword_1E2AC + 8 * i + 4)) & a1) != 0 )
      v6 |= 1 << *(_DWORD *)(dword_1E2AC + 8 * i);
  }
  *a2 = v6;
  return 0;
}
// 1B2BC: using guessed type int dword_1B2BC;
// 1E2A8: using guessed type int dword_1E2A8;
// 1E2AC: using guessed type int dword_1E2AC;

//----- (0001175C) --------------------------------------------------------
unsigned int __fastcall sub_1175C(unsigned int result, unsigned int a2)
{
  unsigned int v2; // r3
  bool v3; // cf
  bool v4; // cf
  int v5; // r2
  bool v6; // zf
  int v7; // r2

  if ( a2 != 1 )
  {
    if ( a2 )
    {
      if ( result <= a2 )
      {
        return result == a2;
      }
      else if ( (a2 & (a2 - 1)) != 0 )
      {
        if ( (a2 & 0xE0000000) != 0 )
        {
          v2 = 1;
        }
        else
        {
          a2 *= 8;
          v2 = 8;
        }
        while ( 1 )
        {
          v3 = a2 >= 0x10000000;
          if ( a2 < 0x10000000 )
            v3 = a2 >= result;
          if ( v3 )
            break;
          a2 *= 16;
          v2 *= 16;
        }
        while ( 1 )
        {
          v4 = a2 >= 0x80000000;
          if ( a2 < 0x80000000 )
            v4 = a2 >= result;
          if ( v4 )
            break;
          a2 *= 2;
          v2 *= 2;
        }
        v5 = 0;
        while ( 1 )
        {
          if ( result >= a2 )
          {
            result -= a2;
            v5 |= v2;
          }
          if ( result >= a2 >> 1 )
          {
            result -= a2 >> 1;
            v5 |= v2 >> 1;
          }
          if ( result >= a2 >> 2 )
          {
            result -= a2 >> 2;
            v5 |= v2 >> 2;
          }
          if ( result >= a2 >> 3 )
          {
            result -= a2 >> 3;
            v5 |= v2 >> 3;
          }
          v6 = result == 0;
          if ( result )
          {
            v2 >>= 4;
            v6 = v2 == 0;
          }
          if ( v6 )
            break;
          a2 >>= 4;
        }
        return v5;
      }
      else
      {
        if ( a2 < 0x10000 )
        {
          v7 = 0;
        }
        else
        {
          a2 >>= 16;
          v7 = 16;
        }
        if ( a2 >= 0x100 )
        {
          a2 >>= 8;
          v7 += 8;
        }
        if ( a2 >= 0x10 )
        {
          a2 >>= 4;
          v7 += 4;
        }
        if ( a2 <= 4 )
          v7 += a2 >> 1;
        else
          LOBYTE(v7) = v7 + 3;
        result >>= v7;
      }
    }
    else
    {
      sub_119AC();
      return 0;
    }
  }
  return result;
}

//----- (00011854) --------------------------------------------------------
unsigned int __fastcall sub_11854(unsigned int a1, unsigned int a2)
{
  return sub_1175C(a1, a2);
}

//----- (0001186C) --------------------------------------------------------
int __fastcall sub_1186C(int result, unsigned int a2)
{
  int v2; // r12
  unsigned int v3; // r3
  unsigned int v4; // r2
  bool v5; // cf
  bool v6; // cf
  bool v7; // zf
  int v8; // r2

  v2 = result ^ a2;
  if ( a2 )
  {
    if ( (a2 & 0x80000000) != 0 )
      a2 = -a2;
    if ( a2 == 1 )
    {
      if ( (v2 ^ result) < 0 )
        return -result;
    }
    else
    {
      v3 = result;
      if ( result < 0 )
        v3 = -result;
      if ( v3 <= a2 )
      {
        if ( v3 < a2 )
          result = 0;
        if ( v3 == a2 )
          return (v2 >> 31) | 1;
      }
      else if ( (a2 & (a2 - 1)) != 0 )
      {
        if ( (a2 & 0xE0000000) != 0 )
        {
          v4 = 1;
        }
        else
        {
          a2 *= 8;
          v4 = 8;
        }
        while ( 1 )
        {
          v5 = a2 >= 0x10000000;
          if ( a2 < 0x10000000 )
            v5 = a2 >= v3;
          if ( v5 )
            break;
          a2 *= 16;
          v4 *= 16;
        }
        while ( 1 )
        {
          v6 = a2 >= 0x80000000;
          if ( a2 < 0x80000000 )
            v6 = a2 >= v3;
          if ( v6 )
            break;
          a2 *= 2;
          v4 *= 2;
        }
        result = 0;
        while ( 1 )
        {
          if ( v3 >= a2 )
          {
            v3 -= a2;
            result |= v4;
          }
          if ( v3 >= a2 >> 1 )
          {
            v3 -= a2 >> 1;
            result |= v4 >> 1;
          }
          if ( v3 >= a2 >> 2 )
          {
            v3 -= a2 >> 2;
            result |= v4 >> 2;
          }
          if ( v3 >= a2 >> 3 )
          {
            v3 -= a2 >> 3;
            result |= v4 >> 3;
          }
          v7 = v3 == 0;
          if ( v3 )
          {
            v4 >>= 4;
            v7 = v4 == 0;
          }
          if ( v7 )
            break;
          a2 >>= 4;
        }
        if ( v2 < 0 )
          return -result;
      }
      else
      {
        if ( a2 < 0x10000 )
        {
          v8 = 0;
        }
        else
        {
          a2 >>= 16;
          v8 = 16;
        }
        if ( a2 >= 0x100 )
        {
          a2 >>= 8;
          v8 += 8;
        }
        if ( a2 >= 0x10 )
        {
          a2 >>= 4;
          v8 += 4;
        }
        if ( a2 <= 4 )
          v8 += a2 >> 1;
        else
          LOBYTE(v8) = v8 + 3;
        result = v3 >> v8;
        if ( v2 < 0 )
          return -result;
      }
    }
  }
  else
  {
    sub_119AC();
    return 0;
  }
  return result;
}

//----- (00011994) --------------------------------------------------------
int __fastcall sub_11994(int a1, unsigned int a2)
{
  return sub_1186C(a1, a2);
}

//----- (000119AC) --------------------------------------------------------
int sub_119AC()
{
  return raise(8);
}

//----- (000119C0) --------------------------------------------------------
void init(void)
{
  init_proc();
}

//----- (00011A28) --------------------------------------------------------
int sub_11A28()
{
  int (*v0)(void); // r3
  _UNKNOWN **v1; // r4
  int result; // r0
  int (*v3)(void); // t1

  v0 = (int (*)(void))off_1B050;
  if ( off_1B050 != (_UNKNOWN *)-1 )
  {
    v1 = &off_1B050;
    do
    {
      result = v0();
      v3 = (int (*)(void))*--v1;
      v0 = v3;
    }
    while ( v3 != (int (*)(void))-1 );
  }
  return result;
}
// 1B050: using guessed type _UNKNOWN *off_1B050;

//----- (00011A5C) --------------------------------------------------------
void sub_11A5C()
{
  ;
}

//----- (00011A64) --------------------------------------------------------
int term_proc()
{
  return sub_90F0();
}

// nfuncs=231 queued=130 decompiled=130 lumina nreq=0 worse=0 better=0
// ALL OK, 130 function(s) have been successfully decompiled
