/* This file was generated by the Hex-Rays decompiler version 9.1.0.250226.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>

#include <stdarg.h>


//-------------------------------------------------------------------------
// Function declarations

int init_proc();
void sub_8B04();
// void abort(void);
// int *_errno_location(void);
// int __fastcall _deregister_frame_info(_DWORD); weak
// int sprintf(char *s, const char *format, ...);
// int open(const char *file, int oflag, ...);
// char *strerror(int errnum);
// int memcmp(const void *s1, const void *s2, size_t n);
// int _gmon_start__(void); weak
// int system(const char *command);
// ssize_t write(int fd, const void *buf, size_t n);
// int __fastcall _register_frame_info(_DWORD, _DWORD); weak
// void *memset(void *s, int c, size_t n);
// int _libc_start_main(int (*main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// uint16_t htons(uint16_t hostshort);
// int __fastcall net_OpenSocketToInterface_Recv(_DWORD, _DWORD); weak
// ssize_t read(int fd, void *buf, size_t nbytes);
// void perror(const char *s);
// int ioctl(int fd, unsigned int request, ...);
// int pthread_mutex_unlock(pthread_mutex_t *mutex);
// void bcopy(const void *src, void *dest, size_t n);
// int nanosleep(const struct timespec *requested_time, struct timespec *remaining);
// void *memcpy(void *dest, const void *src, size_t n);
// int printf(const char *format, ...);
// int raise(int sig);
// int clock_gettime(clockid_t clock_id, struct timespec *tp);
// int __fastcall sock_path(_DWORD, _DWORD, _DWORD); weak
// int close(int fd);
// int fprintf(FILE *stream, const char *format, ...);
// int pthread_mutex_lock(pthread_mutex_t *mutex);
// int __fastcall shm_sysGetEepromInfo(_DWORD); weak
// int puts(const char *s);
// int vfprintf(FILE *s, const char *format, __gnuc_va_list arg);
// int __fastcall net_RecvFromInterface1(_DWORD, _DWORD, _DWORD); weak
void __noreturn start(void (*a1)(void), int a2, int a3, int a4, ...);
int sub_8CE0();
int sub_8D04();
void sub_8D8C();
int *sub_8D94();
void sub_8DE8();
int __fastcall sub_8DF0(int a1, int a2);
int sub_8FEC();
bool sub_91DC();
int sub_92AC();
int sub_9340();
int __fastcall sub_9374(int a1, int a2, _DWORD *a3);
int __fastcall sub_9484(int a1, int a2, int a3);
int __fastcall sub_9588(int a1, int a2, _DWORD *a3);
int __fastcall sub_968C(int a1, int a2, int a3);
int __fastcall sub_9784(int a1);
int __fastcall sub_9814(int a1);
int __fastcall sub_98E0(int a1, _DWORD *a2);
int __fastcall sub_99D0(int a1, int a2);
int __fastcall sub_9AE0(int a1);
int __fastcall sub_9BB4(int a1);
int sub_9C74();
int sub_9D10();
int __fastcall sub_9DAC(int a1, int a2);
int __fastcall sub_9E98(int a1, int a2);
int __fastcall sub_9F84(int a1, int a2);
int __fastcall sub_A070(int a1, int a2);
int __fastcall sub_A15C(int a1, int a2);
int __fastcall sub_A240(int a1, const char *a2);
int __fastcall sub_A34C(int a1, int a2);
int __fastcall sub_A438(int a1, const char *a2);
int __fastcall sub_A548(int a1, int a2);
int __fastcall sub_A634(int a1, const char *a2);
int __fastcall sub_A744(int a1);
int __fastcall sub_A840(int a1, int a2, int a3);
int __fastcall sub_A9D4(int a1, int a2);
int __fastcall Ssc_getPortLinkState(_DWORD *a1);
int __fastcall sub_AC64(int a1);
void *__fastcall Ssc_getPortStatsCounter(void *a1, int a2);
int __fastcall sub_AE50(_DWORD *a1);
int __fastcall sub_AE9C(int a1);
int __fastcall sub_AEE4(int a1);
int __fastcall sub_AFE4(int a1);
int sub_B0A8();
int __fastcall sub_B178(const void *a1, _DWORD *a2);
int __fastcall sub_B2A4(const void *a1, void *a2);
int __fastcall sub_B49C(const void *a1, void *a2);
int __fastcall sub_B694(_DWORD *a1);
int __fastcall sub_B77C(char *a1, size_t a2, int a3);
int __fastcall sub_BF30(const void *a1, char a2, int a3);
int __fastcall sub_C060(const void *a1, int a2, int a3);
int sub_C1B8();
int sub_C210();
int sub_C268();
int __fastcall sub_C28C(int a1, const void *a2, int a3);
int __fastcall sub_C2E4(int a1, const void *a2, int a3);
int __fastcall sub_C350(int a1, const void *a2);
int __fastcall sub_C3A8(int a1);
int __fastcall sub_C48C(int a1, int a2);
int __fastcall sub_C59C(_DWORD *a1, int a2);
int __fastcall sub_C6DC(_DWORD *a1, unsigned __int8 a2, int a3, int a4);
int __fastcall sub_C85C(_DWORD *a1, int a2, int a3);
int __fastcall sub_C9A8(_DWORD *a1, int a2, int a3);
void sub_CB04();
int __fastcall sub_CB18(int a1);
int __fastcall sub_CBE4(int result);
int __fastcall sub_CC60(int result);
int __fastcall sub_CCDC(int a1, int a2);
int __fastcall sub_CDBC(int a1, int a2);
int __fastcall sub_CE9C(int a1, int a2);
int __fastcall sub_CFA8(int a1);
int __fastcall sub_D0B0(int a1, int a2, const void *a3);
void sub_D1C8();
int __fastcall sub_D1E4(int a1, _DWORD *a2, _DWORD *a3);
int __fastcall sub_D330(int a1, int a2);
int sub_D4FC();
int sub_D5F4();
int sub_D720();
void sub_D854();
int __fastcall sub_D868(const void *a1, int a2, int a3);
int __fastcall sub_D998(const void *a1, __int16 a2);
int __fastcall sub_DAD8(int a1);
int sub_DBA4();
int __fastcall sub_DC60(int a1, int a2);
int __fastcall sub_DD68(int a1, int a2);
int __fastcall sub_DE70(int a1, int a2);
int __fastcall sub_DF50(int a1, int a2);
int __fastcall sub_E030(int a1, int a2);
int __fastcall sub_E110(int a1);
int __fastcall sub_E1E4(int a1);
int __fastcall sub_E2B0(int a1);
int __fastcall sub_E384(int a1);
int __fastcall sub_E450(int a1);
int __fastcall sub_E524(unsigned __int8 *a1, int *a2, _DWORD *a3);
_BYTE *__fastcall sub_E614(_BYTE *result, char a2, __int16 a3);
ssize_t __fastcall sub_E6E8(int a1, int a2, int a3, int a4, int a5, __int16 a6);
ssize_t __fastcall sub_E8C8(int a1, int a2, int a3, int a4, int a5, int a6, __int16 a7);
int __fastcall sub_EA28(int a1, int a2, int a3, const void *a4, size_t n, int a6);
int __fastcall sub_EBC4(int a1, int a2, int a3, int a4, void *src, size_t n, int a7); // idb
char *__fastcall sub_EE20(const char *a1);
int __fastcall sub_EE64(int a1, int a2, int a3);
int __fastcall sub_EEFC(int a1);
int __fastcall sub_EF3C(int a1);
__time_t Ssys_current_secs();
int Ssys_current_msecs();
int __fastcall sub_F0B8(_DWORD *a1);
int __fastcall sub_F130(_DWORD *a1, _DWORD *a2);
char *sub_F1AC();
int __fastcall sub_F1E0(unsigned __int8 *a1, int a2);
int __fastcall Ssys_UI_port2MdlPort(int a1, _DWORD *a2, int *a3);
int sub_F2F8(int result, const char *a2, ...);
int __fastcall sub_F368(int a1);
void sub_F3AC();
int __fastcall sub_F3E4(int a1);
int __fastcall sub_F4B0(int a1);
int __fastcall sub_F5A0(int a1, _DWORD *a2);
int __fastcall sub_F688(int a1, _DWORD *a2);
unsigned int __fastcall sub_F770(unsigned int result, unsigned int a2);
unsigned int __fastcall sub_F868(unsigned int a1, unsigned int a2);
int __fastcall sub_F880(int result, unsigned int a2);
int __fastcall sub_F9A8(int a1, unsigned int a2);
int sub_F9C0();
int nullsub_1(); // weak
void init(void); // idb
int sub_FA3C();
void sub_FA70();
int term_proc();

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN main;
_UNKNOWN unk_10828; // weak
_UNKNOWN *off_19000 = (_UNKNOWN *)0xFFFFFFFF; // weak
int dword_19008[] = { -1 }; // weak
int dword_1900C = 0; // weak
int dword_19010 = 0; // weak
_UNKNOWN *off_191BC = &unk_191B4; // weak
char byte_191C0 = '\0'; // weak
char byte_191C1 = '\x90'; // weak
char byte_191C2 = '\xE8'; // weak
char byte_191C3 = '\x05'; // weak
char byte_191C4 = '\0'; // weak
char byte_191C5 = '\b'; // weak
_UNKNOWN unk_191C8; // weak
_UNKNOWN unk_191D0; // weak
int dword_19228 = 11; // weak
int stderr; // weak
char byte_19234; // weak
int dword_19238; // weak
_UNKNOWN unk_1923C; // weak
int dword_19254[21]; // weak
_UNKNOWN unk_192A8; // weak
int dword_19300; // weak
int dword_19304; // weak
int dword_1930C; // weak
pthread_mutex_t mutex; // idb
_UNKNOWN unk_19328; // weak
_UNKNOWN unk_1932C; // weak
int dword_19330; // weak
_BYTE byte_19338[12]; // weak
__int16 word_19344; // weak
char byte_19346; // weak
char byte_19347; // weak
char byte_19348; // weak
_UNKNOWN unk_19349; // weak
char byte_19914; // weak
char byte_19915; // weak
char byte_19916; // weak
char byte_19917; // weak
char byte_19918; // weak
char byte_19919; // weak
char byte_1991A; // weak
char byte_1991B; // weak
char byte_1991C; // weak
char byte_1991D; // weak
char byte_1991E; // weak
char byte_1991F; // weak
_UNKNOWN unk_19920; // weak
_UNKNOWN unk_19924; // weak
char byte_19F00[128]; // idb
int dword_19F80; // weak
int dword_19F84; // weak
int dword_19F88; // weak
int dword_19F8C; // weak
int dword_19F90; // weak
// extern _UNKNOWN __gmon_start__; weak


//----- (00008AF0) --------------------------------------------------------
int init_proc()
{
  sub_8CE0();
  sub_8D94();
  return sub_FA3C();
}

//----- (00008B04) --------------------------------------------------------
void sub_8B04()
{
  JUMPOUT(0);
}
// 8B10: control flows out of bounds to 0

//----- (00008CA4) --------------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __noreturn start(void (*a1)(void), int a2, int a3, int a4, ...)
{
  int v4; // [sp-4h] [bp-4h]
  va_list va; // [sp+0h] [bp+0h] BYREF

  va_start(va, a4);
  _libc_start_main((int (*)(int, char **, char **))main, v4, (char **)va, init, (void (*)(void))nullsub_1, a1, va);
  abort();
}
// 8CB0: positive sp value 4 has been found
// 8CCC: variable 'v4' is possibly undefined
// F9D0: using guessed type int nullsub_1();

//----- (00008CE0) --------------------------------------------------------
int sub_8CE0()
{
  int result; // r0

  if ( &__gmon_start__ )
    return _gmon_start__();
  return result;
}
// 8B6C: using guessed type int _gmon_start__(void);

//----- (00008D04) --------------------------------------------------------
int sub_8D04()
{
  int v0; // r3
  unsigned int i; // r6
  int result; // r0

  if ( !byte_19234 )
  {
    v0 = dword_19238;
    for ( i = &dword_1900C - dword_19008 - 1; dword_19238 < i; v0 = dword_19238 )
    {
      dword_19238 = v0 + 1;
      result = ((int (*)(void))dword_19008[v0 + 1])();
    }
    if ( _deregister_frame_info )
      result = _deregister_frame_info(&unk_10828);
    byte_19234 = 1;
  }
  return result;
}
// 8B30: using guessed type int __fastcall _deregister_frame_info(_DWORD);
// 19008: using guessed type int dword_19008[];
// 1900C: using guessed type int dword_1900C;
// 19234: using guessed type char byte_19234;
// 19238: using guessed type int dword_19238;

//----- (00008D8C) --------------------------------------------------------
void sub_8D8C()
{
  ;
}

//----- (00008D94) --------------------------------------------------------
int *sub_8D94()
{
  if ( _register_frame_info )
    _register_frame_info(&unk_10828, &unk_1923C);
  return &dword_19010;
}
// 8B90: using guessed type int __fastcall _register_frame_info(_DWORD, _DWORD);
// 19010: using guessed type int dword_19010;

//----- (00008DE8) --------------------------------------------------------
void sub_8DE8()
{
  ;
}

//----- (00008DF0) --------------------------------------------------------
int __fastcall sub_8DF0(int a1, int a2)
{
  int v3; // [sp+Ch] [bp-8h]

  switch ( a1 )
  {
    case 1:
      v3 = sub_F880(3 * a2, 0x64u);
      break;
    case 2:
      v3 = sub_F880(5 * a2, 0x64u);
      break;
    case 3:
      v3 = sub_F880(10 * a2, 0x64u);
      break;
    case 4:
      v3 = sub_F880(15 * a2, 0x64u);
      break;
    case 5:
      v3 = sub_F880(25 * a2, 0x64u);
      break;
    case 6:
      v3 = sub_F880(35 * a2, 0x64u);
      break;
    case 7:
      v3 = sub_F880(50 * a2, 0x64u);
      break;
    case 8:
      v3 = sub_F880(65 * a2, 0x64u);
      break;
    case 9:
      v3 = sub_F880(85 * a2, 0x64u);
      break;
    default:
      v3 = 0;
      break;
  }
  return v3;
}
// 8E1C: control flows out of bounds to 8E20

//----- (00008FEC) --------------------------------------------------------
int sub_8FEC()
{
  int result; // r0
  int v1; // [sp+4h] [bp-2D8h] BYREF
  _BYTE v2[700]; // [sp+8h] [bp-2D4h] BYREF
  int v3; // [sp+2C4h] [bp-18h] BYREF
  int v4; // [sp+2C8h] [bp-14h]
  int i; // [sp+2CCh] [bp-10h]
  int v6; // [sp+2D0h] [bp-Ch]
  int v7; // [sp+2D4h] [bp-8h]

  v4 = 0;
  i = 0;
  v3 = 0;
  v6 = 0;
  v7 = 0;
  v1 = 0;
  Ssc_getPortLinkState(&v1);
  result = shm_sysGetEepromInfo(v2);
  for ( i = 0; i <= 9; ++i )
  {
    if ( ((1 << i) & v1) != 0 )
    {
      v4 = sub_98E0(i, &v3);
    }
    else
    {
      switch ( v2[32 * i + 380] & 3 )
      {
        case 0:
          v3 = 100;
          break;
        case 1:
          v3 = 1000;
          break;
        case 2:
          v3 = 10;
          break;
        case 3:
          v3 = 10000;
          break;
        default:
          break;
      }
    }
    v3 *= 1000;
    v6 = sub_8DF0(dword_19254[i + 1], v3);
    v7 = sub_8DF0(dword_19254[i + 11], v3);
    sub_DE70(i, dword_19254[0]);
    sub_DF50(i, v6);
    result = sub_E030(i, v7);
  }
  return result;
}
// 90B4: control flows out of bounds to 90B8
// 8C74: using guessed type int __fastcall shm_sysGetEepromInfo(_DWORD);
// 19254: using guessed type int dword_19254[21];

//----- (000091DC) --------------------------------------------------------
bool sub_91DC()
{
  return memcmp(&unk_192A8, &dword_19254, 0x54u) != 0;
}
// 19254: using guessed type int dword_19254;

//----- (0000921C) --------------------------------------------------------
void __fastcall __noreturn main(int a1, char **a2, char **a3)
{
  int v3; // r0
  _BYTE v4[148]; // [sp+0h] [bp-9Ch] BYREF
  int v5; // [sp+94h] [bp-8h]

  v3 = sock_path("NET_RATE_LIMIT.SOCKET", a2, a3);
  net_OpenSocketToInterface_Recv(v4, v3);
  sub_92AC();
  while ( 1 )
  {
    do
      v5 = net_RecvFromInterface1(v4, dword_19254, 0);
    while ( v5 < 0 );
    if ( sub_91DC() )
    {
      sub_8FEC();
      memcpy(&unk_192A8, dword_19254, 0x54u);
    }
  }
}
// 8BC0: using guessed type int __fastcall net_OpenSocketToInterface_Recv(_DWORD, _DWORD);
// 8C44: using guessed type int __fastcall sock_path(_DWORD, _DWORD, _DWORD);
// 8C98: using guessed type int __fastcall net_RecvFromInterface1(_DWORD, _DWORD, _DWORD);
// 19254: using guessed type int dword_19254[21];

//----- (000092AC) --------------------------------------------------------
int sub_92AC()
{
  dword_19300 = 0;
  if ( dword_19304 )
    return dword_19304;
  dword_19304 = open("/dev/eth_switch", 2);
  if ( dword_19304 >= 0 )
    return dword_19304;
  perror("open");
  dword_19304 = 0;
  return -1;
}
// 19300: using guessed type int dword_19300;
// 19304: using guessed type int dword_19304;

//----- (00009340) --------------------------------------------------------
int sub_9340()
{
  close(dword_19304);
  dword_19304 = 0;
  return 0;
}
// 19304: using guessed type int dword_19304;

//----- (00009374) --------------------------------------------------------
int __fastcall sub_9374(int a1, int a2, _DWORD *a3)
{
  int v4; // r0
  _BYTE v9[4]; // [sp+18h] [bp-214h] BYREF
  int v10; // [sp+1Ch] [bp-210h] BYREF
  int fd; // [sp+21Ch] [bp-10h]
  int v12; // [sp+220h] [bp-Ch]
  int *v13; // [sp+224h] [bp-8h]

  v12 = 1;
  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  v9[0] = 1;
  v9[2] = 12;
  v9[3] = 0;
  v13 = &v10;
  v4 = sub_F3E4(a1);
  *v13 = v4;
  v13[1] = a2;
  if ( ioctl(fd, 0x82044700, v9) < 0 )
    sub_F2F8(3, "ioctl READ_REG_IOCTL error\n");
  sub_F2F8(6, "port %d, REG 0x%x => 0x%x\n", a1, a2, v13[2]);
  *a3 = v13[2];
  return v12;
}

//----- (00009484) --------------------------------------------------------
int __fastcall sub_9484(int a1, int a2, int a3)
{
  int v4; // r0
  _BYTE v9[4]; // [sp+18h] [bp-214h] BYREF
  int v10; // [sp+1Ch] [bp-210h] BYREF
  int fd; // [sp+21Ch] [bp-10h]
  int v12; // [sp+220h] [bp-Ch]
  int *v13; // [sp+224h] [bp-8h]

  v12 = 1;
  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  v9[0] = 1;
  v9[2] = 12;
  v9[3] = 0;
  v13 = &v10;
  v4 = sub_F3E4(a1);
  *v13 = v4;
  v13[1] = a2;
  v13[2] = a3;
  if ( ioctl(fd, 0x42044701u, v9) < 0 )
    sub_F2F8(3, "ioctl WRITE_REG_IOCTL error\n");
  sub_F2F8(6, "port %d, REG 0x%x , VAL = 0x%x\n", a1, a2, a3);
  return v12;
}

//----- (00009588) --------------------------------------------------------
int __fastcall sub_9588(int a1, int a2, _DWORD *a3)
{
  _BYTE v8[4]; // [sp+18h] [bp-214h] BYREF
  _DWORD v9[128]; // [sp+1Ch] [bp-210h] BYREF
  int fd; // [sp+21Ch] [bp-10h]
  int v11; // [sp+220h] [bp-Ch]
  _DWORD *v12; // [sp+224h] [bp-8h]

  v11 = 1;
  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  v8[0] = 0;
  v8[2] = 12;
  v8[3] = 0;
  v12 = v9;
  v9[0] = a1;
  v9[1] = a2;
  if ( ioctl(fd, 0x82044700, v8) < 0 )
    sub_F2F8(3, "ioctl READ_REG_IOCTL error\n");
  sub_F2F8(6, "PHY 0x%x, REG 0x%x => 0x%x\n", a1, a2, v12[2]);
  *a3 = v12[2];
  return v11;
}

//----- (0000968C) --------------------------------------------------------
int __fastcall sub_968C(int a1, int a2, int a3)
{
  _BYTE v8[4]; // [sp+18h] [bp-214h] BYREF
  _DWORD v9[128]; // [sp+1Ch] [bp-210h] BYREF
  int fd; // [sp+21Ch] [bp-10h]
  int v11; // [sp+220h] [bp-Ch]
  _DWORD *v12; // [sp+224h] [bp-8h]

  v11 = 1;
  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  v8[0] = 0;
  v8[2] = 12;
  v8[3] = 0;
  v12 = v9;
  v9[0] = a1;
  v9[1] = a2;
  v9[2] = a3;
  if ( ioctl(fd, 0x42044701u, v8) < 0 )
    sub_F2F8(3, "ioctl WRITE_REG_IOCTL error\n");
  sub_F2F8(6, "PHY 0x%x, REG 0x%x , VAL = 0x%x\n", a1, a2, a3);
  return v11;
}

//----- (00009784) --------------------------------------------------------
int __fastcall sub_9784(int a1)
{
  if ( ((1 << a1) & dword_19300) != 0 )
  {
    sub_F2F8(7, "%s() %d vport = %d isGiga\n", "Ssc_isGigaCopperLink", 184, a1);
    return 1;
  }
  else
  {
    sub_F2F8(7, "%s() %d vport = %d notGiga\n", "Ssc_isGigaCopperLink", 188, a1);
    return 0;
  }
}
// 19300: using guessed type int dword_19300;

//----- (00009814) --------------------------------------------------------
int __fastcall sub_9814(int a1)
{
  char v2; // r0
  int v5; // [sp+Ch] [bp-10h] BYREF
  int fd; // [sp+10h] [bp-Ch]
  int v7; // [sp+14h] [bp-8h]

  v7 = 1;
  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  if ( ioctl(fd, 0x8004470A, &v5) < 0 )
    sub_F2F8(3, "ioctl ETHSW_LINK_STATUS_GET error\n");
  v2 = sub_F3E4(a1);
  if ( ((1 << v2) & v5) != 0 )
    v7 = 0;
  sub_F2F8(7, "port %d isDown = %d\n", a1, v7);
  return v7;
}

//----- (000098E0) --------------------------------------------------------
int __fastcall sub_98E0(int a1, _DWORD *a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 1;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_F3E4(a1);
  *v8 = v3;
  if ( ioctl(fd, 0x82044702, s) >= 0 )
  {
    *a2 = v8[1];
    return 0;
  }
  else
  {
    sub_F2F8(3, "%s() ioctl error\n", "Ssc_port_speed_get");
    return -1;
  }
}

//----- (000099D0) --------------------------------------------------------
int __fastcall sub_99D0(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+14h] [bp-210h] BYREF
  int *v8; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  sub_F2F8(7, "%s() %d >>>>>>> port %d %d\n", "Ssc_port_speed_set", 266, a1, a2);
  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 1;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_F3E4(a1);
  *v8 = v3;
  v8[1] = a2;
  if ( ioctl(fd, 0x42044703u, s) < 0 )
    sub_F2F8(3, "%s() ioctl error\n", "Ssc_port_speed_set");
  return 0;
}

//----- (00009AE0) --------------------------------------------------------
int __fastcall sub_9AE0(int a1)
{
  int v2; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v6; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 7;
  s[2] = 8;
  s[3] = 0;
  v6 = (int *)&s[4];
  v2 = sub_F3E4(a1);
  *v6 = v2;
  if ( ioctl(fd, 0x42044703u, s) < 0 )
    sub_F2F8(3, "%s() ioctl error\n", "Ssc_port_learing_disable");
  return 0;
}

//----- (00009BB4) --------------------------------------------------------
int __fastcall sub_9BB4(int a1)
{
  int v2; // r0
  _BYTE v5[4]; // [sp+Ch] [bp-210h] BYREF
  int v6; // [sp+10h] [bp-20Ch] BYREF
  int *v7; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  v5[0] = 8;
  v5[2] = 8;
  v5[3] = 0;
  v7 = &v6;
  v2 = sub_F3E4(a1);
  *v7 = v2;
  if ( ioctl(fd, 0x42044703u, v5) < 0 )
    sub_F2F8(3, "%s() ioctl error\n", "Ssc_port_learing_enable");
  return 0;
}

//----- (00009C74) --------------------------------------------------------
int sub_9C74()
{
  _BYTE v2[516]; // [sp+4h] [bp-210h] BYREF
  int fd; // [sp+208h] [bp-Ch]

  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  v2[0] = 9;
  v2[2] = 8;
  v2[3] = 0;
  if ( ioctl(fd, 0x42044703u, v2) < 0 )
    sub_F2F8(3, "%s() ioctl error\n", "Ssc_cpuport_learing_disable");
  return 0;
}

//----- (00009D10) --------------------------------------------------------
int sub_9D10()
{
  _BYTE v2[520]; // [sp+4h] [bp-210h] BYREF
  int fd; // [sp+20Ch] [bp-8h]

  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  v2[0] = 10;
  v2[2] = 8;
  v2[3] = 0;
  if ( ioctl(fd, 0x42044703u, v2) < 0 )
    sub_F2F8(3, "%s() ioctl error\n", "Ssc_cpuport_learing_enable");
  return 0;
}

//----- (00009DAC) --------------------------------------------------------
int __fastcall sub_9DAC(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 2;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_F3E4(a1);
  *v8 = v3;
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_F2F8(3, "%s() ioctl error\n", "Ssc_port_duplex_get");
  *(_DWORD *)a2 = v8[1];
  return *(_DWORD *)a2;
}

//----- (00009E98) --------------------------------------------------------
int __fastcall sub_9E98(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 11;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_F3E4(a1);
  *v8 = v3;
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_F2F8(3, "%s() ioctl error\n", "Ssc_port_qinq_get");
  *(_DWORD *)a2 = v8[1];
  return *(_DWORD *)a2;
}

//----- (00009F84) --------------------------------------------------------
int __fastcall sub_9F84(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 12;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_F3E4(a1);
  *v8 = v3;
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_F2F8(3, "%s() ioctl error\n", "Ssc_port_egress_get");
  *(_DWORD *)a2 = v8[1];
  return *(_DWORD *)a2;
}

//----- (0000A070) --------------------------------------------------------
int __fastcall sub_A070(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 13;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_F3E4(a1);
  *v8 = v3;
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_F2F8(3, "%s() ioctl error\n", "Ssc_port_802dot1q_mode_get");
  *(_DWORD *)a2 = v8[1];
  return *(_DWORD *)a2;
}

//----- (0000A15C) --------------------------------------------------------
int __fastcall sub_A15C(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+8h] [bp-214h] BYREF
  int v8; // [sp+20Ch] [bp-10h]
  int *v9; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 13;
  s[2] = 8;
  s[3] = 0;
  v9 = (int *)&s[4];
  v3 = sub_F3E4(a1);
  *v9 = v3;
  v9[1] = a2;
  if ( ioctl(fd, 0x42044703u, s) < 0 )
    sub_F2F8(3, "%s() ioctl error\n", "Ssc_port_802dot1q_mode_set");
  return v8;
}

//----- (0000A240) --------------------------------------------------------
int __fastcall sub_A240(int a1, const char *a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+14h] [bp-210h] BYREF
  int *v8; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  sub_F2F8(7, "%s() %d >>>>>>> port %d %s\n", "Ssc_port_duplex_set", 548, a1, a2);
  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 2;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_F3E4(a1);
  *v8 = v3;
  v8[1] = (int)a2;
  if ( ioctl(fd, 0x42044703u, s) < 0 )
    sub_F2F8(3, "%s() ioctl error\n", "Ssc_port_duplex_set");
  return 0;
}

//----- (0000A34C) --------------------------------------------------------
int __fastcall sub_A34C(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 4;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_F3E4(a1);
  *v8 = v3;
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_F2F8(3, "%s() ioctl error\n", "Ssc_port_pause_get");
  *(_DWORD *)a2 = v8[1];
  return *(_DWORD *)a2;
}

//----- (0000A438) --------------------------------------------------------
int __fastcall sub_A438(int a1, const char *a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+14h] [bp-210h] BYREF
  int *v8; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  sub_F2F8(7, "%s() %d >>>>>>> port %d %s\n", "Ssc_port_pause_set", 619, a1, a2);
  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 4;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_F3E4(a1);
  *v8 = v3;
  v8[1] = (int)a2;
  if ( ioctl(fd, 0x42044703u, s) < 0 )
    sub_F2F8(3, "%s() ioctl error\n", "Ssc_port_pause_set");
  return 0;
}

//----- (0000A548) --------------------------------------------------------
int __fastcall sub_A548(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 3;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_F3E4(a1);
  *v8 = v3;
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_F2F8(3, "%s() ioctl error\n", "Ssc_port_mdi_get");
  *(_DWORD *)a2 = v8[1];
  return *(_DWORD *)a2;
}

//----- (0000A634) --------------------------------------------------------
int __fastcall sub_A634(int a1, const char *a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+14h] [bp-210h] BYREF
  int *v8; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  sub_F2F8(7, "%s() %d >>>>>>> port %d %s\n", "Ssc_port_mdi_set", 689, a1, a2);
  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 3;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_F3E4(a1);
  *v8 = v3;
  v8[1] = (int)a2;
  if ( ioctl(fd, 0x42044703u, s) < 0 )
    sub_F2F8(3, "%s() ioctl SET_PORT_STATE error\n", "Ssc_port_mdi_set");
  return 0;
}

//----- (0000A744) --------------------------------------------------------
int __fastcall sub_A744(int a1)
{
  int v2; // r0
  _BYTE s[516]; // [sp+14h] [bp-210h] BYREF
  int *v6; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 1;
  s[2] = 8;
  s[3] = 0;
  v6 = (int *)&s[4];
  v2 = sub_F3E4(a1);
  *v6 = v2;
  if ( ioctl(fd, 0x82044708, s) < 0 )
    sub_F2F8(3, "ioctl GET_PORT_STATE error\n");
  sub_F2F8(5, "%s() Port %d state = %d\n", "Ssc_getPortState", *v6, v6[1]);
  return v6[1];
}

//----- (0000A840) --------------------------------------------------------
int __fastcall sub_A840(int a1, int a2, int a3)
{
  int result; // r0
  int v4; // r0
  char v5; // [sp+14h] [bp-220h]
  int v6; // [sp+18h] [bp-21Ch]
  _BYTE s[516]; // [sp+24h] [bp-210h] BYREF
  int *v9; // [sp+228h] [bp-Ch]
  int fd; // [sp+22Ch] [bp-8h]

  v6 = a2;
  v5 = a3;
  sub_F2F8(5, "%s() %d >>>>>> port %d state %d, flags = 0x%02x\n", "Ssc_setPortState", 772, a1, a2, a3);
  result = sub_92AC();
  fd = result;
  if ( result >= 0 )
  {
    if ( (unsigned int)(v6 - 2) > 3 )
    {
      if ( (v5 & 1) != 0 )
      {
        v6 = 2;
      }
      else if ( (v5 & 4) != 0 )
      {
        v6 = 1;
      }
      else
      {
        v6 = 5;
      }
    }
    memset(s, 0, sizeof(s));
    s[0] = 1;
    s[2] = 8;
    s[3] = 0;
    v9 = (int *)&s[4];
    v4 = sub_F3E4(a1);
    *v9 = v4;
    v9[1] = v6;
    if ( ioctl(fd, 0x42044709u, s) < 0 )
      sub_F2F8(3, "ioctl SET_PORT_STATE error\n");
    return sub_F2F8(5, "%s() Port %d state = %d\n", "Ssc_setPortState", *v9, v9[1]);
  }
  return result;
}

//----- (0000A9D4) --------------------------------------------------------
int __fastcall sub_A9D4(int a1, int a2)
{
  const char *v2; // r3
  char *v3; // r0
  int v5; // r0
  char s[128]; // [sp+14h] [bp-298h] BYREF
  _BYTE v10[516]; // [sp+94h] [bp-218h] BYREF
  int *v11; // [sp+298h] [bp-14h]
  int fd; // [sp+29Ch] [bp-10h]

  fd = 0;
  if ( a2 )
    v2 = "Enable";
  else
    v2 = "Disable";
  sub_F2F8(7, "%s() %d >>>>>>> port %d %s\n", "Ssc_port_enable_set", 834, a1, v2);
  if ( a1 <= 7 )
  {
    fd = sub_92AC();
    if ( fd >= 0 )
    {
      memset(v10, 0, sizeof(v10));
      v10[0] = 0;
      v10[2] = 8;
      v10[3] = 0;
      v11 = (int *)&v10[4];
      v5 = sub_F3E4(a1);
      *v11 = v5;
      v11[1] = a2;
      if ( ioctl(fd, 0x42044703u, v10) < 0 )
        sub_F2F8(3, "%s() ioctl SET_PORT_STATE error\n", "Ssc_port_enable_set");
      return 0;
    }
    else
    {
      return -1;
    }
  }
  else
  {
    v3 = sub_EE20("port_enable");
    sprintf(s, " echo %x,%d > %s", a1, a2, v3);
    system(s);
    printf("msg = %s\n", s);
    return 0;
  }
}

//----- (0000AB6C) --------------------------------------------------------
int __fastcall Ssc_getPortLinkState(_DWORD *a1)
{
  char v2; // r0
  int v5; // [sp+8h] [bp-14h] BYREF
  int v6; // [sp+Ch] [bp-10h]
  int i; // [sp+10h] [bp-Ch]
  int fd; // [sp+14h] [bp-8h]

  v6 = 1;
  i = 0;
  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  if ( ioctl(fd, 0x8004470A, &v5) < 0 )
    sub_F2F8(3, "ioctl ETHSW_LINK_STATUS_GET error\n");
  for ( i = 0; i <= 9; ++i )
  {
    v2 = sub_F3E4(i);
    if ( ((1 << v2) & v5) != 0 )
      *a1 |= 1 << i;
  }
  return v6;
}

//----- (0000AC64) --------------------------------------------------------
int __fastcall sub_AC64(int a1)
{
  int v2; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v6; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 0;
  s[2] = 8;
  s[3] = 0;
  v6 = (int *)&s[4];
  v2 = sub_F3E4(a1);
  *v6 = v2;
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_F2F8(3, "%s() ioctl SET_PORT_STATE error\n", "Ssc_port_enable_get");
  return v6[1];
}

//----- (0000AD3C) --------------------------------------------------------
void *__fastcall Ssc_getPortStatsCounter(void *a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-218h] BYREF
  int *v7; // [sp+210h] [bp-14h]
  int fd; // [sp+214h] [bp-10h]

  fd = sub_92AC();
  if ( fd < 0 )
    fprintf((FILE *)stderr, "%s() device open failed\n", "Ssc_getPortStatsCounter");
  memset(s, 0, sizeof(s));
  s[0] = 0;
  strcpy(&s[2], "d");
  v7 = (int *)&s[4];
  v3 = sub_F3E4(a2);
  *v7 = v3;
  if ( ioctl(fd, 0x80044714, s) < 0 )
    sub_F2F8(3, "%s() ioctl GET_PORT_STATSCOUNTER error\n", "Ssc_getPortStatsCounter");
  memcpy(a1, v7 + 1, 0x60u);
  return a1;
}
// 19230: using guessed type int stderr;

//----- (0000AE50) --------------------------------------------------------
int __fastcall sub_AE50(_DWORD *a1)
{
  pthread_mutex_lock(&mutex);
  *a1 = dword_1930C;
  dword_1930C = 0;
  return pthread_mutex_unlock(&mutex);
}
// 1930C: using guessed type int dword_1930C;

//----- (0000AE9C) --------------------------------------------------------
int __fastcall sub_AE9C(int a1)
{
  pthread_mutex_lock(&mutex);
  dword_1930C |= a1;
  return pthread_mutex_unlock(&mutex);
}
// 1930C: using guessed type int dword_1930C;

//----- (0000AEE4) --------------------------------------------------------
int __fastcall sub_AEE4(int a1)
{
  int result; // r0
  int v3; // [sp+10h] [bp-214h] BYREF
  _BYTE s[516]; // [sp+14h] [bp-210h] BYREF
  _BYTE *v5; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  sub_F2F8(5, "%s() %d pbmp = %lx\n", "Ssc_flushMacAddr", 979, a1);
  result = sub_92AC();
  fd = result;
  if ( result >= 0 )
  {
    memset(s, 0, sizeof(s));
    s[0] = 1;
    s[2] = 12;
    s[3] = 0;
    v5 = &s[4];
    sub_F5A0(a1, &v3);
    *((_DWORD *)v5 + 2) = v3;
    if ( ioctl(fd, 0x42044705u, s) < 0 )
      sub_F2F8(3, "ioctl ETHSW_FDB_FLUSH error\n");
    return sub_AE9C(a1);
  }
  return result;
}

//----- (0000AFE4) --------------------------------------------------------
int __fastcall sub_AFE4(int a1)
{
  _DWORD s[130]; // [sp+Ch] [bp-210h] BYREF
  int fd; // [sp+214h] [bp-8h]

  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, 0x204u);
  LOBYTE(s[0]) = 8;
  HIWORD(s[0]) = 4;
  s[129] = &s[1];
  s[1] = a1;
  if ( ioctl(fd, 0x42044705u, s) < 0 )
    sub_F2F8(3, "ioctl ETHSW_TYPE_FDB_AGE_TIME error\n");
  return 0;
}

//----- (0000B0A8) --------------------------------------------------------
int sub_B0A8()
{
  _DWORD s[129]; // [sp+0h] [bp-214h] BYREF
  int v3; // [sp+204h] [bp-10h]
  _DWORD *v4; // [sp+208h] [bp-Ch]
  int fd; // [sp+20Ch] [bp-8h]

  v3 = 0;
  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  LOBYTE(s[0]) = 0;
  HIWORD(s[0]) = 4;
  v4 = &s[1];
  s[1] = 1;
  if ( ioctl(fd, 0x82044704, s, s) < 0 )
    sub_F2F8(3, "%s() ioctl ETHSW_FDB_GET error\n", "Ssc_fdbGetEntry");
  return v3;
}

//----- (0000B178) --------------------------------------------------------
int __fastcall sub_B178(const void *a1, _DWORD *a2)
{
  int v6; // [sp+8h] [bp-21Ch] BYREF
  _BYTE s[516]; // [sp+Ch] [bp-218h] BYREF
  int v8; // [sp+210h] [bp-14h]
  int fd; // [sp+214h] [bp-10h]
  void *dest; // [sp+218h] [bp-Ch]
  int v11; // [sp+21Ch] [bp-8h]

  v8 = 0;
  v11 = 0;
  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  v6 = 0;
  memset(s, 0, sizeof(s));
  s[0] = 7;
  s[2] = 28;
  s[3] = 0;
  dest = &s[4];
  memcpy(&s[4], a1, 6u);
  if ( ioctl(fd, 0x82044704, s) < 0 )
    sub_F2F8(3, "%s() ioctl ETHSW_FDB_GET error\n", "Ssc_fdbGetMacPbmp");
  v8 = *((unsigned __int8 *)dest + 25);
  if ( v8 )
    sub_F688(*((_DWORD *)dest + 3), &v6);
  *a2 = v6;
  return v8;
}

//----- (0000B2A4) --------------------------------------------------------
int __fastcall sub_B2A4(const void *a1, void *a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+2Ch] [bp-228h] BYREF
  int v8; // [sp+230h] [bp-24h]
  int fd; // [sp+234h] [bp-20h]
  void *dest; // [sp+238h] [bp-1Ch]
  int i; // [sp+23Ch] [bp-18h]

  v8 = 0;
  i = 0;
  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 7;
  s[2] = 28;
  s[3] = 0;
  dest = &s[4];
  memcpy(&s[4], a1, 6u);
  if ( ioctl(fd, 0x82044704, s) < 0 )
    sub_F2F8(3, "%s() ioctl ETHSW_FDB_GET error\n", "Ssc_fdbFindMacEntry");
  v8 = *((unsigned __int8 *)dest + 25);
  if ( v8 )
  {
    for ( i = 0; i <= 9; ++i )
    {
      if ( (*((_DWORD *)dest + 3) & (1 << i)) != 0 )
      {
        v3 = sub_F4B0(i);
        *((_DWORD *)dest + 2) = v3;
        break;
      }
    }
    memcpy(a2, dest, 0x1Cu);
  }
  printf(
    "%s() addr = %02x:%02x:%02x:%02x:%02x:%02x, port = %02x (%d), inused = %d\n",
    "Ssc_fdbFindMacEntry",
    *(unsigned __int8 *)dest,
    *((unsigned __int8 *)dest + 1),
    *((unsigned __int8 *)dest + 2),
    *((unsigned __int8 *)dest + 3),
    *((unsigned __int8 *)dest + 4),
    *((unsigned __int8 *)dest + 5),
    *((_DWORD *)dest + 3),
    *((_DWORD *)dest + 2),
    *((unsigned __int8 *)dest + 25));
  return v8;
}

//----- (0000B49C) --------------------------------------------------------
int __fastcall sub_B49C(const void *a1, void *a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+2Ch] [bp-228h] BYREF
  int v8; // [sp+230h] [bp-24h]
  int fd; // [sp+234h] [bp-20h]
  void *dest; // [sp+238h] [bp-1Ch]
  int i; // [sp+23Ch] [bp-18h]

  v8 = 0;
  i = 0;
  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 7;
  s[2] = 28;
  s[3] = 0;
  dest = &s[4];
  memcpy(&s[4], a1, 6u);
  if ( ioctl(fd, 0x82044704, s) < 0 )
    sub_F2F8(3, "%s() ioctl ETHSW_FDB_GET error\n", "Ssc_fdbFindAllMacEntry");
  v8 = *((unsigned __int8 *)dest + 25);
  if ( v8 )
  {
    for ( i = 0; i <= 13; ++i )
    {
      if ( (*((_DWORD *)dest + 3) & (1 << i)) != 0 )
      {
        v3 = sub_F4B0(i);
        *((_DWORD *)dest + 2) = v3;
        break;
      }
    }
    memcpy(a2, dest, 0x1Cu);
  }
  printf(
    "%s() addr = %02x:%02x:%02x:%02x:%02x:%02x, port = %02x (%d), inused = %d\n",
    "Ssc_fdbFindAllMacEntry",
    *(unsigned __int8 *)dest,
    *((unsigned __int8 *)dest + 1),
    *((unsigned __int8 *)dest + 2),
    *((unsigned __int8 *)dest + 3),
    *((unsigned __int8 *)dest + 4),
    *((unsigned __int8 *)dest + 5),
    *((_DWORD *)dest + 3),
    *((_DWORD *)dest + 2),
    *((unsigned __int8 *)dest + 25));
  return v8;
}

//----- (0000B694) --------------------------------------------------------
int __fastcall sub_B694(_DWORD *a1)
{
  int v2; // r4
  _BYTE s[516]; // [sp+8h] [bp-21Ch] BYREF
  int v6; // [sp+20Ch] [bp-18h]
  int *v7; // [sp+210h] [bp-14h]
  int fd; // [sp+214h] [bp-10h]

  v6 = 0;
  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 6;
  s[2] = 16;
  s[3] = 0;
  v7 = (int *)&s[4];
  if ( ioctl(fd, 0x82044704, s) < 0 )
    sub_F2F8(3, "%s() ioctl ETHSW_FDB_GET error\n", "Ssc_fdbGetAddrTableSize");
  v6 = *v7;
  v2 = v7[3];
  *a1 = v7[2];
  a1[1] = v2;
  return v6;
}

//----- (0000B77C) --------------------------------------------------------
int __fastcall sub_B77C(char *a1, size_t a2, int a3)
{
  unsigned int v4; // r0
  int v5; // r4
  _BYTE v10[14336]; // [sp+10h] [bp-3834h] BYREF
  int v11; // [sp+3810h] [bp-34h] BYREF
  int v12; // [sp+3814h] [bp-30h]
  int fd; // [sp+3818h] [bp-2Ch]
  ssize_t v14; // [sp+381Ch] [bp-28h]
  int v15; // [sp+3820h] [bp-24h]
  int i; // [sp+3824h] [bp-20h]
  int v17; // [sp+3828h] [bp-1Ch]
  int v18; // [sp+382Ch] [bp-18h]
  int v19; // [sp+3830h] [bp-14h]
  int v20; // [sp+3834h] [bp-10h]

  fd = 0;
  v14 = 0;
  v15 = 0;
  i = 0;
  v17 = 0;
  v18 = 0;
  v19 = 0;
  v20 = 0;
  v11 = 0;
  v12 = 0;
  if ( a1 )
  {
    fd = sub_92AC();
    if ( fd >= 0 )
    {
      memset(v10, 0, sizeof(v10));
      v17 = sub_B694(&v11);
      if ( v17 > 511 )
        v18 = 512;
      else
        v18 = v17;
      if ( v11 == unk_19328 && v12 == unk_1932C )
      {
LABEL_10:
        sub_9340();
        return dword_19330;
      }
      else
      {
        memset(a1, 0, a2);
        dword_19330 = 0;
        unk_19328 = v11;
        unk_1932C = v12;
        while ( 1 )
        {
          v14 = read(fd, v10, 28 * v18);
          if ( v14 == -1 )
            break;
          v4 = sub_F770(v14, 0x1Cu);
          v15 += v4;
          for ( i = 0; i < v18; ++i )
          {
            if ( a3 )
            {
              if ( v10[28 * i] == 1
                && (unsigned __int8)v10[28 * i + 1] == 128
                && (unsigned __int8)v10[28 * i + 2] == 194 )
              {
                continue;
              }
              v5 = *(_DWORD *)&v10[28 * i + 12];
              if ( (v5 & (1 << sub_F3E4(14))) != 0 )
                continue;
            }
            memcpy(&a1[92 * dword_19330], &v10[28 * i], 6u);
            if ( a1[92 * dword_19330] == 1 )
            {
              strcpy(&a1[92 * dword_19330 + 6], "mcast");
              strcpy(&a1[92 * dword_19330 + 14], "static");
            }
            else
            {
              strcpy(&a1[92 * dword_19330 + 6], "ucast");
              if ( *(_DWORD *)&v10[28 * i + 16] == 1 )
                strcpy(&a1[92 * dword_19330 + 14], "learn");
              else
                strcpy(&a1[92 * dword_19330 + 14], "static");
            }
            a1[92 * dword_19330 + 32] = v10[28 * i + 26];
            sub_F688(*(_DWORD *)&v10[28 * i + 12], &a1[92 * dword_19330 + 28]);
            ++dword_19330;
          }
          if ( v15 >= v17 )
            goto LABEL_10;
          v19 = v17 - v15;
          if ( v17 - v15 <= 512 )
            v18 = v19;
          else
            v18 = 512;
        }
        fprintf((FILE *)stderr, "%s() %d read error\n", "Ssc_fdbGetAddrTable", 1260);
        return -1;
      }
    }
    else
    {
      return -1;
    }
  }
  else
  {
    fprintf((FILE *)stderr, "%s() %d Invalid argument\n", "Ssc_fdbGetAddrTable", 1228);
    return -1;
  }
}
// 19230: using guessed type int stderr;
// 19330: using guessed type int dword_19330;

//----- (0000BF30) --------------------------------------------------------
int __fastcall sub_BF30(const void *a1, char a2, int a3)
{
  int result; // r0
  int v7; // [sp+18h] [bp-214h] BYREF
  _BYTE s[516]; // [sp+1Ch] [bp-210h] BYREF
  void *dest; // [sp+220h] [bp-Ch]
  int fd; // [sp+224h] [bp-8h]

  sub_F2F8(5, "%s() %d lpbmp = %lx\n", "Ssc_fdbAddUcastEntry", 1338, a3);
  result = sub_92AC();
  fd = result;
  if ( result >= 0 )
  {
    memset(s, 0, sizeof(s));
    v7 = 0;
    s[0] = 3;
    s[2] = 16;
    s[3] = 0;
    dest = &s[4];
    memcpy(&s[4], a1, 6u);
    sub_F5A0(a3, &v7);
    *((_DWORD *)dest + 2) = v7;
    *((_BYTE *)dest + 13) = a2;
    result = ioctl(fd, 0x42044705u, s);
    if ( result < 0 )
      return sub_F2F8(3, "ioctl ETHSW_FDB_SET error\n");
  }
  return result;
}

//----- (0000C060) --------------------------------------------------------
int __fastcall sub_C060(const void *a1, int a2, int a3)
{
  int result; // r0
  int v7; // [sp+18h] [bp-214h] BYREF
  _BYTE s[516]; // [sp+1Ch] [bp-210h] BYREF
  _BYTE *v9; // [sp+220h] [bp-Ch]
  int fd; // [sp+224h] [bp-8h]

  sub_F2F8(5, "%s() %d lpbmp = %lx\n", "Ssc_setMgmtFrame", 1386, a3);
  result = sub_92AC();
  fd = result;
  if ( result >= 0 )
  {
    memset(s, 0, sizeof(s));
    v7 = 0;
    s[0] = 2;
    s[2] = 20;
    s[3] = 0;
    v9 = &s[4];
    memcpy(&s[8], a1, 6u);
    sub_F5A0(a3, &v7);
    *((_DWORD *)v9 + 3) = v7;
    *(_DWORD *)v9 = a2;
    if ( a2 )
    {
      v9[16] = a2;
      v9[17] = 7;
    }
    result = ioctl(fd, 0x42044705u, s);
    if ( result < 0 )
      return sub_F2F8(3, "ioctl ETHSW_FDB_SET error\n");
  }
  return result;
}

//----- (0000C1B8) --------------------------------------------------------
int sub_C1B8()
{
  sub_F2F8(7, "%s() %d\n", "Ssc_enable_manage_port", 1429);
  return sub_C060(off_191BC, 1, 0x4000);
}
// 191BC: using guessed type _UNKNOWN *off_191BC;

//----- (0000C210) --------------------------------------------------------
int sub_C210()
{
  sub_F2F8(7, "%s() %d\n", "Ssc_disable_manage_port", 1447);
  return sub_C060(off_191BC, 0, 0);
}
// 191BC: using guessed type _UNKNOWN *off_191BC;

//----- (0000C268) --------------------------------------------------------
int sub_C268()
{
  return sub_D998(off_191BC, 0);
}
// 191BC: using guessed type _UNKNOWN *off_191BC;

//----- (0000C28C) --------------------------------------------------------
int __fastcall sub_C28C(int a1, const void *a2, int a3)
{
  sub_F2F8(5, "%s() %d lpbmp = 0x%lx\n", "Ssc_enable_manage_multiport", 1464, a3);
  return sub_C060(a2, 1, a3);
}

//----- (0000C2E4) --------------------------------------------------------
int __fastcall sub_C2E4(int a1, const void *a2, int a3)
{
  sub_F2F8(5, "%s() %d lpbmp = 0x%lx\n", "Ssc_disable_manage_multiport", 1473, a3);
  return sub_C060(a2, 1, 0x4000);
}

//----- (0000C350) --------------------------------------------------------
int __fastcall sub_C350(int a1, const void *a2)
{
  sub_F2F8(7, "%s() %d\n", "Ssc_delete_manage_multiport", 1484);
  return sub_C060(a2, 0, 0);
}

//----- (0000C3A8) --------------------------------------------------------
int __fastcall sub_C3A8(int a1)
{
  _BYTE s[516]; // [sp+14h] [bp-210h] BYREF
  _BYTE *v4; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  sub_F2F8(7, "%s() %d >>>>>>> port %d\n", "Ssc_cpuGetRate", 1500, a1);
  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 6;
  s[2] = 8;
  s[3] = 0;
  v4 = &s[4];
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_F2F8(3, "%s() ioctl error\n", "Ssc_cpuGetRate");
  return 0;
}

//----- (0000C48C) --------------------------------------------------------
int __fastcall sub_C48C(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+14h] [bp-210h] BYREF
  int *v8; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  sub_F2F8(7, "%s() %d >>>>>>> port %d %d\n", "Ssc_cpuSetRate", 1526, a1, a2);
  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 6;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_F3E4(a1);
  *v8 = v3;
  v8[1] = a2;
  if ( ioctl(fd, 0x42044703u, s) < 0 )
    sub_F2F8(3, "%s() ioctl error\n", "Ssc_cpuSetRate");
  return 0;
}

//----- (0000C59C) --------------------------------------------------------
int __fastcall sub_C59C(_DWORD *a1, int a2)
{
  int v3; // r0
  _DWORD s[129]; // [sp+8h] [bp-214h] BYREF
  int i; // [sp+20Ch] [bp-10h]
  _DWORD *v9; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  LOBYTE(s[0]) = 0;
  HIWORD(s[0]) = 16;
  v9 = &s[1];
  s[3] = a2;
  s[1] = -1;
  s[4] = 0;
  for ( i = 0; i <= 13; ++i )
  {
    if ( (*a1 & (1 << i)) != 0 )
    {
      v3 = sub_F3E4(i);
      v9[1] = v3;
      if ( ioctl(fd, 0x4204470Du, s) < 0 )
        sub_F2F8(3, "%s() ioctl error\n", "Ssc_mirrorport_reset");
    }
  }
  return 0;
}

//----- (0000C6DC) --------------------------------------------------------
int __fastcall sub_C6DC(_DWORD *a1, unsigned __int8 a2, int a3, int a4)
{
  int v5; // r0
  _DWORD s[129]; // [sp+10h] [bp-214h] BYREF
  int i; // [sp+214h] [bp-10h]
  int *v13; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  i = 0;
  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  LOBYTE(s[0]) = 0;
  HIWORD(s[0]) = 16;
  v13 = &s[1];
  s[3] = a3;
  if ( a4 )
    *v13 = sub_F3E4(a2 - 1);
  else
    *v13 = -1;
  v13[3] = a4;
  for ( i = 0; i <= 13; ++i )
  {
    if ( (*a1 & (1 << i)) != 0 )
    {
      v5 = sub_F3E4(i);
      v13[1] = v5;
      if ( ioctl(fd, 0x4204470Du, s) < 0 )
        sub_F2F8(3, "%s() ioctl error\n", "Ssc_mirrorport_enable_set");
    }
  }
  return 0;
}

//----- (0000C85C) --------------------------------------------------------
int __fastcall sub_C85C(_DWORD *a1, int a2, int a3)
{
  int v4; // r0
  _DWORD s[129]; // [sp+14h] [bp-218h] BYREF
  int i; // [sp+218h] [bp-14h]
  int v11; // [sp+21Ch] [bp-10h]
  _DWORD *v12; // [sp+220h] [bp-Ch]
  int fd; // [sp+224h] [bp-8h]

  v11 = 0;
  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  LOBYTE(s[0]) = 1;
  HIWORD(s[0]) = 16;
  v12 = &s[1];
  s[3] = a2;
  s[1] = -1;
  s[4] = a3;
  for ( i = 0; i <= 13; ++i )
  {
    if ( (*a1 & (1 << i)) != 0 )
    {
      v4 = sub_F3E4(i);
      v12[1] = v4;
      if ( ioctl(fd, 0x4204470Du, s) < 0 )
        sub_F2F8(3, "%s() ioctl error\n", "Ssc_targetport_reset");
    }
  }
  return 0;
}

//----- (0000C9A8) --------------------------------------------------------
int __fastcall sub_C9A8(_DWORD *a1, int a2, int a3)
{
  int v4; // r0
  _DWORD s[134]; // [sp+10h] [bp-22Ch] BYREF
  int i; // [sp+228h] [bp-14h]
  _DWORD *v11; // [sp+230h] [bp-Ch]
  int fd; // [sp+234h] [bp-8h]

  s[129] = 0;
  s[130] = 0;
  s[132] = 0;
  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, 0x204u);
  LOBYTE(s[0]) = 1;
  HIWORD(s[0]) = 16;
  v11 = &s[1];
  s[3] = a2;
  s[1] = -1;
  s[4] = a3;
  for ( i = 0; i <= 13; ++i )
  {
    if ( (*a1 & (1 << i)) != 0 )
    {
      v4 = sub_F3E4(i);
      v11[1] = v4;
      if ( ioctl(fd, 0x4204470Du, s) < 0 )
        sub_F2F8(3, "%s() ioctl error\n", "Ssc_targetport_enable_set");
    }
  }
  return 0;
}

//----- (0000CB04) --------------------------------------------------------
void sub_CB04()
{
  ;
}

//----- (0000CB18) --------------------------------------------------------
int __fastcall sub_CB18(int a1)
{
  _DWORD s[130]; // [sp+Ch] [bp-210h] BYREF
  int fd; // [sp+214h] [bp-8h]

  puts("Ssc_setQosSchedulingMode");
  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, 0x204u);
  LOBYTE(s[0]) = 0;
  HIWORD(s[0]) = 4;
  s[129] = &s[1];
  s[1] = a1;
  if ( ioctl(fd, 0x42044711u, s) < 0 )
    sub_F2F8(3, "ioctl ETHSW_TYPE_QOS_SCHEDULING_MODE error\n");
  return 0;
}

//----- (0000CBE4) --------------------------------------------------------
int __fastcall sub_CBE4(int result)
{
  int v1; // [sp+4h] [bp-10h]
  int i; // [sp+Ch] [bp-8h]

  v1 = result;
  for ( i = 0; i <= 9; ++i )
  {
    if ( ((1 << i) & v1) != 0 )
      result = sub_CCDC(i, 1);
    else
      result = sub_CCDC(i, 0);
  }
  return result;
}

//----- (0000CC60) --------------------------------------------------------
int __fastcall sub_CC60(int result)
{
  int v1; // [sp+4h] [bp-10h]
  int i; // [sp+Ch] [bp-8h]

  v1 = result;
  for ( i = 0; i <= 9; ++i )
  {
    if ( ((1 << i) & v1) != 0 )
      result = sub_CDBC(i, 1);
    else
      result = sub_CDBC(i, 0);
  }
  return result;
}

//----- (0000CCDC) --------------------------------------------------------
int __fastcall sub_CCDC(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 1;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_F3E4(a1);
  *v8 = v3;
  v8[1] = a2;
  if ( ioctl(fd, 0x42044711u, s) < 0 )
    sub_F2F8(3, "%s() ioctl error\n", "Ssc_port_tos_set");
  return 0;
}

//----- (0000CDBC) --------------------------------------------------------
int __fastcall sub_CDBC(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 2;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_F3E4(a1);
  *v8 = v3;
  v8[1] = a2;
  if ( ioctl(fd, 0x42044711u, s) < 0 )
    sub_F2F8(3, "%s() ioctl error\n", "Ssc_port_cos_set");
  return 0;
}

//----- (0000CE9C) --------------------------------------------------------
int __fastcall sub_CE9C(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+14h] [bp-210h] BYREF
  int *v8; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  sub_F2F8(7, "%s() %d >>>>>>> port %d %d\n", "Ssc_port_priority_set", 1861, a1, a2);
  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 3;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_F3E4(a1);
  *v8 = v3;
  v8[1] = a2;
  if ( ioctl(fd, 0x42044711u, s) < 0 )
    sub_F2F8(3, "%s() ioctl error\n", "Ssc_port_priority_set");
  return 0;
}

//----- (0000CFA8) --------------------------------------------------------
int __fastcall sub_CFA8(int a1)
{
  _BYTE s[516]; // [sp+8h] [bp-214h] BYREF
  int *v5; // [sp+20Ch] [bp-10h]
  int fd; // [sp+210h] [bp-Ch]
  int i; // [sp+214h] [bp-8h]

  i = 0;
  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 4;
  s[2] = 8;
  s[3] = 0;
  v5 = (int *)&s[4];
  for ( i = 0; i <= 7; ++i )
  {
    *v5 = i;
    v5[1] = *(_DWORD *)(a1 + 4 * i);
    if ( ioctl(fd, 0x42044711u, s) < 0 )
      sub_F2F8(3, "ioctl ETHSW_TYPE_QOS_SCHEDULING_MODE error\n");
  }
  return 0;
}

//----- (0000D0B0) --------------------------------------------------------
int __fastcall sub_D0B0(int a1, int a2, const void *a3)
{
  _DWORD s[130]; // [sp+10h] [bp-21Ch] BYREF
  int fd; // [sp+218h] [bp-14h]
  int v10; // [sp+21Ch] [bp-10h]

  v10 = 0;
  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, 0x204u);
  LOBYTE(s[0]) = 5;
  HIWORD(s[0]) = 264;
  s[129] = &s[1];
  s[1] = a1;
  s[2] = a2;
  memcpy(&s[3], a3, 0x100u);
  if ( ioctl(fd, 0x42044711u, s) < 0 )
    sub_F2F8(3, "ioctl ETHSW_TYPE_QOS_SCHEDULING_MODE error\n");
  return 0;
}

//----- (0000D1C8) --------------------------------------------------------
void sub_D1C8()
{
  ;
}

//----- (0000D1E4) --------------------------------------------------------
int __fastcall sub_D1E4(int a1, _DWORD *a2, _DWORD *a3)
{
  _DWORD s[129]; // [sp+1Ch] [bp-210h] BYREF
  _DWORD *v9; // [sp+220h] [bp-Ch]
  int fd; // [sp+224h] [bp-8h]

  sub_F2F8(7, "%s() %d >>>>>>> vid %d\n", "Ssc_getVlanPortmap", 2011, a1);
  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  LOBYTE(s[0]) = 0;
  HIWORD(s[0]) = 12;
  v9 = &s[1];
  s[1] = a1;
  if ( ioctl(fd, 0x82044706, s) >= 0 )
  {
    sub_F688(v9[1], a2);
    sub_F688(v9[2], a3);
    printf("vid=%d, tagged=%x, untagged=%x\r\n", a1, *a2, *a3);
    return 0;
  }
  else
  {
    sub_F2F8(3, "%s() ioctl error\n", "Ssc_getVlanPortmap");
    return -1;
  }
}

//----- (0000D330) --------------------------------------------------------
int __fastcall sub_D330(int a1, int a2)
{
  int v6; // [sp+14h] [bp-218h] BYREF
  int v7; // [sp+18h] [bp-214h] BYREF
  _DWORD s[129]; // [sp+1Ch] [bp-210h] BYREF
  _DWORD *v9; // [sp+220h] [bp-Ch]
  int fd; // [sp+224h] [bp-8h]

  fd = 0;
  sub_F2F8(7, "%s() %d >>>>>>> vid %d enable = %d\n", "Ssc_vlanEnableCpuPort", 2043, a1, a2);
  if ( a1 > 0 && a1 <= 4094 )
  {
    fd = sub_92AC();
    if ( fd >= 0 )
    {
      v7 = 0;
      v6 = 0;
      memset(s, 0, sizeof(s));
      sub_D1E4(a1, &v7, &v6);
      LOBYTE(s[0]) = 1;
      HIWORD(s[0]) = 12;
      v9 = &s[1];
      s[1] = a1;
      if ( a2 )
        v7 |= 0x4000u;
      else
        v7 &= ~0x4000u;
      sub_F5A0(v7, v9 + 1);
      sub_F5A0(v6, v9 + 2);
      if ( ioctl(fd, 0x82044707, s) >= 0 )
      {
        return 0;
      }
      else
      {
        sub_F2F8(3, "%s() ioctl error\n", "Ssc_vlanEnableCpuPort");
        return -1;
      }
    }
    else
    {
      return -1;
    }
  }
  else
  {
    printf("%s() %d Invalid vid = %d\n", "Ssc_vlanEnableCpuPort", 2046, a1);
    return -1;
  }
}

//----- (0000D4FC) --------------------------------------------------------
int sub_D4FC()
{
  _BYTE s[516]; // [sp+4h] [bp-210h] BYREF
  _BYTE *v3; // [sp+208h] [bp-Ch]
  int fd; // [sp+20Ch] [bp-8h]

  sub_F2F8(7, "%s() %d \n", "Ssc_vlanGetTable", 2089);
  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 2;
  s[2] = 12;
  s[3] = 0;
  v3 = &s[4];
  if ( ioctl(fd, 0x82044706, s) >= 0 )
  {
    printf("%s() %d \n", "Ssc_vlanGetTable", 2106);
    return 0;
  }
  else
  {
    sub_F2F8(3, "%s() ioctl error\n", "Ssc_vlanGetTable");
    return -1;
  }
}

//----- (0000D5F4) --------------------------------------------------------
int sub_D5F4()
{
  int v1; // r0
  _BYTE s[516]; // [sp+8h] [bp-214h] BYREF
  int i; // [sp+20Ch] [bp-10h]
  int *v5; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  for ( i = 0; i <= 9; ++i )
  {
    sub_F2F8(7, "%s() %d >>>>>>> port %d\n", "Ssc_initIgmpsnooping", 2133, i);
    memset(s, 0, sizeof(s));
    s[0] = 5;
    s[2] = 8;
    s[3] = 0;
    v5 = (int *)&s[4];
    v1 = sub_F3E4(i);
    *v5 = v1;
    v5[1] = 1;
    if ( ioctl(fd, 0x42044703u, s) < 0 )
    {
      sub_F2F8(3, "%s() ioctl error\n", "Ssc_initIgmpsnooping");
      return -1;
    }
  }
  return 0;
}

//----- (0000D720) --------------------------------------------------------
int sub_D720()
{
  int v1; // r0
  _BYTE s[516]; // [sp+8h] [bp-214h] BYREF
  int i; // [sp+20Ch] [bp-10h]
  int *v5; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  for ( i = 0; i <= 9; ++i )
  {
    sub_F2F8(7, "%s() %d >>>>>>> port %d %d\n", "Ssc_destroyIgmpsnooping", 2169, i, 0);
    memset(s, 0, sizeof(s));
    s[0] = 5;
    s[2] = 8;
    s[3] = 0;
    v5 = (int *)&s[4];
    v1 = sub_F3E4(i);
    *v5 = v1;
    v5[1] = 0;
    if ( ioctl(fd, 0x42044703u, s) < 0 )
    {
      sub_F2F8(3, "%s() ioctl error\n", "Ssc_destroyIgmpsnooping");
      return -1;
    }
  }
  return 0;
}

//----- (0000D854) --------------------------------------------------------
void sub_D854()
{
  ;
}

//----- (0000D868) --------------------------------------------------------
int __fastcall sub_D868(const void *a1, int a2, int a3)
{
  _DWORD s[129]; // [sp+10h] [bp-214h] BYREF
  int v8; // [sp+214h] [bp-10h]
  _DWORD *v9; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  v8 = 0;
  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  LOBYTE(s[0]) = 2;
  HIWORD(s[0]) = 20;
  v9 = &s[1];
  memcpy(&s[2], a1, 6u);
  sub_F5A0(a3, &s[4]);
  if ( ioctl(fd, 0x42044705u, s) >= 0 )
  {
    if ( v8 )
      sub_F2F8(3, "%s: bcm_mcast_addr_add fail err=%d\n", "Ssc_mcastAddrAdd", v8);
    return v8;
  }
  else
  {
    sub_F2F8(3, "ioctl ETHSW_FDB_SET error\n");
    return -1;
  }
}

//----- (0000D998) --------------------------------------------------------
int __fastcall sub_D998(const void *a1, __int16 a2)
{
  _BYTE s[520]; // [sp+8h] [bp-214h] BYREF
  int fd; // [sp+210h] [bp-Ch]
  _BYTE *v8; // [sp+214h] [bp-8h]

  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, 0x204u);
  if ( (unsigned __int8)a2 | (__int16)(HIBYTE(a2) << 8) )
    s[0] = 2;
  else
    s[0] = 5;
  s[2] = 20;
  s[3] = 0;
  v8 = &s[4];
  memcpy(&s[8], a1, 6u);
  if ( ioctl(fd, 0x42044705u, s) >= 0 )
    return 0;
  sub_F2F8(3, "ioctl ETHSW_FDB_SET error\n");
  return -1;
}

//----- (0000DAD8) --------------------------------------------------------
int __fastcall sub_DAD8(int a1)
{
  _DWORD s[129]; // [sp+Ch] [bp-210h] BYREF
  int fd; // [sp+210h] [bp-Ch]
  _DWORD *v6; // [sp+214h] [bp-8h]

  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  LOBYTE(s[0]) = 1;
  HIWORD(s[0]) = 4;
  v6 = &s[1];
  s[1] = a1;
  if ( ioctl(fd, 0x4204470Fu, s) < 0 )
    sub_F2F8(3, "%s() ioctl ETHSW_PORT_TRUNK_SET error\n", "Ssc_trunkSetHashMode");
  return 0;
}

//----- (0000DBA4) --------------------------------------------------------
int sub_DBA4()
{
  _BYTE s[516]; // [sp+4h] [bp-210h] BYREF
  int fd; // [sp+208h] [bp-Ch]
  _BYTE *v4; // [sp+20Ch] [bp-8h]

  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 0;
  s[2] = 8;
  s[3] = 0;
  v4 = &s[4];
  if ( ioctl(fd, 0x8204470E, s) < 0 )
    sub_F2F8(3, "%s() ioctl ETHSW_PORT_TRUNK_GET error\n", "Ssc_trunkGetInfo");
  return 0;
}

//----- (0000DC60) --------------------------------------------------------
int __fastcall sub_DC60(int a1, int a2)
{
  int v6; // [sp+8h] [bp-214h] BYREF
  _DWORD s[129]; // [sp+Ch] [bp-210h] BYREF
  int fd; // [sp+210h] [bp-Ch]
  _DWORD *v9; // [sp+214h] [bp-8h]

  printf("%s() %d %x\n", "Ssc_trunkSetMember", a1, a2);
  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  LOBYTE(s[0]) = 2;
  HIWORD(s[0]) = 8;
  v9 = &s[1];
  s[1] = a1;
  sub_F5A0(a2, &v6);
  v9[1] = v6;
  if ( ioctl(fd, 0x4204470Fu, s) < 0 )
    sub_F2F8(3, "%s() ioctl ETHSW_PORT_TRUNK_SET error\n", "Ssc_trunkSetMember");
  return 0;
}

//----- (0000DD68) --------------------------------------------------------
int __fastcall sub_DD68(int a1, int a2)
{
  int v6; // [sp+8h] [bp-214h] BYREF
  _DWORD s[129]; // [sp+Ch] [bp-210h] BYREF
  int fd; // [sp+210h] [bp-Ch]
  _DWORD *v9; // [sp+214h] [bp-8h]

  printf("%s() %d %x\n", "Ssc_trunkClearMember", a1, a2);
  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  LOBYTE(s[0]) = 3;
  HIWORD(s[0]) = 8;
  v9 = &s[1];
  s[1] = a1;
  sub_F5A0(a2, &v6);
  v9[1] = v6;
  if ( ioctl(fd, 0x4204470Fu, s) < 0 )
    sub_F2F8(3, "%s() ioctl ETHSW_PORT_TRUNK_SET error\n", "Ssc_trunkClearMember");
  return 0;
}

//----- (0000DE70) --------------------------------------------------------
int __fastcall sub_DE70(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 0;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_F3E4(a1);
  *v8 = v3;
  v8[1] = a2;
  if ( ioctl(fd, 0x42044713u, s) < 0 )
    sub_F2F8(3, "%s() ioctl error\n", "Ssc_setIngressRateLimitMode");
  return 0;
}

//----- (0000DF50) --------------------------------------------------------
int __fastcall sub_DF50(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 1;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_F3E4(a1);
  *v8 = v3;
  v8[1] = a2;
  if ( ioctl(fd, 0x42044713u, s) < 0 )
    sub_F2F8(3, "%s() ioctl error\n", "Ssc_setIngressRateLimit");
  return 0;
}

//----- (0000E030) --------------------------------------------------------
int __fastcall sub_E030(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 2;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_F3E4(a1);
  *v8 = v3;
  v8[1] = a2;
  if ( ioctl(fd, 0x42044713u, s) < 0 )
    sub_F2F8(3, "%s() ioctl error\n", "Ssc_setEgressRateLimit");
  return 0;
}

//----- (0000E110) --------------------------------------------------------
int __fastcall sub_E110(int a1)
{
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  _BYTE *v5; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 14;
  s[2] = 8;
  s[3] = 0;
  v5 = &s[4];
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_F2F8(3, "%s() ioctl error\n", "Ssc_cpu_qinq_get");
  *(_DWORD *)a1 = *((_DWORD *)v5 + 1);
  return *(_DWORD *)a1;
}

//----- (0000E1E4) --------------------------------------------------------
int __fastcall sub_E1E4(int a1)
{
  _DWORD s[131]; // [sp+8h] [bp-214h] BYREF
  int fd; // [sp+214h] [bp-8h]

  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, 0x204u);
  LOBYTE(s[0]) = 14;
  HIWORD(s[0]) = 8;
  s[130] = &s[1];
  s[2] = a1;
  if ( ioctl(fd, 0x42044703u, s) < 0 )
    sub_F2F8(3, "%s() ioctl error\n", "Ssc_cpu_qinq_set");
  return 0;
}

//----- (0000E2B0) --------------------------------------------------------
int __fastcall sub_E2B0(int a1)
{
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  _BYTE *v5; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 15;
  s[2] = 8;
  s[3] = 0;
  v5 = &s[4];
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_F2F8(3, "%s() ioctl error\n", "Ssc_cpu_egress_get");
  *(_DWORD *)a1 = *((_DWORD *)v5 + 1);
  return *(_DWORD *)a1;
}

//----- (0000E384) --------------------------------------------------------
int __fastcall sub_E384(int a1)
{
  _DWORD s[131]; // [sp+8h] [bp-214h] BYREF
  int fd; // [sp+214h] [bp-8h]

  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, 0x204u);
  LOBYTE(s[0]) = 15;
  HIWORD(s[0]) = 8;
  s[130] = &s[1];
  s[2] = a1;
  if ( ioctl(fd, 0x42044703u, s) < 0 )
    sub_F2F8(3, "%s() ioctl error\n", "Ssc_cpu_egress_set");
  return 0;
}

//----- (0000E450) --------------------------------------------------------
int __fastcall sub_E450(int a1)
{
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  _BYTE *v5; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_92AC();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 16;
  s[2] = 8;
  s[3] = 0;
  v5 = &s[4];
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_F2F8(3, "%s() ioctl error\n", "Ssc_cpu_802dot1q_mode_get");
  *(_DWORD *)a1 = *((_DWORD *)v5 + 1);
  return *(_DWORD *)a1;
}

//----- (0000E524) --------------------------------------------------------
int __fastcall sub_E524(unsigned __int8 *a1, int *a2, _DWORD *a3)
{
  sub_F2F8(7, "dsa[0-3]=0x%x 0x%x 0x%x 0x%x\n", *a1, a1[1], a1[2], a1[3]);
  *a2 = a1[1] >> 3;
  *a3 = ((a1[2] & 0xF) << 8) + a1[3];
  sub_F2F8(7, "Packet from port %d, vid %d\n", *a2, *a3);
  return 0;
}

//----- (0000E614) --------------------------------------------------------
_BYTE *__fastcall sub_E614(_BYTE *result, char a2, __int16 a3)
{
  *result = 64;
  if ( a3 )
    *result |= 0x20u;
  result[1] = 8 * a2;
  result[2] = ~((unsigned int)~((unsigned __int16)(((unsigned __int8)a3 | (HIBYTE(a3) << 8)) & 0xF00) >> 8 << 27) >> 27);
  result[3] = a3;
  return result;
}

//----- (0000E6E8) --------------------------------------------------------
ssize_t __fastcall sub_E6E8(int a1, int a2, int a3, int a4, int a5, __int16 a6)
{
  _BYTE v10[4]; // [sp+48h] [bp-2Ch] BYREF
  int v11; // [sp+4Ch] [bp-28h]
  size_t n; // [sp+50h] [bp-24h]
  int v13; // [sp+54h] [bp-20h]

  v11 = 0;
  memset(&byte_19914, 0, 0x5EAu);
  v13 = sub_F3E4(a3);
  sub_E614(v10, v13, (unsigned __int8)a6 | (HIBYTE(a6) << 8));
  memcpy(&byte_19914, (const void *)a4, 0xCu);
  memcpy(&unk_19920, v10, 4u);
  memcpy(&unk_19924, (const void *)(a4 + 12), a5 - 12);
  n = a5 + 4;
  sub_F2F8(
    7,
    "%s() %d DA=%x:%x:%x:%x:%x:%x SA=%x:%x:%x:%x:%x:%x frame_len = %d\n",
    "frame_send",
    98,
    (unsigned __int8)byte_19914,
    (unsigned __int8)byte_19915,
    (unsigned __int8)byte_19916,
    (unsigned __int8)byte_19917,
    (unsigned __int8)byte_19918,
    (unsigned __int8)byte_19919,
    (unsigned __int8)byte_1991A,
    (unsigned __int8)byte_1991B,
    (unsigned __int8)byte_1991C,
    (unsigned __int8)byte_1991D,
    (unsigned __int8)byte_1991E,
    (unsigned __int8)byte_1991F,
    a5 + 4);
  return write(a1, &byte_19914, n);
}
// 19914: using guessed type char byte_19914;
// 19915: using guessed type char byte_19915;
// 19916: using guessed type char byte_19916;
// 19917: using guessed type char byte_19917;
// 19918: using guessed type char byte_19918;
// 19919: using guessed type char byte_19919;
// 1991A: using guessed type char byte_1991A;
// 1991B: using guessed type char byte_1991B;
// 1991C: using guessed type char byte_1991C;
// 1991D: using guessed type char byte_1991D;
// 1991E: using guessed type char byte_1991E;
// 1991F: using guessed type char byte_1991F;

//----- (0000E8C8) --------------------------------------------------------
ssize_t __fastcall sub_E8C8(int a1, int a2, int a3, int a4, int a5, int a6, __int16 a7)
{
  int v12; // [sp+18h] [bp-14h] BYREF
  int v13; // [sp+1Ch] [bp-10h] BYREF
  ssize_t v14; // [sp+20h] [bp-Ch]
  int i; // [sp+24h] [bp-8h]

  v14 = 0;
  sub_F2F8(7, "%s() %d\n", "Ssc_sendPacket", 158);
  v13 = 0;
  v12 = 0;
  sub_F5A0(a5, &v13);
  sub_F5A0(a6, &v12);
  for ( i = 0; i <= 9; ++i )
  {
    if ( ((1 << i) & a6) != 0 )
      v14 = sub_E6E8(a1, a2, i, a3, a4, 0);
    if ( ((1 << i) & a5) != 0 )
      v14 = sub_E6E8(a1, a2, i, a3, a4, (unsigned __int8)a7 | (HIBYTE(a7) << 8));
  }
  sub_F2F8(6, "%s() len = %d, ret = %d\n", "Ssc_sendPacket", a4, v14);
  return v14;
}

//----- (0000EA28) --------------------------------------------------------
int __fastcall sub_EA28(int a1, int a2, int a3, const void *a4, size_t n, int a6)
{
  ssize_t v11; // [sp+24h] [bp-10h]
  signed int na; // [sp+38h] [bp+4h]

  sub_F2F8(7, "%s() sendBPDU to port %d\n", "Ssc_sendBpduPacket", a3);
  memcpy(byte_19338, off_191BC, 6u);
  if ( a6 )
    bcopy(&unk_191C8, &byte_19338[6], 6u);
  else
    bcopy(&byte_191C0, &byte_19338[6], 6u);
  word_19344 = htons(n + 3);
  byte_19346 = 66;
  byte_19347 = 66;
  byte_19348 = 3;
  bcopy(a4, &unk_19349, n);
  for ( na = n + 17; na <= 59; ++na )
    byte_19338[na] = 0;
  v11 = sub_E6E8(a1, a2, a3, (int)byte_19338, na, 0);
  return sub_F2F8(6, "%s() len = %d, ret = %d\n", "Ssc_sendBpduPacket", na, v11);
}
// 191BC: using guessed type _UNKNOWN *off_191BC;
// 191C0: using guessed type char byte_191C0;
// 19338: using guessed type _BYTE byte_19338[12];
// 19344: using guessed type __int16 word_19344;
// 19346: using guessed type char byte_19346;
// 19347: using guessed type char byte_19347;
// 19348: using guessed type char byte_19348;

//----- (0000EBC4) --------------------------------------------------------
int __fastcall sub_EBC4(int a1, int a2, int a3, int a4, void *src, size_t n, int a7)
{
  int result; // r0
  _BYTE dest[6]; // [sp+34h] [bp-68h] BYREF
  _WORD v13[4]; // [sp+3Ah] [bp-62h] BYREF
  char v14; // [sp+42h] [bp-5Ah]
  char v15; // [sp+43h] [bp-59h]
  char v16; // [sp+44h] [bp-58h]
  _BYTE v17[3]; // [sp+45h] [bp-57h] BYREF
  ssize_t v18; // [sp+8Ch] [bp-10h]
  signed int na; // [sp+A4h] [bp+8h]

  v18 = 0;
  sub_F2F8(
    7,
    "%s() sendBPDU to port %d for ring %d, SA = %x:%x:%x:%x:%x:%x\n",
    "Ssc_sendTR2Packet",
    a4,
    a3,
    (unsigned __int8)byte_191C0,
    (unsigned __int8)byte_191C1,
    (unsigned __int8)byte_191C2,
    (unsigned __int8)byte_191C3,
    (unsigned __int8)byte_191C4,
    (unsigned __int8)byte_191C5);
  result = sub_9814(a4);
  if ( !result )
  {
    if ( a3 )
      memcpy(dest, (const void *)dword_19F8C, sizeof(dest));
    else
      memcpy(dest, (const void *)dword_19F88, sizeof(dest));
    if ( a7 )
      bcopy(&unk_191C8, v13, 6u);
    else
      bcopy(&byte_191C0, v13, 6u);
    v13[3] = htons(n + 3);
    v14 = 66;
    v15 = 66;
    v16 = 3;
    bcopy(src, v17, n);
    for ( na = n + 17; na <= 59; ++na )
      dest[na] = 0;
    v18 = sub_E6E8(a1, a2, a4, (int)dest, na, 0);
    return sub_F2F8(6, "%s() len = %d, ret = %d\n", "Ssc_sendTR2Packet", na, v18);
  }
  return result;
}
// 191C0: using guessed type char byte_191C0;
// 191C1: using guessed type char byte_191C1;
// 191C2: using guessed type char byte_191C2;
// 191C3: using guessed type char byte_191C3;
// 191C4: using guessed type char byte_191C4;
// 191C5: using guessed type char byte_191C5;
// 19F88: using guessed type int dword_19F88;
// 19F8C: using guessed type int dword_19F8C;

//----- (0000EE20) --------------------------------------------------------
char *__fastcall sub_EE20(const char *a1)
{
  sprintf(byte_19F00, "%s/%s", "/proc/moxa", a1);
  return byte_19F00;
}

//----- (0000EE64) --------------------------------------------------------
int __fastcall sub_EE64(int a1, int a2, int a3)
{
  char *v3; // r0
  char s[128]; // [sp+1Ch] [bp-90h] BYREF
  int v8; // [sp+9Ch] [bp-10h]

  v8 = sub_F3E4(a1);
  v3 = sub_EE20("port_speed_set");
  sprintf(s, " echo %x,%x,%x > %s", v8, a2, a3, v3);
  printf("msg = %s\n", s);
  system(s);
  return 0;
}

//----- (0000EEFC) --------------------------------------------------------
int __fastcall sub_EEFC(int a1)
{
  printf("%s() %d >>>>>> %d ms\n", "Ssys_ms2ticks", 28, a1);
  return a1;
}

//----- (0000EF3C) --------------------------------------------------------
int __fastcall sub_EF3C(int a1)
{
  struct timespec remaining; // [sp+10h] [bp-14h] BYREF
  struct timespec requested_time; // [sp+18h] [bp-Ch] BYREF

  requested_time.tv_sec = 0;
  requested_time.tv_nsec = 1000000 * a1;
  return nanosleep(&requested_time, &remaining);
}

//----- (0000EF98) --------------------------------------------------------
__time_t Ssys_current_secs()
{
  int *v0; // r0
  char *v1; // r0
  timespec tp; // [sp+0h] [bp-Ch] BYREF

  if ( clock_gettime(1, &tp) != -1 )
    return tp.tv_sec;
  v0 = _errno_location();
  v1 = strerror(*v0);
  sub_F2F8(3, "%s() error = %s\n", "Ssys_current_secs", v1);
  return -1;
}

//----- (0000F008) --------------------------------------------------------
int Ssys_current_msecs()
{
  int *v0; // r0
  char *v1; // r0
  int v3; // r4
  struct timespec tp; // [sp+0h] [bp-14h] BYREF

  if ( clock_gettime(1, &tp) == -1 )
  {
    v0 = _errno_location();
    v1 = strerror(*v0);
    sub_F2F8(3, "%s() error = %s\n", "Ssys_current_msecs", v1);
    return -1;
  }
  else
  {
    v3 = 1000 * tp.tv_sec;
    return v3 + sub_F880(tp.tv_nsec, 0xF4240u);
  }
}

//----- (0000F0B8) --------------------------------------------------------
int __fastcall sub_F0B8(_DWORD *a1)
{
  int v1; // r4
  int result; // r0
  struct timespec tp; // [sp+8h] [bp-14h] BYREF

  clock_gettime(1, &tp);
  v1 = (1000 * tp.tv_sec) >> 31;
  *a1 = 1000 * tp.tv_sec;
  a1[1] = v1;
  result = sub_F880(tp.tv_nsec, 0x3E8u);
  a1[2] = result;
  return result;
}

//----- (0000F130) --------------------------------------------------------
int __fastcall sub_F130(_DWORD *a1, _DWORD *a2)
{
  return 1000 * (*a2 - *a1) + a2[2] - a1[2];
}

//----- (0000F1AC) --------------------------------------------------------
char *sub_F1AC()
{
  return &byte_191C0;
}
// 191C0: using guessed type char byte_191C0;

//----- (0000F1E0) --------------------------------------------------------
int __fastcall sub_F1E0(unsigned __int8 *a1, int a2)
{
  unsigned int v4; // r4

  v4 = 0;
  while ( a2 > 1 )
  {
    v4 += *a1 | (a1[1] << 8);
    a1 += 2;
    a2 -= 2;
  }
  if ( a2 == 1 )
    v4 += *a1;
  return (unsigned __int16)~(HIWORD(v4) + v4 + ((unsigned int)(HIWORD(v4) + (unsigned __int16)v4) >> 16));
}

//----- (0000F2A0) --------------------------------------------------------
int __fastcall Ssys_UI_port2MdlPort(int a1, _DWORD *a2, int *a3)
{
  if ( a1 > 9 )
    return 0;
  *a2 = 0;
  *a3 = a1;
  return 1;
}

//----- (0000F2F8) --------------------------------------------------------
int sub_F2F8(int result, const char *a2, ...)
{
  va_list varg_r2; // [sp+20h] [bp+8h] BYREF

  va_start(varg_r2, a2);
  if ( result <= dword_19F90 )
    return vfprintf((FILE *)stderr, a2, varg_r2);
  return result;
}
// 19230: using guessed type int stderr;
// 19F90: using guessed type int dword_19F90;

//----- (0000F368) --------------------------------------------------------
int __fastcall sub_F368(int a1)
{
  dword_19F90 = a1;
  return printf("Debug message level set to %d\n", a1);
}
// 19F90: using guessed type int dword_19F90;

//----- (0000F3AC) --------------------------------------------------------
void sub_F3AC()
{
  dword_19F84 = (int)&unk_191D0;
  dword_19F80 = 1;
}
// 19F80: using guessed type int dword_19F80;
// 19F84: using guessed type int dword_19F84;

//----- (0000F3E4) --------------------------------------------------------
int __fastcall sub_F3E4(int a1)
{
  int i; // [sp+Ch] [bp-10h]
  int v5; // [sp+10h] [bp-Ch]

  v5 = -1;
  if ( !dword_19F80 )
    sub_F3AC();
  for ( i = 0; i < dword_19228; ++i )
  {
    if ( *(_DWORD *)(dword_19F84 + 8 * i) == a1 )
    {
      v5 = *(_DWORD *)(dword_19F84 + 8 * i + 4);
      break;
    }
  }
  if ( i == dword_19228 )
    return -1;
  else
    return v5;
}
// 19228: using guessed type int dword_19228;
// 19F80: using guessed type int dword_19F80;
// 19F84: using guessed type int dword_19F84;

//----- (0000F4B0) --------------------------------------------------------
int __fastcall sub_F4B0(int a1)
{
  int i; // [sp+14h] [bp-10h]
  int v5; // [sp+18h] [bp-Ch]

  v5 = -1;
  if ( !dword_19F80 )
    sub_F3AC();
  for ( i = 0; i < dword_19228; ++i )
  {
    if ( *(_DWORD *)(dword_19F84 + 8 * i + 4) == a1 )
    {
      v5 = *(_DWORD *)(dword_19F84 + 8 * i);
      break;
    }
  }
  if ( i == dword_19228 )
    return -1;
  sub_F2F8(7, "%s(): port %d from port %d\n", "spm_getLogicalPortId", v5, a1);
  return v5;
}
// 19228: using guessed type int dword_19228;
// 19F80: using guessed type int dword_19F80;
// 19F84: using guessed type int dword_19F84;

//----- (0000F5A0) --------------------------------------------------------
int __fastcall sub_F5A0(int a1, _DWORD *a2)
{
  int i; // [sp+8h] [bp-14h]
  int v6; // [sp+10h] [bp-Ch]

  if ( !dword_19F80 )
    sub_F3AC();
  v6 = 0;
  for ( i = 0; i < dword_19228; ++i )
  {
    if ( ((1 << *(_DWORD *)(dword_19F84 + 8 * i)) & a1) != 0 )
      v6 |= 1 << *(_DWORD *)(dword_19F84 + 8 * i + 4);
  }
  *a2 = v6;
  return 0;
}
// 19228: using guessed type int dword_19228;
// 19F80: using guessed type int dword_19F80;
// 19F84: using guessed type int dword_19F84;

//----- (0000F688) --------------------------------------------------------
int __fastcall sub_F688(int a1, _DWORD *a2)
{
  int i; // [sp+8h] [bp-14h]
  int v6; // [sp+10h] [bp-Ch]

  if ( !dword_19F80 )
    sub_F3AC();
  v6 = 0;
  for ( i = 0; i < dword_19228; ++i )
  {
    if ( ((1 << *(_DWORD *)(dword_19F84 + 8 * i + 4)) & a1) != 0 )
      v6 |= 1 << *(_DWORD *)(dword_19F84 + 8 * i);
  }
  *a2 = v6;
  return 0;
}
// 19228: using guessed type int dword_19228;
// 19F80: using guessed type int dword_19F80;
// 19F84: using guessed type int dword_19F84;

//----- (0000F770) --------------------------------------------------------
unsigned int __fastcall sub_F770(unsigned int result, unsigned int a2)
{
  unsigned int v2; // r3
  bool v3; // cf
  bool v4; // cf
  int v5; // r2
  bool v6; // zf
  int v7; // r2

  if ( a2 != 1 )
  {
    if ( a2 )
    {
      if ( result <= a2 )
      {
        return result == a2;
      }
      else if ( (a2 & (a2 - 1)) != 0 )
      {
        if ( (a2 & 0xE0000000) != 0 )
        {
          v2 = 1;
        }
        else
        {
          a2 *= 8;
          v2 = 8;
        }
        while ( 1 )
        {
          v3 = a2 >= 0x10000000;
          if ( a2 < 0x10000000 )
            v3 = a2 >= result;
          if ( v3 )
            break;
          a2 *= 16;
          v2 *= 16;
        }
        while ( 1 )
        {
          v4 = a2 >= 0x80000000;
          if ( a2 < 0x80000000 )
            v4 = a2 >= result;
          if ( v4 )
            break;
          a2 *= 2;
          v2 *= 2;
        }
        v5 = 0;
        while ( 1 )
        {
          if ( result >= a2 )
          {
            result -= a2;
            v5 |= v2;
          }
          if ( result >= a2 >> 1 )
          {
            result -= a2 >> 1;
            v5 |= v2 >> 1;
          }
          if ( result >= a2 >> 2 )
          {
            result -= a2 >> 2;
            v5 |= v2 >> 2;
          }
          if ( result >= a2 >> 3 )
          {
            result -= a2 >> 3;
            v5 |= v2 >> 3;
          }
          v6 = result == 0;
          if ( result )
          {
            v2 >>= 4;
            v6 = v2 == 0;
          }
          if ( v6 )
            break;
          a2 >>= 4;
        }
        return v5;
      }
      else
      {
        if ( a2 < 0x10000 )
        {
          v7 = 0;
        }
        else
        {
          a2 >>= 16;
          v7 = 16;
        }
        if ( a2 >= 0x100 )
        {
          a2 >>= 8;
          v7 += 8;
        }
        if ( a2 >= 0x10 )
        {
          a2 >>= 4;
          v7 += 4;
        }
        if ( a2 <= 4 )
          v7 += a2 >> 1;
        else
          LOBYTE(v7) = v7 + 3;
        result >>= v7;
      }
    }
    else
    {
      sub_F9C0();
      return 0;
    }
  }
  return result;
}

//----- (0000F868) --------------------------------------------------------
unsigned int __fastcall sub_F868(unsigned int a1, unsigned int a2)
{
  return sub_F770(a1, a2);
}

//----- (0000F880) --------------------------------------------------------
int __fastcall sub_F880(int result, unsigned int a2)
{
  int v2; // r12
  unsigned int v3; // r3
  unsigned int v4; // r2
  bool v5; // cf
  bool v6; // cf
  bool v7; // zf
  int v8; // r2

  v2 = result ^ a2;
  if ( a2 )
  {
    if ( (a2 & 0x80000000) != 0 )
      a2 = -a2;
    if ( a2 == 1 )
    {
      if ( (v2 ^ result) < 0 )
        return -result;
    }
    else
    {
      v3 = result;
      if ( result < 0 )
        v3 = -result;
      if ( v3 <= a2 )
      {
        if ( v3 < a2 )
          result = 0;
        if ( v3 == a2 )
          return (v2 >> 31) | 1;
      }
      else if ( (a2 & (a2 - 1)) != 0 )
      {
        if ( (a2 & 0xE0000000) != 0 )
        {
          v4 = 1;
        }
        else
        {
          a2 *= 8;
          v4 = 8;
        }
        while ( 1 )
        {
          v5 = a2 >= 0x10000000;
          if ( a2 < 0x10000000 )
            v5 = a2 >= v3;
          if ( v5 )
            break;
          a2 *= 16;
          v4 *= 16;
        }
        while ( 1 )
        {
          v6 = a2 >= 0x80000000;
          if ( a2 < 0x80000000 )
            v6 = a2 >= v3;
          if ( v6 )
            break;
          a2 *= 2;
          v4 *= 2;
        }
        result = 0;
        while ( 1 )
        {
          if ( v3 >= a2 )
          {
            v3 -= a2;
            result |= v4;
          }
          if ( v3 >= a2 >> 1 )
          {
            v3 -= a2 >> 1;
            result |= v4 >> 1;
          }
          if ( v3 >= a2 >> 2 )
          {
            v3 -= a2 >> 2;
            result |= v4 >> 2;
          }
          if ( v3 >= a2 >> 3 )
          {
            v3 -= a2 >> 3;
            result |= v4 >> 3;
          }
          v7 = v3 == 0;
          if ( v3 )
          {
            v4 >>= 4;
            v7 = v4 == 0;
          }
          if ( v7 )
            break;
          a2 >>= 4;
        }
        if ( v2 < 0 )
          return -result;
      }
      else
      {
        if ( a2 < 0x10000 )
        {
          v8 = 0;
        }
        else
        {
          a2 >>= 16;
          v8 = 16;
        }
        if ( a2 >= 0x100 )
        {
          a2 >>= 8;
          v8 += 8;
        }
        if ( a2 >= 0x10 )
        {
          a2 >>= 4;
          v8 += 4;
        }
        if ( a2 <= 4 )
          v8 += a2 >> 1;
        else
          LOBYTE(v8) = v8 + 3;
        result = v3 >> v8;
        if ( v2 < 0 )
          return -result;
      }
    }
  }
  else
  {
    sub_F9C0();
    return 0;
  }
  return result;
}

//----- (0000F9A8) --------------------------------------------------------
int __fastcall sub_F9A8(int a1, unsigned int a2)
{
  return sub_F880(a1, a2);
}

//----- (0000F9C0) --------------------------------------------------------
int sub_F9C0()
{
  return raise(8);
}

//----- (0000F9D4) --------------------------------------------------------
void init(void)
{
  init_proc();
}

//----- (0000FA3C) --------------------------------------------------------
int sub_FA3C()
{
  int (*v0)(void); // r3
  _UNKNOWN **v1; // r4
  int result; // r0
  int (*v3)(void); // t1

  v0 = (int (*)(void))off_19000;
  if ( off_19000 != (_UNKNOWN *)-1 )
  {
    v1 = &off_19000;
    do
    {
      result = v0();
      v3 = (int (*)(void))*--v1;
      v0 = v3;
    }
    while ( v3 != (int (*)(void))-1 );
  }
  return result;
}
// 19000: using guessed type _UNKNOWN *off_19000;

//----- (0000FA70) --------------------------------------------------------
void sub_FA70()
{
  ;
}

//----- (0000FA78) --------------------------------------------------------
int term_proc()
{
  return sub_8D04();
}

// nfuncs=196 queued=129 decompiled=129 lumina nreq=0 worse=0 better=0
// ALL OK, 129 function(s) have been successfully decompiled
