/* This file was generated by the Hex-Rays decompiler version 9.1.0.250226.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>

#include <stdarg.h>


//-------------------------------------------------------------------------
// Function declarations

int init_proc();
void sub_8B54();
// void abort(void);
// int *_errno_location(void);
// int __fastcall _deregister_frame_info(_DWORD); weak
// int sprintf(char *s, const char *format, ...);
// FILE *popen(const char *command, const char *modes);
// int open(const char *file, int oflag, ...);
// char *strerror(int errnum);
// int _xstat(int ver, const char *filename, struct stat *stat_buf);
// int _gmon_start__(void); weak
// int system(const char *command);
// ssize_t write(int fd, const void *buf, size_t n);
// char *fgets(char *s, int n, FILE *stream);
// int __fastcall _register_frame_info(_DWORD, _DWORD); weak
// void *memset(void *s, int c, size_t n);
// int _libc_start_main(int (*main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// uint16_t htons(uint16_t hostshort);
// ssize_t read(int fd, void *buf, size_t nbytes);
// void perror(const char *s);
// int ioctl(int fd, unsigned int request, ...);
// int pthread_mutex_unlock(pthread_mutex_t *mutex);
// void bcopy(const void *src, void *dest, size_t n);
// int nanosleep(const struct timespec *requested_time, struct timespec *remaining);
// void *memcpy(void *dest, const void *src, size_t n);
// int __fastcall shm_init(_DWORD); weak
// int printf(const char *format, ...);
// int raise(int sig);
// int atoi(const char *nptr);
// int clock_gettime(clockid_t clock_id, struct timespec *tp);
// int __fastcall shm_set_fast_bootup_state(_DWORD); weak
// int close(int fd);
// int fprintf(FILE *stream, const char *format, ...);
// int pthread_mutex_lock(pthread_mutex_t *mutex);
// int __fastcall Get_Mac(_DWORD); weak
// int puts(const char *s);
// int vfprintf(FILE *s, const char *format, __gnuc_va_list arg);
// int __fastcall Semaphore_init(_DWORD); weak
// int pclose(FILE *stream);
void __noreturn start(void (*a1)(void), int a2, int a3, int a4, ...);
int sub_8D60();
int sub_8D84();
void sub_8E0C();
int *sub_8E14();
void sub_8E68();
int sub_8E70();
void __fastcall sub_9000(int *a1);
void __fastcall sub_913C(void *a1);
int sub_9170();
int sub_919C();
int __fastcall main(int a1, char **a2, char **a3); // idb
int sub_935C();
int sub_93F0();
int __fastcall sub_9424(int a1, int a2, _DWORD *a3);
int __fastcall sub_9534(int a1, int a2, int a3);
int __fastcall sub_9638(int a1, int a2, _DWORD *a3);
int __fastcall sub_973C(int a1, int a2, int a3);
int __fastcall sub_9834(int a1);
int __fastcall sub_98C4(int a1);
int __fastcall sub_9990(int a1, _DWORD *a2);
int __fastcall sub_9A80(int a1, int a2);
int __fastcall sub_9B90(int a1);
int __fastcall sub_9C64(int a1);
int sub_9D24();
int sub_9DC0();
int __fastcall sub_9E5C(int a1, int a2);
int __fastcall sub_9F48(int a1, int a2);
int __fastcall sub_A034(int a1, int a2);
int __fastcall sub_A120(int a1, int a2);
int __fastcall sub_A20C(int a1, int a2);
int __fastcall sub_A2F0(int a1, const char *a2);
int __fastcall sub_A3FC(int a1, int a2);
int __fastcall sub_A4E8(int a1, const char *a2);
int __fastcall sub_A5F8(int a1, int a2);
int __fastcall sub_A6E4(int a1, const char *a2);
int __fastcall sub_A7F4(int a1);
int __fastcall sub_A8F0(int a1, int a2, int a3);
int __fastcall sub_AA84(int a1, int a2);
int __fastcall Ssc_getPortLinkState(_DWORD *a1);
int __fastcall sub_AD14(int a1);
void *__fastcall Ssc_getPortStatsCounter(void *a1, int a2);
int __fastcall sub_AF00(_DWORD *a1);
int __fastcall sub_AF4C(int a1);
int __fastcall sub_AF94(int a1);
int __fastcall sub_B094(int a1);
int sub_B158();
int __fastcall sub_B228(const void *a1, _DWORD *a2);
int __fastcall sub_B354(const void *a1, void *a2);
int __fastcall sub_B54C(const void *a1, void *a2);
int __fastcall sub_B744(_DWORD *a1);
int __fastcall sub_B82C(char *a1, size_t a2, int a3);
int __fastcall sub_BFE0(const void *a1, char a2, int a3);
int __fastcall sub_C110(const void *a1, int a2, int a3);
int sub_C268();
int sub_C2C0();
int sub_C318();
int __fastcall sub_C33C(int a1, const void *a2, int a3);
int __fastcall sub_C394(int a1, const void *a2, int a3);
int __fastcall sub_C400(int a1, const void *a2);
int __fastcall sub_C458(int a1);
int __fastcall sub_C53C(int a1, int a2);
int __fastcall sub_C64C(_DWORD *a1, int a2);
int __fastcall sub_C78C(_DWORD *a1, unsigned __int8 a2, int a3, int a4);
int __fastcall sub_C90C(_DWORD *a1, int a2, int a3);
int __fastcall sub_CA58(_DWORD *a1, int a2, int a3);
void sub_CBB4();
int __fastcall sub_CBC8(int a1);
int __fastcall sub_CC94(int result);
int __fastcall sub_CD10(int result);
int __fastcall sub_CD8C(int a1, int a2);
int __fastcall sub_CE6C(int a1, int a2);
int __fastcall sub_CF4C(int a1, int a2);
int __fastcall sub_D058(int a1);
int __fastcall sub_D160(int a1, int a2, const void *a3);
void sub_D278();
int __fastcall sub_D294(int a1, _DWORD *a2, _DWORD *a3);
int __fastcall sub_D3E0(int a1, int a2);
int sub_D5AC();
int sub_D6A4();
int sub_D7D0();
void sub_D904();
int __fastcall sub_D918(const void *a1, int a2, int a3);
int __fastcall sub_DA48(const void *a1, __int16 a2);
int __fastcall sub_DB88(int a1);
int sub_DC54();
int __fastcall sub_DD10(int a1, int a2);
int __fastcall sub_DE18(int a1, int a2);
int __fastcall sub_DF20(int a1, int a2);
int __fastcall sub_E000(int a1, int a2);
int __fastcall sub_E0E0(int a1, int a2);
int __fastcall sub_E1C0(int a1);
int __fastcall sub_E294(int a1);
int __fastcall sub_E360(int a1);
int __fastcall sub_E434(int a1);
int __fastcall sub_E500(int a1);
int __fastcall sub_E5D4(unsigned __int8 *a1, int *a2, _DWORD *a3);
_BYTE *__fastcall sub_E6C4(_BYTE *result, char a2, __int16 a3);
ssize_t __fastcall sub_E798(int a1, int a2, int a3, int a4, int a5, __int16 a6);
ssize_t __fastcall sub_E978(int a1, int a2, int a3, int a4, int a5, int a6, __int16 a7);
int __fastcall sub_EAD8(int a1, int a2, int a3, const void *a4, size_t n, int a6);
int __fastcall sub_EC74(int a1, int a2, int a3, int a4, void *src, size_t n, int a7); // idb
char *__fastcall sub_EED0(const char *a1);
int __fastcall sub_EF14(int a1, int a2, int a3);
int __fastcall sub_EFAC(int a1);
int __fastcall sub_EFEC(int a1);
__time_t Ssys_current_secs();
int Ssys_current_msecs();
int __fastcall sub_F168(_DWORD *a1);
int __fastcall sub_F1E0(_DWORD *a1, _DWORD *a2);
char *sub_F25C();
int __fastcall sub_F290(unsigned __int8 *a1, int a2);
int __fastcall Ssys_UI_port2MdlPort(int a1, _DWORD *a2, int *a3);
int sub_F3A8(int result, const char *a2, ...);
int __fastcall sub_F418(int a1);
void sub_F45C();
int __fastcall sub_F494(int a1);
int __fastcall sub_F560(int a1);
int __fastcall sub_F650(int a1, _DWORD *a2);
int __fastcall sub_F738(int a1, _DWORD *a2);
unsigned int __fastcall sub_F820(unsigned int result, unsigned int a2);
unsigned int __fastcall sub_F918(unsigned int a1, unsigned int a2);
int __fastcall sub_F930(int result, unsigned int a2);
int __fastcall sub_FA58(int a1, unsigned int a2);
int sub_FA70();
int nullsub_1(); // weak
void init(void); // idb
int __fastcall sub_FAEC(char *filename, struct stat *stat_buf); // idb
int sub_FAFC();
void sub_FB30();
int term_proc();

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN unk_10B44; // weak
_UNKNOWN *off_19000 = (_UNKNOWN *)0xFFFFFFFF; // weak
int dword_19008[] = { -1 }; // weak
int dword_1900C = 0; // weak
int dword_19010 = 0; // weak
char *off_191E0 = "/mnt/ramdisk/cfg"; // weak
_UNKNOWN *off_19268 = &unk_19260; // weak
char byte_1926C = '\0'; // weak
char byte_1926D = '\x90'; // weak
char byte_1926E = '\xE8'; // weak
char byte_1926F = '\x05'; // weak
char byte_19270 = '\0'; // weak
char byte_19271 = '\b'; // weak
_UNKNOWN unk_19274; // weak
_UNKNOWN unk_1927C; // weak
int dword_192D4 = 11; // weak
int stderr; // weak
char byte_192E4; // weak
int dword_192E8; // weak
_UNKNOWN unk_192EC; // weak
int dword_19308; // weak
int dword_1930C; // weak
int dword_19314; // weak
pthread_mutex_t mutex; // idb
_UNKNOWN unk_19330; // weak
_UNKNOWN unk_19334; // weak
int dword_19338; // weak
_BYTE byte_19340[12]; // weak
__int16 word_1934C; // weak
char byte_1934E; // weak
char byte_1934F; // weak
char byte_19350; // weak
_UNKNOWN unk_19351; // weak
char byte_1991C; // weak
char byte_1991D; // weak
char byte_1991E; // weak
char byte_1991F; // weak
char byte_19920; // weak
char byte_19921; // weak
char byte_19922; // weak
char byte_19923; // weak
char byte_19924; // weak
char byte_19925; // weak
char byte_19926; // weak
char byte_19927; // weak
_UNKNOWN unk_19928; // weak
_UNKNOWN unk_1992C; // weak
char byte_19F08[128]; // idb
int dword_19F88; // weak
int dword_19F8C; // weak
int dword_19F90; // weak
int dword_19F94; // weak
int dword_19F98; // weak
// extern _UNKNOWN __gmon_start__; weak


//----- (00008B40) --------------------------------------------------------
int init_proc()
{
  sub_8D60();
  sub_8E14();
  return sub_FAFC();
}

//----- (00008B54) --------------------------------------------------------
void sub_8B54()
{
  JUMPOUT(0);
}
// 8B60: control flows out of bounds to 0

//----- (00008D24) --------------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __noreturn start(void (*a1)(void), int a2, int a3, int a4, ...)
{
  int v4; // [sp-4h] [bp-4h]
  va_list va; // [sp+0h] [bp+0h] BYREF

  va_start(va, a4);
  _libc_start_main(main, v4, (char **)va, init, (void (*)(void))nullsub_1, a1, va);
  abort();
}
// 8D30: positive sp value 4 has been found
// 8D4C: variable 'v4' is possibly undefined
// FA80: using guessed type int nullsub_1();

//----- (00008D60) --------------------------------------------------------
int sub_8D60()
{
  int result; // r0

  if ( &__gmon_start__ )
    return _gmon_start__();
  return result;
}
// 8BC8: using guessed type int _gmon_start__(void);

//----- (00008D84) --------------------------------------------------------
int sub_8D84()
{
  int v0; // r3
  unsigned int i; // r6
  int result; // r0

  if ( !byte_192E4 )
  {
    v0 = dword_192E8;
    for ( i = &dword_1900C - dword_19008 - 1; dword_192E8 < i; v0 = dword_192E8 )
    {
      dword_192E8 = v0 + 1;
      result = ((int (*)(void))dword_19008[v0 + 1])();
    }
    if ( _deregister_frame_info )
      result = _deregister_frame_info(&unk_10B44);
    byte_192E4 = 1;
  }
  return result;
}
// 8B80: using guessed type int __fastcall _deregister_frame_info(_DWORD);
// 19008: using guessed type int dword_19008[];
// 1900C: using guessed type int dword_1900C;
// 192E4: using guessed type char byte_192E4;
// 192E8: using guessed type int dword_192E8;

//----- (00008E0C) --------------------------------------------------------
void sub_8E0C()
{
  ;
}

//----- (00008E14) --------------------------------------------------------
int *sub_8E14()
{
  if ( _register_frame_info )
    _register_frame_info(&unk_10B44, &unk_192EC);
  return &dword_19010;
}
// 8BF8: using guessed type int __fastcall _register_frame_info(_DWORD, _DWORD);
// 19010: using guessed type int dword_19010;

//----- (00008E68) --------------------------------------------------------
void sub_8E68()
{
  ;
}

//----- (00008E70) --------------------------------------------------------
int sub_8E70()
{
  char s[128]; // [sp+90h] [bp-B4h] BYREF
  char v2[8]; // [sp+110h] [bp-34h] BYREF
  int v3; // [sp+118h] [bp-2Ch]
  int v4; // [sp+11Ch] [bp-28h]
  char v5[12]; // [sp+120h] [bp-24h] BYREF
  int v6; // [sp+12Ch] [bp-18h]
  int v7; // [sp+138h] [bp-Ch]

  v3 = 0;
  v4 = 0;
  strcpy(v2, "router");
  v2[7] = 0;
  strcpy(v5, "transparent");
  v6 = 0;
  v7 = 0;
  sprintf(s, "tar %s %s/%s/%s.%s -C /", "-zxf", "/mnt/cfg2", v2, "FAST_BOOTUP_SETTING.CFG", "gzip");
  return system(s);
}

//----- (00009000) --------------------------------------------------------
void __fastcall sub_9000(int *a1)
{
  char nptr[32]; // [sp+8h] [bp-104h] BYREF
  char s[128]; // [sp+28h] [bp-E4h] BYREF
  stat stat_buf; // [sp+A8h] [bp-64h] BYREF
  FILE *stream; // [sp+104h] [bp-8h]

  sprintf(s, "%s/%s", "/mnt/ramdisk/cfg", "FAST_BOOTUP_SETTING.CFG");
  if ( sub_FAEC(s, &stat_buf) >= 0 )
  {
    sprintf(
      s,
      "cat %s/%s |grep '$fast_bootup\\[0\\]' |  grep '$enable\\[0\\]' | awk 'BEGIN {FS=\"\\\"\"}; {print $2}'",
      "/mnt/ramdisk/cfg",
      "FAST_BOOTUP_SETTING.CFG");
    stream = popen(s, "r");
    if ( stream )
    {
      memset(nptr, 0, sizeof(nptr));
      fgets(nptr, 32, stream);
      pclose(stream);
      if ( (unsigned int)(unsigned __int8)nptr[0] - 48 > 9 )
        *a1 = 0;
      else
        *a1 = atoi(nptr);
    }
    else
    {
      perror("popen error");
      *a1 = 0;
    }
  }
  else
  {
    *a1 = 0;
  }
}

//----- (0000913C) --------------------------------------------------------
void __fastcall sub_913C(void *a1)
{
  memset(a1, 0, 8u);
  sub_8E70();
  sub_9000((int *)a1);
}

//----- (00009170) --------------------------------------------------------
int sub_9170()
{
  _BYTE v1[268]; // [sp+0h] [bp-10Ch] BYREF

  sub_913C(v1);
  return shm_set_fast_bootup_state(v1);
}
// 8CB8: using guessed type int __fastcall shm_set_fast_bootup_state(_DWORD);

//----- (0000919C) --------------------------------------------------------
int sub_919C()
{
  int result; // r0
  char s[64]; // [sp+4h] [bp-48h] BYREF
  unsigned int i; // [sp+44h] [bp-8h]

  sprintf(s, "rm -r %s", "/mnt/ramdisk/cfg");
  result = system(s);
  for ( i = 0; i <= 0xF; ++i )
  {
    sprintf(s, "mkdir -p %s/%s", (&off_191E0)[2 * i + 1], (&off_191E0)[2 * i]);
    system(s);
    result = printf("msg = %s\n", s);
  }
  return result;
}
// 191E0: using guessed type char *off_191E0;

//----- (00009260) --------------------------------------------------------
int __fastcall main(int a1, char **a2, char **a3)
{
  int v3; // r0
  char s[128]; // [sp+8h] [bp-ECh] BYREF
  struct stat stat_buf; // [sp+88h] [bp-6Ch] BYREF
  _BYTE v7[8]; // [sp+E0h] [bp-14h] BYREF
  int v8; // [sp+E8h] [bp-Ch]
  int v9; // [sp+ECh] [bp-8h]

  v9 = 0;
  sprintf(s, "/%s/%s", "/mnt/ramdisk", "moxa_sysinit");
  if ( sub_FAEC(s, &stat_buf) < 0 )
  {
    sprintf(s, "echo 1 > /%s/%s", "/mnt/ramdisk", "moxa_sysinit");
    system(s);
    sub_919C();
    v8 = 0;
    Get_Mac(v7);
    v8 = 0x4000;
    sub_BFE0(v7, 0, 0x4000);
    sub_CF4C(14, 1);
    v3 = Semaphore_init(1492);
    shm_init(v3);
    sub_9170();
  }
  return 0;
}
// 8C7C: using guessed type int __fastcall shm_init(_DWORD);
// 8CE8: using guessed type int __fastcall Get_Mac(_DWORD);
// 8D0C: using guessed type int __fastcall Semaphore_init(_DWORD);

//----- (0000935C) --------------------------------------------------------
int sub_935C()
{
  dword_19308 = 0;
  if ( dword_1930C )
    return dword_1930C;
  dword_1930C = open("/dev/eth_switch", 2);
  if ( dword_1930C >= 0 )
    return dword_1930C;
  perror("open");
  dword_1930C = 0;
  return -1;
}
// 19308: using guessed type int dword_19308;
// 1930C: using guessed type int dword_1930C;

//----- (000093F0) --------------------------------------------------------
int sub_93F0()
{
  close(dword_1930C);
  dword_1930C = 0;
  return 0;
}
// 1930C: using guessed type int dword_1930C;

//----- (00009424) --------------------------------------------------------
int __fastcall sub_9424(int a1, int a2, _DWORD *a3)
{
  int v4; // r0
  _BYTE v9[4]; // [sp+18h] [bp-214h] BYREF
  int v10; // [sp+1Ch] [bp-210h] BYREF
  int fd; // [sp+21Ch] [bp-10h]
  int v12; // [sp+220h] [bp-Ch]
  int *v13; // [sp+224h] [bp-8h]

  v12 = 1;
  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  v9[0] = 1;
  v9[2] = 12;
  v9[3] = 0;
  v13 = &v10;
  v4 = sub_F494(a1);
  *v13 = v4;
  v13[1] = a2;
  if ( ioctl(fd, 0x82044700, v9) < 0 )
    sub_F3A8(3, "ioctl READ_REG_IOCTL error\n");
  sub_F3A8(6, "port %d, REG 0x%x => 0x%x\n", a1, a2, v13[2]);
  *a3 = v13[2];
  return v12;
}

//----- (00009534) --------------------------------------------------------
int __fastcall sub_9534(int a1, int a2, int a3)
{
  int v4; // r0
  _BYTE v9[4]; // [sp+18h] [bp-214h] BYREF
  int v10; // [sp+1Ch] [bp-210h] BYREF
  int fd; // [sp+21Ch] [bp-10h]
  int v12; // [sp+220h] [bp-Ch]
  int *v13; // [sp+224h] [bp-8h]

  v12 = 1;
  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  v9[0] = 1;
  v9[2] = 12;
  v9[3] = 0;
  v13 = &v10;
  v4 = sub_F494(a1);
  *v13 = v4;
  v13[1] = a2;
  v13[2] = a3;
  if ( ioctl(fd, 0x42044701u, v9) < 0 )
    sub_F3A8(3, "ioctl WRITE_REG_IOCTL error\n");
  sub_F3A8(6, "port %d, REG 0x%x , VAL = 0x%x\n", a1, a2, a3);
  return v12;
}

//----- (00009638) --------------------------------------------------------
int __fastcall sub_9638(int a1, int a2, _DWORD *a3)
{
  _BYTE v8[4]; // [sp+18h] [bp-214h] BYREF
  _DWORD v9[128]; // [sp+1Ch] [bp-210h] BYREF
  int fd; // [sp+21Ch] [bp-10h]
  int v11; // [sp+220h] [bp-Ch]
  _DWORD *v12; // [sp+224h] [bp-8h]

  v11 = 1;
  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  v8[0] = 0;
  v8[2] = 12;
  v8[3] = 0;
  v12 = v9;
  v9[0] = a1;
  v9[1] = a2;
  if ( ioctl(fd, 0x82044700, v8) < 0 )
    sub_F3A8(3, "ioctl READ_REG_IOCTL error\n");
  sub_F3A8(6, "PHY 0x%x, REG 0x%x => 0x%x\n", a1, a2, v12[2]);
  *a3 = v12[2];
  return v11;
}

//----- (0000973C) --------------------------------------------------------
int __fastcall sub_973C(int a1, int a2, int a3)
{
  _BYTE v8[4]; // [sp+18h] [bp-214h] BYREF
  _DWORD v9[128]; // [sp+1Ch] [bp-210h] BYREF
  int fd; // [sp+21Ch] [bp-10h]
  int v11; // [sp+220h] [bp-Ch]
  _DWORD *v12; // [sp+224h] [bp-8h]

  v11 = 1;
  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  v8[0] = 0;
  v8[2] = 12;
  v8[3] = 0;
  v12 = v9;
  v9[0] = a1;
  v9[1] = a2;
  v9[2] = a3;
  if ( ioctl(fd, 0x42044701u, v8) < 0 )
    sub_F3A8(3, "ioctl WRITE_REG_IOCTL error\n");
  sub_F3A8(6, "PHY 0x%x, REG 0x%x , VAL = 0x%x\n", a1, a2, a3);
  return v11;
}

//----- (00009834) --------------------------------------------------------
int __fastcall sub_9834(int a1)
{
  if ( ((1 << a1) & dword_19308) != 0 )
  {
    sub_F3A8(7, "%s() %d vport = %d isGiga\n", "Ssc_isGigaCopperLink", 184, a1);
    return 1;
  }
  else
  {
    sub_F3A8(7, "%s() %d vport = %d notGiga\n", "Ssc_isGigaCopperLink", 188, a1);
    return 0;
  }
}
// 19308: using guessed type int dword_19308;

//----- (000098C4) --------------------------------------------------------
int __fastcall sub_98C4(int a1)
{
  char v2; // r0
  int v5; // [sp+Ch] [bp-10h] BYREF
  int fd; // [sp+10h] [bp-Ch]
  int v7; // [sp+14h] [bp-8h]

  v7 = 1;
  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  if ( ioctl(fd, 0x8004470A, &v5) < 0 )
    sub_F3A8(3, "ioctl ETHSW_LINK_STATUS_GET error\n");
  v2 = sub_F494(a1);
  if ( ((1 << v2) & v5) != 0 )
    v7 = 0;
  sub_F3A8(7, "port %d isDown = %d\n", a1, v7);
  return v7;
}

//----- (00009990) --------------------------------------------------------
int __fastcall sub_9990(int a1, _DWORD *a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 1;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_F494(a1);
  *v8 = v3;
  if ( ioctl(fd, 0x82044702, s) >= 0 )
  {
    *a2 = v8[1];
    return 0;
  }
  else
  {
    sub_F3A8(3, "%s() ioctl error\n", "Ssc_port_speed_get");
    return -1;
  }
}

//----- (00009A80) --------------------------------------------------------
int __fastcall sub_9A80(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+14h] [bp-210h] BYREF
  int *v8; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  sub_F3A8(7, "%s() %d >>>>>>> port %d %d\n", "Ssc_port_speed_set", 266, a1, a2);
  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 1;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_F494(a1);
  *v8 = v3;
  v8[1] = a2;
  if ( ioctl(fd, 0x42044703u, s) < 0 )
    sub_F3A8(3, "%s() ioctl error\n", "Ssc_port_speed_set");
  return 0;
}

//----- (00009B90) --------------------------------------------------------
int __fastcall sub_9B90(int a1)
{
  int v2; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v6; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 7;
  s[2] = 8;
  s[3] = 0;
  v6 = (int *)&s[4];
  v2 = sub_F494(a1);
  *v6 = v2;
  if ( ioctl(fd, 0x42044703u, s) < 0 )
    sub_F3A8(3, "%s() ioctl error\n", "Ssc_port_learing_disable");
  return 0;
}

//----- (00009C64) --------------------------------------------------------
int __fastcall sub_9C64(int a1)
{
  int v2; // r0
  _BYTE v5[4]; // [sp+Ch] [bp-210h] BYREF
  int v6; // [sp+10h] [bp-20Ch] BYREF
  int *v7; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  v5[0] = 8;
  v5[2] = 8;
  v5[3] = 0;
  v7 = &v6;
  v2 = sub_F494(a1);
  *v7 = v2;
  if ( ioctl(fd, 0x42044703u, v5) < 0 )
    sub_F3A8(3, "%s() ioctl error\n", "Ssc_port_learing_enable");
  return 0;
}

//----- (00009D24) --------------------------------------------------------
int sub_9D24()
{
  _BYTE v2[516]; // [sp+4h] [bp-210h] BYREF
  int fd; // [sp+208h] [bp-Ch]

  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  v2[0] = 9;
  v2[2] = 8;
  v2[3] = 0;
  if ( ioctl(fd, 0x42044703u, v2) < 0 )
    sub_F3A8(3, "%s() ioctl error\n", "Ssc_cpuport_learing_disable");
  return 0;
}

//----- (00009DC0) --------------------------------------------------------
int sub_9DC0()
{
  _BYTE v2[520]; // [sp+4h] [bp-210h] BYREF
  int fd; // [sp+20Ch] [bp-8h]

  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  v2[0] = 10;
  v2[2] = 8;
  v2[3] = 0;
  if ( ioctl(fd, 0x42044703u, v2) < 0 )
    sub_F3A8(3, "%s() ioctl error\n", "Ssc_cpuport_learing_enable");
  return 0;
}

//----- (00009E5C) --------------------------------------------------------
int __fastcall sub_9E5C(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 2;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_F494(a1);
  *v8 = v3;
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_F3A8(3, "%s() ioctl error\n", "Ssc_port_duplex_get");
  *(_DWORD *)a2 = v8[1];
  return *(_DWORD *)a2;
}

//----- (00009F48) --------------------------------------------------------
int __fastcall sub_9F48(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 11;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_F494(a1);
  *v8 = v3;
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_F3A8(3, "%s() ioctl error\n", "Ssc_port_qinq_get");
  *(_DWORD *)a2 = v8[1];
  return *(_DWORD *)a2;
}

//----- (0000A034) --------------------------------------------------------
int __fastcall sub_A034(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 12;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_F494(a1);
  *v8 = v3;
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_F3A8(3, "%s() ioctl error\n", "Ssc_port_egress_get");
  *(_DWORD *)a2 = v8[1];
  return *(_DWORD *)a2;
}

//----- (0000A120) --------------------------------------------------------
int __fastcall sub_A120(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 13;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_F494(a1);
  *v8 = v3;
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_F3A8(3, "%s() ioctl error\n", "Ssc_port_802dot1q_mode_get");
  *(_DWORD *)a2 = v8[1];
  return *(_DWORD *)a2;
}

//----- (0000A20C) --------------------------------------------------------
int __fastcall sub_A20C(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+8h] [bp-214h] BYREF
  int v8; // [sp+20Ch] [bp-10h]
  int *v9; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 13;
  s[2] = 8;
  s[3] = 0;
  v9 = (int *)&s[4];
  v3 = sub_F494(a1);
  *v9 = v3;
  v9[1] = a2;
  if ( ioctl(fd, 0x42044703u, s) < 0 )
    sub_F3A8(3, "%s() ioctl error\n", "Ssc_port_802dot1q_mode_set");
  return v8;
}

//----- (0000A2F0) --------------------------------------------------------
int __fastcall sub_A2F0(int a1, const char *a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+14h] [bp-210h] BYREF
  int *v8; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  sub_F3A8(7, "%s() %d >>>>>>> port %d %s\n", "Ssc_port_duplex_set", 548, a1, a2);
  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 2;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_F494(a1);
  *v8 = v3;
  v8[1] = (int)a2;
  if ( ioctl(fd, 0x42044703u, s) < 0 )
    sub_F3A8(3, "%s() ioctl error\n", "Ssc_port_duplex_set");
  return 0;
}

//----- (0000A3FC) --------------------------------------------------------
int __fastcall sub_A3FC(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 4;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_F494(a1);
  *v8 = v3;
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_F3A8(3, "%s() ioctl error\n", "Ssc_port_pause_get");
  *(_DWORD *)a2 = v8[1];
  return *(_DWORD *)a2;
}

//----- (0000A4E8) --------------------------------------------------------
int __fastcall sub_A4E8(int a1, const char *a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+14h] [bp-210h] BYREF
  int *v8; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  sub_F3A8(7, "%s() %d >>>>>>> port %d %s\n", "Ssc_port_pause_set", 619, a1, a2);
  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 4;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_F494(a1);
  *v8 = v3;
  v8[1] = (int)a2;
  if ( ioctl(fd, 0x42044703u, s) < 0 )
    sub_F3A8(3, "%s() ioctl error\n", "Ssc_port_pause_set");
  return 0;
}

//----- (0000A5F8) --------------------------------------------------------
int __fastcall sub_A5F8(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 3;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_F494(a1);
  *v8 = v3;
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_F3A8(3, "%s() ioctl error\n", "Ssc_port_mdi_get");
  *(_DWORD *)a2 = v8[1];
  return *(_DWORD *)a2;
}

//----- (0000A6E4) --------------------------------------------------------
int __fastcall sub_A6E4(int a1, const char *a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+14h] [bp-210h] BYREF
  int *v8; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  sub_F3A8(7, "%s() %d >>>>>>> port %d %s\n", "Ssc_port_mdi_set", 689, a1, a2);
  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 3;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_F494(a1);
  *v8 = v3;
  v8[1] = (int)a2;
  if ( ioctl(fd, 0x42044703u, s) < 0 )
    sub_F3A8(3, "%s() ioctl SET_PORT_STATE error\n", "Ssc_port_mdi_set");
  return 0;
}

//----- (0000A7F4) --------------------------------------------------------
int __fastcall sub_A7F4(int a1)
{
  int v2; // r0
  _BYTE s[516]; // [sp+14h] [bp-210h] BYREF
  int *v6; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 1;
  s[2] = 8;
  s[3] = 0;
  v6 = (int *)&s[4];
  v2 = sub_F494(a1);
  *v6 = v2;
  if ( ioctl(fd, 0x82044708, s) < 0 )
    sub_F3A8(3, "ioctl GET_PORT_STATE error\n");
  sub_F3A8(5, "%s() Port %d state = %d\n", "Ssc_getPortState", *v6, v6[1]);
  return v6[1];
}

//----- (0000A8F0) --------------------------------------------------------
int __fastcall sub_A8F0(int a1, int a2, int a3)
{
  int result; // r0
  int v4; // r0
  char v5; // [sp+14h] [bp-220h]
  int v6; // [sp+18h] [bp-21Ch]
  _BYTE s[516]; // [sp+24h] [bp-210h] BYREF
  int *v9; // [sp+228h] [bp-Ch]
  int fd; // [sp+22Ch] [bp-8h]

  v6 = a2;
  v5 = a3;
  sub_F3A8(5, "%s() %d >>>>>> port %d state %d, flags = 0x%02x\n", "Ssc_setPortState", 772, a1, a2, a3);
  result = sub_935C();
  fd = result;
  if ( result >= 0 )
  {
    if ( (unsigned int)(v6 - 2) > 3 )
    {
      if ( (v5 & 1) != 0 )
      {
        v6 = 2;
      }
      else if ( (v5 & 4) != 0 )
      {
        v6 = 1;
      }
      else
      {
        v6 = 5;
      }
    }
    memset(s, 0, sizeof(s));
    s[0] = 1;
    s[2] = 8;
    s[3] = 0;
    v9 = (int *)&s[4];
    v4 = sub_F494(a1);
    *v9 = v4;
    v9[1] = v6;
    if ( ioctl(fd, 0x42044709u, s) < 0 )
      sub_F3A8(3, "ioctl SET_PORT_STATE error\n");
    return sub_F3A8(5, "%s() Port %d state = %d\n", "Ssc_setPortState", *v9, v9[1]);
  }
  return result;
}

//----- (0000AA84) --------------------------------------------------------
int __fastcall sub_AA84(int a1, int a2)
{
  const char *v2; // r3
  char *v3; // r0
  int v5; // r0
  char s[128]; // [sp+14h] [bp-298h] BYREF
  _BYTE v10[516]; // [sp+94h] [bp-218h] BYREF
  int *v11; // [sp+298h] [bp-14h]
  int fd; // [sp+29Ch] [bp-10h]

  fd = 0;
  if ( a2 )
    v2 = "Enable";
  else
    v2 = "Disable";
  sub_F3A8(7, "%s() %d >>>>>>> port %d %s\n", "Ssc_port_enable_set", 834, a1, v2);
  if ( a1 <= 7 )
  {
    fd = sub_935C();
    if ( fd >= 0 )
    {
      memset(v10, 0, sizeof(v10));
      v10[0] = 0;
      v10[2] = 8;
      v10[3] = 0;
      v11 = (int *)&v10[4];
      v5 = sub_F494(a1);
      *v11 = v5;
      v11[1] = a2;
      if ( ioctl(fd, 0x42044703u, v10) < 0 )
        sub_F3A8(3, "%s() ioctl SET_PORT_STATE error\n", "Ssc_port_enable_set");
      return 0;
    }
    else
    {
      return -1;
    }
  }
  else
  {
    v3 = sub_EED0("port_enable");
    sprintf(s, " echo %x,%d > %s", a1, a2, v3);
    system(s);
    printf("msg = %s\n", s);
    return 0;
  }
}

//----- (0000AC1C) --------------------------------------------------------
int __fastcall Ssc_getPortLinkState(_DWORD *a1)
{
  char v2; // r0
  int v5; // [sp+8h] [bp-14h] BYREF
  int v6; // [sp+Ch] [bp-10h]
  int i; // [sp+10h] [bp-Ch]
  int fd; // [sp+14h] [bp-8h]

  v6 = 1;
  i = 0;
  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  if ( ioctl(fd, 0x8004470A, &v5) < 0 )
    sub_F3A8(3, "ioctl ETHSW_LINK_STATUS_GET error\n");
  for ( i = 0; i <= 9; ++i )
  {
    v2 = sub_F494(i);
    if ( ((1 << v2) & v5) != 0 )
      *a1 |= 1 << i;
  }
  return v6;
}

//----- (0000AD14) --------------------------------------------------------
int __fastcall sub_AD14(int a1)
{
  int v2; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v6; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 0;
  s[2] = 8;
  s[3] = 0;
  v6 = (int *)&s[4];
  v2 = sub_F494(a1);
  *v6 = v2;
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_F3A8(3, "%s() ioctl SET_PORT_STATE error\n", "Ssc_port_enable_get");
  return v6[1];
}

//----- (0000ADEC) --------------------------------------------------------
void *__fastcall Ssc_getPortStatsCounter(void *a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-218h] BYREF
  int *v7; // [sp+210h] [bp-14h]
  int fd; // [sp+214h] [bp-10h]

  fd = sub_935C();
  if ( fd < 0 )
    fprintf((FILE *)stderr, "%s() device open failed\n", "Ssc_getPortStatsCounter");
  memset(s, 0, sizeof(s));
  s[0] = 0;
  strcpy(&s[2], "d");
  v7 = (int *)&s[4];
  v3 = sub_F494(a2);
  *v7 = v3;
  if ( ioctl(fd, 0x80044714, s) < 0 )
    sub_F3A8(3, "%s() ioctl GET_PORT_STATSCOUNTER error\n", "Ssc_getPortStatsCounter");
  memcpy(a1, v7 + 1, 0x60u);
  return a1;
}
// 192E0: using guessed type int stderr;

//----- (0000AF00) --------------------------------------------------------
int __fastcall sub_AF00(_DWORD *a1)
{
  pthread_mutex_lock(&mutex);
  *a1 = dword_19314;
  dword_19314 = 0;
  return pthread_mutex_unlock(&mutex);
}
// 19314: using guessed type int dword_19314;

//----- (0000AF4C) --------------------------------------------------------
int __fastcall sub_AF4C(int a1)
{
  pthread_mutex_lock(&mutex);
  dword_19314 |= a1;
  return pthread_mutex_unlock(&mutex);
}
// 19314: using guessed type int dword_19314;

//----- (0000AF94) --------------------------------------------------------
int __fastcall sub_AF94(int a1)
{
  int result; // r0
  int v3; // [sp+10h] [bp-214h] BYREF
  _BYTE s[516]; // [sp+14h] [bp-210h] BYREF
  _BYTE *v5; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  sub_F3A8(5, "%s() %d pbmp = %lx\n", "Ssc_flushMacAddr", 979, a1);
  result = sub_935C();
  fd = result;
  if ( result >= 0 )
  {
    memset(s, 0, sizeof(s));
    s[0] = 1;
    s[2] = 12;
    s[3] = 0;
    v5 = &s[4];
    sub_F650(a1, &v3);
    *((_DWORD *)v5 + 2) = v3;
    if ( ioctl(fd, 0x42044705u, s) < 0 )
      sub_F3A8(3, "ioctl ETHSW_FDB_FLUSH error\n");
    return sub_AF4C(a1);
  }
  return result;
}

//----- (0000B094) --------------------------------------------------------
int __fastcall sub_B094(int a1)
{
  _DWORD s[130]; // [sp+Ch] [bp-210h] BYREF
  int fd; // [sp+214h] [bp-8h]

  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, 0x204u);
  LOBYTE(s[0]) = 8;
  HIWORD(s[0]) = 4;
  s[129] = &s[1];
  s[1] = a1;
  if ( ioctl(fd, 0x42044705u, s) < 0 )
    sub_F3A8(3, "ioctl ETHSW_TYPE_FDB_AGE_TIME error\n");
  return 0;
}

//----- (0000B158) --------------------------------------------------------
int sub_B158()
{
  _DWORD s[129]; // [sp+0h] [bp-214h] BYREF
  int v3; // [sp+204h] [bp-10h]
  _DWORD *v4; // [sp+208h] [bp-Ch]
  int fd; // [sp+20Ch] [bp-8h]

  v3 = 0;
  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  LOBYTE(s[0]) = 0;
  HIWORD(s[0]) = 4;
  v4 = &s[1];
  s[1] = 1;
  if ( ioctl(fd, 0x82044704, s, s) < 0 )
    sub_F3A8(3, "%s() ioctl ETHSW_FDB_GET error\n", "Ssc_fdbGetEntry");
  return v3;
}

//----- (0000B228) --------------------------------------------------------
int __fastcall sub_B228(const void *a1, _DWORD *a2)
{
  int v6; // [sp+8h] [bp-21Ch] BYREF
  _BYTE s[516]; // [sp+Ch] [bp-218h] BYREF
  int v8; // [sp+210h] [bp-14h]
  int fd; // [sp+214h] [bp-10h]
  void *dest; // [sp+218h] [bp-Ch]
  int v11; // [sp+21Ch] [bp-8h]

  v8 = 0;
  v11 = 0;
  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  v6 = 0;
  memset(s, 0, sizeof(s));
  s[0] = 7;
  s[2] = 28;
  s[3] = 0;
  dest = &s[4];
  memcpy(&s[4], a1, 6u);
  if ( ioctl(fd, 0x82044704, s) < 0 )
    sub_F3A8(3, "%s() ioctl ETHSW_FDB_GET error\n", "Ssc_fdbGetMacPbmp");
  v8 = *((unsigned __int8 *)dest + 25);
  if ( v8 )
    sub_F738(*((_DWORD *)dest + 3), &v6);
  *a2 = v6;
  return v8;
}

//----- (0000B354) --------------------------------------------------------
int __fastcall sub_B354(const void *a1, void *a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+2Ch] [bp-228h] BYREF
  int v8; // [sp+230h] [bp-24h]
  int fd; // [sp+234h] [bp-20h]
  void *dest; // [sp+238h] [bp-1Ch]
  int i; // [sp+23Ch] [bp-18h]

  v8 = 0;
  i = 0;
  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 7;
  s[2] = 28;
  s[3] = 0;
  dest = &s[4];
  memcpy(&s[4], a1, 6u);
  if ( ioctl(fd, 0x82044704, s) < 0 )
    sub_F3A8(3, "%s() ioctl ETHSW_FDB_GET error\n", "Ssc_fdbFindMacEntry");
  v8 = *((unsigned __int8 *)dest + 25);
  if ( v8 )
  {
    for ( i = 0; i <= 9; ++i )
    {
      if ( (*((_DWORD *)dest + 3) & (1 << i)) != 0 )
      {
        v3 = sub_F560(i);
        *((_DWORD *)dest + 2) = v3;
        break;
      }
    }
    memcpy(a2, dest, 0x1Cu);
  }
  printf(
    "%s() addr = %02x:%02x:%02x:%02x:%02x:%02x, port = %02x (%d), inused = %d\n",
    "Ssc_fdbFindMacEntry",
    *(unsigned __int8 *)dest,
    *((unsigned __int8 *)dest + 1),
    *((unsigned __int8 *)dest + 2),
    *((unsigned __int8 *)dest + 3),
    *((unsigned __int8 *)dest + 4),
    *((unsigned __int8 *)dest + 5),
    *((_DWORD *)dest + 3),
    *((_DWORD *)dest + 2),
    *((unsigned __int8 *)dest + 25));
  return v8;
}

//----- (0000B54C) --------------------------------------------------------
int __fastcall sub_B54C(const void *a1, void *a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+2Ch] [bp-228h] BYREF
  int v8; // [sp+230h] [bp-24h]
  int fd; // [sp+234h] [bp-20h]
  void *dest; // [sp+238h] [bp-1Ch]
  int i; // [sp+23Ch] [bp-18h]

  v8 = 0;
  i = 0;
  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 7;
  s[2] = 28;
  s[3] = 0;
  dest = &s[4];
  memcpy(&s[4], a1, 6u);
  if ( ioctl(fd, 0x82044704, s) < 0 )
    sub_F3A8(3, "%s() ioctl ETHSW_FDB_GET error\n", "Ssc_fdbFindAllMacEntry");
  v8 = *((unsigned __int8 *)dest + 25);
  if ( v8 )
  {
    for ( i = 0; i <= 13; ++i )
    {
      if ( (*((_DWORD *)dest + 3) & (1 << i)) != 0 )
      {
        v3 = sub_F560(i);
        *((_DWORD *)dest + 2) = v3;
        break;
      }
    }
    memcpy(a2, dest, 0x1Cu);
  }
  printf(
    "%s() addr = %02x:%02x:%02x:%02x:%02x:%02x, port = %02x (%d), inused = %d\n",
    "Ssc_fdbFindAllMacEntry",
    *(unsigned __int8 *)dest,
    *((unsigned __int8 *)dest + 1),
    *((unsigned __int8 *)dest + 2),
    *((unsigned __int8 *)dest + 3),
    *((unsigned __int8 *)dest + 4),
    *((unsigned __int8 *)dest + 5),
    *((_DWORD *)dest + 3),
    *((_DWORD *)dest + 2),
    *((unsigned __int8 *)dest + 25));
  return v8;
}

//----- (0000B744) --------------------------------------------------------
int __fastcall sub_B744(_DWORD *a1)
{
  int v2; // r4
  _BYTE s[516]; // [sp+8h] [bp-21Ch] BYREF
  int v6; // [sp+20Ch] [bp-18h]
  int *v7; // [sp+210h] [bp-14h]
  int fd; // [sp+214h] [bp-10h]

  v6 = 0;
  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 6;
  s[2] = 16;
  s[3] = 0;
  v7 = (int *)&s[4];
  if ( ioctl(fd, 0x82044704, s) < 0 )
    sub_F3A8(3, "%s() ioctl ETHSW_FDB_GET error\n", "Ssc_fdbGetAddrTableSize");
  v6 = *v7;
  v2 = v7[3];
  *a1 = v7[2];
  a1[1] = v2;
  return v6;
}

//----- (0000B82C) --------------------------------------------------------
int __fastcall sub_B82C(char *a1, size_t a2, int a3)
{
  unsigned int v4; // r0
  int v5; // r4
  _BYTE v10[14336]; // [sp+10h] [bp-3834h] BYREF
  int v11; // [sp+3810h] [bp-34h] BYREF
  int v12; // [sp+3814h] [bp-30h]
  int fd; // [sp+3818h] [bp-2Ch]
  ssize_t v14; // [sp+381Ch] [bp-28h]
  int v15; // [sp+3820h] [bp-24h]
  int i; // [sp+3824h] [bp-20h]
  int v17; // [sp+3828h] [bp-1Ch]
  int v18; // [sp+382Ch] [bp-18h]
  int v19; // [sp+3830h] [bp-14h]
  int v20; // [sp+3834h] [bp-10h]

  fd = 0;
  v14 = 0;
  v15 = 0;
  i = 0;
  v17 = 0;
  v18 = 0;
  v19 = 0;
  v20 = 0;
  v11 = 0;
  v12 = 0;
  if ( a1 )
  {
    fd = sub_935C();
    if ( fd >= 0 )
    {
      memset(v10, 0, sizeof(v10));
      v17 = sub_B744(&v11);
      if ( v17 > 511 )
        v18 = 512;
      else
        v18 = v17;
      if ( v11 == unk_19330 && v12 == unk_19334 )
      {
LABEL_10:
        sub_93F0();
        return dword_19338;
      }
      else
      {
        memset(a1, 0, a2);
        dword_19338 = 0;
        unk_19330 = v11;
        unk_19334 = v12;
        while ( 1 )
        {
          v14 = read(fd, v10, 28 * v18);
          if ( v14 == -1 )
            break;
          v4 = sub_F820(v14, 0x1Cu);
          v15 += v4;
          for ( i = 0; i < v18; ++i )
          {
            if ( a3 )
            {
              if ( v10[28 * i] == 1
                && (unsigned __int8)v10[28 * i + 1] == 128
                && (unsigned __int8)v10[28 * i + 2] == 194 )
              {
                continue;
              }
              v5 = *(_DWORD *)&v10[28 * i + 12];
              if ( (v5 & (1 << sub_F494(14))) != 0 )
                continue;
            }
            memcpy(&a1[92 * dword_19338], &v10[28 * i], 6u);
            if ( a1[92 * dword_19338] == 1 )
            {
              strcpy(&a1[92 * dword_19338 + 6], "mcast");
              strcpy(&a1[92 * dword_19338 + 14], "static");
            }
            else
            {
              strcpy(&a1[92 * dword_19338 + 6], "ucast");
              if ( *(_DWORD *)&v10[28 * i + 16] == 1 )
                strcpy(&a1[92 * dword_19338 + 14], "learn");
              else
                strcpy(&a1[92 * dword_19338 + 14], "static");
            }
            a1[92 * dword_19338 + 32] = v10[28 * i + 26];
            sub_F738(*(_DWORD *)&v10[28 * i + 12], &a1[92 * dword_19338 + 28]);
            ++dword_19338;
          }
          if ( v15 >= v17 )
            goto LABEL_10;
          v19 = v17 - v15;
          if ( v17 - v15 <= 512 )
            v18 = v19;
          else
            v18 = 512;
        }
        fprintf((FILE *)stderr, "%s() %d read error\n", "Ssc_fdbGetAddrTable", 1260);
        return -1;
      }
    }
    else
    {
      return -1;
    }
  }
  else
  {
    fprintf((FILE *)stderr, "%s() %d Invalid argument\n", "Ssc_fdbGetAddrTable", 1228);
    return -1;
  }
}
// 192E0: using guessed type int stderr;
// 19338: using guessed type int dword_19338;

//----- (0000BFE0) --------------------------------------------------------
int __fastcall sub_BFE0(const void *a1, char a2, int a3)
{
  int result; // r0
  int v7; // [sp+18h] [bp-214h] BYREF
  _BYTE s[516]; // [sp+1Ch] [bp-210h] BYREF
  void *dest; // [sp+220h] [bp-Ch]
  int fd; // [sp+224h] [bp-8h]

  sub_F3A8(5, "%s() %d lpbmp = %lx\n", "Ssc_fdbAddUcastEntry", 1338, a3);
  result = sub_935C();
  fd = result;
  if ( result >= 0 )
  {
    memset(s, 0, sizeof(s));
    v7 = 0;
    s[0] = 3;
    s[2] = 16;
    s[3] = 0;
    dest = &s[4];
    memcpy(&s[4], a1, 6u);
    sub_F650(a3, &v7);
    *((_DWORD *)dest + 2) = v7;
    *((_BYTE *)dest + 13) = a2;
    result = ioctl(fd, 0x42044705u, s);
    if ( result < 0 )
      return sub_F3A8(3, "ioctl ETHSW_FDB_SET error\n");
  }
  return result;
}

//----- (0000C110) --------------------------------------------------------
int __fastcall sub_C110(const void *a1, int a2, int a3)
{
  int result; // r0
  int v7; // [sp+18h] [bp-214h] BYREF
  _BYTE s[516]; // [sp+1Ch] [bp-210h] BYREF
  _BYTE *v9; // [sp+220h] [bp-Ch]
  int fd; // [sp+224h] [bp-8h]

  sub_F3A8(5, "%s() %d lpbmp = %lx\n", "Ssc_setMgmtFrame", 1386, a3);
  result = sub_935C();
  fd = result;
  if ( result >= 0 )
  {
    memset(s, 0, sizeof(s));
    v7 = 0;
    s[0] = 2;
    s[2] = 20;
    s[3] = 0;
    v9 = &s[4];
    memcpy(&s[8], a1, 6u);
    sub_F650(a3, &v7);
    *((_DWORD *)v9 + 3) = v7;
    *(_DWORD *)v9 = a2;
    if ( a2 )
    {
      v9[16] = a2;
      v9[17] = 7;
    }
    result = ioctl(fd, 0x42044705u, s);
    if ( result < 0 )
      return sub_F3A8(3, "ioctl ETHSW_FDB_SET error\n");
  }
  return result;
}

//----- (0000C268) --------------------------------------------------------
int sub_C268()
{
  sub_F3A8(7, "%s() %d\n", "Ssc_enable_manage_port", 1429);
  return sub_C110(off_19268, 1, 0x4000);
}
// 19268: using guessed type _UNKNOWN *off_19268;

//----- (0000C2C0) --------------------------------------------------------
int sub_C2C0()
{
  sub_F3A8(7, "%s() %d\n", "Ssc_disable_manage_port", 1447);
  return sub_C110(off_19268, 0, 0);
}
// 19268: using guessed type _UNKNOWN *off_19268;

//----- (0000C318) --------------------------------------------------------
int sub_C318()
{
  return sub_DA48(off_19268, 0);
}
// 19268: using guessed type _UNKNOWN *off_19268;

//----- (0000C33C) --------------------------------------------------------
int __fastcall sub_C33C(int a1, const void *a2, int a3)
{
  sub_F3A8(5, "%s() %d lpbmp = 0x%lx\n", "Ssc_enable_manage_multiport", 1464, a3);
  return sub_C110(a2, 1, a3);
}

//----- (0000C394) --------------------------------------------------------
int __fastcall sub_C394(int a1, const void *a2, int a3)
{
  sub_F3A8(5, "%s() %d lpbmp = 0x%lx\n", "Ssc_disable_manage_multiport", 1473, a3);
  return sub_C110(a2, 1, 0x4000);
}

//----- (0000C400) --------------------------------------------------------
int __fastcall sub_C400(int a1, const void *a2)
{
  sub_F3A8(7, "%s() %d\n", "Ssc_delete_manage_multiport", 1484);
  return sub_C110(a2, 0, 0);
}

//----- (0000C458) --------------------------------------------------------
int __fastcall sub_C458(int a1)
{
  _BYTE s[516]; // [sp+14h] [bp-210h] BYREF
  _BYTE *v4; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  sub_F3A8(7, "%s() %d >>>>>>> port %d\n", "Ssc_cpuGetRate", 1500, a1);
  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 6;
  s[2] = 8;
  s[3] = 0;
  v4 = &s[4];
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_F3A8(3, "%s() ioctl error\n", "Ssc_cpuGetRate");
  return 0;
}

//----- (0000C53C) --------------------------------------------------------
int __fastcall sub_C53C(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+14h] [bp-210h] BYREF
  int *v8; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  sub_F3A8(7, "%s() %d >>>>>>> port %d %d\n", "Ssc_cpuSetRate", 1526, a1, a2);
  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 6;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_F494(a1);
  *v8 = v3;
  v8[1] = a2;
  if ( ioctl(fd, 0x42044703u, s) < 0 )
    sub_F3A8(3, "%s() ioctl error\n", "Ssc_cpuSetRate");
  return 0;
}

//----- (0000C64C) --------------------------------------------------------
int __fastcall sub_C64C(_DWORD *a1, int a2)
{
  int v3; // r0
  _DWORD s[129]; // [sp+8h] [bp-214h] BYREF
  int i; // [sp+20Ch] [bp-10h]
  _DWORD *v9; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  LOBYTE(s[0]) = 0;
  HIWORD(s[0]) = 16;
  v9 = &s[1];
  s[3] = a2;
  s[1] = -1;
  s[4] = 0;
  for ( i = 0; i <= 13; ++i )
  {
    if ( (*a1 & (1 << i)) != 0 )
    {
      v3 = sub_F494(i);
      v9[1] = v3;
      if ( ioctl(fd, 0x4204470Du, s) < 0 )
        sub_F3A8(3, "%s() ioctl error\n", "Ssc_mirrorport_reset");
    }
  }
  return 0;
}

//----- (0000C78C) --------------------------------------------------------
int __fastcall sub_C78C(_DWORD *a1, unsigned __int8 a2, int a3, int a4)
{
  int v5; // r0
  _DWORD s[129]; // [sp+10h] [bp-214h] BYREF
  int i; // [sp+214h] [bp-10h]
  int *v13; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  i = 0;
  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  LOBYTE(s[0]) = 0;
  HIWORD(s[0]) = 16;
  v13 = &s[1];
  s[3] = a3;
  if ( a4 )
    *v13 = sub_F494(a2 - 1);
  else
    *v13 = -1;
  v13[3] = a4;
  for ( i = 0; i <= 13; ++i )
  {
    if ( (*a1 & (1 << i)) != 0 )
    {
      v5 = sub_F494(i);
      v13[1] = v5;
      if ( ioctl(fd, 0x4204470Du, s) < 0 )
        sub_F3A8(3, "%s() ioctl error\n", "Ssc_mirrorport_enable_set");
    }
  }
  return 0;
}

//----- (0000C90C) --------------------------------------------------------
int __fastcall sub_C90C(_DWORD *a1, int a2, int a3)
{
  int v4; // r0
  _DWORD s[129]; // [sp+14h] [bp-218h] BYREF
  int i; // [sp+218h] [bp-14h]
  int v11; // [sp+21Ch] [bp-10h]
  _DWORD *v12; // [sp+220h] [bp-Ch]
  int fd; // [sp+224h] [bp-8h]

  v11 = 0;
  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  LOBYTE(s[0]) = 1;
  HIWORD(s[0]) = 16;
  v12 = &s[1];
  s[3] = a2;
  s[1] = -1;
  s[4] = a3;
  for ( i = 0; i <= 13; ++i )
  {
    if ( (*a1 & (1 << i)) != 0 )
    {
      v4 = sub_F494(i);
      v12[1] = v4;
      if ( ioctl(fd, 0x4204470Du, s) < 0 )
        sub_F3A8(3, "%s() ioctl error\n", "Ssc_targetport_reset");
    }
  }
  return 0;
}

//----- (0000CA58) --------------------------------------------------------
int __fastcall sub_CA58(_DWORD *a1, int a2, int a3)
{
  int v4; // r0
  _DWORD s[134]; // [sp+10h] [bp-22Ch] BYREF
  int i; // [sp+228h] [bp-14h]
  _DWORD *v11; // [sp+230h] [bp-Ch]
  int fd; // [sp+234h] [bp-8h]

  s[129] = 0;
  s[130] = 0;
  s[132] = 0;
  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, 0x204u);
  LOBYTE(s[0]) = 1;
  HIWORD(s[0]) = 16;
  v11 = &s[1];
  s[3] = a2;
  s[1] = -1;
  s[4] = a3;
  for ( i = 0; i <= 13; ++i )
  {
    if ( (*a1 & (1 << i)) != 0 )
    {
      v4 = sub_F494(i);
      v11[1] = v4;
      if ( ioctl(fd, 0x4204470Du, s) < 0 )
        sub_F3A8(3, "%s() ioctl error\n", "Ssc_targetport_enable_set");
    }
  }
  return 0;
}

//----- (0000CBB4) --------------------------------------------------------
void sub_CBB4()
{
  ;
}

//----- (0000CBC8) --------------------------------------------------------
int __fastcall sub_CBC8(int a1)
{
  _DWORD s[130]; // [sp+Ch] [bp-210h] BYREF
  int fd; // [sp+214h] [bp-8h]

  puts("Ssc_setQosSchedulingMode");
  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, 0x204u);
  LOBYTE(s[0]) = 0;
  HIWORD(s[0]) = 4;
  s[129] = &s[1];
  s[1] = a1;
  if ( ioctl(fd, 0x42044711u, s) < 0 )
    sub_F3A8(3, "ioctl ETHSW_TYPE_QOS_SCHEDULING_MODE error\n");
  return 0;
}

//----- (0000CC94) --------------------------------------------------------
int __fastcall sub_CC94(int result)
{
  int v1; // [sp+4h] [bp-10h]
  int i; // [sp+Ch] [bp-8h]

  v1 = result;
  for ( i = 0; i <= 9; ++i )
  {
    if ( ((1 << i) & v1) != 0 )
      result = sub_CD8C(i, 1);
    else
      result = sub_CD8C(i, 0);
  }
  return result;
}

//----- (0000CD10) --------------------------------------------------------
int __fastcall sub_CD10(int result)
{
  int v1; // [sp+4h] [bp-10h]
  int i; // [sp+Ch] [bp-8h]

  v1 = result;
  for ( i = 0; i <= 9; ++i )
  {
    if ( ((1 << i) & v1) != 0 )
      result = sub_CE6C(i, 1);
    else
      result = sub_CE6C(i, 0);
  }
  return result;
}

//----- (0000CD8C) --------------------------------------------------------
int __fastcall sub_CD8C(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 1;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_F494(a1);
  *v8 = v3;
  v8[1] = a2;
  if ( ioctl(fd, 0x42044711u, s) < 0 )
    sub_F3A8(3, "%s() ioctl error\n", "Ssc_port_tos_set");
  return 0;
}

//----- (0000CE6C) --------------------------------------------------------
int __fastcall sub_CE6C(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 2;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_F494(a1);
  *v8 = v3;
  v8[1] = a2;
  if ( ioctl(fd, 0x42044711u, s) < 0 )
    sub_F3A8(3, "%s() ioctl error\n", "Ssc_port_cos_set");
  return 0;
}

//----- (0000CF4C) --------------------------------------------------------
int __fastcall sub_CF4C(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+14h] [bp-210h] BYREF
  int *v8; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  sub_F3A8(7, "%s() %d >>>>>>> port %d %d\n", "Ssc_port_priority_set", 1861, a1, a2);
  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 3;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_F494(a1);
  *v8 = v3;
  v8[1] = a2;
  if ( ioctl(fd, 0x42044711u, s) < 0 )
    sub_F3A8(3, "%s() ioctl error\n", "Ssc_port_priority_set");
  return 0;
}

//----- (0000D058) --------------------------------------------------------
int __fastcall sub_D058(int a1)
{
  _BYTE s[516]; // [sp+8h] [bp-214h] BYREF
  int *v5; // [sp+20Ch] [bp-10h]
  int fd; // [sp+210h] [bp-Ch]
  int i; // [sp+214h] [bp-8h]

  i = 0;
  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 4;
  s[2] = 8;
  s[3] = 0;
  v5 = (int *)&s[4];
  for ( i = 0; i <= 7; ++i )
  {
    *v5 = i;
    v5[1] = *(_DWORD *)(a1 + 4 * i);
    if ( ioctl(fd, 0x42044711u, s) < 0 )
      sub_F3A8(3, "ioctl ETHSW_TYPE_QOS_SCHEDULING_MODE error\n");
  }
  return 0;
}

//----- (0000D160) --------------------------------------------------------
int __fastcall sub_D160(int a1, int a2, const void *a3)
{
  _DWORD s[130]; // [sp+10h] [bp-21Ch] BYREF
  int fd; // [sp+218h] [bp-14h]
  int v10; // [sp+21Ch] [bp-10h]

  v10 = 0;
  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, 0x204u);
  LOBYTE(s[0]) = 5;
  HIWORD(s[0]) = 264;
  s[129] = &s[1];
  s[1] = a1;
  s[2] = a2;
  memcpy(&s[3], a3, 0x100u);
  if ( ioctl(fd, 0x42044711u, s) < 0 )
    sub_F3A8(3, "ioctl ETHSW_TYPE_QOS_SCHEDULING_MODE error\n");
  return 0;
}

//----- (0000D278) --------------------------------------------------------
void sub_D278()
{
  ;
}

//----- (0000D294) --------------------------------------------------------
int __fastcall sub_D294(int a1, _DWORD *a2, _DWORD *a3)
{
  _DWORD s[129]; // [sp+1Ch] [bp-210h] BYREF
  _DWORD *v9; // [sp+220h] [bp-Ch]
  int fd; // [sp+224h] [bp-8h]

  sub_F3A8(7, "%s() %d >>>>>>> vid %d\n", "Ssc_getVlanPortmap", 2011, a1);
  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  LOBYTE(s[0]) = 0;
  HIWORD(s[0]) = 12;
  v9 = &s[1];
  s[1] = a1;
  if ( ioctl(fd, 0x82044706, s) >= 0 )
  {
    sub_F738(v9[1], a2);
    sub_F738(v9[2], a3);
    printf("vid=%d, tagged=%x, untagged=%x\r\n", a1, *a2, *a3);
    return 0;
  }
  else
  {
    sub_F3A8(3, "%s() ioctl error\n", "Ssc_getVlanPortmap");
    return -1;
  }
}

//----- (0000D3E0) --------------------------------------------------------
int __fastcall sub_D3E0(int a1, int a2)
{
  int v6; // [sp+14h] [bp-218h] BYREF
  int v7; // [sp+18h] [bp-214h] BYREF
  _DWORD s[129]; // [sp+1Ch] [bp-210h] BYREF
  _DWORD *v9; // [sp+220h] [bp-Ch]
  int fd; // [sp+224h] [bp-8h]

  fd = 0;
  sub_F3A8(7, "%s() %d >>>>>>> vid %d enable = %d\n", "Ssc_vlanEnableCpuPort", 2043, a1, a2);
  if ( a1 > 0 && a1 <= 4094 )
  {
    fd = sub_935C();
    if ( fd >= 0 )
    {
      v7 = 0;
      v6 = 0;
      memset(s, 0, sizeof(s));
      sub_D294(a1, &v7, &v6);
      LOBYTE(s[0]) = 1;
      HIWORD(s[0]) = 12;
      v9 = &s[1];
      s[1] = a1;
      if ( a2 )
        v7 |= 0x4000u;
      else
        v7 &= ~0x4000u;
      sub_F650(v7, v9 + 1);
      sub_F650(v6, v9 + 2);
      if ( ioctl(fd, 0x82044707, s) >= 0 )
      {
        return 0;
      }
      else
      {
        sub_F3A8(3, "%s() ioctl error\n", "Ssc_vlanEnableCpuPort");
        return -1;
      }
    }
    else
    {
      return -1;
    }
  }
  else
  {
    printf("%s() %d Invalid vid = %d\n", "Ssc_vlanEnableCpuPort", 2046, a1);
    return -1;
  }
}

//----- (0000D5AC) --------------------------------------------------------
int sub_D5AC()
{
  _BYTE s[516]; // [sp+4h] [bp-210h] BYREF
  _BYTE *v3; // [sp+208h] [bp-Ch]
  int fd; // [sp+20Ch] [bp-8h]

  sub_F3A8(7, "%s() %d \n", "Ssc_vlanGetTable", 2089);
  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 2;
  s[2] = 12;
  s[3] = 0;
  v3 = &s[4];
  if ( ioctl(fd, 0x82044706, s) >= 0 )
  {
    printf("%s() %d \n", "Ssc_vlanGetTable", 2106);
    return 0;
  }
  else
  {
    sub_F3A8(3, "%s() ioctl error\n", "Ssc_vlanGetTable");
    return -1;
  }
}

//----- (0000D6A4) --------------------------------------------------------
int sub_D6A4()
{
  int v1; // r0
  _BYTE s[516]; // [sp+8h] [bp-214h] BYREF
  int i; // [sp+20Ch] [bp-10h]
  int *v5; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  for ( i = 0; i <= 9; ++i )
  {
    sub_F3A8(7, "%s() %d >>>>>>> port %d\n", "Ssc_initIgmpsnooping", 2133, i);
    memset(s, 0, sizeof(s));
    s[0] = 5;
    s[2] = 8;
    s[3] = 0;
    v5 = (int *)&s[4];
    v1 = sub_F494(i);
    *v5 = v1;
    v5[1] = 1;
    if ( ioctl(fd, 0x42044703u, s) < 0 )
    {
      sub_F3A8(3, "%s() ioctl error\n", "Ssc_initIgmpsnooping");
      return -1;
    }
  }
  return 0;
}

//----- (0000D7D0) --------------------------------------------------------
int sub_D7D0()
{
  int v1; // r0
  _BYTE s[516]; // [sp+8h] [bp-214h] BYREF
  int i; // [sp+20Ch] [bp-10h]
  int *v5; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  for ( i = 0; i <= 9; ++i )
  {
    sub_F3A8(7, "%s() %d >>>>>>> port %d %d\n", "Ssc_destroyIgmpsnooping", 2169, i, 0);
    memset(s, 0, sizeof(s));
    s[0] = 5;
    s[2] = 8;
    s[3] = 0;
    v5 = (int *)&s[4];
    v1 = sub_F494(i);
    *v5 = v1;
    v5[1] = 0;
    if ( ioctl(fd, 0x42044703u, s) < 0 )
    {
      sub_F3A8(3, "%s() ioctl error\n", "Ssc_destroyIgmpsnooping");
      return -1;
    }
  }
  return 0;
}

//----- (0000D904) --------------------------------------------------------
void sub_D904()
{
  ;
}

//----- (0000D918) --------------------------------------------------------
int __fastcall sub_D918(const void *a1, int a2, int a3)
{
  _DWORD s[129]; // [sp+10h] [bp-214h] BYREF
  int v8; // [sp+214h] [bp-10h]
  _DWORD *v9; // [sp+218h] [bp-Ch]
  int fd; // [sp+21Ch] [bp-8h]

  v8 = 0;
  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  LOBYTE(s[0]) = 2;
  HIWORD(s[0]) = 20;
  v9 = &s[1];
  memcpy(&s[2], a1, 6u);
  sub_F650(a3, &s[4]);
  if ( ioctl(fd, 0x42044705u, s) >= 0 )
  {
    if ( v8 )
      sub_F3A8(3, "%s: bcm_mcast_addr_add fail err=%d\n", "Ssc_mcastAddrAdd", v8);
    return v8;
  }
  else
  {
    sub_F3A8(3, "ioctl ETHSW_FDB_SET error\n");
    return -1;
  }
}

//----- (0000DA48) --------------------------------------------------------
int __fastcall sub_DA48(const void *a1, __int16 a2)
{
  _BYTE s[520]; // [sp+8h] [bp-214h] BYREF
  int fd; // [sp+210h] [bp-Ch]
  _BYTE *v8; // [sp+214h] [bp-8h]

  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, 0x204u);
  if ( (unsigned __int8)a2 | (__int16)(HIBYTE(a2) << 8) )
    s[0] = 2;
  else
    s[0] = 5;
  s[2] = 20;
  s[3] = 0;
  v8 = &s[4];
  memcpy(&s[8], a1, 6u);
  if ( ioctl(fd, 0x42044705u, s) >= 0 )
    return 0;
  sub_F3A8(3, "ioctl ETHSW_FDB_SET error\n");
  return -1;
}

//----- (0000DB88) --------------------------------------------------------
int __fastcall sub_DB88(int a1)
{
  _DWORD s[129]; // [sp+Ch] [bp-210h] BYREF
  int fd; // [sp+210h] [bp-Ch]
  _DWORD *v6; // [sp+214h] [bp-8h]

  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  LOBYTE(s[0]) = 1;
  HIWORD(s[0]) = 4;
  v6 = &s[1];
  s[1] = a1;
  if ( ioctl(fd, 0x4204470Fu, s) < 0 )
    sub_F3A8(3, "%s() ioctl ETHSW_PORT_TRUNK_SET error\n", "Ssc_trunkSetHashMode");
  return 0;
}

//----- (0000DC54) --------------------------------------------------------
int sub_DC54()
{
  _BYTE s[516]; // [sp+4h] [bp-210h] BYREF
  int fd; // [sp+208h] [bp-Ch]
  _BYTE *v4; // [sp+20Ch] [bp-8h]

  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 0;
  s[2] = 8;
  s[3] = 0;
  v4 = &s[4];
  if ( ioctl(fd, 0x8204470E, s) < 0 )
    sub_F3A8(3, "%s() ioctl ETHSW_PORT_TRUNK_GET error\n", "Ssc_trunkGetInfo");
  return 0;
}

//----- (0000DD10) --------------------------------------------------------
int __fastcall sub_DD10(int a1, int a2)
{
  int v6; // [sp+8h] [bp-214h] BYREF
  _DWORD s[129]; // [sp+Ch] [bp-210h] BYREF
  int fd; // [sp+210h] [bp-Ch]
  _DWORD *v9; // [sp+214h] [bp-8h]

  printf("%s() %d %x\n", "Ssc_trunkSetMember", a1, a2);
  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  LOBYTE(s[0]) = 2;
  HIWORD(s[0]) = 8;
  v9 = &s[1];
  s[1] = a1;
  sub_F650(a2, &v6);
  v9[1] = v6;
  if ( ioctl(fd, 0x4204470Fu, s) < 0 )
    sub_F3A8(3, "%s() ioctl ETHSW_PORT_TRUNK_SET error\n", "Ssc_trunkSetMember");
  return 0;
}

//----- (0000DE18) --------------------------------------------------------
int __fastcall sub_DE18(int a1, int a2)
{
  int v6; // [sp+8h] [bp-214h] BYREF
  _DWORD s[129]; // [sp+Ch] [bp-210h] BYREF
  int fd; // [sp+210h] [bp-Ch]
  _DWORD *v9; // [sp+214h] [bp-8h]

  printf("%s() %d %x\n", "Ssc_trunkClearMember", a1, a2);
  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  LOBYTE(s[0]) = 3;
  HIWORD(s[0]) = 8;
  v9 = &s[1];
  s[1] = a1;
  sub_F650(a2, &v6);
  v9[1] = v6;
  if ( ioctl(fd, 0x4204470Fu, s) < 0 )
    sub_F3A8(3, "%s() ioctl ETHSW_PORT_TRUNK_SET error\n", "Ssc_trunkClearMember");
  return 0;
}

//----- (0000DF20) --------------------------------------------------------
int __fastcall sub_DF20(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 0;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_F494(a1);
  *v8 = v3;
  v8[1] = a2;
  if ( ioctl(fd, 0x42044713u, s) < 0 )
    sub_F3A8(3, "%s() ioctl error\n", "Ssc_setIngressRateLimitMode");
  return 0;
}

//----- (0000E000) --------------------------------------------------------
int __fastcall sub_E000(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 1;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_F494(a1);
  *v8 = v3;
  v8[1] = a2;
  if ( ioctl(fd, 0x42044713u, s) < 0 )
    sub_F3A8(3, "%s() ioctl error\n", "Ssc_setIngressRateLimit");
  return 0;
}

//----- (0000E0E0) --------------------------------------------------------
int __fastcall sub_E0E0(int a1, int a2)
{
  int v3; // r0
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  int *v8; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 2;
  s[2] = 8;
  s[3] = 0;
  v8 = (int *)&s[4];
  v3 = sub_F494(a1);
  *v8 = v3;
  v8[1] = a2;
  if ( ioctl(fd, 0x42044713u, s) < 0 )
    sub_F3A8(3, "%s() ioctl error\n", "Ssc_setEgressRateLimit");
  return 0;
}

//----- (0000E1C0) --------------------------------------------------------
int __fastcall sub_E1C0(int a1)
{
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  _BYTE *v5; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 14;
  s[2] = 8;
  s[3] = 0;
  v5 = &s[4];
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_F3A8(3, "%s() ioctl error\n", "Ssc_cpu_qinq_get");
  *(_DWORD *)a1 = *((_DWORD *)v5 + 1);
  return *(_DWORD *)a1;
}

//----- (0000E294) --------------------------------------------------------
int __fastcall sub_E294(int a1)
{
  _DWORD s[131]; // [sp+8h] [bp-214h] BYREF
  int fd; // [sp+214h] [bp-8h]

  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, 0x204u);
  LOBYTE(s[0]) = 14;
  HIWORD(s[0]) = 8;
  s[130] = &s[1];
  s[2] = a1;
  if ( ioctl(fd, 0x42044703u, s) < 0 )
    sub_F3A8(3, "%s() ioctl error\n", "Ssc_cpu_qinq_set");
  return 0;
}

//----- (0000E360) --------------------------------------------------------
int __fastcall sub_E360(int a1)
{
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  _BYTE *v5; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 15;
  s[2] = 8;
  s[3] = 0;
  v5 = &s[4];
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_F3A8(3, "%s() ioctl error\n", "Ssc_cpu_egress_get");
  *(_DWORD *)a1 = *((_DWORD *)v5 + 1);
  return *(_DWORD *)a1;
}

//----- (0000E434) --------------------------------------------------------
int __fastcall sub_E434(int a1)
{
  _DWORD s[131]; // [sp+8h] [bp-214h] BYREF
  int fd; // [sp+214h] [bp-8h]

  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, 0x204u);
  LOBYTE(s[0]) = 15;
  HIWORD(s[0]) = 8;
  s[130] = &s[1];
  s[2] = a1;
  if ( ioctl(fd, 0x42044703u, s) < 0 )
    sub_F3A8(3, "%s() ioctl error\n", "Ssc_cpu_egress_set");
  return 0;
}

//----- (0000E500) --------------------------------------------------------
int __fastcall sub_E500(int a1)
{
  _BYTE s[516]; // [sp+Ch] [bp-210h] BYREF
  _BYTE *v5; // [sp+210h] [bp-Ch]
  int fd; // [sp+214h] [bp-8h]

  fd = sub_935C();
  if ( fd < 0 )
    return -1;
  memset(s, 0, sizeof(s));
  s[0] = 16;
  s[2] = 8;
  s[3] = 0;
  v5 = &s[4];
  if ( ioctl(fd, 0x82044702, s) < 0 )
    sub_F3A8(3, "%s() ioctl error\n", "Ssc_cpu_802dot1q_mode_get");
  *(_DWORD *)a1 = *((_DWORD *)v5 + 1);
  return *(_DWORD *)a1;
}

//----- (0000E5D4) --------------------------------------------------------
int __fastcall sub_E5D4(unsigned __int8 *a1, int *a2, _DWORD *a3)
{
  sub_F3A8(7, "dsa[0-3]=0x%x 0x%x 0x%x 0x%x\n", *a1, a1[1], a1[2], a1[3]);
  *a2 = a1[1] >> 3;
  *a3 = ((a1[2] & 0xF) << 8) + a1[3];
  sub_F3A8(7, "Packet from port %d, vid %d\n", *a2, *a3);
  return 0;
}

//----- (0000E6C4) --------------------------------------------------------
_BYTE *__fastcall sub_E6C4(_BYTE *result, char a2, __int16 a3)
{
  *result = 64;
  if ( a3 )
    *result |= 0x20u;
  result[1] = 8 * a2;
  result[2] = ~((unsigned int)~((unsigned __int16)(((unsigned __int8)a3 | (HIBYTE(a3) << 8)) & 0xF00) >> 8 << 27) >> 27);
  result[3] = a3;
  return result;
}

//----- (0000E798) --------------------------------------------------------
ssize_t __fastcall sub_E798(int a1, int a2, int a3, int a4, int a5, __int16 a6)
{
  _BYTE v10[4]; // [sp+48h] [bp-2Ch] BYREF
  int v11; // [sp+4Ch] [bp-28h]
  size_t n; // [sp+50h] [bp-24h]
  int v13; // [sp+54h] [bp-20h]

  v11 = 0;
  memset(&byte_1991C, 0, 0x5EAu);
  v13 = sub_F494(a3);
  sub_E6C4(v10, v13, (unsigned __int8)a6 | (HIBYTE(a6) << 8));
  memcpy(&byte_1991C, (const void *)a4, 0xCu);
  memcpy(&unk_19928, v10, 4u);
  memcpy(&unk_1992C, (const void *)(a4 + 12), a5 - 12);
  n = a5 + 4;
  sub_F3A8(
    7,
    "%s() %d DA=%x:%x:%x:%x:%x:%x SA=%x:%x:%x:%x:%x:%x frame_len = %d\n",
    "frame_send",
    98,
    (unsigned __int8)byte_1991C,
    (unsigned __int8)byte_1991D,
    (unsigned __int8)byte_1991E,
    (unsigned __int8)byte_1991F,
    (unsigned __int8)byte_19920,
    (unsigned __int8)byte_19921,
    (unsigned __int8)byte_19922,
    (unsigned __int8)byte_19923,
    (unsigned __int8)byte_19924,
    (unsigned __int8)byte_19925,
    (unsigned __int8)byte_19926,
    (unsigned __int8)byte_19927,
    a5 + 4);
  return write(a1, &byte_1991C, n);
}
// 1991C: using guessed type char byte_1991C;
// 1991D: using guessed type char byte_1991D;
// 1991E: using guessed type char byte_1991E;
// 1991F: using guessed type char byte_1991F;
// 19920: using guessed type char byte_19920;
// 19921: using guessed type char byte_19921;
// 19922: using guessed type char byte_19922;
// 19923: using guessed type char byte_19923;
// 19924: using guessed type char byte_19924;
// 19925: using guessed type char byte_19925;
// 19926: using guessed type char byte_19926;
// 19927: using guessed type char byte_19927;

//----- (0000E978) --------------------------------------------------------
ssize_t __fastcall sub_E978(int a1, int a2, int a3, int a4, int a5, int a6, __int16 a7)
{
  int v12; // [sp+18h] [bp-14h] BYREF
  int v13; // [sp+1Ch] [bp-10h] BYREF
  ssize_t v14; // [sp+20h] [bp-Ch]
  int i; // [sp+24h] [bp-8h]

  v14 = 0;
  sub_F3A8(7, "%s() %d\n", "Ssc_sendPacket", 158);
  v13 = 0;
  v12 = 0;
  sub_F650(a5, &v13);
  sub_F650(a6, &v12);
  for ( i = 0; i <= 9; ++i )
  {
    if ( ((1 << i) & a6) != 0 )
      v14 = sub_E798(a1, a2, i, a3, a4, 0);
    if ( ((1 << i) & a5) != 0 )
      v14 = sub_E798(a1, a2, i, a3, a4, (unsigned __int8)a7 | (HIBYTE(a7) << 8));
  }
  sub_F3A8(6, "%s() len = %d, ret = %d\n", "Ssc_sendPacket", a4, v14);
  return v14;
}

//----- (0000EAD8) --------------------------------------------------------
int __fastcall sub_EAD8(int a1, int a2, int a3, const void *a4, size_t n, int a6)
{
  ssize_t v11; // [sp+24h] [bp-10h]
  signed int na; // [sp+38h] [bp+4h]

  sub_F3A8(7, "%s() sendBPDU to port %d\n", "Ssc_sendBpduPacket", a3);
  memcpy(byte_19340, off_19268, 6u);
  if ( a6 )
    bcopy(&unk_19274, &byte_19340[6], 6u);
  else
    bcopy(&byte_1926C, &byte_19340[6], 6u);
  word_1934C = htons(n + 3);
  byte_1934E = 66;
  byte_1934F = 66;
  byte_19350 = 3;
  bcopy(a4, &unk_19351, n);
  for ( na = n + 17; na <= 59; ++na )
    byte_19340[na] = 0;
  v11 = sub_E798(a1, a2, a3, (int)byte_19340, na, 0);
  return sub_F3A8(6, "%s() len = %d, ret = %d\n", "Ssc_sendBpduPacket", na, v11);
}
// 19268: using guessed type _UNKNOWN *off_19268;
// 1926C: using guessed type char byte_1926C;
// 19340: using guessed type _BYTE byte_19340[12];
// 1934C: using guessed type __int16 word_1934C;
// 1934E: using guessed type char byte_1934E;
// 1934F: using guessed type char byte_1934F;
// 19350: using guessed type char byte_19350;

//----- (0000EC74) --------------------------------------------------------
int __fastcall sub_EC74(int a1, int a2, int a3, int a4, void *src, size_t n, int a7)
{
  int result; // r0
  _BYTE dest[6]; // [sp+34h] [bp-68h] BYREF
  _WORD v13[4]; // [sp+3Ah] [bp-62h] BYREF
  char v14; // [sp+42h] [bp-5Ah]
  char v15; // [sp+43h] [bp-59h]
  char v16; // [sp+44h] [bp-58h]
  _BYTE v17[3]; // [sp+45h] [bp-57h] BYREF
  ssize_t v18; // [sp+8Ch] [bp-10h]
  signed int na; // [sp+A4h] [bp+8h]

  v18 = 0;
  sub_F3A8(
    7,
    "%s() sendBPDU to port %d for ring %d, SA = %x:%x:%x:%x:%x:%x\n",
    "Ssc_sendTR2Packet",
    a4,
    a3,
    (unsigned __int8)byte_1926C,
    (unsigned __int8)byte_1926D,
    (unsigned __int8)byte_1926E,
    (unsigned __int8)byte_1926F,
    (unsigned __int8)byte_19270,
    (unsigned __int8)byte_19271);
  result = sub_98C4(a4);
  if ( !result )
  {
    if ( a3 )
      memcpy(dest, (const void *)dword_19F94, sizeof(dest));
    else
      memcpy(dest, (const void *)dword_19F90, sizeof(dest));
    if ( a7 )
      bcopy(&unk_19274, v13, 6u);
    else
      bcopy(&byte_1926C, v13, 6u);
    v13[3] = htons(n + 3);
    v14 = 66;
    v15 = 66;
    v16 = 3;
    bcopy(src, v17, n);
    for ( na = n + 17; na <= 59; ++na )
      dest[na] = 0;
    v18 = sub_E798(a1, a2, a4, (int)dest, na, 0);
    return sub_F3A8(6, "%s() len = %d, ret = %d\n", "Ssc_sendTR2Packet", na, v18);
  }
  return result;
}
// 1926C: using guessed type char byte_1926C;
// 1926D: using guessed type char byte_1926D;
// 1926E: using guessed type char byte_1926E;
// 1926F: using guessed type char byte_1926F;
// 19270: using guessed type char byte_19270;
// 19271: using guessed type char byte_19271;
// 19F90: using guessed type int dword_19F90;
// 19F94: using guessed type int dword_19F94;

//----- (0000EED0) --------------------------------------------------------
char *__fastcall sub_EED0(const char *a1)
{
  sprintf(byte_19F08, "%s/%s", "/proc/moxa", a1);
  return byte_19F08;
}

//----- (0000EF14) --------------------------------------------------------
int __fastcall sub_EF14(int a1, int a2, int a3)
{
  char *v3; // r0
  char s[128]; // [sp+1Ch] [bp-90h] BYREF
  int v8; // [sp+9Ch] [bp-10h]

  v8 = sub_F494(a1);
  v3 = sub_EED0("port_speed_set");
  sprintf(s, " echo %x,%x,%x > %s", v8, a2, a3, v3);
  printf("msg = %s\n", s);
  system(s);
  return 0;
}

//----- (0000EFAC) --------------------------------------------------------
int __fastcall sub_EFAC(int a1)
{
  printf("%s() %d >>>>>> %d ms\n", "Ssys_ms2ticks", 28, a1);
  return a1;
}

//----- (0000EFEC) --------------------------------------------------------
int __fastcall sub_EFEC(int a1)
{
  struct timespec remaining; // [sp+10h] [bp-14h] BYREF
  struct timespec requested_time; // [sp+18h] [bp-Ch] BYREF

  requested_time.tv_sec = 0;
  requested_time.tv_nsec = 1000000 * a1;
  return nanosleep(&requested_time, &remaining);
}

//----- (0000F048) --------------------------------------------------------
__time_t Ssys_current_secs()
{
  int *v0; // r0
  char *v1; // r0
  timespec tp; // [sp+0h] [bp-Ch] BYREF

  if ( clock_gettime(1, &tp) != -1 )
    return tp.tv_sec;
  v0 = _errno_location();
  v1 = strerror(*v0);
  sub_F3A8(3, "%s() error = %s\n", "Ssys_current_secs", v1);
  return -1;
}

//----- (0000F0B8) --------------------------------------------------------
int Ssys_current_msecs()
{
  int *v0; // r0
  char *v1; // r0
  int v3; // r4
  struct timespec tp; // [sp+0h] [bp-14h] BYREF

  if ( clock_gettime(1, &tp) == -1 )
  {
    v0 = _errno_location();
    v1 = strerror(*v0);
    sub_F3A8(3, "%s() error = %s\n", "Ssys_current_msecs", v1);
    return -1;
  }
  else
  {
    v3 = 1000 * tp.tv_sec;
    return v3 + sub_F930(tp.tv_nsec, 0xF4240u);
  }
}

//----- (0000F168) --------------------------------------------------------
int __fastcall sub_F168(_DWORD *a1)
{
  int v1; // r4
  int result; // r0
  struct timespec tp; // [sp+8h] [bp-14h] BYREF

  clock_gettime(1, &tp);
  v1 = (1000 * tp.tv_sec) >> 31;
  *a1 = 1000 * tp.tv_sec;
  a1[1] = v1;
  result = sub_F930(tp.tv_nsec, 0x3E8u);
  a1[2] = result;
  return result;
}

//----- (0000F1E0) --------------------------------------------------------
int __fastcall sub_F1E0(_DWORD *a1, _DWORD *a2)
{
  return 1000 * (*a2 - *a1) + a2[2] - a1[2];
}

//----- (0000F25C) --------------------------------------------------------
char *sub_F25C()
{
  return &byte_1926C;
}
// 1926C: using guessed type char byte_1926C;

//----- (0000F290) --------------------------------------------------------
int __fastcall sub_F290(unsigned __int8 *a1, int a2)
{
  unsigned int v4; // r4

  v4 = 0;
  while ( a2 > 1 )
  {
    v4 += *a1 | (a1[1] << 8);
    a1 += 2;
    a2 -= 2;
  }
  if ( a2 == 1 )
    v4 += *a1;
  return (unsigned __int16)~(HIWORD(v4) + v4 + ((unsigned int)(HIWORD(v4) + (unsigned __int16)v4) >> 16));
}

//----- (0000F350) --------------------------------------------------------
int __fastcall Ssys_UI_port2MdlPort(int a1, _DWORD *a2, int *a3)
{
  if ( a1 > 9 )
    return 0;
  *a2 = 0;
  *a3 = a1;
  return 1;
}

//----- (0000F3A8) --------------------------------------------------------
int sub_F3A8(int result, const char *a2, ...)
{
  va_list varg_r2; // [sp+20h] [bp+8h] BYREF

  va_start(varg_r2, a2);
  if ( result <= dword_19F98 )
    return vfprintf((FILE *)stderr, a2, varg_r2);
  return result;
}
// 192E0: using guessed type int stderr;
// 19F98: using guessed type int dword_19F98;

//----- (0000F418) --------------------------------------------------------
int __fastcall sub_F418(int a1)
{
  dword_19F98 = a1;
  return printf("Debug message level set to %d\n", a1);
}
// 19F98: using guessed type int dword_19F98;

//----- (0000F45C) --------------------------------------------------------
void sub_F45C()
{
  dword_19F8C = (int)&unk_1927C;
  dword_19F88 = 1;
}
// 19F88: using guessed type int dword_19F88;
// 19F8C: using guessed type int dword_19F8C;

//----- (0000F494) --------------------------------------------------------
int __fastcall sub_F494(int a1)
{
  int i; // [sp+Ch] [bp-10h]
  int v5; // [sp+10h] [bp-Ch]

  v5 = -1;
  if ( !dword_19F88 )
    sub_F45C();
  for ( i = 0; i < dword_192D4; ++i )
  {
    if ( *(_DWORD *)(dword_19F8C + 8 * i) == a1 )
    {
      v5 = *(_DWORD *)(dword_19F8C + 8 * i + 4);
      break;
    }
  }
  if ( i == dword_192D4 )
    return -1;
  else
    return v5;
}
// 192D4: using guessed type int dword_192D4;
// 19F88: using guessed type int dword_19F88;
// 19F8C: using guessed type int dword_19F8C;

//----- (0000F560) --------------------------------------------------------
int __fastcall sub_F560(int a1)
{
  int i; // [sp+14h] [bp-10h]
  int v5; // [sp+18h] [bp-Ch]

  v5 = -1;
  if ( !dword_19F88 )
    sub_F45C();
  for ( i = 0; i < dword_192D4; ++i )
  {
    if ( *(_DWORD *)(dword_19F8C + 8 * i + 4) == a1 )
    {
      v5 = *(_DWORD *)(dword_19F8C + 8 * i);
      break;
    }
  }
  if ( i == dword_192D4 )
    return -1;
  sub_F3A8(7, "%s(): port %d from port %d\n", "spm_getLogicalPortId", v5, a1);
  return v5;
}
// 192D4: using guessed type int dword_192D4;
// 19F88: using guessed type int dword_19F88;
// 19F8C: using guessed type int dword_19F8C;

//----- (0000F650) --------------------------------------------------------
int __fastcall sub_F650(int a1, _DWORD *a2)
{
  int i; // [sp+8h] [bp-14h]
  int v6; // [sp+10h] [bp-Ch]

  if ( !dword_19F88 )
    sub_F45C();
  v6 = 0;
  for ( i = 0; i < dword_192D4; ++i )
  {
    if ( ((1 << *(_DWORD *)(dword_19F8C + 8 * i)) & a1) != 0 )
      v6 |= 1 << *(_DWORD *)(dword_19F8C + 8 * i + 4);
  }
  *a2 = v6;
  return 0;
}
// 192D4: using guessed type int dword_192D4;
// 19F88: using guessed type int dword_19F88;
// 19F8C: using guessed type int dword_19F8C;

//----- (0000F738) --------------------------------------------------------
int __fastcall sub_F738(int a1, _DWORD *a2)
{
  int i; // [sp+8h] [bp-14h]
  int v6; // [sp+10h] [bp-Ch]

  if ( !dword_19F88 )
    sub_F45C();
  v6 = 0;
  for ( i = 0; i < dword_192D4; ++i )
  {
    if ( ((1 << *(_DWORD *)(dword_19F8C + 8 * i + 4)) & a1) != 0 )
      v6 |= 1 << *(_DWORD *)(dword_19F8C + 8 * i);
  }
  *a2 = v6;
  return 0;
}
// 192D4: using guessed type int dword_192D4;
// 19F88: using guessed type int dword_19F88;
// 19F8C: using guessed type int dword_19F8C;

//----- (0000F820) --------------------------------------------------------
unsigned int __fastcall sub_F820(unsigned int result, unsigned int a2)
{
  unsigned int v2; // r3
  bool v3; // cf
  bool v4; // cf
  int v5; // r2
  bool v6; // zf
  int v7; // r2

  if ( a2 != 1 )
  {
    if ( a2 )
    {
      if ( result <= a2 )
      {
        return result == a2;
      }
      else if ( (a2 & (a2 - 1)) != 0 )
      {
        if ( (a2 & 0xE0000000) != 0 )
        {
          v2 = 1;
        }
        else
        {
          a2 *= 8;
          v2 = 8;
        }
        while ( 1 )
        {
          v3 = a2 >= 0x10000000;
          if ( a2 < 0x10000000 )
            v3 = a2 >= result;
          if ( v3 )
            break;
          a2 *= 16;
          v2 *= 16;
        }
        while ( 1 )
        {
          v4 = a2 >= 0x80000000;
          if ( a2 < 0x80000000 )
            v4 = a2 >= result;
          if ( v4 )
            break;
          a2 *= 2;
          v2 *= 2;
        }
        v5 = 0;
        while ( 1 )
        {
          if ( result >= a2 )
          {
            result -= a2;
            v5 |= v2;
          }
          if ( result >= a2 >> 1 )
          {
            result -= a2 >> 1;
            v5 |= v2 >> 1;
          }
          if ( result >= a2 >> 2 )
          {
            result -= a2 >> 2;
            v5 |= v2 >> 2;
          }
          if ( result >= a2 >> 3 )
          {
            result -= a2 >> 3;
            v5 |= v2 >> 3;
          }
          v6 = result == 0;
          if ( result )
          {
            v2 >>= 4;
            v6 = v2 == 0;
          }
          if ( v6 )
            break;
          a2 >>= 4;
        }
        return v5;
      }
      else
      {
        if ( a2 < 0x10000 )
        {
          v7 = 0;
        }
        else
        {
          a2 >>= 16;
          v7 = 16;
        }
        if ( a2 >= 0x100 )
        {
          a2 >>= 8;
          v7 += 8;
        }
        if ( a2 >= 0x10 )
        {
          a2 >>= 4;
          v7 += 4;
        }
        if ( a2 <= 4 )
          v7 += a2 >> 1;
        else
          LOBYTE(v7) = v7 + 3;
        result >>= v7;
      }
    }
    else
    {
      sub_FA70();
      return 0;
    }
  }
  return result;
}

//----- (0000F918) --------------------------------------------------------
unsigned int __fastcall sub_F918(unsigned int a1, unsigned int a2)
{
  return sub_F820(a1, a2);
}

//----- (0000F930) --------------------------------------------------------
int __fastcall sub_F930(int result, unsigned int a2)
{
  int v2; // r12
  unsigned int v3; // r3
  unsigned int v4; // r2
  bool v5; // cf
  bool v6; // cf
  bool v7; // zf
  int v8; // r2

  v2 = result ^ a2;
  if ( a2 )
  {
    if ( (a2 & 0x80000000) != 0 )
      a2 = -a2;
    if ( a2 == 1 )
    {
      if ( (v2 ^ result) < 0 )
        return -result;
    }
    else
    {
      v3 = result;
      if ( result < 0 )
        v3 = -result;
      if ( v3 <= a2 )
      {
        if ( v3 < a2 )
          result = 0;
        if ( v3 == a2 )
          return (v2 >> 31) | 1;
      }
      else if ( (a2 & (a2 - 1)) != 0 )
      {
        if ( (a2 & 0xE0000000) != 0 )
        {
          v4 = 1;
        }
        else
        {
          a2 *= 8;
          v4 = 8;
        }
        while ( 1 )
        {
          v5 = a2 >= 0x10000000;
          if ( a2 < 0x10000000 )
            v5 = a2 >= v3;
          if ( v5 )
            break;
          a2 *= 16;
          v4 *= 16;
        }
        while ( 1 )
        {
          v6 = a2 >= 0x80000000;
          if ( a2 < 0x80000000 )
            v6 = a2 >= v3;
          if ( v6 )
            break;
          a2 *= 2;
          v4 *= 2;
        }
        result = 0;
        while ( 1 )
        {
          if ( v3 >= a2 )
          {
            v3 -= a2;
            result |= v4;
          }
          if ( v3 >= a2 >> 1 )
          {
            v3 -= a2 >> 1;
            result |= v4 >> 1;
          }
          if ( v3 >= a2 >> 2 )
          {
            v3 -= a2 >> 2;
            result |= v4 >> 2;
          }
          if ( v3 >= a2 >> 3 )
          {
            v3 -= a2 >> 3;
            result |= v4 >> 3;
          }
          v7 = v3 == 0;
          if ( v3 )
          {
            v4 >>= 4;
            v7 = v4 == 0;
          }
          if ( v7 )
            break;
          a2 >>= 4;
        }
        if ( v2 < 0 )
          return -result;
      }
      else
      {
        if ( a2 < 0x10000 )
        {
          v8 = 0;
        }
        else
        {
          a2 >>= 16;
          v8 = 16;
        }
        if ( a2 >= 0x100 )
        {
          a2 >>= 8;
          v8 += 8;
        }
        if ( a2 >= 0x10 )
        {
          a2 >>= 4;
          v8 += 4;
        }
        if ( a2 <= 4 )
          v8 += a2 >> 1;
        else
          LOBYTE(v8) = v8 + 3;
        result = v3 >> v8;
        if ( v2 < 0 )
          return -result;
      }
    }
  }
  else
  {
    sub_FA70();
    return 0;
  }
  return result;
}

//----- (0000FA58) --------------------------------------------------------
int __fastcall sub_FA58(int a1, unsigned int a2)
{
  return sub_F930(a1, a2);
}

//----- (0000FA70) --------------------------------------------------------
int sub_FA70()
{
  return raise(8);
}

//----- (0000FA84) --------------------------------------------------------
void init(void)
{
  init_proc();
}

//----- (0000FAEC) --------------------------------------------------------
int __fastcall sub_FAEC(char *filename, struct stat *stat_buf)
{
  return _xstat(3, filename, stat_buf);
}

//----- (0000FAFC) --------------------------------------------------------
int sub_FAFC()
{
  int (*v0)(void); // r3
  _UNKNOWN **v1; // r4
  int result; // r0
  int (*v3)(void); // t1

  v0 = (int (*)(void))off_19000;
  if ( off_19000 != (_UNKNOWN *)-1 )
  {
    v1 = &off_19000;
    do
    {
      result = v0();
      v3 = (int (*)(void))*--v1;
      v0 = v3;
    }
    while ( v3 != (int (*)(void))-1 );
  }
  return result;
}
// 19000: using guessed type _UNKNOWN *off_19000;

//----- (0000FB30) --------------------------------------------------------
void sub_FB30()
{
  ;
}

//----- (0000FB38) --------------------------------------------------------
int term_proc()
{
  return sub_8D84();
}

// nfuncs=207 queued=132 decompiled=132 lumina nreq=0 worse=0 better=0
// ALL OK, 132 function(s) have been successfully decompiled
